[CmdletBinding()]
param(
    [string]$RawRoot,
    [string]$OutputPath
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoRoot = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '..')).Path
$evidenceRoot = Join-Path $repoRoot 'docs/evidence'
if (-not $RawRoot) {
    $RawRoot = Join-Path $repoRoot 'private/evidence/M2-008/non-force-first-run'
}
if (-not $OutputPath) {
    $OutputPath = Join-Path $evidenceRoot 'M2-008-non-force-codegen.md'
}

function Resolve-InputFile {
    param([Parameter(Mandatory)][string]$Path)
    if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) {
        throw "Required input was not found: '$Path'."
    }
    $resolved = (Resolve-Path -LiteralPath $Path).Path
    if ((Get-Item -LiteralPath $resolved -Force).Attributes -band [System.IO.FileAttributes]::ReparsePoint) {
        throw "Input file must not be a reparse point: '$resolved'."
    }
    return $resolved
}

$resolvedRawRoot = (Resolve-Path -LiteralPath $RawRoot).Path
if ((Get-Item -LiteralPath $resolvedRawRoot -Force).Attributes -band [System.IO.FileAttributes]::ReparsePoint) {
    throw "Raw evidence root must not be a reparse point: '$resolvedRawRoot'."
}
$metadataPath = Resolve-InputFile (Join-Path $resolvedRawRoot 'run.json')
$stdoutPath = Resolve-InputFile (Join-Path $resolvedRawRoot 'stdout.log')
$stderrPath = Resolve-InputFile (Join-Path $resolvedRawRoot 'stderr.log')

$resolvedOutput = [System.IO.Path]::GetFullPath($OutputPath)
$resolvedEvidenceRoot = [System.IO.Path]::GetFullPath($evidenceRoot).TrimEnd('\')
if (-not $resolvedOutput.StartsWith("$resolvedEvidenceRoot\", [System.StringComparison]::OrdinalIgnoreCase) -or
    [System.IO.Path]::GetExtension($resolvedOutput) -ne '.md') {
    throw "Output must be a Markdown file below '$resolvedEvidenceRoot'."
}
if ((Get-Item -LiteralPath (Split-Path -Parent $resolvedOutput) -Force).Attributes -band [System.IO.FileAttributes]::ReparsePoint) {
    throw 'Output directory must not be a reparse point.'
}
if (Test-Path -LiteralPath $resolvedOutput) {
    $outputItem = Get-Item -LiteralPath $resolvedOutput -Force
    if ($outputItem.PSIsContainer -or ($outputItem.Attributes -band [System.IO.FileAttributes]::ReparsePoint)) {
        throw 'Output must be a regular file, not a directory or reparse point.'
    }
}

$metadata = Get-Content -LiteralPath $metadataPath -Raw | ConvertFrom-Json
if ($metadata.schema -ne 1 -or $metadata.task -ne 'M2-008' -or
    $metadata.command -ne 'rexglue codegen mcla_manifest.toml' -or
    $metadata.force_enabled -ne $false -or $metadata.exit_code -ne 1 -or
    $metadata.generated_target_exists -ne $false -or
    $metadata.generated_file_count -ne 0 -or $metadata.generated_total_bytes -ne 0) {
    throw 'Run metadata does not describe the expected M2-008 non-force validation rejection.'
}

$stdoutHash = (Get-FileHash -LiteralPath $stdoutPath -Algorithm SHA256).Hash
$stderrHash = (Get-FileHash -LiteralPath $stderrPath -Algorithm SHA256).Hash
if ($stdoutHash -ne $metadata.stdout_sha256 -or $stderrHash -ne $metadata.stderr_sha256) {
    throw 'Raw stream hash does not match immutable run metadata.'
}
if ((Get-Item -LiteralPath $stdoutPath).Length -ne 0 -or $metadata.stdout_bytes -ne 0) {
    throw 'The captured first run unexpectedly contains stdout data.'
}

$rawLines = @(Get-Content -LiteralPath $stderrPath)
$expectedManifestLine = '  Manifest: ' + $repoRoot.Replace('\', '/') + '/mcla_manifest.toml'
$expectedMountLine = '  Mounted ' + (Join-Path $repoRoot 'private/game') + ' at \Device\Harddisk0\Partition1'
if (@($rawLines | Where-Object { $_ -ceq $expectedManifestLine }).Count -ne 1 -or
    @($rawLines | Where-Object { $_ -ceq $expectedMountLine }).Count -ne 1) {
    throw 'Raw log does not contain the exact expected manifest and private mount paths.'
}
$allowedPatterns = @(
    '^$',
    '^ReXGlue v0\.9\.0 - Xbox 360 Recompilation Toolkit$',
    '^  Manifest: .+/mcla_manifest\.toml$',
    '^  Project:  mcla$',
    '^  SDK:      0\.9\.0 \(project last generated by 0\.9\.0\)$',
    '^Recompiling mcla$',
    '^FunctionDispatcher initialized$',
    '^  Mounted .+\\private\\game at \\Device\\Harddisk0\\Partition1$',
    '^Runtime initialized in tool mode \(no GPU\)$',
    '^Loading XEX image: game:\\default\.xex$',
    "^XThread::Execute thid 1 \(handle=F8000014, 'Kernel Dispatch \(F8000014\)', native=[0-9A-F]+, <host>\)$",
    '^Achievement store: loaded 55 entries$',
    '^default\.xex$',
    '^  Title ID: 545407F8$',
    '^  Media ID: 5940C9DB$',
    '^  Version:  0\.0\.0\.8$',
    '^  Filetime: 2009-07-17 22:23:19 UTC$',
    '^  start  default\.xex$',
    '^  phase  default\.xex: (Register|Scan|Discover|GapFill|Merge|Validate)$',
    '^Analyze: found 7 errors$',
    '^=== ANALYSIS ERRORS ===$',
    '^UnresolvedCall \(7\):$',
    '^  0x[0-9A-F]{8} from 0x[0-9A-F]{8}: b 0x[0-9A-F]{8} from 0x[0-9A-F]{8} - target not in any function$',
    '^Total: 7 errors$',
    "^Analysis failed for 'default'$",
    '^Failed: Validation failed: 7 unresolved calls \(after [0-9]+\.[0-9]+s\)$'
)
for ($index = 0; $index -lt $rawLines.Count; $index++) {
    $accepted = $false
    foreach ($pattern in $allowedPatterns) {
        if ($rawLines[$index] -match $pattern) {
            $accepted = $true
            break
        }
    }
    if (-not $accepted) {
        throw "Unrecognized raw log line $($index + 1); sanitization is fail-closed."
    }
}

$errorLines = @($rawLines | Where-Object { $_ -match '^  0x[0-9A-F]{8} from 0x[0-9A-F]{8}:' })
if ($errorLines.Count -ne 7) {
    throw "Expected exactly 7 UnresolvedCall detail lines, got $($errorLines.Count)."
}
$phaseLines = @($rawLines | Where-Object { $_ -match '^  phase  default\.xex:' })
if ($phaseLines.Count -ne 6) {
    throw "Expected all 6 pre-codegen analysis phases, got $($phaseLines.Count)."
}

$repoForward = $repoRoot.Replace('\', '/')
$privateGame = (Join-Path $repoRoot 'private/game')
$sanitizedLines = foreach ($line in $rawLines) {
    $sanitized = $line.Replace($repoForward, '[REPO]')
    $sanitized = $sanitized.Replace($privateGame, '[PRIVATE_GAME_ROOT]')
    $sanitized = $sanitized -replace 'native=[0-9A-F]+', 'native=[HOST_THREAD]'
    $sanitized
}
$sanitizedText = $sanitizedLines -join "`n"
if ($sanitizedText -match '(?i)(^|[^A-Za-z])[A-Z]:[\\/]|(^|\s)\\\\|\\Users\\|/Users/|native=[0-9A-F]+') {
    throw 'Sanitized transcript still contains an absolute host path, username root, or native thread identifier.'
}

$report = @(
    '# M2-008 non-force codegen validation'
    ''
    'Date: 2026-08-11'
    'Result: EXPECTED VALIDATION REJECTION'
    ''
    '## Immutable run identity'
    ''
    '- Command: `rexglue codegen mcla_manifest.toml`'
    '- `--force`: absent (`false`)'
    '- ReXGlue: `0.9.0`'
    "- Exit code: ``$($metadata.exit_code)``"
    "- Duration: ``$($metadata.duration_seconds) s``"
    "- Private stdout SHA-256: ``$stdoutHash`` (empty stream)"
    "- Private stderr SHA-256: ``$stderrHash``"
    '- Generated target output: absent'
    ''
    '## Classification'
    ''
    'The pinned analyzer completed Register, Scan, Discover, GapFill, Merge, and Validate, then rejected emission because validation found exactly seven findings of one analyzer class: `UnresolvedCall`. Every finding reports a direct branch whose target was not assigned to any recovered function. This is a bounded analysis/config investigation input for M2-009 and M2-010; it is not a host runtime, compiler, GPU, or disk failure.'
    ''
    'No guest-derived C++ or partial generated target was emitted. The non-force gate remains immutable under ignored `private/evidence/M2-008/non-force-first-run/`; the force inventory in M2-009 must use a separate evidence root.'
    ''
    '## Full sanitized validation transcript'
    ''
    'Host repository/private paths and the host-native thread identifier are replaced. Guest addresses and single branch diagnostics are retained as the minimum complete validation evidence allowed by the source-data policy.'
    ''
    '```text'
) + $sanitizedLines + @(
    '```'
    ''
    '## Export verification'
    ''
    '- raw stdout/stderr hashes match immutable private metadata: PASS'
    '- exact command, non-force state, and exit code: PASS'
    '- fail-closed line allowlist: PASS'
    '- 6/6 analysis phases and 7/7 detail findings: PASS'
    '- absolute host path/native-thread scan: PASS'
)

[System.IO.File]::WriteAllText(
    $resolvedOutput,
    (($report -join [Environment]::NewLine) + [Environment]::NewLine),
    [System.Text.UTF8Encoding]::new($false)
)

[pscustomobject]@{
    Exported             = $true
    ExitCode             = $metadata.exit_code
    UnresolvedCallCount  = $errorLines.Count
    AnalysisPhaseCount   = $phaseLines.Count
    OutputPath           = $resolvedOutput
    OutputSha256         = (Get-FileHash -LiteralPath $resolvedOutput -Algorithm SHA256).Hash
}
