[CmdletBinding()]
param(
  [string]$BuildRoot='out/build/win-amd64-release',
  [string]$GameRoot='private/game',
  [string]$InitialUserRoot='private/evidence/M5-013/20260817-013319-c2e7223f/runs/01/user',
  [string]$FinalizeRun,
  [ValidateSet('IAN','MARTIN')][string]$RecoverOpponent,
  [ValidateSet('seen','not-seen')][string]$RecoverPolice
)

Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$repo=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$verify=Join-Path $PSScriptRoot 'verify-race-system-smoke.ps1'
$cmake=(& (Join-Path $PSScriptRoot 'Resolve-Toolchain.ps1') -ExportPath).CMakePath
$utf8=[Text.UTF8Encoding]::new($false)
$sdkCommit='576b34fd233acf4579dd2375691dbe86fb4bf8e1'
$seedSaveSha='126F7482878C7AACB09AA6795331C906DFB9C4218BE94EDB1D8E51B27CA78AB2'
$seedHeaderSha='5827A913515AC0E5D55BB56AEC56DE99CACC0ABB7C8061F59336DF4CEA4A8731'
$trafficResultSha='299392E59CB38AFB44256E773884856FF0C869A96D2045086A65396C1ED4EFCA'
$seriesResultSha='D993E2612D1AC769D88264C83FD9C9186BC761E2067317F5A7EB66038C250E58'
$resourceResultSha='D890A903775A3B53262B9957E7B7DC1D4B76B49B8735360BECD8233842446298'
$scope='one current representative Ian or Martin head-to-head event with machine-observed Race_Finish invocation, current start/reward frames, and external owner completion/police observation; prior immutable Ian series, five-race reward, and traffic evidence; optional description/checkpoint/UI-result wrappers may be zero-hit and are not required or claimed as current machine telemetry; no claim of every race type, opponent, checkpoint implementation, police behavior, reward amount, difficulty, or campaign branch'

if(-not('MclaRaceSystemNative'-as[type])){Add-Type -TypeDefinition @'
using System;using System.Collections.Generic;using System.Runtime.InteropServices;using System.Text;
public static class MclaRaceSystemNative{delegate bool E(IntPtr h,IntPtr p);[DllImport("user32.dll")]static extern bool EnumWindows(E c,IntPtr p);[DllImport("user32.dll")]static extern uint GetWindowThreadProcessId(IntPtr h,out uint p);[DllImport("user32.dll")]static extern bool IsWindowVisible(IntPtr h);[DllImport("user32.dll",CharSet=CharSet.Unicode)]static extern int GetWindowText(IntPtr h,StringBuilder s,int n);[DllImport("user32.dll")]static extern bool PostMessage(IntPtr h,uint m,IntPtr w,IntPtr l);public static IntPtr[] Handles(int pid){var a=new List<IntPtr>();EnumWindows(delegate(IntPtr h,IntPtr x){uint p;GetWindowThreadProcessId(h,out p);if(p==(uint)pid&&IsWindowVisible(h))a.Add(h);return true;},IntPtr.Zero);return a.ToArray();}public static string Title(IntPtr h){var s=new StringBuilder(1024);int n=GetWindowText(h,s,s.Capacity);return n>0?s.ToString(0,n):String.Empty;}public static bool Close(IntPtr h){return PostMessage(h,0x10,IntPtr.Zero,IntPtr.Zero);}}
'@}

function Resolve-Safe([string]$Path,[string]$Description,[switch]$Exists){$full=if([IO.Path]::IsPathRooted($Path)){[IO.Path]::GetFullPath($Path)}else{[IO.Path]::GetFullPath((Join-Path $repo $Path))};$prefix=$repo.TrimEnd('\')+'\';if(-not$full.StartsWith($prefix,[StringComparison]::OrdinalIgnoreCase)){throw "$Description escapes repository."};$current=$repo;foreach($part in @($full.Substring($prefix.Length).Split('\')|Where-Object{$_.Length})){$current=Join-Path $current $part;if((Test-Path -LiteralPath $current)-and((Get-Item -LiteralPath $current -Force).Attributes-band[IO.FileAttributes]::ReparsePoint)){throw "$Description traverses a reparse point."}};if($Exists-and-not(Test-Path -LiteralPath $full)){throw "$Description is missing."};$full}
function Invoke-Logged([scriptblock]$Command,[string]$Log,[switch]$Append){$prior=$ErrorActionPreference;$ErrorActionPreference='Continue';try{if($Append){&$Command *>&1|Tee-Object -FilePath $Log -Append|Out-Null}else{&$Command *>&1|Tee-Object -FilePath $Log|Out-Null};$LASTEXITCODE}finally{$ErrorActionPreference=$prior}}
function Read-LiveLogs([string]$Root){$text='';foreach($file in @(Get-ChildItem -LiteralPath $Root -File -Filter 'mcla*.log' -ErrorAction SilentlyContinue)){try{$stream=[IO.File]::Open($file.FullName,'Open','Read','ReadWrite');try{$reader=[IO.StreamReader]::new($stream);$text+=$reader.ReadToEnd();$reader.Dispose()}finally{$stream.Dispose()}}catch{}};$text}
function Wait-Marker([Diagnostics.Process]$Process,[string]$Root,[string]$Marker,[int]$Seconds,[string]$Step){$deadline=[DateTime]::UtcNow.AddSeconds($Seconds);while([DateTime]::UtcNow-lt$deadline){if($Process.HasExited){throw "Process exited during '$Step'."};if((Read-LiveLogs $Root).Contains($Marker)){return};Start-Sleep -Milliseconds 200};throw "Timed out during '$Step'."}
function Close-ExactWindow([Diagnostics.Process]$Process){$matches=@();foreach($handle in [MclaRaceSystemNative]::Handles($Process.Id)){if([regex]::IsMatch([MclaRaceSystemNative]::Title($handle),'^mcla \[rexglue-v[^\]]+\]$')){$matches+=$handle}};if($matches.Count-ne1-or-not[MclaRaceSystemNative]::Close($matches[0])){throw 'Exact PID/window WM_CLOSE failed.'}}
function Get-Artifacts([string]$Build){@('mcla.exe','rexruntime.dll','TracyClient.dll','rexgpu-xenos.dll')|ForEach-Object{$path=Resolve-Safe (Join-Path $Build $_) "Artifact $_" -Exists;[ordered]@{name=$_;sha256=(Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash}}}
function Write-Json([string]$Path,$Value){[IO.File]::WriteAllText($Path,(ConvertTo-Json $Value -Depth 14)+[Environment]::NewLine,$utf8)}
function Get-SavePaths([string]$UserRoot){[ordered]@{save=Join-Path $UserRoot 'B13EBABEBABEBABE/545407F8/00000001/mc4.sav/mc4.sav';header=Join-Path $UserRoot 'B13EBABEBABEBABE/545407F8/Headers/00000001/mc4.sav.header'}}
function Read-Exact([Diagnostics.Process]$Process,[string]$Instruction,[string[]]$Allowed){while($true){if($Process.HasExited){throw 'Process exited while waiting for operator confirmation.'};Write-Host $Instruction -ForegroundColor Yellow;$answer=Read-Host;if($answer-cin$Allowed){return $answer};Write-Host 'Ignored; exact phrase required and the game remains running.' -ForegroundColor DarkYellow}}
function Complete-Run([string]$Root,[string]$Build,[string]$Opponent,[string]$Police){$observation=[ordered]@{schema='mcla-race-system-operator-observation-v1';opponent=$Opponent;event_completed=$true;police_observed=($Police-ceq'seen');prior_police_observed=$true;source='owner-console-transcript-and-chat-report';recorded_in_runtime_log=$false;machine_verified=$false};Write-Json (Join-Path $Root 'operator-observation.json') $observation;$probe=&$verify -RunPath $Root;$record=[ordered]@{schema='mcla-race-system-v1';task='M6-003';decision='representative-race-system-matrix-pass';sdk_version='0.9.0.22';sdk_commit=$sdkCommit;build_configuration='Release';route_id='representative-ian-martin-race-v1';opponent=$Opponent;police_observation=$Police;traffic_result_sha256=$trafficResultSha;series_result_sha256=$seriesResultSha;resource_result_sha256=$resourceResultSha;seed_save_sha256=$seedSaveSha;seed_header_sha256=$seedHeaderSha;signin_compatibility_state=2;probe=$probe;release_artifacts=@(Get-Artifacts $Build);scope=$scope};$result=Join-Path $Root 'result.json';Write-Json $result $record;&$verify -ResultPath $result}

$build=Resolve-Safe $BuildRoot 'Build root' -Exists
if($FinalizeRun){if(-not$RecoverOpponent-or-not$RecoverPolice){throw 'Recovery requires -RecoverOpponent and -RecoverPolice.'};$root=Resolve-Safe $FinalizeRun 'M6-003 recovery run' -Exists;if((Split-Path $root -Parent)-cne(Resolve-Safe 'private/evidence/M6-003' 'M6-003 evidence root' -Exists)){throw 'Recovery run must be one direct M6-003 evidence child.'};Write-Host 'M6-003 recovery: preserving the completed physical race and recalibrating the zero-hit optional wrappers...' -ForegroundColor Cyan;$final=Complete-Run $root $build $RecoverOpponent $RecoverPolice;Write-Host "M6-003 recovered PASS: '$root\result.json'." -ForegroundColor Green;$final;return}
$game=Resolve-Safe $GameRoot 'Game root' -Exists;$initial=Resolve-Safe $InitialUserRoot 'Initial user root' -Exists
if($build-cne(Resolve-Safe 'out/build/win-amd64-release' 'Canonical Release build')-or$game-cne(Resolve-Safe 'private/game' 'Canonical game')-or$initial-cne(Resolve-Safe 'private/evidence/M5-013/20260817-013319-c2e7223f/runs/01/user' 'Canonical HANGOUT save root')){throw 'M6-003 requires canonical build, game, and HANGOUT save inputs.'}
$seed=Get-SavePaths $initial;if((Get-FileHash $seed.save -Algorithm SHA256).Hash-cne$seedSaveSha-or(Get-FileHash $seed.header -Algorithm SHA256).Hash-cne$seedHeaderSha){throw 'HANGOUT save identity drifted.'}
foreach($prior in @(@('private/evidence/M5-003/20260814-104624-fde51a30/result.json',$trafficResultSha),@('private/evidence/M5-012/20260817-001225-ade395f8/result.json',$seriesResultSha),@('private/evidence/M5-013/20260817-015958-36eec226/result.json',$resourceResultSha))){$path=Resolve-Safe $prior[0] 'Prior race evidence' -Exists;if((Get-FileHash $path -Algorithm SHA256).Hash-cne$prior[1]){throw 'Prior race evidence drifted.'}}
$sdk=Join-Path $repo 'third_party/rexglue-sdk';if((&git -C $sdk describe --tags --exact-match HEAD 2>$null).Trim()-cne'v0.9.0.22'-or(&git -C $sdk rev-parse HEAD).Trim()-cne$sdkCommit-or(git -C $sdk status --porcelain)){throw 'M6-003 requires clean exact ReXGlue v0.9.0.22.'}
$evidence=Resolve-Safe 'private/evidence/M6-003' 'M6-003 evidence root';[IO.Directory]::CreateDirectory($evidence)|Out-Null;$runRoot=Join-Path $evidence ((Get-Date -Format 'yyyyMMdd-HHmmss')+'-'+[guid]::NewGuid().ToString('N').Substring(0,8));[IO.Directory]::CreateDirectory($runRoot)|Out-Null;$buildLog=Join-Path $runRoot 'release-clean-build.log'
Write-Host 'M6-003 [1/5]: validating prior race matrix, HANGOUT save, and exact SDK identity...' -ForegroundColor Cyan
Write-Host 'M6-003 [2/5]: clean-building the Release host...' -ForegroundColor Cyan;if(Invoke-Logged {&$cmake --preset win-amd64-release} $buildLog){throw 'Release configure failed.'};if(Invoke-Logged {&$cmake --build --preset win-amd64-release --target mcla --clean-first --parallel 8} $buildLog -Append){throw "Release clean build failed. Private run: '$runRoot'."}
$exe=Resolve-Safe (Join-Path $build 'mcla.exe') 'Release executable' -Exists;if(@((Get-Process mcla -ErrorAction SilentlyContinue)|Where-Object{try{$_.Path-ceq$exe}catch{$false}}).Count){throw 'Canonical Release MCLA is already running.'};$artifactsBefore=@(Get-Artifacts $build);Write-Json (Join-Path $runRoot 'physical-artifacts.json') $artifactsBefore
$cycle=Join-Path $runRoot 'runs/01';$user=Join-Path $cycle 'user';$cache=Join-Path $cycle 'cache';[IO.Directory]::CreateDirectory($user)|Out-Null;[IO.Directory]::CreateDirectory($cache)|Out-Null;Copy-Item -LiteralPath (Join-Path $initial 'B13EBABEBABEBABE') -Destination $user -Recurse -Force
$runtimeLog=Join-Path $cycle 'mcla.log';$args=@('--mcla_race_system_probe=true','--xam_user_signin_state=2','--mcla_first_frame_settle_seconds=35','--input_backend=sdl','--mnk_mode=false','--async_shader_compilation=false','--d3d12_pipeline_creation_threads=0','--log_max_file_size_mb=8','--log_max_files=30','--log_level=info','--fullscreen=false',"--game_data_root=`"$game`"","--user_data_root=`"$user`"","--cache_root=`"$cache`"","--log_file=`"$runtimeLog`"")
Write-Host 'M6-003 [3/5]: launching one representative race-system event...' -ForegroundColor Cyan;$process=$null;$forced=$false
try{$process=Start-Process $exe -ArgumentList $args -WorkingDirectory $build -PassThru;Wait-Marker $process $cycle 'MCLA_RACE_SYSTEM_READY v=1 phases=start,rewards external_close_required=1' 90 'title/race audit readiness';Write-Host 'TITLE              | PASS - press START, open GPS with BACK, select available Ian or Martin, reach and challenge with Y.' -ForegroundColor Green
  $start=Read-Exact $process 'At the two-car start (HUD 2/2), Alt-Tab and type exactly: RACE SYSTEM START IAN  or  RACE SYSTEM START MARTIN' @('RACE SYSTEM START IAN','RACE SYSTEM START MARTIN');$opponent=$start.Substring('RACE SYSTEM START '.Length);[IO.File]::WriteAllText((Join-Path $user '.mcla-race-system-start.request'),'1',$utf8);Wait-Marker $process $cycle 'MCLA_RACE_SYSTEM_FRAME v=1 phase=start width=1280 height=720' 15 'race-start capture';Write-Host 'RACE START         | CAPTURED - complete this one event normally.' -ForegroundColor Green
  $finish=Read-Exact $process "At the stable reward/results screen, type exactly one:`nRACE SYSTEM FINISH $opponent POLICE SEEN`nRACE SYSTEM FINISH $opponent POLICE NOT SEEN" @("RACE SYSTEM FINISH $opponent POLICE SEEN","RACE SYSTEM FINISH $opponent POLICE NOT SEEN");$police=if($finish.EndsWith('POLICE SEEN')){'seen'}else{'not-seen'};[IO.File]::WriteAllText((Join-Path $user '.mcla-race-system-rewards.request'),'1',$utf8);Wait-Marker $process $cycle 'MCLA_RACE_SYSTEM_FRAME v=1 phase=rewards width=1280 height=720' 15 'reward capture';Wait-Marker $process $cycle 'MCLA_RACE_SYSTEM_SUMMARY v=1 status=PASS' 10 'race-system summary';Write-Host 'RACE RESULT        | MACHINE AUDIT PASS - closing externally with WM_CLOSE.' -ForegroundColor Green;Close-ExactWindow $process;if(-not$process.WaitForExit(10000)-or$process.ExitCode-ne0){throw 'Controlled external WM_CLOSE failed.'}
}catch{$failure=$_;if($null-ne$process-and-not$process.HasExited){$forced=$true;Stop-Process -Id $process.Id -Force -ErrorAction SilentlyContinue;$null=$process.WaitForExit(5000)};if($forced){throw "M6-003 failure required force cleanup. $($failure.Exception.Message) Private run: '$runRoot'."};throw}
Write-Host 'M6-003 [4/5]: verifying current telemetry, captures, prior evidence, and integrity...' -ForegroundColor Cyan;$artifactsAfter=@(Get-Artifacts $build);if(($artifactsBefore|ConvertTo-Json -Compress)-cne($artifactsAfter|ConvertTo-Json -Compress)){throw 'Release artifacts changed during the run.'};$final=Complete-Run $runRoot $build $opponent $police
Write-Host 'M6-003 [5/5]: persisted physical result revalidated.' -ForegroundColor Cyan;Write-Host "M6-003 PASS: representative race-system matrix verified. Result: '$runRoot\result.json'." -ForegroundColor Green;$final
