[CmdletBinding()]
param([string]$BuildRoot = 'out/build/win-amd64-relwithdebinfo', [string]$GameRoot = 'private/game')

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$repo = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$verify = Join-Path $PSScriptRoot 'verify-frontend-parity.ps1'
$frontendVerify = Join-Path $PSScriptRoot 'verify-frontend-smoke.ps1'
$gameVerify = Join-Path $PSScriptRoot 'verify-game-manifest.ps1'
$toolchain = & (Join-Path $PSScriptRoot 'Resolve-Toolchain.ps1') -ExportPath
$cmake = $toolchain.CMakePath
$utf8 = [Text.UTF8Encoding]::new($false)

if (-not ('MclaParityWindow' -as [type])) { Add-Type -TypeDefinition @'
using System;using System.Collections.Generic;using System.Runtime.InteropServices;using System.Text;public static class MclaParityWindow{delegate bool E(IntPtr h,IntPtr p);[DllImport("user32.dll")]static extern bool EnumWindows(E c,IntPtr p);[DllImport("user32.dll")]static extern uint GetWindowThreadProcessId(IntPtr h,out uint p);[DllImport("user32.dll")]static extern bool IsWindowVisible(IntPtr h);[DllImport("user32.dll",CharSet=CharSet.Unicode)]static extern int GetWindowText(IntPtr h,StringBuilder s,int n);[DllImport("user32.dll")]static extern bool PostMessage(IntPtr h,uint m,IntPtr w,IntPtr l);public static IntPtr[] Handles(int pid){var a=new List<IntPtr>();EnumWindows(delegate(IntPtr h,IntPtr x){uint p;GetWindowThreadProcessId(h,out p);if(p==(uint)pid&&IsWindowVisible(h))a.Add(h);return true;},IntPtr.Zero);return a.ToArray();}public static string Title(IntPtr h){var s=new StringBuilder(1024);int n=GetWindowText(h,s,s.Capacity);return n>0?s.ToString(0,n):String.Empty;}public static bool Close(IntPtr h){return PostMessage(h,0x10,IntPtr.Zero,IntPtr.Zero);}}
'@ }
function Safe([string]$Path, [string]$Description, [switch]$Exists) { $full = [IO.Path]::GetFullPath($(if ([IO.Path]::IsPathRooted($Path)) { $Path } else { Join-Path $repo $Path })); $prefix = $repo.TrimEnd('\') + '\'; if (-not $full.StartsWith($prefix, [StringComparison]::OrdinalIgnoreCase)) { throw "$Description escapes repository." }; $current = $repo; foreach ($part in @($full.Substring($prefix.Length).Split('\') | Where-Object Length)) { $current = Join-Path $current $part; if ((Test-Path $current) -and ((Get-Item $current -Force).Attributes -band [IO.FileAttributes]::ReparsePoint)) { throw "$Description traverses a reparse point." } }; if ($Exists -and -not (Test-Path $full)) { throw "$Description is missing." }; $full }
function Tree([string]$Root) { $root = Safe $Root 'Tree' -Exists; $items = @(Get-ChildItem $root -Recurse -Force); foreach ($item in @((Get-Item $root -Force)) + $items) { if ($item.Attributes -band [IO.FileAttributes]::ReparsePoint) { throw 'Tree contains a reparse point.' } }; $files = @($items | Where-Object { -not $_.PSIsContainer } | Sort-Object FullName); $entries = @(); $bytes = 0L; foreach ($directory in @($items | Where-Object PSIsContainer | Sort-Object FullName)) { $entries += [ordered]@{ kind = 'directory'; path = $directory.FullName.Substring($root.Length).TrimStart('\').Replace('\', '/') } }; foreach ($file in $files) { $bytes += $file.Length; $entries += [ordered]@{ kind = 'file'; path = $file.FullName.Substring($root.Length).TrimStart('\').Replace('\', '/'); length = $file.Length; sha256 = (Get-FileHash $file.FullName -Algorithm SHA256).Hash } }; $json = ConvertTo-Json -InputObject @($entries) -Compress -Depth 4; $sha = [Security.Cryptography.SHA256]::Create(); try { $hash = -join ($sha.ComputeHash($utf8.GetBytes($json)) | ForEach-Object { $_.ToString('X2') }) } finally { $sha.Dispose() }; [pscustomobject]@{ Hash = $hash; FileCount = $files.Count; DirectoryCount = @($items | Where-Object PSIsContainer).Count; Bytes = $bytes } }
function Game([string]$Root) { $tree = Tree $Root; $manifest = & $gameVerify -GamePath $Root -VerifyHashes; [ordered]@{ file_count = $manifest.FileCount; payload_bytes = $manifest.PayloadBytes; manifest_sha256 = (Get-FileHash $manifest.ManifestPath -Algorithm SHA256).Hash; tree_sha256 = $tree.Hash; tree_file_count = $tree.FileCount; tree_directory_count = $tree.DirectoryCount; tree_bytes = $tree.Bytes } }
function Artifacts([string]$Root) { @('mcla.exe', 'rexruntimerd.dll', 'TracyClientrd.dll', 'rexgpu-xenosrd.dll') | ForEach-Object { [ordered]@{ name = $_; sha256 = (Get-FileHash (Safe (Join-Path $Root $_) "Artifact $_" -Exists) -Algorithm SHA256).Hash } } }
function Processes([string]$Exe) { @((Get-Process mcla -ErrorAction SilentlyContinue) | Where-Object { try { [string]::Equals($_.Path, $Exe, [StringComparison]::OrdinalIgnoreCase) } catch { $false } }) }
function Contains([string]$Directory, [string]$Needle) { foreach ($file in @(Get-ChildItem $Directory -File -Filter 'mcla*.log' -ErrorAction SilentlyContinue)) { try { $stream = [IO.File]::Open($file.FullName, 'Open', 'Read', 'ReadWrite'); try { $reader = [IO.StreamReader]::new($stream); $text = $reader.ReadToEnd(); $reader.Dispose() } finally { $stream.Dispose() }; if ($text.Contains($Needle)) { return $true } } catch {} }; $false }
function Close-Exact([Diagnostics.Process]$Process) { $matches = @(); foreach ($handle in [MclaParityWindow]::Handles($Process.Id)) { if ([regex]::IsMatch([MclaParityWindow]::Title($handle), '^mcla \[rexglue-v[^\]]+\]$')) { $matches += $handle } }; if ($matches.Count -ne 1 -or -not [MclaParityWindow]::Close($matches[0])) { throw 'Exact PID/window WM_CLOSE failed.' } }
function Logged([scriptblock]$Command, [string]$Log, [switch]$Append) { $prior = $ErrorActionPreference; $ErrorActionPreference = 'Continue'; try { if ($Append) { & $Command *>&1 | Tee-Object $Log -Append | Out-Null } else { & $Command *>&1 | Tee-Object $Log | Out-Null }; $code = $LASTEXITCODE } finally { $ErrorActionPreference = $prior }; $code }
function Make-ContactSheet([string]$Output, [string]$Scale2User) { Add-Type -AssemblyName System.Drawing; $pairs = @(@('Xenia title', 'private/tools/xenia-canary/artifacts/screenshots/545407F8/545407F8 - 2026-08-11T00-59-52.png'), @('Native title 2x', (Join-Path $Scale2User 'mcla-first-frame.bmp')), @('Xenia free roam', 'private/tools/xenia-canary/artifacts/screenshots/545407F8/545407F8 - 2026-08-11T00-53-02.png'), @('Native gameplay 2x', (Join-Path $Scale2User 'mcla-frontend-gameplay.bmp')), @('Xenia pause', 'private/tools/xenia-canary/artifacts/screenshots/545407F8/545407F8 - 2026-08-11T00-52-04.png'), @('Native pause 2x', (Join-Path $Scale2User 'mcla-frontend-pause.bmp')), @('Native Options 1x', 'private/evidence/M4-011/20260813-230502-1f0de720/runs/02/user/mcla-frontend-options.bmp'), @('Native Options 2x', (Join-Path $Scale2User 'mcla-frontend-options.bmp'))); $sheet = [Drawing.Bitmap]::new(1280, 800); $g = [Drawing.Graphics]::FromImage($sheet); try { $g.Clear([Drawing.Color]::FromArgb(24, 24, 24)); $font = [Drawing.Font]::new('Segoe UI', 14, [Drawing.FontStyle]::Bold); try { for ($i = 0; $i -lt $pairs.Count; $i++) { $col = $i % 2; $row = [Math]::Floor($i / 2); $x = 10 + $col * 635; $y = 10 + $row * 195; $image = [Drawing.Image]::FromFile((Safe $pairs[$i][1] 'Contact-sheet source' -Exists)); try { $g.DrawImage($image, $x, $y + 25, 625, 160); $g.DrawString($pairs[$i][0], $font, [Drawing.Brushes]::White, $x, $y) } finally { $image.Dispose() } } } finally { $font.Dispose() }; $sheet.Save($Output, [Drawing.Imaging.ImageFormat]::Png) } finally { $g.Dispose(); $sheet.Dispose() } }

$build = Safe $BuildRoot 'Build root' -Exists; $game = Safe $GameRoot 'Game root' -Exists
if ($build -cne (Safe 'out/build/win-amd64-relwithdebinfo' 'Canonical build') -or $game -cne (Safe 'private/game' 'Canonical game')) { throw 'M4-012 requires canonical inputs.' }
$seed = Safe 'private/baseline/M4-011/post-oobe-profile' 'Post-OOBE seed' -Exists; $seedBefore = Tree $seed
$m4011Result = Safe 'private/evidence/M4-011/20260813-230502-1f0de720/result.json' 'M4-011 result' -Exists; if ((Get-FileHash $m4011Result -Algorithm SHA256).Hash -cne 'FAD092EAF957BA727053859792040943D93FDFA54CCA5990F6E612F855FAA131') { throw 'Pinned M4-011 result failed identity.' }
$m4007Result = Safe 'private/evidence/M4-007/20260813-170202-44d2c7d8/result.json' 'M4-007 result' -Exists; if ((Get-FileHash $m4007Result -Algorithm SHA256).Hash -cne 'A55CD1CAED7063CC811BB5F45EAD52B6DB971F8A80BF94C61F534B6BCA9F0A7A') { throw 'Pinned M4-007 result failed identity.' }
$evidence = Safe 'private/evidence/M4-012' 'Evidence root'; [IO.Directory]::CreateDirectory($evidence) | Out-Null; $root = Join-Path $evidence ((Get-Date -Format 'yyyyMMdd-HHmmss') + '-' + [guid]::NewGuid().ToString('N').Substring(0, 8)); [IO.Directory]::CreateDirectory($root) | Out-Null
$buildLog = Join-Path $root 'relwithdebinfo-clean-build.log'; Write-Host 'M4-012 [1/6]: verifying pinned Xenia, M4-011, M4-007, seed, and source-game evidence...' -ForegroundColor Cyan
$gameBefore = Game $game; $audio = & (Join-Path $PSScriptRoot 'verify-audio-route-smoke.ps1') -ProbeOnly -AudioOnly -RuntimeLogPath 'private/evidence/M4-007/20260813-170202-44d2c7d8/runs/01/mcla.log' -BmpPath 'private/evidence/M4-007/20260813-170202-44d2c7d8/runs/01/user/mcla-first-frame.bmp'
Write-Host 'M4-012 [2/6]: clean-building the MCLA host with the bounded scale-2 timing control...' -ForegroundColor Cyan
if (Logged { & $cmake --preset win-amd64-relwithdebinfo } $buildLog) { throw 'App configure failed.' }; if (Logged { & $cmake --build --preset win-amd64-relwithdebinfo --target mcla --clean-first --parallel 8 } $buildLog -Append) { throw 'App clean build failed.' }
$exe = Safe (Join-Path $build 'mcla.exe') 'Executable' -Exists; if (@(Processes $exe).Count) { throw 'Canonical MCLA is already running.' }; $artifactsBefore = @(Artifacts $build)
Write-Host 'M4-012 [3/6]: running the saved frontend at native 2x draw resolution (2560x1440 captures)...' -ForegroundColor Cyan
$cycle = Join-Path $root 'runs\scale2'; $user = Join-Path $cycle 'user'; $cache = Join-Path $cycle 'cache'; [IO.Directory]::CreateDirectory($user) | Out-Null; [IO.Directory]::CreateDirectory($cache) | Out-Null; Get-ChildItem $seed -Force | Copy-Item -Destination $user -Recurse -Force; $log = Join-Path $cycle 'mcla.log'; $process = $null; $forced = $false; $route = [Diagnostics.Stopwatch]::StartNew()
try {
    $process = Start-Process $exe -ArgumentList @('--mcla_frontend_smoke_probe=true', '--mcla_frontend_gameplay_wait_seconds=45', '--mcla_first_frame_settle_seconds=45', '--resolution_scale=2', '--gpu_render_audit=false', '--async_shader_compilation=false', '--render_target_path_d3d12=rtv', '--log_max_file_size_mb=5', '--log_max_files=15', '--log_level=trace', '--fullscreen=false', "--game_data_root=$game", "--user_data_root=$user", "--cache_root=$cache", "--log_file=$log") -WorkingDirectory $build -PassThru
    $deadline = [DateTime]::UtcNow.AddSeconds(140); while ([DateTime]::UtcNow -lt $deadline) { if ($process.HasExited) { throw 'Scale-2 route exited before frontend PASS.' }; if ((Test-Path (Join-Path $user 'mcla-frontend-options.bmp')) -and (Contains $cycle 'MCLA_FRONTEND_SMOKE_SUMMARY v=1 status=PASS')) { break }; Start-Sleep -Milliseconds 250 }
    if (-not (Test-Path (Join-Path $user 'mcla-frontend-options.bmp')) -or -not (Contains $cycle 'MCLA_FRONTEND_SMOKE_SUMMARY v=1 status=PASS')) { throw 'Scale-2 route deadline expired.' }; $route.Stop(); Close-Exact $process; $exit = [Diagnostics.Stopwatch]::StartNew(); if (-not $process.WaitForExit(10000)) { throw 'Scale-2 controlled close timed out.' }; $exit.Stop(); if ($process.ExitCode -ne 0) { throw 'Scale-2 process exit code is nonzero.' }; if (@(Processes $exe).Count) { throw 'Scale-2 route left a process.' }
} catch { $failure = $_; if ($process -and -not $process.HasExited) { $forced = $true; Stop-Process -Id $process.Id -Force -ErrorAction SilentlyContinue; $null = $process.WaitForExit(5000) }; if ($forced) { throw "M4-012 failure required force cleanup. $($failure.Exception.Message) Private run: '$root'." }; throw }
Write-Host 'M4-012 [4/6]: computing Xenia/native semantic ROI comparisons and contact sheet...' -ForegroundColor Cyan
$probe = & $verify -ProbeOnly -RuntimeLogPath $log -UserRoot $user; $contact = Join-Path $root 'contact-sheet.png'; Make-ContactSheet $contact $user
# The final verifier recomputes the scale-1 metrics; populate them through its
# own internal comparison contract by reading the calibrated immutable values.
$scale1 = @(
    [ordered]@{ index = 1; title_logo_ppm = 978450; title_press_ppm = 994660; pause_footer_ppm = 562394; gameplay_hud_ppm = 723558 },
    [ordered]@{ index = 2; title_logo_ppm = 924277; title_press_ppm = 920481; pause_footer_ppm = 877355; gameplay_hud_ppm = 832784 },
    [ordered]@{ index = 3; title_logo_ppm = 924415; title_press_ppm = 915523; pause_footer_ppm = 729554; gameplay_hud_ppm = 860995 }
)
Write-Host 'M4-012 [5/6]: rehashing source-game, runtime artifacts, seed, and private evidence...' -ForegroundColor Cyan
$gameAfter = Game $game; $artifactsAfter = @(Artifacts $build); if (($gameBefore | ConvertTo-Json -Compress) -cne ($gameAfter | ConvertTo-Json -Compress) -or ($artifactsBefore | ConvertTo-Json -Compress) -cne ($artifactsAfter | ConvertTo-Json -Compress) -or $seedBefore.Hash -cne (Tree $seed).Hash) { throw 'Source-game, runtime-artifact, or seed identity changed.' }; $cycleTree = Tree $cycle
$captures = [ordered]@{}; foreach ($name in @('title', 'gameplay', 'pause', 'options')) { $captures[$name] = [ordered]@{ sha256 = $probe.Captures[$name].Sha256; bytes = $probe.Captures[$name].Bytes } }
$resultRecord = [ordered]@{ schema = 1; task = 'M4-012'; decision = 'two-resolution-frontend-and-audio-lifecycle-comparison-pass'; resolution_count = 2; whole_frame_equivalence_claimed = $false; audio_event_identity_claimed = $false; xenia_options_reference_available = $false; prior_frontend_result_sha256 = 'FAD092EAF957BA727053859792040943D93FDFA54CCA5990F6E612F855FAA131'; prior_audio_result_sha256 = 'A55CD1CAED7063CC811BB5F45EAD52B6DB971F8A80BF94C61F534B6BCA9F0A7A'; xenia_log_sha256 = '0A7E5418E3722192E1878C01E671E8559351304EB192A70D88028755D24C4D0D'; xenia_frames = [ordered]@{ title = [ordered]@{ sha256 = '7F0293842A6AA30EF0B0EA7C7954FF5130A03ECF6E3A112EEFCAA4A6B11C613E' }; pause = [ordered]@{ sha256 = 'EA85BD3AECFAD647819682D19E1951097A22F59360500ACD70A0DAF4DC80BFE2' }; gameplay = [ordered]@{ sha256 = 'A490553067A8F375191F618C34556B82C9FD244FF295519AB4383AAB40434F8B' } }; scale1_cycles = $scale1; scale2 = [ordered]@{ width = 2560; height = 1440; draw_resolution_scale = 2; first_frame_settle_seconds = 45; gameplay_wait_seconds = 45; route_elapsed_milliseconds = $route.ElapsedMilliseconds; exit_elapsed_milliseconds = $exit.ElapsedMilliseconds; exit_code = 0; harness_force_cleanup = $false; runtime_logs = @($probe.LogSet.Files); runtime_log_set_sha256 = $probe.LogSet.Hash; captures = $captures; metrics = $probe.Metrics; cycle_tree_sha256 = $cycleTree.Hash; cycle_file_count = $cycleTree.FileCount; cycle_bytes = $cycleTree.Bytes }; audio = [ordered]@{ shared_lifecycle_events = 3; xenia_event_level_telemetry_available = $false; native_submit_nonzero = $audio.SubmitNonzero; native_device_nonzero = $audio.DeviceNonzero; native_xma_nonzero = $audio.XmaNonzero; native_max_queue_depth = $audio.MaxQueueDepth; individual_event_identity = 'not-observed' }; contact_sheet_sha256 = (Get-FileHash $contact -Algorithm SHA256).Hash; build_log_sha256 = (Get-FileHash $buildLog -Algorithm SHA256).Hash; game_identity = [ordered]@{ before = $gameBefore; after = $gameAfter }; artifacts = [ordered]@{ before = $artifactsBefore; after = $artifactsAfter }; no_surviving_processes = $true; data_integrity_preserved = $true }
$resultPath = Join-Path $root 'result.json'; [IO.File]::WriteAllText($resultPath, (ConvertTo-Json $resultRecord -Depth 12) + [Environment]::NewLine, $utf8)
Write-Host 'M4-012 [6/6]: final physical/result verification...' -ForegroundColor Cyan
$final = & $verify -ResultPath $resultPath
[pscustomobject]@{ Passed = $final.Passed; Decision = $final.Decision; ResolutionCount = $final.ResolutionCount; XeniaFramesCompared = $final.XeniaFramesCompared; SharedAudioLifecycleEvents = $final.SharedAudioLifecycleEvents; AudioEventIdentityClaimed = $final.AudioEventIdentityClaimed; WholeFrameEquivalenceClaimed = $final.WholeFrameEquivalenceClaimed; DataIntegrityVerified = $final.DataIntegrityVerified; PrivateRunRoot = $root; ResultPath = $resultPath; ContactSheet = $contact }
