[CmdletBinding()]
param(
  [string]$BuildRoot='out/build/win-amd64-release',
  [string]$GameRoot='private/game',
  [string]$InitialUserRoot='private/evidence/M5-013/20260817-013319-c2e7223f/runs/01/user'
)

Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$repo=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$verify=Join-Path $PSScriptRoot 'verify-environment-effects-smoke.ps1'
$gameVerify=Join-Path $PSScriptRoot 'verify-game-manifest.ps1'
$cmake=(& (Join-Path $PSScriptRoot 'Resolve-Toolchain.ps1') -ExportPath).CMakePath
$utf8=[Text.UTF8Encoding]::new($false)
$prerequisites=[ordered]@{
  m5_003=@('private/evidence/M5-003/20260814-104624-fde51a30/result.json','299392E59CB38AFB44256E773884856FF0C869A96D2045086A65396C1ED4EFCA')
  m6_001=@('private/evidence/M6-001/20260817-115619-d269e2a9/result.json','519B84FF456BDD3220BFC8BE3DD230CCB209A56CF2B203D51CFF5454729E178F')
  m5_012=@('private/evidence/M5-012/20260817-001225-ade395f8/result.json','D993E2612D1AC769D88264C83FD9C9186BC761E2067317F5A7EB66038C250E58')
  m5_013=@('private/evidence/M5-013/20260817-015958-36eec226/result.json','D890A903775A3B53262B9957E7B7DC1D4B76B49B8735360BECD8233842446298')
  traffic_red=@('private/evidence/M6-004/diagnostic-colored-reflections-20260817-000206/user-captures/traffic-light-000523.png','0ECD702B94586BDE2E9C1566B8C19BE45F4796CBD21C3C736FECD1FED0DBE484')
  traffic_green=@('private/evidence/M6-004/diagnostic-colored-reflections-20260817-000206/user-captures/traffic-light-000529.png','72EA8F650313735F72C4C1E1F0B1EFA325F2402A682FDFDF4247E7197D2D6E9C')
  traffic_off=@('private/evidence/M6-004/diagnostic-colored-reflections-20260817-000206/user-captures/traffic-light-000538.png','D7391B5BA9F963721F178418395E0639FBF91A12DED2DEEDCB9189ECF48A36E7')
}

if(-not('MclaEnvironmentWindow'-as[type])){Add-Type -TypeDefinition @'
using System;using System.Collections.Generic;using System.Runtime.InteropServices;using System.Text;
public static class MclaEnvironmentWindow{delegate bool E(IntPtr h,IntPtr p);[DllImport("user32.dll")]static extern bool EnumWindows(E c,IntPtr p);[DllImport("user32.dll")]static extern uint GetWindowThreadProcessId(IntPtr h,out uint p);[DllImport("user32.dll")]static extern bool IsWindowVisible(IntPtr h);[DllImport("user32.dll",CharSet=CharSet.Unicode)]static extern int GetWindowText(IntPtr h,StringBuilder s,int n);[DllImport("user32.dll")]static extern bool PostMessage(IntPtr h,uint m,IntPtr w,IntPtr l);public static IntPtr[] Handles(int pid){var a=new List<IntPtr>();EnumWindows(delegate(IntPtr h,IntPtr x){uint p;GetWindowThreadProcessId(h,out p);if(p==(uint)pid&&IsWindowVisible(h))a.Add(h);return true;},IntPtr.Zero);return a.ToArray();}public static string Title(IntPtr h){var s=new StringBuilder(1024);int n=GetWindowText(h,s,s.Capacity);return n>0?s.ToString(0,n):String.Empty;}public static bool Close(IntPtr h){return PostMessage(h,0x10,IntPtr.Zero,IntPtr.Zero);}}
'@}
function Safe([string]$Path,[string]$Description,[switch]$Exists){$full=if([IO.Path]::IsPathRooted($Path)){[IO.Path]::GetFullPath($Path)}else{[IO.Path]::GetFullPath((Join-Path $repo $Path))};$prefix=$repo.TrimEnd('\')+'\';if(-not$full.StartsWith($prefix,[StringComparison]::OrdinalIgnoreCase)){throw "$Description escapes repository."};$current=$repo;foreach($part in @($full.Substring($prefix.Length).Split('\')|Where-Object{$_.Length})){$current=Join-Path $current $part;if((Test-Path -LiteralPath $current)-and((Get-Item -LiteralPath $current -Force).Attributes-band[IO.FileAttributes]::ReparsePoint)){throw "$Description traverses a reparse point."}};if($Exists-and-not(Test-Path -LiteralPath $full)){throw "$Description is missing."};$full}
function Hash([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash}
function Tree([string]$Root){$root=Safe $Root 'Tree' -Exists;$items=@(Get-ChildItem -LiteralPath $root -Recurse -Force);foreach($item in $items){if($item.Attributes-band[IO.FileAttributes]::ReparsePoint){throw 'Tree contains a reparse point.'}};$files=@($items|Where-Object{-not$_.PSIsContainer}|Sort-Object FullName);$entries=@();foreach($directory in @($items|Where-Object PSIsContainer|Sort-Object FullName)){$entries+=[ordered]@{kind='directory';path=$directory.FullName.Substring($root.Length).TrimStart('\').Replace('\','/')}};foreach($file in $files){$entries+=[ordered]@{kind='file';path=$file.FullName.Substring($root.Length).TrimStart('\').Replace('\','/');length=[long]$file.Length;sha256=Hash $file.FullName}};$json=ConvertTo-Json -InputObject @($entries) -Compress -Depth 4;$sha=[Security.Cryptography.SHA256]::Create();try{$value=-join($sha.ComputeHash($utf8.GetBytes($json))|ForEach-Object{$_.ToString('X2')})}finally{$sha.Dispose()};$bytes=0L;foreach($file in $files){$bytes+=$file.Length};[pscustomobject]@{Hash=$value;FileCount=$files.Count;DirectoryCount=@($items|Where-Object PSIsContainer).Count;Bytes=$bytes}}
function Game([string]$Root){$tree=Tree $Root;$verified=&$gameVerify -GamePath $Root -VerifyHashes;[ordered]@{file_count=$verified.FileCount;payload_bytes=[long]$verified.PayloadBytes;manifest_sha256=Hash $verified.ManifestPath;tree_sha256=$tree.Hash;tree_file_count=$tree.FileCount;tree_directory_count=$tree.DirectoryCount;tree_bytes=$tree.Bytes}}
function Artifacts([string]$Build){@('mcla.exe','rexruntime.dll','TracyClient.dll','rexgpu-xenos.dll')|ForEach-Object{$path=Safe (Join-Path $Build $_) "Artifact $_" -Exists;[ordered]@{name=$_;sha256=Hash $path}}}
function Processes([string]$Exe){@((Get-Process mcla -ErrorAction SilentlyContinue)|Where-Object{try{[string]::Equals($_.Path,$Exe,[StringComparison]::OrdinalIgnoreCase)}catch{$false}})}
function Contains([string]$Root,[string]$Needle){foreach($file in @(Get-ChildItem -LiteralPath $Root -File -Filter 'mcla*.log' -ErrorAction SilentlyContinue)){try{$stream=[IO.File]::Open($file.FullName,'Open','Read','ReadWrite');try{$reader=[IO.StreamReader]::new($stream);$text=$reader.ReadToEnd();$reader.Dispose()}finally{$stream.Dispose()};if($text.Contains($Needle)){return $true}}catch{}};$false}
function Close-Exact([Diagnostics.Process]$Process){$matches=@();foreach($handle in [MclaEnvironmentWindow]::Handles($Process.Id)){if([regex]::IsMatch([MclaEnvironmentWindow]::Title($handle),'^mcla \[rexglue-v[^\]]+\]$')){$matches+=$handle}};if($matches.Count-ne1-or-not[MclaEnvironmentWindow]::Close($matches[0])){throw 'Exact PID/window WM_CLOSE failed.'}}
function Logged([scriptblock]$Command,[string]$Log,[switch]$Append){$prior=$ErrorActionPreference;$ErrorActionPreference='Continue';try{if($Append){&$Command *>&1|Tee-Object -FilePath $Log -Append|Out-Null}else{&$Command *>&1|Tee-Object -FilePath $Log|Out-Null};$LASTEXITCODE}finally{$ErrorActionPreference=$prior}}

$build=Safe $BuildRoot 'Build root';$game=Safe $GameRoot 'Game root' -Exists;$seed=Safe $InitialUserRoot 'Completed-save seed' -Exists
if($build-cne(Safe 'out/build/win-amd64-release' 'Canonical build')-or$game-cne(Safe 'private/game' 'Canonical game')){throw 'M6-004 requires canonical Release/game inputs.'}
$sdk=Safe 'third_party/rexglue-sdk' 'SDK checkout' -Exists;if((&git -C $sdk rev-parse HEAD).Trim()-cne'576b34fd233acf4579dd2375691dbe86fb4bf8e1'-or(&git -C $sdk describe --tags --exact-match HEAD).Trim()-cne'v0.9.0.22'){throw 'M6-004 requires the exact ReXGlue v0.9.0.22 pin.'}
Write-Host 'M6-004 [1/6]: validating prior rendering, city, race, and known-defect evidence...' -ForegroundColor Cyan
$boundPrerequisites=[ordered]@{};foreach($name in $prerequisites.Keys){$path=Safe $prerequisites[$name][0] "Prerequisite $name" -Exists;$hash=Hash $path;if($hash-cne$prerequisites[$name][1]){throw "Prerequisite '$name' identity failed."};$boundPrerequisites[$name]=$hash}
$seedBefore=Tree $seed;$gameBefore=Game $game
$evidence=Safe 'private/evidence/M6-004' 'M6-004 evidence root';[IO.Directory]::CreateDirectory($evidence)|Out-Null;$runId=(Get-Date -Format 'yyyyMMdd-HHmmss')+'-'+[guid]::NewGuid().ToString('N').Substring(0,8);$root=Join-Path $evidence $runId;[IO.Directory]::CreateDirectory($root)|Out-Null;$buildLog=Join-Path $root 'release-clean-build.log'
Write-Host 'M6-004 [2/6]: clean-building the Release host...' -ForegroundColor Cyan
if(Logged {&$cmake --preset win-amd64-release} $buildLog){throw 'Release configure failed.'};if(Logged {&$cmake --build --preset win-amd64-release --target mcla --clean-first --parallel 8} $buildLog -Append){throw "Release clean build failed. Private run: '$root'."}
$exe=Safe (Join-Path $build 'mcla.exe') 'Release executable' -Exists;if(@(Processes $exe).Count){throw 'Canonical MCLA is already running.'};$artifactsBefore=@(Artifacts $build)
Write-Host 'M6-004 [3/6]: autonomously selecting Arcade RAINY/DAWN and capturing six frames...' -ForegroundColor Cyan
$cycle=Join-Path $root 'runs\01';$user=Join-Path $cycle 'user';$cache=Join-Path $cycle 'cache';[IO.Directory]::CreateDirectory($user)|Out-Null;[IO.Directory]::CreateDirectory($cache)|Out-Null;Get-ChildItem -LiteralPath $seed -Force|Copy-Item -Destination $user -Recurse -Force;if((Tree $user).Hash-cne$seedBefore.Hash){throw 'Cycle did not start from the exact completed save.'}
$log=Join-Path $cycle 'mcla.log';$process=$null;$forced=$false
try{$args=@('--mcla_environment_effects_probe=true','--xam_user_signin_state=2','--mcla_first_frame_settle_seconds=35','--mcla_frontend_gameplay_wait_seconds=30','--input_backend=sdl','--mnk_mode=false','--async_shader_compilation=false','--d3d12_pipeline_creation_threads=0','--log_max_file_size_mb=8','--log_max_files=15','--log_level=info','--fullscreen=false',"--game_data_root=`"$game`"","--user_data_root=`"$user`"","--cache_root=`"$cache`"","--log_file=`"$log`"");$process=Start-Process $exe -ArgumentList $args -WorkingDirectory $build -PassThru;$deadline=[DateTime]::UtcNow.AddSeconds(220);while([DateTime]::UtcNow-lt$deadline){if($process.HasExited){throw "Process exited before environment PASS (exit $($process.ExitCode))."};if(Contains $cycle 'MCLA_ENVIRONMENT_EFFECTS_SUMMARY v=1 status=PASS'){break};Start-Sleep -Milliseconds 250};if(-not(Contains $cycle 'MCLA_ENVIRONMENT_EFFECTS_SUMMARY v=1 status=PASS')){throw 'Environment probe deadline expired.'};Close-Exact $process;if(-not$process.WaitForExit(10000)-or$process.ExitCode-ne0){throw 'Controlled external WM_CLOSE failed.'};if(@(Processes $exe).Count){throw 'Exact-path MCLA process survived close.'}}catch{$failure=$_;if($process-and-not$process.HasExited){$forced=$true;Stop-Process -Id $process.Id -Force -ErrorAction SilentlyContinue;$null=$process.WaitForExit(5000)};if($forced){throw "M6-004 failure required force cleanup. $($failure.Exception.Message) Private run: '$root'."};throw}
Write-Host 'M6-004 [4/6]: verifying causal input, capture chronology, and physical frame differences...' -ForegroundColor Cyan
$probe=&$verify -ProbeOnly -RuntimeLogPath $log -UserRoot $user
Write-Host 'M6-004 [5/6]: revalidating source-game, seed, and Release artifacts...' -ForegroundColor Cyan
$gameAfter=Game $game;$seedAfter=Tree $seed;$artifactsAfter=@(Artifacts $build);if(($gameBefore|ConvertTo-Json -Compress)-cne($gameAfter|ConvertTo-Json -Compress)-or$seedBefore.Hash-cne$seedAfter.Hash-or($artifactsBefore|ConvertTo-Json -Compress)-cne($artifactsAfter|ConvertTo-Json -Compress)){throw 'Source-game, seed, or runtime-artifact identity changed.'}
$cycleTree=Tree $cycle;$scope='Representative deterministic dry-night and Rainy/Dawn Arcade coverage plus inherited night/shadow/particle, time-transition, race-motion, and fixed-camera defect evidence. KI-013, KI-015, and KI-016 remain open S2; no ROV, whole-frame console parity, every weather/time combination, or indefinite HUD stability is claimed.'
$record=[ordered]@{schema='mcla-environment-effects-v1';task='M6-004';decision='representative-environment-effects-pass-open-s2-defects';sdk_version='0.9.0.22';sdk_commit='576b34fd233acf4579dd2375691dbe86fb4bf8e1';build_configuration='Release';build_log=[ordered]@{sha256=Hash $buildLog;bytes=[long](Get-Item -LiteralPath $buildLog).Length};run_id=$runId;prerequisites=$boundPrerequisites;probe=[ordered]@{frames=@($probe.Frames);metrics=$probe.Metrics;runtime_logs=@($probe.LogSet.Files);runtime_log_file_count=$probe.LogSet.Count;runtime_log_bytes=$probe.LogSet.Bytes;runtime_log_set_sha256=$probe.LogSet.Hash;frontend_input_records=72;render_input_records=8;controlled_exit=$true;exit_code=0;harness_force_cleanup=$false;condition_selection='deterministic-arcade-menu-rainy-dawn';machine_ocr_claimed=$false};coverage=[ordered]@{day_night=$true;rainy_weather=$true;wet_reflections=$true;post_processing=$true;motion_blur=$true;shadows=$true;particles=$true;whole_frame_console_parity_claimed=$false};known_issues=[ordered]@{ki_013='open-s2-preserved';ki_015='open-s2-preserved';ki_016='open-s2-intermittent-preserved'};game_before=$gameBefore;game_after=$gameAfter;artifacts_before=$artifactsBefore;artifacts_after=$artifactsAfter;seed_before_sha256=$seedBefore.Hash;seed_after_sha256=$seedAfter.Hash;cycle_tree_sha256=$cycleTree.Hash;cycle_file_count=$cycleTree.FileCount;cycle_directory_count=$cycleTree.DirectoryCount;cycle_bytes=$cycleTree.Bytes;scope=$scope}
$result=Join-Path $root 'result.json';[IO.File]::WriteAllText($result,(ConvertTo-Json $record -Depth 15)+[Environment]::NewLine,$utf8)
Write-Host 'M6-004 [6/6]: revalidating the persisted physical result...' -ForegroundColor Cyan
$final=&$verify -ResultPath $result
[pscustomobject]@{Decision=$final.Decision;DayNightVerified=$final.DayNightVerified;RainyWeatherVerified=$final.RainyWeatherVerified;MotionAndParticlesVerified=$final.MotionAndParticlesVerified;KnownS2DefectsRemainOpen=$final.KnownS2DefectsRemainOpen;ControlledExitVerified=$final.ControlledExitVerified;DataIntegrityVerified=$final.DataIntegrityVerified;ResultPath=$result}
