[CmdletBinding()]
param([string]$BuildRoot='out/build/win-amd64-relwithdebinfo',[string]$GameRoot='private/game',[switch]$SkipCleanBuild)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$repo=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path;$sdk=Join-Path $repo 'third_party/rexglue-sdk';$verify=Join-Path $PSScriptRoot 'verify-audio-route-smoke.ps1';$gameVerify=Join-Path $PSScriptRoot 'verify-game-manifest.ps1';$tc=& (Join-Path $PSScriptRoot 'Resolve-Toolchain.ps1') -ExportPath;$cmake=$tc.CMakePath;$utf8=[Text.UTF8Encoding]::new($false)
if(-not('MclaAudioRouteWindow'-as[type])){Add-Type -TypeDefinition @'
using System;using System.Collections.Generic;using System.Runtime.InteropServices;using System.Text;
public static class MclaAudioRouteWindow{delegate bool E(IntPtr h,IntPtr p);[DllImport("user32.dll")]static extern bool EnumWindows(E c,IntPtr p);[DllImport("user32.dll")]static extern uint GetWindowThreadProcessId(IntPtr h,out uint p);[DllImport("user32.dll")]static extern bool IsWindowVisible(IntPtr h);[DllImport("user32.dll",CharSet=CharSet.Unicode)]static extern int GetWindowText(IntPtr h,StringBuilder s,int n);[DllImport("user32.dll")]static extern bool PostMessage(IntPtr h,uint m,IntPtr w,IntPtr l);public static IntPtr[] Handles(int pid){var a=new List<IntPtr>();EnumWindows(delegate(IntPtr h,IntPtr x){uint p;GetWindowThreadProcessId(h,out p);if(p==(uint)pid&&IsWindowVisible(h))a.Add(h);return true;},IntPtr.Zero);return a.ToArray();}public static string Title(IntPtr h){var s=new StringBuilder(1024);int n=GetWindowText(h,s,s.Capacity);return n>0?s.ToString(0,n):String.Empty;}public static bool Close(IntPtr h){return PostMessage(h,0x10,IntPtr.Zero,IntPtr.Zero);}}
'@}
function Safe([string]$Path,[string]$What,[switch]$Exists){$full=[IO.Path]::GetFullPath($(if([IO.Path]::IsPathRooted($Path)){$Path}else{Join-Path $repo $Path}));$prefix=$repo.TrimEnd('\')+'\';if(-not$full.StartsWith($prefix,[StringComparison]::OrdinalIgnoreCase)){throw "$What escapes the repository."};$cur=$repo;foreach($part in @($full.Substring($prefix.Length).Split('\')|Where-Object Length)){$cur=Join-Path $cur $part;if(Test-Path $cur){if((Get-Item $cur -Force).Attributes-band[IO.FileAttributes]::ReparsePoint){throw "$What traverses a reparse point."}}};if($Exists-and-not(Test-Path $full)){throw "$What is missing."};$full}
function Tree([string]$Root){$items=@(Get-ChildItem $Root -Recurse -Force);$entries=@();$files=@($items|Where-Object{-not$_.PSIsContainer}|Sort-Object FullName);foreach($i in (@((Get-Item $Root -Force))+$items)){if($i.Attributes-band[IO.FileAttributes]::ReparsePoint){throw 'Tree contains a reparse point.'}};foreach($d in @($items|Where-Object PSIsContainer|Sort-Object FullName)){$entries+=[ordered]@{kind='directory';path=$d.FullName.Substring($Root.Length).TrimStart('\').Replace('\','/')}};foreach($f in $files){$entries+=[ordered]@{kind='file';path=$f.FullName.Substring($Root.Length).TrimStart('\').Replace('\','/');length=$f.Length;sha256=(Get-FileHash $f.FullName -Algorithm SHA256).Hash}};$j=ConvertTo-Json -InputObject @($entries)-Compress -Depth 4;$s=[Security.Cryptography.SHA256]::Create();try{$h=-join($s.ComputeHash($utf8.GetBytes($j))|ForEach-Object{$_.ToString('X2')})}finally{$s.Dispose()};$b=0L;foreach($f in $files){$b+=$f.Length};[pscustomobject]@{Hash=$h;FileCount=$files.Count;DirectoryCount=@($items|Where-Object PSIsContainer).Count;Bytes=$b}}
function Game([string]$Root){$t=Tree $Root;$v=&$gameVerify -GamePath $Root -VerifyHashes;[ordered]@{file_count=$v.FileCount;payload_bytes=$v.PayloadBytes;hashes_verified=$v.HashesVerified;manifest_sha256=(Get-FileHash $v.ManifestPath -Algorithm SHA256).Hash;tree_sha256=$t.Hash;tree_file_count=$t.FileCount;tree_directory_count=$t.DirectoryCount;tree_bytes=$t.Bytes}}
function Artifacts([string]$Root){@('mcla.exe','rexruntimerd.dll','TracyClientrd.dll','rexgpu-xenosrd.dll')|ForEach-Object{$p=Safe (Join-Path $Root $_) "Artifact $_" -Exists;[ordered]@{name=$_;sha256=(Get-FileHash $p -Algorithm SHA256).Hash}}}
function Targets([string]$Exe){@((Get-Process mcla -ErrorAction SilentlyContinue)|Where-Object{try{[string]::Equals($_.Path,$Exe,[StringComparison]::OrdinalIgnoreCase)}catch{$false}})}
function LogContains([string]$Dir,[string]$Needle){foreach($f in @(Get-ChildItem $Dir -File -Filter 'mcla*.log' -ErrorAction SilentlyContinue)){try{$stream=[IO.File]::Open($f.FullName,[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::ReadWrite);try{$reader=[IO.StreamReader]::new($stream,$utf8,$true,65536,$false);$text=$reader.ReadToEnd();$reader.Dispose()}finally{$stream.Dispose()};if($text.Contains($Needle)){return $true}}catch{}};$false}
function CloseExact([Diagnostics.Process]$P){$hits=@();foreach($h in ([MclaAudioRouteWindow]::Handles($P.Id))){if([regex]::IsMatch([MclaAudioRouteWindow]::Title($h),'^mcla \[rexglue-v[^\]]+\]$')){$hits+=$h}};if($hits.Count-ne1-or-not[MclaAudioRouteWindow]::Close($hits[0])){throw 'Exact PID/window WM_CLOSE failed.'}}

$build=Safe $BuildRoot 'Build root' -Exists;$game=Safe $GameRoot 'Game root' -Exists;if($build-cne(Safe 'out/build/win-amd64-relwithdebinfo' 'Canonical build')-or$game-cne(Safe 'private/game' 'Canonical game')){throw 'M4-007 requires canonical inputs.'}
$evidence=Safe 'private/evidence/M4-007' 'Evidence root';[IO.Directory]::CreateDirectory($evidence)|Out-Null;$root=Join-Path $evidence ((Get-Date -Format 'yyyyMMdd-HHmmss')+'-'+[guid]::NewGuid().ToString('N').Substring(0,8));$cycle=Join-Path $root 'runs\01';$user=Join-Path $cycle 'user';$cache=Join-Path $cycle 'cache';[IO.Directory]::CreateDirectory($user)|Out-Null;[IO.Directory]::CreateDirectory($cache)|Out-Null
Write-Host 'M4-007 [1/7]: validating canonical inputs and source-game integrity...' -ForegroundColor Cyan;$gameBefore=Game $game
$sdkLog=Join-Path $root 'sdk-install.log';$unitLog=Join-Path $root 'sdk-audio-test.log';$buildLog=Join-Path $root 'relwithdebinfo-clean-build.log'
if(-not$SkipCleanBuild){Write-Host 'M4-007 [2/7]: clean-building and installing ReXGlue SDK...' -ForegroundColor Cyan;Push-Location $sdk;try{&$cmake --preset win-amd64 -DREXGLUE_BUILD_TESTS=ON *>&1|Tee-Object $sdkLog|Out-Null;if($LASTEXITCODE){throw 'SDK configure failed.'};&$cmake --build out/build/win-amd64 --config RelWithDebInfo --target install unit_tests --clean-first --parallel 8 *>&1|Tee-Object $sdkLog -Append|Out-Null;if($LASTEXITCODE){throw 'SDK install/build failed.'}}finally{Pop-Location};Write-Host 'M4-007 [3/7]: running focused audio-route tests...' -ForegroundColor Cyan;$unit=Safe (Join-Path $sdk 'out/win-amd64/RelWithDebInfo/unit_tests.exe') 'Unit tests' -Exists;&$unit '[audio][route-audit]' *>&1|Tee-Object $unitLog|Out-Null;if($LASTEXITCODE){throw 'Focused audio-route tests failed.'};if([IO.File]::ReadAllText($unitLog)-notmatch'All tests passed \(16 assertions in 5 test cases\)'){throw 'Focused audio-route test totals changed.'};Write-Host 'M4-007 [4/7]: clean-building the MCLA host...' -ForegroundColor Cyan;Push-Location $repo;try{&$cmake --preset win-amd64-relwithdebinfo *>&1|Tee-Object $buildLog|Out-Null;if($LASTEXITCODE){throw 'App configure failed.'};&$cmake --build --preset win-amd64-relwithdebinfo --target mcla --clean-first --parallel 8 *>&1|Tee-Object $buildLog -Append|Out-Null;if($LASTEXITCODE){throw 'App clean build failed.'}}finally{Pop-Location}}else{Write-Host 'M4-007 [2-4/7]: reusing the already verified clean build.' -ForegroundColor DarkYellow}
$exe=Safe (Join-Path $build 'mcla.exe') 'MCLA executable' -Exists;if(@(Targets $exe).Count){throw 'Canonical MCLA is already running.'};$artBefore=@(Artifacts $build);$log=Join-Path $cycle 'mcla.log';$bmp=Join-Path $user 'mcla-first-frame.bmp';$p=$null;$forced=$false
Write-Host 'M4-007 [5/7]: launching title, then observing audio for 300 seconds...' -ForegroundColor Cyan
try{$timer=[Diagnostics.Stopwatch]::StartNew();$p=Start-Process $exe -ArgumentList @('--sdl_audio_route_audit=true','--mcla_audio_route_soak_seconds=300','--gpu_render_audit=true','--async_shader_compilation=false','--mcla_first_frame_probe=true','--mcla_first_frame_settle_seconds=35','--render_target_path_d3d12=rtv','--log_max_file_size_mb=5','--log_max_files=15',"--game_data_root=`"$game`"","--user_data_root=`"$user`"","--cache_root=`"$cache`"","--log_file=`"$log`"",'--log_level=info','--fullscreen=false') -WorkingDirectory $build -PassThru;$deadline=[datetime]::UtcNow.AddSeconds(420);$next=60;while([datetime]::UtcNow-lt$deadline){if($p.HasExited){throw 'Process exited during audio soak.'};if((Test-Path $bmp)-and(LogContains $cycle 'MCLA audio: title soak completed seconds 300')-and(LogContains $cycle 'SDL_AUDIO_AUDIT_SUMMARY v=1 phase=title status=PASS')){break};if($timer.Elapsed.TotalSeconds-ge$next){Write-Host ("M4-007 audio soak: {0}/300 seconds after launch..."-f[math]::Min(300,[int]$timer.Elapsed.TotalSeconds)) -ForegroundColor DarkCyan;$next+=60};Start-Sleep -Milliseconds 500};if(-not(Test-Path $bmp)-or-not(LogContains $cycle 'MCLA audio: title soak completed seconds 300')){throw 'Audio/title soak deadline expired.'};$soakMs=$timer.ElapsedMilliseconds;CloseExact $p;$exit=[Diagnostics.Stopwatch]::StartNew();if(-not$p.WaitForExit(10000)-or$p.ExitCode-ne0){throw 'Controlled exit failed.'};$exit.Stop();if(@(Targets $exe).Count){throw 'MCLA process survived controlled exit.'}}
catch{$e=$_;if($p-and-not$p.HasExited){$forced=$true;Stop-Process -Id $p.Id -Force -ErrorAction SilentlyContinue;$null=$p.WaitForExit(5000)};if($forced){throw "M4-007 failure required force cleanup. $($e.Exception.Message) Private run: '$root'."};throw}
$probe=&$verify -ProbeOnly -RuntimeLogPath $log -BmpPath $bmp
Write-Host 'M4-007 [6/7]: rehashing game, runtime artifacts, and private evidence...' -ForegroundColor Cyan;$gameAfter=Game $game;$artAfter=@(Artifacts $build);if(($gameBefore|ConvertTo-Json -Compress)-cne($gameAfter|ConvertTo-Json -Compress)){throw 'Source-game identity changed.'};if(($artBefore|ConvertTo-Json -Compress)-cne($artAfter|ConvertTo-Json -Compress)){throw 'Runtime artifacts changed during the cycle.'}
$record=[ordered]@{runtime_logs=@($probe.LogSet.Files);runtime_log_set_sha256=$probe.LogSet.Hash;capture_sha256=$probe.Bmp.Sha256;submit_frames=$probe.SubmitFrames;submit_nonzero=$probe.SubmitNonzero;device_frames=$probe.DeviceFrames;device_nonzero=$probe.DeviceNonzero;xma_frames=$probe.XmaFrames;xma_nonzero=$probe.XmaNonzero;max_queue_depth=$probe.MaxQueueDepth;starvation_fills=$probe.StarvationFills;max_consecutive_starvation_fills=$probe.MaxConsecutiveStarvation;soak_elapsed_milliseconds=$soakMs;exit_elapsed_milliseconds=$exit.ElapsedMilliseconds;exit_code=0;harness_force_cleanup=$false;cycle_tree_sha256=(Tree $cycle).Hash}
$result=[ordered]@{schema=1;task='M4-007';decision='frontend-audio-route-pass';cycle_count=1;soak_seconds=300;clean_build_performed=(-not$SkipCleanBuild);build=[ordered]@{focused_test_cases=5;focused_test_assertions=16;sdk_install_log_sha256=(Get-FileHash $sdkLog -Algorithm SHA256).Hash;focused_test_log_sha256=(Get-FileHash $unitLog -Algorithm SHA256).Hash;app_build_log_sha256=(Get-FileHash $buildLog -Algorithm SHA256).Hash};game_identity=[ordered]@{before=$gameBefore;after=$gameAfter};artifacts=[ordered]@{before=$artBefore;after=$artAfter};cycle=$record;no_surviving_processes=$true;data_integrity_preserved=$true}
$resultPath=Join-Path $root 'result.json';[IO.File]::WriteAllText($resultPath,(ConvertTo-Json $result -Depth 10)+[Environment]::NewLine,$utf8)
Write-Host 'M4-007 [7/7]: final physical/result verification...' -ForegroundColor Cyan;$final=&$verify -ResultPath $resultPath;[pscustomobject]@{Passed=$final.Passed;Decision=$final.Decision;SoakSeconds=$final.SoakSeconds;SubmitNonzero=$final.SubmitNonzero;DeviceNonzero=$final.DeviceNonzero;XmaNonzero=$final.XmaNonzero;MaxQueueDepth=$final.MaxQueueDepth;MaxConsecutiveStarvation=$final.MaxConsecutiveStarvation;PrivateRunRoot=$root;ResultPath=$resultPath}
