[CmdletBinding()]
param(
    [string]$BuildRoot = 'out/build/win-amd64-relwithdebinfo',
    [string]$GameRoot = 'private/game'
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$repoRoot=(Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '..')).Path
$verifier=Join-Path $PSScriptRoot 'verify-xam-profile-smoke.ps1'
$gameVerifier=Join-Path $PSScriptRoot 'verify-game-manifest.ps1'
$toolchainResolver=Join-Path $PSScriptRoot 'Resolve-Toolchain.ps1'
$sdkRoot=Join-Path $repoRoot 'third_party/rexglue-sdk'
$utf8=[Text.UTF8Encoding]::new($false)
$windowPattern='^mcla \[rexglue-v[^\]]+\]$'
$captureMarker='MCLA graphics: nontrivial guest frame captured '
$summaryMarker='XAM_PROFILE_AUDIT_SUMMARY v=1 phase=checkpoint status=PASS '
$artifactNames=@('mcla.exe','rexruntimerd.dll','TracyClientrd.dll','rexgpu-xenosrd.dll')

if(-not('MclaXamProfileWindow'-as[type])){Add-Type -TypeDefinition @'
using System; using System.Collections.Generic; using System.Runtime.InteropServices; using System.Text;
public static class MclaXamProfileWindow {
  private delegate bool E(IntPtr h,IntPtr p); [DllImport("user32.dll")] static extern bool EnumWindows(E c,IntPtr p);
  [DllImport("user32.dll")] static extern uint GetWindowThreadProcessId(IntPtr h,out uint p); [DllImport("user32.dll")] static extern bool IsWindowVisible(IntPtr h);
  [DllImport("user32.dll",CharSet=CharSet.Unicode)] static extern int GetWindowText(IntPtr h,StringBuilder s,int n); [DllImport("user32.dll")] static extern bool PostMessage(IntPtr h,uint m,IntPtr w,IntPtr l);
  public static IntPtr[] Handles(int pid){var a=new List<IntPtr>();EnumWindows(delegate(IntPtr h,IntPtr x){uint p;GetWindowThreadProcessId(h,out p);if(p==(uint)pid&&IsWindowVisible(h))a.Add(h);return true;},IntPtr.Zero);return a.ToArray();}
  public static string Title(IntPtr h){var s=new StringBuilder(1024);int n=GetWindowText(h,s,s.Capacity);return n>0?s.ToString(0,n):String.Empty;} public static bool Close(IntPtr h){return PostMessage(h,0x10,IntPtr.Zero,IntPtr.Zero);}
}
'@}
function Get-PathInside {param([string]$Path,[string]$Description,[switch]$MustExist)$candidate=if([IO.Path]::IsPathRooted($Path)){$Path}else{Join-Path $repoRoot $Path};$full=[IO.Path]::GetFullPath($candidate);$prefix=$repoRoot.TrimEnd('\')+'\';if(-not$full.StartsWith($prefix,[StringComparison]::OrdinalIgnoreCase)){throw "$Description must stay inside the repository."};$current=$repoRoot;foreach($part in @($full.Substring($prefix.Length).Split('\')|Where-Object{$_.Length})){$current=Join-Path $current $part;if((Test-Path $current)-and((Get-Item $current -Force).Attributes-band[IO.FileAttributes]::ReparsePoint)){throw "$Description traverses a reparse point."}};if($MustExist-and-not(Test-Path $full)){throw "$Description is missing."};$full}
function Get-Tree {param([string]$Root)$items=@(Get-ChildItem $Root -Recurse -Force);$entries=@();$files=@($items|Where-Object{-not$_.PSIsContainer}|Sort-Object FullName);foreach($i in @((Get-Item $Root -Force))+$items){if($i.Attributes-band[IO.FileAttributes]::ReparsePoint){throw 'Tree contains a reparse point.'}};foreach($d in @($items|Where-Object PSIsContainer|Sort-Object FullName)){$entries+=[ordered]@{kind='directory';path=$d.FullName.Substring($Root.Length).TrimStart('\').Replace('\','/')}};foreach($f in $files){$entries+=[ordered]@{kind='file';path=$f.FullName.Substring($Root.Length).TrimStart('\').Replace('\','/');length=$f.Length;sha256=(Get-FileHash $f.FullName -Algorithm SHA256).Hash}};$json=ConvertTo-Json -InputObject @($entries) -Depth 4 -Compress;$sha=[Security.Cryptography.SHA256]::Create();try{$hash=-join($sha.ComputeHash($utf8.GetBytes($json))|ForEach-Object{$_.ToString('X2')})}finally{$sha.Dispose()};$bytes=0L;foreach($f in $files){$bytes+=$f.Length};[pscustomobject]@{Hash=$hash;FileCount=$files.Count;DirectoryCount=@($items|Where-Object PSIsContainer).Count;Bytes=$bytes}}
function Get-Game {param([string]$Root)$t=Get-Tree $Root;$v=&$gameVerifier -GamePath $Root -VerifyHashes;[ordered]@{file_count=$v.FileCount;payload_bytes=$v.PayloadBytes;hashes_verified=$v.HashesVerified;manifest_sha256=(Get-FileHash $v.ManifestPath -Algorithm SHA256).Hash;tree_sha256=$t.Hash;tree_file_count=$t.FileCount;tree_directory_count=$t.DirectoryCount;tree_bytes=$t.Bytes}}
function Get-Artifacts {param([string]$Root)@($artifactNames|ForEach-Object{$p=Get-PathInside(Join-Path $Root $_)"Artifact $_" -MustExist;[ordered]@{name=$_;sha256=(Get-FileHash $p -Algorithm SHA256).Hash}})}
function Get-Targets {param([string]$Exe)@((Get-Process mcla -ErrorAction SilentlyContinue)|Where-Object{try{[string]::Equals($_.Path,$Exe,[StringComparison]::OrdinalIgnoreCase)}catch{$false}})}
function Assert-NoTarget {param([string]$Exe)if(@(Get-Targets $Exe).Count){throw 'Exact canonical MCLA process is already running.'}}
function Test-LogMarkers {param([string]$Current,[string[]]$Markers)$dir=Split-Path -Parent $Current;if(-not(Test-Path $dir)){return $false};$found=@{};foreach($marker in $Markers){$found[$marker]=$false};foreach($file in @(Get-ChildItem $dir -File -Filter 'mcla*.log')){try{$stream=[IO.File]::Open($file.FullName,[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::ReadWrite);try{$reader=[IO.StreamReader]::new($stream,$utf8,$true,65536,$false);$text=$reader.ReadToEnd();$reader.Dispose()}finally{$stream.Dispose()};foreach($marker in $Markers){if(-not$found[$marker]-and$text.Contains($marker)){$found[$marker]=$true}}}catch{}};foreach($marker in $Markers){if(-not$found[$marker]){return $false}};return $true}
function Close-Window {param([Diagnostics.Process]$Process)$m=@();foreach($h in [MclaXamProfileWindow]::Handles($Process.Id)){if([regex]::IsMatch([MclaXamProfileWindow]::Title($h),$windowPattern)){$m+=$h}};if($m.Count-ne1-or-not[MclaXamProfileWindow]::Close($m[0])){throw 'Exact PID/window WM_CLOSE contract failed.'}}
function Assert-Prior {param([Collections.ArrayList]$Prior)foreach($p in $Prior){if((Get-Tree $p.Root).Hash-ne$p.Hash){throw 'A prior cycle mutated.'}}}

$build=Get-PathInside $BuildRoot 'Build root' -MustExist;$game=Get-PathInside $GameRoot 'Game root' -MustExist
if(-not[string]::Equals($build,[IO.Path]::GetFullPath((Join-Path $repoRoot 'out/build/win-amd64-relwithdebinfo')),[StringComparison]::OrdinalIgnoreCase)-or-not[string]::Equals($game,[IO.Path]::GetFullPath((Join-Path $repoRoot 'private/game')),[StringComparison]::OrdinalIgnoreCase)){throw 'M4-004 final gate requires canonical inputs.'}
foreach($p in @($verifier,$gameVerifier,$toolchainResolver,(Join-Path $sdkRoot 'CMakePresets.json'),(Join-Path $game 'default.xex'))){[void](Get-PathInside $p 'Required input' -MustExist)}
$evidence=Get-PathInside 'private/evidence/M4-004' 'Evidence root';[IO.Directory]::CreateDirectory($evidence)|Out-Null;$runRoot=Join-Path $evidence ((Get-Date -Format 'yyyyMMdd-HHmmss')+'-'+[guid]::NewGuid().ToString('N').Substring(0,8));$runs=Join-Path $runRoot 'runs';[IO.Directory]::CreateDirectory($runs)|Out-Null
$sdkLog=Join-Path $runRoot 'sdk-install.log';$profileTestLog=Join-Path $runRoot 'sdk-profile-test.log';$buildLog=Join-Path $runRoot 'relwithdebinfo-clean-build.log';$toolchain=&$toolchainResolver -ExportPath;$cmake=$toolchain.CMakePath;$gameBefore=Get-Game $game
$timer=[Diagnostics.Stopwatch]::StartNew();Push-Location $sdkRoot;try{&$cmake --preset win-amd64 -DREXGLUE_BUILD_TESTS=ON *>&1|Tee-Object -FilePath $sdkLog|Out-Null;if($LASTEXITCODE-ne0){throw "SDK configure failed with exit $LASTEXITCODE."};&$cmake --build out/build/win-amd64 --config RelWithDebInfo --target install --clean-first --parallel *>&1|Tee-Object -FilePath $sdkLog -Append|Out-Null;if($LASTEXITCODE-ne0){throw "SDK install failed with exit $LASTEXITCODE."};&$cmake --build out/build/win-amd64 --config RelWithDebInfo --target unit_tests --parallel *>&1|Tee-Object -FilePath $sdkLog -Append|Out-Null;$sdkExit=$LASTEXITCODE}finally{Pop-Location};$timer.Stop();if($sdkExit-ne0){throw "SDK install/unit build failed with exit $sdkExit. Private run: '$runRoot'."};$sdkMs=$timer.ElapsedMilliseconds
$unitExe=Get-PathInside (Join-Path $sdkRoot 'out/win-amd64/RelWithDebInfo/unit_tests.exe') 'SDK focused unit test executable' -MustExist;$timer.Restart();&$unitExe '[kernel][xam][profile]' *>&1|Tee-Object -FilePath $profileTestLog|Out-Null;$profileTestExit=$LASTEXITCODE;$timer.Stop();if($profileTestExit-ne0){throw "Focused SDK profile tests failed with exit $profileTestExit. Private run: '$runRoot'."};$profileTestMs=$timer.ElapsedMilliseconds;$profileTestText=[IO.File]::ReadAllText($profileTestLog);if($profileTestText-notmatch'All tests passed \(15 assertions in 2 test cases\)'){throw "Focused SDK profile test totals changed. Private run: '$runRoot'."}
$timer.Restart();Push-Location $repoRoot;try{&$cmake --preset win-amd64-relwithdebinfo *>&1|Tee-Object -FilePath $buildLog|Out-Null;if($LASTEXITCODE-ne0){throw "App configure failed with exit $LASTEXITCODE."};&$cmake --build --preset win-amd64-relwithdebinfo --target mcla --clean-first --parallel *>&1|Tee-Object -FilePath $buildLog -Append|Out-Null;$buildExit=$LASTEXITCODE}finally{Pop-Location};$timer.Stop();if($buildExit-ne0){throw "App clean build failed with exit $buildExit. Private run: '$runRoot'."};$buildMs=$timer.ElapsedMilliseconds
$exe=Join-Path $build 'mcla.exe';Assert-NoTarget $exe;$artifactsBefore=Get-Artifacts $build;$records=@();$prior=[Collections.ArrayList]::new()
for($cycle=1;$cycle-le3;$cycle++){Assert-Prior $prior;Assert-NoTarget $exe;$name='{0:D2}'-f$cycle;$root=Join-Path $runs $name;$user=Join-Path $root 'user';$cache=Join-Path $root 'cache';[IO.Directory]::CreateDirectory($user)|Out-Null;[IO.Directory]::CreateDirectory($cache)|Out-Null;$log=Join-Path $root 'mcla.log';$bmp=Join-Path $user 'mcla-first-frame.bmp';$process=$null;$forced=$false
 try{$capture=[Diagnostics.Stopwatch]::StartNew();$process=Start-Process $exe -ArgumentList @('--xam_profile_audit=true','--gpu_render_audit=true','--async_shader_compilation=false','--mcla_first_frame_probe=true','--mcla_first_frame_settle_seconds=35','--render_target_path_d3d12=rtv','--log_max_file_size_mb=5','--log_max_files=15',"--game_data_root=`"$game`"","--user_data_root=`"$user`"","--cache_root=`"$cache`"","--log_file=`"$log`"",'--log_level=trace','--fullscreen=false') -WorkingDirectory $build -PassThru;$ready=$false;while($capture.ElapsedMilliseconds-lt60000){if($process.HasExited){throw 'Process exited before profile/title checkpoint.'};if((Test-Path $bmp)-and(Test-LogMarkers $log @($captureMarker,$summaryMarker))){$ready=$true;break};Start-Sleep -Milliseconds 250};$capture.Stop();if(-not$ready){throw '60-second profile/title deadline expired.'};$dwell=[Diagnostics.Stopwatch]::StartNew();while($dwell.ElapsedMilliseconds-lt2000){Start-Sleep -Milliseconds 50};$dwell.Stop();if($process.HasExited){throw 'Process exited during dwell.'};Close-Window $process;$exit=[Diagnostics.Stopwatch]::StartNew();$signaled=$process.WaitForExit(10000);$exit.Stop();if(-not$signaled-or$process.ExitCode-ne0){throw 'Controlled exit contract failed.'};Assert-NoTarget $exe;$p=&$verifier -ProbeOnly -RuntimeLogPath $log -BmpPath $bmp;$u=Get-Tree $user;$k=Get-Tree $cache;$records+=[ordered]@{index=$cycle;capture_elapsed_milliseconds=$capture.ElapsedMilliseconds;dwell_elapsed_milliseconds=$dwell.ElapsedMilliseconds;exit_elapsed_milliseconds=$exit.ElapsedMilliseconds;exit_code=0;close_requested=$true;harness_force_cleanup=$false;process_signal_confirmed=$true;process_cleanup_confirmed=$true;prior_cycles_immutable=$true;runtime_logs=@($p.LogSet.Files);runtime_log_file_count=$p.LogSet.Count;runtime_log_bytes=$p.LogSet.Bytes;runtime_log_set_sha256=$p.LogSet.Hash;capture_relative_path="runs/$name/user/mcla-first-frame.bmp";capture_sha256=$p.Title.Bmp.Sha256;capture_bytes=$p.Title.Bmp.Bytes;logo_edge_correlation_ppm=$p.Title.Roi.LogoCorrelationPpm;press_edge_correlation_ppm=$p.Title.Roi.PressCorrelationPpm;resolve_calls=$p.Title.Audit.ResolveCalls;draw_issued=$p.Title.Audit.DrawIssued;profile_config_count=1;profile_summary_count=1;signin_records=$p.SigninRecords;xuid_records=$p.XuidRecords;profile_read_records=$p.ReadRecords;privilege_records=$p.PrivilegeRecords;name_records=$p.NameRecords;signin_info_records=$p.InfoRecords;signin_ui_records=$p.UiRecords;user_tree_sha256=$u.Hash;cache_tree_sha256=$k.Hash;cycle_tree_sha256=('0'*64);user_file_count=$u.FileCount;cache_file_count=$k.FileCount;user_bytes=$u.Bytes;cache_bytes=$k.Bytes}}
 catch{$failure=$_;if($process-and-not$process.HasExited){$forced=$true;Stop-Process -Id $process.Id -Force -ErrorAction SilentlyContinue;$null=$process.WaitForExit(5000)};if($forced){throw "M4-004 failure required force cleanup. $($failure.Exception.Message) Private run: '$runRoot'."};throw};$t=Get-Tree $root;$records[-1].cycle_tree_sha256=$t.Hash;[void]$prior.Add([pscustomobject]@{Root=$root;Hash=$t.Hash})}
Assert-Prior $prior;Assert-NoTarget $exe;$gameAfter=Get-Game $game;$artifactsAfter=Get-Artifacts $build
$result=[ordered]@{schema=1;task='M4-004';decision='single-local-offline-profile';cycle_count=3;capture_timeout_seconds=60;first_frame_settle_seconds=35;post_marker_dwell_milliseconds=2000;exit_timeout_seconds=10;clean_build=[ordered]@{sdk_install_performed=$true;sdk_install_success=$true;sdk_install_exit_code=0;sdk_install_duration_milliseconds=$sdkMs;sdk_install_log_sha256=(Get-FileHash $sdkLog -Algorithm SHA256).Hash;sdk_profile_test_performed=$true;sdk_profile_test_success=$true;sdk_profile_test_exit_code=0;sdk_profile_test_duration_milliseconds=$profileTestMs;sdk_profile_test_cases=2;sdk_profile_test_assertions=15;sdk_profile_test_log_sha256=(Get-FileHash $profileTestLog -Algorithm SHA256).Hash;sdk_profile_test_executable_sha256=(Get-FileHash $unitExe -Algorithm SHA256).Hash;app_clean_build_performed=$true;app_clean_build_success=$true;app_clean_build_exit_code=0;app_clean_build_duration_milliseconds=$buildMs;app_clean_build_log_sha256=(Get-FileHash $buildLog -Algorithm SHA256).Hash;executable_sha256=(Get-FileHash $exe -Algorithm SHA256).Hash};game_identity=[ordered]@{before=$gameBefore;after=$gameAfter};artifacts=[ordered]@{before=$artifactsBefore;after=$artifactsAfter};cycles=$records;all_write_roots_contained=$true;all_prior_cycles_immutable=$true;no_surviving_processes=$true;data_integrity_preserved=$true;all_title_probes_passed=$true;all_profile_probes_passed=$true}
$resultPath=Join-Path $runRoot 'result.json';[IO.File]::WriteAllText($resultPath,(($result|ConvertTo-Json -Depth 10)+[Environment]::NewLine),$utf8);$verified=&$verifier -ResultPath $resultPath;[pscustomobject]@{Passed=$verified.Passed;Decision=$verified.Decision;Cycles=$verified.Cycles;PrivateRunRoot=$runRoot;ResultPath=$resultPath}
