[CmdletBinding()]
param([string]$BuildRoot='out/build/win-amd64-release',[string]$GameRoot='private/game')

Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$repo=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$verifier=Join-Path $PSScriptRoot 'verify-physics-timing-smoke.ps1'
$gameVerifier=Join-Path $PSScriptRoot 'verify-game-manifest.ps1'
$toolchain=& (Join-Path $PSScriptRoot 'Resolve-Toolchain.ps1') -ExportPath
$cmake=$toolchain.CMakePath;$utf8=[Text.UTF8Encoding]::new($false)
$seed=Join-Path $repo 'private/baseline/M4-011/post-oobe-profile'
$sdk=Join-Path $repo 'third_party/rexglue-sdk'

if(-not('MclaPhysicsWindow'-as[type])){Add-Type -TypeDefinition @'
using System;using System.Collections.Generic;using System.Runtime.InteropServices;using System.Text;
public static class MclaPhysicsWindow{delegate bool E(IntPtr h,IntPtr p);[DllImport("user32.dll")]static extern bool EnumWindows(E c,IntPtr p);[DllImport("user32.dll")]static extern uint GetWindowThreadProcessId(IntPtr h,out uint p);[DllImport("user32.dll")]static extern bool IsWindowVisible(IntPtr h);[DllImport("user32.dll",CharSet=CharSet.Unicode)]static extern int GetWindowText(IntPtr h,StringBuilder s,int n);[DllImport("user32.dll")]static extern bool PostMessage(IntPtr h,uint m,IntPtr w,IntPtr l);public static IntPtr[] Handles(int pid){var a=new List<IntPtr>();EnumWindows(delegate(IntPtr h,IntPtr x){uint p;GetWindowThreadProcessId(h,out p);if(p==(uint)pid&&IsWindowVisible(h))a.Add(h);return true;},IntPtr.Zero);return a.ToArray();}public static string Title(IntPtr h){var s=new StringBuilder(1024);int n=GetWindowText(h,s,s.Capacity);return n>0?s.ToString(0,n):String.Empty;}public static bool Close(IntPtr h){return PostMessage(h,0x10,IntPtr.Zero,IntPtr.Zero);}}
'@}

function Resolve-SafePath([string]$Path,[string]$Description,[switch]$Exists){$full=if([IO.Path]::IsPathRooted($Path)){[IO.Path]::GetFullPath($Path)}else{[IO.Path]::GetFullPath((Join-Path $repo $Path))};$prefix=$repo.TrimEnd('\')+'\';if(-not$full.StartsWith($prefix,[StringComparison]::OrdinalIgnoreCase)){throw "$Description escapes repository."};$current=$repo;foreach($part in @($full.Substring($prefix.Length).Split('\')|Where-Object{$_.Length})){$current=Join-Path $current $part;if((Test-Path -LiteralPath $current)-and((Get-Item -LiteralPath $current -Force).Attributes-band[IO.FileAttributes]::ReparsePoint)){throw "$Description traverses a reparse point."}};if($Exists-and-not(Test-Path -LiteralPath $full)){throw "$Description is missing."};$full}
function Assert-NoReparseTree([string]$Root){$pending=[Collections.Generic.Stack[string]]::new();$pending.Push($Root);while($pending.Count){foreach($item in @(Get-ChildItem -LiteralPath $pending.Pop() -Force)){if($item.Attributes-band[IO.FileAttributes]::ReparsePoint){throw 'Tree contains a reparse point.'};if($item.PSIsContainer){$pending.Push($item.FullName)}}}}
function Get-TreeSnapshot([string]$Root){$rootPath=Resolve-SafePath $Root 'Tree' -Exists;Assert-NoReparseTree $rootPath;$items=@(Get-ChildItem -LiteralPath $rootPath -Recurse -Force);$files=@($items|Where-Object{-not$_.PSIsContainer-and-not($_.FullName-ceq(Join-Path $rootPath 'result.json'))}|Sort-Object FullName);$entries=@();$bytes=0L;foreach($directory in @($items|Where-Object{$_.PSIsContainer}|Sort-Object FullName)){$entries+=[ordered]@{kind='directory';path=$directory.FullName.Substring($rootPath.Length).TrimStart('\').Replace('\','/')}};foreach($file in $files){$bytes+=$file.Length;$entries+=[ordered]@{kind='file';path=$file.FullName.Substring($rootPath.Length).TrimStart('\').Replace('\','/');bytes=$file.Length;sha256=(Get-FileHash -LiteralPath $file.FullName -Algorithm SHA256).Hash}};$json=ConvertTo-Json -InputObject @($entries) -Compress -Depth 4;$sha=[Security.Cryptography.SHA256]::Create();try{$hash=-join($sha.ComputeHash($utf8.GetBytes($json))|ForEach-Object{$_.ToString('X2')})}finally{$sha.Dispose()};[pscustomobject]@{Hash=$hash;FileCount=$files.Count;DirectoryCount=@($items|Where-Object{$_.PSIsContainer}).Count;Bytes=$bytes}}
function Get-GameIdentity([string]$Root){$tree=Get-TreeSnapshot $Root;$verified=&$gameVerifier -GamePath $Root -VerifyHashes;[ordered]@{file_count=[int]$verified.FileCount;payload_bytes=[int64]$verified.PayloadBytes;manifest_sha256=(Get-FileHash -LiteralPath $verified.ManifestPath -Algorithm SHA256).Hash;tree_sha256=$tree.Hash;tree_file_count=$tree.FileCount;tree_directory_count=$tree.DirectoryCount;tree_bytes=$tree.Bytes}}
function Get-Artifacts([string]$Root){@('mcla.exe','rexruntime.dll','TracyClient.dll','rexgpu-xenos.dll')|ForEach-Object{$path=Resolve-SafePath (Join-Path $Root $_) "Artifact $_" -Exists;[ordered]@{name=$_;sha256=(Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash}}}
function Get-ExactProcesses([string]$Executable){@((Get-Process mcla -ErrorAction SilentlyContinue)|Where-Object{try{[string]::Equals($_.Path,$Executable,[StringComparison]::OrdinalIgnoreCase)}catch{$false}})}
function Test-Log([string]$Directory,[string]$Needle){foreach($file in @(Get-ChildItem -LiteralPath $Directory -File -Filter 'mcla*.log' -ErrorAction SilentlyContinue)){try{$stream=[IO.File]::Open($file.FullName,'Open','Read','ReadWrite');try{$reader=[IO.StreamReader]::new($stream);$text=$reader.ReadToEnd();$reader.Dispose()}finally{$stream.Dispose()};if($text.Contains($Needle)){return $true}}catch{}};$false}
function Close-ExactWindow([Diagnostics.Process]$Process){$matches=@();foreach($handle in [MclaPhysicsWindow]::Handles($Process.Id)){if([regex]::IsMatch([MclaPhysicsWindow]::Title($handle),'^mcla \[rexglue-v[^\]]+\]$')){$matches+=$handle}};if($matches.Count-ne1-or-not[MclaPhysicsWindow]::Close($matches[0])){throw 'Exact PID/window WM_CLOSE failed.'}}
function Invoke-Logged([scriptblock]$Command,[string]$Log,[switch]$Append){$prior=$ErrorActionPreference;$ErrorActionPreference='Continue';try{if($Append){&$Command *>&1|Tee-Object -FilePath $Log -Append|Out-Null}else{&$Command *>&1|Tee-Object -FilePath $Log|Out-Null};$LASTEXITCODE}finally{$ErrorActionPreference=$prior}}

$build=Resolve-SafePath $BuildRoot 'Build root' -Exists;$game=Resolve-SafePath $GameRoot 'Game root' -Exists
if(-not[string]::Equals($build,(Resolve-SafePath 'out/build/win-amd64-release' 'Canonical build' -Exists),[StringComparison]::OrdinalIgnoreCase)-or-not[string]::Equals($game,(Resolve-SafePath 'private/game' 'Canonical game' -Exists),[StringComparison]::OrdinalIgnoreCase)){throw 'M5-008 requires canonical Release build and game roots.'}
Assert-NoReparseTree (Resolve-SafePath $seed 'Pinned save' -Exists)
$seedSave=(Get-FileHash -LiteralPath (Join-Path $seed 'B13EBABEBABEBABE/545407F8/00000001/mc4.sav/mc4.sav') -Algorithm SHA256).Hash;$seedHeader=(Get-FileHash -LiteralPath (Join-Path $seed 'B13EBABEBABEBABE/545407F8/Headers/00000001/mc4.sav.header') -Algorithm SHA256).Hash
if($seedSave-cne'E8B559E1F2D03341B1147CAB4F5A3F3C778E6E9633B0B04B9908360FA2C67D68'-or$seedHeader-cne'1DAEF55FA78BDD3F1AA75A36772B801C6C714B6D1A115A97904F3D1C957BC4C9'){throw 'Pinned save identity failed.'}
$tag=(&git -C $sdk describe --tags --exact-match HEAD 2>$null).Trim();if($LASTEXITCODE-ne0-or$tag-cne'v0.9.0.20'){throw 'M5-008 requires exact ReXGlue v0.9.0.20.'};$sdkCommit=(&git -C $sdk rev-parse HEAD).Trim()
$evidence=Resolve-SafePath 'private/evidence/M5-008' 'Evidence root';[IO.Directory]::CreateDirectory($evidence)|Out-Null;$runRoot=Join-Path $evidence ((Get-Date -Format 'yyyyMMdd-HHmmss')+'-'+[guid]::NewGuid().ToString('N').Substring(0,8));[IO.Directory]::CreateDirectory($runRoot)|Out-Null;$buildLog=Join-Path $runRoot 'release-clean-build.log'

Write-Host 'M5-008 [1/5]: validating stock image, save, and SDK identity...' -ForegroundColor Cyan;$gameBefore=Get-GameIdentity $game
Write-Host 'M5-008 [2/5]: clean-building the MCLA host...' -ForegroundColor Cyan
if((Invoke-Logged {&$cmake --preset win-amd64-release} $buildLog)-ne0-or(Invoke-Logged {&$cmake --build --preset win-amd64-release --target mcla --clean-first --parallel 8} $buildLog -Append)-ne0){throw "Clean Release build failed. Private run: '$runRoot'."}
$exe=Resolve-SafePath (Join-Path $build 'mcla.exe') 'Executable' -Exists;if(@(Get-ExactProcesses $exe).Count){throw 'Canonical MCLA process is already running.'};$artifactsBefore=@(Get-Artifacts $build)

Write-Host 'M5-008 [3/5]: running three isolated 10-second stock-timing samples...' -ForegroundColor Cyan
for($cycle=1;$cycle-le3;$cycle++){
  Write-Host ("M5-008 cycle {0}/3: title -> saved gameplay -> fixed throttle..."-f$cycle) -ForegroundColor DarkCyan
  $cycleRoot=Join-Path $runRoot ('runs/{0:D2}'-f$cycle);$user=Join-Path $cycleRoot 'user';$cache=Join-Path $cycleRoot 'cache';[IO.Directory]::CreateDirectory($user)|Out-Null;[IO.Directory]::CreateDirectory($cache)|Out-Null;Get-ChildItem -LiteralPath $seed -Force|Copy-Item -Destination $user -Recurse -Force;$log=Join-Path $cycleRoot 'mcla.log';$process=$null;$forced=$false
  try{$args=@('--mcla_physics_timing_probe=true','--mcla_first_frame_settle_seconds=45','--mcla_frontend_gameplay_wait_seconds=45','--async_shader_compilation=false','--d3d12_pipeline_creation_threads=0','--log_max_file_size_mb=8','--log_max_files=15','--log_level=info','--fullscreen=false',"--game_data_root=$game","--user_data_root=$user","--cache_root=$cache","--log_file=$log");$process=Start-Process $exe -ArgumentList $args -WorkingDirectory $build -PassThru;$deadline=[DateTime]::UtcNow.AddSeconds(210);while([DateTime]::UtcNow-lt$deadline-and-not$process.HasExited-and-not(Test-Log $cycleRoot 'MCLA_PHYSICS_TIMING_SUMMARY v=1 status=COMPLETE')){Start-Sleep -Milliseconds 250};if($process.HasExited){throw "Process exited early with $($process.ExitCode)."};if(-not(Test-Log $cycleRoot 'MCLA_PHYSICS_TIMING_SUMMARY v=1 status=COMPLETE')){throw 'Timing deadline expired.'};Close-ExactWindow $process;if(-not$process.WaitForExit(10000)-or$process.ExitCode-ne0){throw 'Controlled WM_CLOSE failed.'};if(@(Get-ExactProcesses $exe).Count){throw 'Exact-path MCLA process survived close.'}}
  catch{$failure=$_;if($null-ne$process-and-not$process.HasExited){$forced=$true;Stop-Process -Id $process.Id -Force -ErrorAction SilentlyContinue;$null=$process.WaitForExit(5000)};if($forced){throw "M5-008 failure required force cleanup. $($failure.Exception.Message) Private run: '$runRoot'."};throw}
}

Write-Host 'M5-008 [4/5]: physically verifying timing, frames, and lifecycle...' -ForegroundColor Cyan;$probe=&$verifier -RunPath $runRoot
$gameAfter=Get-GameIdentity $game;$artifactsAfter=@(Get-Artifacts $build);if((ConvertTo-Json $gameBefore -Compress -Depth 5)-cne(ConvertTo-Json $gameAfter -Compress -Depth 5)-or(ConvertTo-Json $artifactsBefore -Compress -Depth 4)-cne(ConvertTo-Json $artifactsAfter -Compress -Depth 4)){throw 'Game or runtime artifacts drifted.'}
$tree=Get-TreeSnapshot $runRoot;$record=[ordered]@{schema='mcla-physics-timing-v1';task='M5-008';decision=$probe.decision;sdk_version='0.9.0.20';sdk_commit=$sdkCommit;build_configuration='Release';stock_30_target=$true;stock_speed_sustained=$true;actual_output_30fps_sustained=$true;fixed_step_microseconds=33333;cycle_count=3;seed_save_sha256=$seedSave;seed_header_sha256=$seedHeader;game_before=$gameBefore;game_after=$gameAfter;artifacts_before=@($artifactsBefore);artifacts_after=@($artifactsAfter);build_log_sha256=(Get-FileHash -LiteralPath $buildLog -Algorithm SHA256).Hash;cycles=@($probe.cycles);evidence_tree_sha256=$tree.Hash;evidence_tree_file_count=$tree.FileCount;evidence_tree_directory_count=$tree.DirectoryCount;evidence_tree_bytes=$tree.Bytes;scope='production Release baseline at the stock 30-FPS target with a fixed 33.333-ms game step and real-time guest/output throughput'}
$result=Join-Path $runRoot 'result.json';[IO.File]::WriteAllText($result,(ConvertTo-Json $record -Depth 10),$utf8)
Write-Host 'M5-008 [5/5]: revalidating the persisted physical result...' -ForegroundColor Cyan;$verified=&$verifier -ResultPath $result
Write-Host "M5-008 PASS: fixed 33.333-ms step, synchronized guest clock, 60-Hz vblank, and real-time 30-Hz Release throughput verified. Result: '$result'." -ForegroundColor Green
$verified
