[CmdletBinding()]
param(
  [ValidateRange(3600,3600)][int]$DurationSeconds=3600,
  [switch]$ValidateOnly
)

Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$repo=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$build=Join-Path $repo 'out/build/win-amd64-release'
$game=Join-Path $repo 'private/game'
$suitePath=Join-Path $repo 'private/evidence/M6-014/20260901-153415-d747cf2d/suite.json'
$deliveryPath=Join-Path $repo 'private/evidence/M6-014/delivery-regressions/20260901-203448-d31ab681/result.json'
$archiveRoot=Join-Path $repo 'private/save-archive/M6-014'
$versionPath=Join-Path $repo 'VERSION'
$historicalSuitePath=Join-Path $repo 'private/evidence/M6-014/20260831-133236-2cecb67b/suite.json'
$historicalFrontendRoot=Join-Path $repo 'private/evidence/M6-014/20260831-133236-2cecb67b/scenarios/frontend'
$historicalFrontendStage=Join-Path $historicalFrontendRoot 'stage.json'
$gameVerifier=Join-Path $PSScriptRoot 'verify-game-manifest.ps1'
$deliveryVerifier=Join-Path $PSScriptRoot 'verify-delivery-transition-regression.ps1'
$saveWatcher=Join-Path $PSScriptRoot 'watch-soak-save.ps1'
$verify=Join-Path $PSScriptRoot 'verify-mixed-gameplay-long-session.ps1'
$pwshHost=(Get-Process -Id $PID).Path
$utf8=[Text.UTF8Encoding]::new($false)
$artifactNames=@('mcla.exe','mcla_crash_handler.exe','rexruntime.dll','TracyClient.dll','rexgpu-xenos.dll')
$saveRelative='B13EBABEBABEBABE/545407F8/00000001/mc4.sav/mc4.sav'
$headerRelative='B13EBABEBABEBABE/545407F8/Headers/00000001/mc4.sav.header'

if(-not('MclaMixedLongSessionNative'-as[type])){Add-Type -AssemblyName System.Drawing;Add-Type -TypeDefinition @'
using System;using System.Collections.Generic;using System.Runtime.InteropServices;using System.Text;
public static class MclaMixedLongSessionNative{
  public struct RECT{public int Left,Top,Right,Bottom;}public struct POINT{public int X,Y;}[StructLayout(LayoutKind.Sequential)]public struct IO{public ulong ReadOperationCount,WriteOperationCount,OtherOperationCount,ReadTransferCount,WriteTransferCount,OtherTransferCount;}
  delegate bool E(IntPtr h,IntPtr p);[DllImport("user32.dll")]static extern bool EnumWindows(E c,IntPtr p);[DllImport("user32.dll")]static extern uint GetWindowThreadProcessId(IntPtr h,out uint p);[DllImport("user32.dll")]static extern bool IsWindowVisible(IntPtr h);[DllImport("user32.dll",CharSet=CharSet.Unicode)]static extern int GetWindowText(IntPtr h,StringBuilder s,int n);[DllImport("user32.dll")]static extern bool GetClientRect(IntPtr h,out RECT r);[DllImport("user32.dll")]static extern bool ClientToScreen(IntPtr h,ref POINT p);[DllImport("user32.dll")]public static extern bool SetForegroundWindow(IntPtr h);[DllImport("user32.dll")]public static extern IntPtr GetForegroundWindow();[DllImport("user32.dll")]static extern bool BringWindowToTop(IntPtr h);[DllImport("user32.dll")]static extern bool ShowWindow(IntPtr h,int c);[DllImport("user32.dll")]static extern IntPtr SetFocus(IntPtr h);[DllImport("user32.dll")]static extern bool AttachThreadInput(uint attach,uint attachTo,bool value);[DllImport("kernel32.dll")]static extern uint GetCurrentThreadId();[DllImport("user32.dll")]public static extern bool PostMessage(IntPtr h,uint m,IntPtr w,IntPtr l);[DllImport("kernel32.dll",SetLastError=true)]public static extern bool GetProcessIoCounters(IntPtr h,out IO c);
  public static IntPtr[] Handles(int pid){var a=new List<IntPtr>();EnumWindows(delegate(IntPtr h,IntPtr x){uint p;GetWindowThreadProcessId(h,out p);if(p==(uint)pid&&IsWindowVisible(h))a.Add(h);return true;},IntPtr.Zero);return a.ToArray();}public static string Title(IntPtr h){var s=new StringBuilder(1024);int n=GetWindowText(h,s,s.Capacity);return n>0?s.ToString(0,n):String.Empty;}public static bool FocusWindow(IntPtr h){IntPtr foreground=GetForegroundWindow();uint unused;uint foregroundThread=foreground==IntPtr.Zero?0:GetWindowThreadProcessId(foreground,out unused);uint targetThread=GetWindowThreadProcessId(h,out unused);uint currentThread=GetCurrentThreadId();bool foregroundAttached=foregroundThread!=0&&foregroundThread!=currentThread&&AttachThreadInput(currentThread,foregroundThread,true);bool targetAttached=targetThread!=0&&targetThread!=currentThread&&targetThread!=foregroundThread&&AttachThreadInput(currentThread,targetThread,true);try{ShowWindow(h,9);BringWindowToTop(h);SetForegroundWindow(h);SetFocus(h);return GetForegroundWindow()==h;}finally{if(targetAttached)AttachThreadInput(currentThread,targetThread,false);if(foregroundAttached)AttachThreadInput(currentThread,foregroundThread,false);}}public static int[] Client(IntPtr h){RECT r;if(!GetClientRect(h,out r))return new int[0];var p=new POINT();if(!ClientToScreen(h,ref p))return new int[0];return new[]{p.X,p.Y,r.Right-r.Left,r.Bottom-r.Top};}
}
'@}

function Safe([string]$Path,[string]$Description,[switch]$Exists){$full=[IO.Path]::GetFullPath($Path);$prefix=$repo.TrimEnd('\')+'\';if(-not$full.StartsWith($prefix,[StringComparison]::OrdinalIgnoreCase)){throw "$Description escapes repository."};$cursor=$repo;foreach($part in @($full.Substring($prefix.Length).Split('\')|Where-Object Length)){$cursor=Join-Path $cursor $part;if((Test-Path -LiteralPath $cursor)-and((Get-Item -LiteralPath $cursor -Force).Attributes-band[IO.FileAttributes]::ReparsePoint)){throw "$Description traverses a reparse point."}};if($Exists-and-not(Test-Path -LiteralPath $full)){throw "$Description is missing."};$full}
function Hash([string]$Path){$stream=[IO.File]::OpenRead((Safe $Path 'Hash source' -Exists));$sha=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($sha.ComputeHash($stream))).Replace('-','')}finally{$sha.Dispose();$stream.Dispose()}}
function Tree([string]$Root){$sha=[Security.Cryptography.SHA256]::Create();try{$files=@(Get-ChildItem -LiteralPath $Root -File -Recurse -Force|Sort-Object FullName);$bytes=0L;foreach($file in $files){$rel=$file.FullName.Substring($Root.TrimEnd('\').Length+1).Replace('\','/');$line=[Text.Encoding]::UTF8.GetBytes("$rel`t$($file.Length)`t$(Hash $file.FullName)`n");$null=$sha.TransformBlock($line,0,$line.Length,$line,0);$bytes+=$file.Length};$null=$sha.TransformFinalBlock([byte[]]::new(0),0,0);[ordered]@{sha256=([BitConverter]::ToString($sha.Hash)).Replace('-','');files=$files.Count;bytes=$bytes}}finally{$sha.Dispose()}}
function Game([string]$Root){$verified=&$gameVerifier -GamePath $Root;$manifest=Get-Content -LiteralPath $verified.ManifestPath -Raw|ConvertFrom-Json;$hashes=0;foreach($entry in @($manifest.Files)){$candidate=Join-Path $Root ([string]$entry.Path).Replace('/','\');if((Hash $candidate)-cne([string]$entry.Sha256).ToUpperInvariant()){throw "Source-game hash drifted for '$($entry.Path)'."};$hashes++};if($hashes-ne[int]$verified.FileCount){throw 'Source-game hash coverage is incomplete.'};[ordered]@{file_count=[int]$verified.FileCount;payload_bytes=[long]$verified.PayloadBytes;source_iso_sha256=[string]$verified.SourceIsoSha256}}
function Artifacts([string]$Root){@($artifactNames|ForEach-Object{[ordered]@{name=$_;sha256=(Hash (Join-Path $Root $_))}})}
function ArgQuote([string]$Value){'"'+$Value.Replace('"','\"')+'"'}
function WriteJson([string]$Path,$Value){[IO.File]::WriteAllText($Path,((ConvertTo-Json $Value -Depth 15)+[Environment]::NewLine),$utf8)}
function ReadLogs([string]$Root){$text='';foreach($file in @(Get-ChildItem -LiteralPath $Root -File -Filter 'mcla*.log' -ErrorAction SilentlyContinue|Sort-Object Name)){try{$stream=[IO.File]::Open($file.FullName,'Open','Read','ReadWrite');try{$reader=[IO.StreamReader]::new($stream);try{$text+=$reader.ReadToEnd()}finally{$reader.Dispose()}}finally{$stream.Dispose()}}catch{}};$text}
function WaitMarker([Diagnostics.Process]$Process,[string]$Root,[string]$Marker,[int]$Seconds){$deadline=[DateTime]::UtcNow.AddSeconds($Seconds);while([DateTime]::UtcNow-lt$deadline){if($Process.HasExited){throw "Process exited before startup marker '$Marker'."};if((ReadLogs $Root).Contains($Marker)){return};Start-Sleep -Milliseconds 200};throw "Startup marker timed out: $Marker"}
function ReadProcessAwareExact([Diagnostics.Process]$Process,[string]$Prompt,[string]$Exact){try{$null=[Console]::KeyAvailable}catch{throw 'Interactive console input is unavailable; run this script in a visible console.'};while($true){Write-Host ($Prompt+"`nType exactly: $Exact`: ") -ForegroundColor Yellow -NoNewline;$input=[Text.StringBuilder]::new();while($true){if($Process.HasExited){Write-Host;throw "Process exited while waiting for '$Exact' (exit $($Process.ExitCode))."};if(-not[Console]::KeyAvailable){Start-Sleep -Milliseconds 50;continue};$key=[Console]::ReadKey($true);if($key.Key-eq[ConsoleKey]::Enter){Write-Host;break};if($key.Key-eq[ConsoleKey]::Backspace){if($input.Length){$input.Length--;Write-Host "`b `b" -NoNewline};continue};if(-not[char]::IsControl($key.KeyChar)){$null=$input.Append($key.KeyChar);Write-Host $key.KeyChar -NoNewline}};if($input.ToString()-ceq$Exact){return};Write-Host 'Ignored; the exact phrase is required and the game remains running.' -ForegroundColor DarkYellow}}
function ExactWindow([Diagnostics.Process]$Process){$hits=@();foreach($handle in [MclaMixedLongSessionNative]::Handles($Process.Id)){if([regex]::IsMatch([MclaMixedLongSessionNative]::Title($handle),'^mcla \[rexglue-v[^\]]+\]$')){$hits+=$handle}};if($hits.Count-ne1){throw 'Exact visible MCLA window was not found.'};$hits[0]}
function CloseExact([Diagnostics.Process]$Process){if(-not[MclaMixedLongSessionNative]::PostMessage((ExactWindow $Process),0x10,[IntPtr]::Zero,[IntPtr]::Zero)){throw 'Exact PID/window WM_CLOSE failed.'}}
function Capture([Diagnostics.Process]$Process,[string]$Path,[int]$Checkpoint,[long]$Elapsed,[switch]$Required){
  if($Process.HasExited){throw "Process exited before capture $Checkpoint (exit $($Process.ExitCode))."}
  $scheduled=[long]$Checkpoint*900
  try{
    $handle=ExactWindow $Process
    $deadline=[DateTime]::UtcNow.AddSeconds($(if($Required){20}else{2}))
    do{
      if($Required){$null=[MclaMixedLongSessionNative]::FocusWindow($handle);Start-Sleep -Milliseconds 250}
      elseif([MclaMixedLongSessionNative]::GetForegroundWindow()-ne$handle){return [ordered]@{status='skipped';checkpoint=$Checkpoint;scheduled_elapsed_seconds=$scheduled;attempted_elapsed_seconds=$Elapsed;reason='mcla-window-not-foreground'}}
      if([MclaMixedLongSessionNative]::GetForegroundWindow()-ne$handle){continue}
      Start-Sleep -Milliseconds 250
      $r=[MclaMixedLongSessionNative]::Client($handle)
      if($r.Count-ne4-or$r[2]-lt640-or$r[3]-lt360){if($Required){throw 'MCLA client geometry is invalid.'};return [ordered]@{status='skipped';checkpoint=$Checkpoint;scheduled_elapsed_seconds=$scheduled;attempted_elapsed_seconds=$Elapsed;reason='invalid-client-geometry'}}
      $source=[Drawing.Bitmap]::new($r[2],$r[3])
      try{$g=[Drawing.Graphics]::FromImage($source);try{$g.CopyFromScreen($r[0],$r[1],0,0,[Drawing.Size]::new($r[2],$r[3]))}finally{$g.Dispose()};$bmp=[Drawing.Bitmap]::new(1280,720);try{$g2=[Drawing.Graphics]::FromImage($bmp);try{$g2.DrawImage($source,0,0,1280,720)}finally{$g2.Dispose()};$bmp.Save($Path,[Drawing.Imaging.ImageFormat]::Bmp)}finally{$bmp.Dispose()}}finally{$source.Dispose()}
      $image=[Drawing.Bitmap]::FromFile($Path)
      try{$bins=New-Object 'Collections.Generic.HashSet[int]';for($y=0;$y-lt720;$y+=12){for($x=0;$x-lt1280;$x+=12){$c=$image.GetPixel($x,$y);$null=$bins.Add((($c.R-shr3)-shl10)-bor(($c.G-shr3)-shl5)-bor($c.B-shr3))}}}finally{$image.Dispose()}
      if($bins.Count-ge80){return [ordered]@{status='captured';checkpoint=$Checkpoint;scheduled_elapsed_seconds=$scheduled;attempted_elapsed_seconds=$Elapsed;name=(Split-Path $Path -Leaf);elapsed_seconds=$Elapsed;sha256=(Hash $Path);bytes=[long](Get-Item -LiteralPath $Path).Length;color_bins=$bins.Count}}
      Remove-Item -LiteralPath $Path -Force -ErrorAction SilentlyContinue
      Start-Sleep -Milliseconds 250
    }while([DateTime]::UtcNow-lt$deadline)
  }catch{if($Required){throw};Remove-Item -LiteralPath $Path -Force -ErrorAction SilentlyContinue;return [ordered]@{status='skipped';checkpoint=$Checkpoint;scheduled_elapsed_seconds=$scheduled;attempted_elapsed_seconds=$Elapsed;reason='capture-error'}}
  if($Required){throw 'Exact MCLA window did not yield a nontrivial physical capture within 20 seconds.'}
  Remove-Item -LiteralPath $Path -Force -ErrorAction SilentlyContinue
  [ordered]@{status='skipped';checkpoint=$Checkpoint;scheduled_elapsed_seconds=$scheduled;attempted_elapsed_seconds=$Elapsed;reason='nontrivial-frame-unavailable'}
}
function Sample([Diagnostics.Process]$Process,[int]$Checkpoint,[long]$Elapsed){if($Process.HasExited){throw 'Process exited during resource sampling.'};$Process.Refresh();$io=[MclaMixedLongSessionNative+IO]::new();if(-not[MclaMixedLongSessionNative]::GetProcessIoCounters($Process.Handle,[ref]$io)){throw 'GetProcessIoCounters failed.'};[ordered]@{checkpoint=$Checkpoint;elapsed_seconds=$Elapsed;private_bytes=[long]$Process.PrivateMemorySize64;working_set_bytes=[long]$Process.WorkingSet64;handle_count=[long]$Process.HandleCount;thread_count=[long]$Process.Threads.Count;io_read_bytes=[long]$io.ReadTransferCount}}
function RecoveryMessage([Diagnostics.Process]$Watcher,[string]$Archive,[string]$User){
  $fallback="No recovery snapshot was confirmed; inspect the working profile at '$User'."
  try{
    if(-not$Watcher-or-not$Watcher.HasExited-or$Watcher.ExitCode-ne0){return $fallback}
    $latestPath=Safe (Join-Path $Archive 'latest.json') 'Recovery latest snapshot' -Exists
    $latest=Get-Content -LiteralPath $latestPath -Raw|ConvertFrom-Json
    if($latest.schema-cne'mcla-soak-save-snapshot-v1'-or-not$latest.complete_profile_tree){return $fallback}
    $snapshot=Safe (Join-Path $Archive ([string]$latest.snapshot_directory)) 'Recovery snapshot' -Exists
    if((Split-Path $snapshot -Parent)-cne[IO.Path]::GetFullPath($Archive)){return $fallback}
    $manifestPath=Safe (Join-Path $snapshot 'snapshot.json') 'Recovery snapshot manifest' -Exists
    $manifest=Get-Content -LiteralPath $manifestPath -Raw|ConvertFrom-Json
    if((ConvertTo-Json $latest -Compress)-cne(ConvertTo-Json $manifest -Compress)-or(Hash (Join-Path $snapshot $saveRelative))-cne$latest.save_sha256-or(Hash (Join-Path $snapshot $headerRelative))-cne$latest.header_sha256){return $fallback}
    "Recovery save snapshot confirmed: '$snapshot'."
  }catch{$fallback}
}
function LatestSeed([string]$Root){
  $candidates=@()
  foreach($directory in @(Get-ChildItem -LiteralPath $Root -Directory -ErrorAction SilentlyContinue)){
    $latestPath=Join-Path $directory.FullName 'latest.json'
    if(-not(Test-Path -LiteralPath $latestPath)){continue}
    try{
      $manifest=Get-Content -LiteralPath $latestPath -Raw|ConvertFrom-Json
      if($manifest.schema-cne'mcla-soak-save-snapshot-v1'-or-not$manifest.complete_profile_tree){continue}
      $snapshot=Safe (Join-Path $directory.FullName ([string]$manifest.snapshot_directory)) 'Candidate snapshot' -Exists
      if((Split-Path $snapshot -Parent)-cne$directory.FullName){continue}
      $snapshotManifestPath=Safe (Join-Path $snapshot 'snapshot.json') 'Candidate snapshot manifest' -Exists
      $snapshotManifest=Get-Content -LiteralPath $snapshotManifestPath -Raw|ConvertFrom-Json
      if((ConvertTo-Json $manifest -Compress)-cne(ConvertTo-Json $snapshotManifest -Compress)){continue}
      if((Hash (Join-Path $snapshot $saveRelative))-cne$manifest.save_sha256-or(Hash (Join-Path $snapshot $headerRelative))-cne$manifest.header_sha256){continue}
      $candidates+=[pscustomobject]@{Captured=[DateTime]::Parse([string]$manifest.captured_utc).ToUniversalTime();Archive=$directory.FullName;Snapshot=$snapshot;Manifest=$manifest;Latest=$latestPath}
    }catch{}
  }
  if(-not$candidates.Count){throw 'No complete hash-verified M6-014 recovery snapshot exists.'}
  @($candidates|Sort-Object Captured -Descending)[0]
}
function Bounds($Samples){$first=$Samples[0];$last=$Samples[-1];[ordered]@{private_growth_bytes=[long]$last.private_bytes-[long]$first.private_bytes;working_growth_bytes=[long]$last.working_set_bytes-[long]$first.working_set_bytes;handle_growth=[long]$last.handle_count-[long]$first.handle_count;thread_growth=[long]$last.thread_count-[long]$first.thread_count;io_read_growth_bytes=[long]$last.io_read_bytes-[long]$first.io_read_bytes;private_peak_growth_bytes=[long](($Samples|ForEach-Object private_bytes|Measure-Object -Maximum).Maximum)-[long]$first.private_bytes;working_peak_growth_bytes=[long](($Samples|ForEach-Object working_set_bytes|Measure-Object -Maximum).Maximum)-[long]$first.working_set_bytes}}
function HostDisplayAudit([DateTime]$Since){try{$null=Get-WinEvent -ListLog System -ErrorAction Stop;$null=Get-WinEvent -ListLog Application -ErrorAction Stop;$nvidia=@(Get-WinEvent -FilterHashtable @{LogName='System';StartTime=$Since;Id=153} -ErrorAction SilentlyContinue|Where-Object{$_.ProviderName-ceq'nvlddmkm'});$sunshine=@(Get-WinEvent -FilterHashtable @{LogName='Application';StartTime=$Since;Id=1000} -ErrorAction SilentlyContinue|Where-Object{$_.ProviderName-ceq'Application Error'-and(($_.Properties.Count-gt0-and[string]$_.Properties[0].Value-ceq'Sunshine.exe')-or$_.Message-match'(?i)Sunshine\.exe')});[ordered]@{schema='mcla-host-display-audit-v1';since_utc=$Since.ToUniversalTime().ToString('O');checked_utc=[DateTime]::UtcNow.ToString('O');audit_available=$true;nvidia_driver_errors=$nvidia.Count;sunshine_application_errors=$sunshine.Count}}catch{[ordered]@{schema='mcla-host-display-audit-v1';since_utc=$Since.ToUniversalTime().ToString('O');checked_utc=[DateTime]::UtcNow.ToString('O');audit_available=$false;nvidia_driver_errors=0;sunshine_application_errors=0}}}
function AssertHost($Audit){if(-not$Audit.audit_available){throw 'Host display event logs could not be audited.'};if($Audit.nvidia_driver_errors){throw 'Host NVIDIA display-driver failure detected.'};if($Audit.sunshine_application_errors){throw 'Host Sunshine streaming-process failure detected.'}}

$build=Safe $build 'Release build';$game=Safe $game 'Game root' -Exists;$suitePath=Safe $suitePath 'SDK baseline suite' -Exists;$deliveryPath=Safe $deliveryPath 'Delivery result' -Exists;$archiveRoot=Safe $archiveRoot 'M6-014 save archive' -Exists;$versionPath=Safe $versionPath 'Project version' -Exists;$historicalSuitePath=Safe $historicalSuitePath 'Historical suite' -Exists;$historicalFrontendRoot=Safe $historicalFrontendRoot 'Historical frontend root' -Exists;$historicalFrontendStage=Safe $historicalFrontendStage 'Historical frontend stage' -Exists
$suite=Get-Content -LiteralPath $suitePath -Raw|ConvertFrom-Json;if((Hash $suitePath)-cne'EB553F0B34F00837A7A0C2FA3FDDD4FBEA9444FE4268EAC266D889A80DCA37C6'-or$suite.suite_id-cne'20260901-153415-d747cf2d'-or$suite.sdk_version-cne'0.10.0.1'-or$suite.sdk_commit-cne'7dd5cb33002a443b097c0f65d5566c0a0f2db838'){throw 'Current suite identity drifted.'}
$gameBefore=Game $game;if((ConvertTo-Json $gameBefore -Compress)-cne(ConvertTo-Json $suite.game -Compress)){throw 'Current source-game payload drifted from the suite.'}
if((Hash $deliveryPath)-cne'E7200300CA38718DD6978C26E8F4CE5CF4EF1279441B5F032CE2075F387FF0F1'-or(Hash $historicalSuitePath)-cne'009DB466CA39195C02B137C45F4A11EBA87080D1C60B15D54887C5CBD85E0F3C'-or(Hash $historicalFrontendStage)-cne'4E97A021296A0521F959CB9A37AE7BA1B0D3A93B6D311651E10DFCF75E39AC9C'-or(Tree $historicalFrontendRoot).sha256-cne'C44F1C9D0E47834BA745CE267500E826E490706B1BDFE4A081AE65FE88D6665D'){throw 'Historical frontend or delivery prerequisite drifted.'}
$deliveryCheck=&$deliveryVerifier -ResultPath $deliveryPath -Fixture;if($deliveryCheck.Decision-cne'delivery-transition-current-artifact-pass'){throw 'Accepted immutable delivery prerequisite did not revalidate.'}
$seedCandidate=LatestSeed $archiveRoot;$latestPath=$seedCandidate.Latest;$latest=$seedCandidate.Manifest;$seed=$seedCandidate.Snapshot;$projectVersion=(Get-Content -LiteralPath $versionPath -Raw).Trim();if($projectVersion-cnotmatch'^\d+\.\d+\.\d+\.\d+$'){throw 'Project version is not four-part.'}
$exe=Join-Path $build 'mcla.exe';if(@((Get-Process mcla -ErrorAction SilentlyContinue)|Where-Object{try{$_.Path-ceq$exe}catch{$false}}).Count){throw 'Canonical MCLA is already running.'};if($ValidateOnly){[pscustomobject]@{Passed=$true;DurationSeconds=$DurationSeconds;SdkBaseline=$suite.suite_id;SeedSnapshot=$seed;SeedSave=$latest.save_sha256;ExpectedArtifacts=$artifactNames.Count;ProjectVersion=$projectVersion};return}

$evidence=Safe (Join-Path $repo 'private/evidence/M6-014/final-hour') 'Final-hour evidence root';[IO.Directory]::CreateDirectory($evidence)|Out-Null;$runId=(Get-Date -Format 'yyyyMMdd-HHmmss')+'-'+[guid]::NewGuid().ToString('N').Substring(0,8);$root=Join-Path $evidence $runId;[IO.Directory]::CreateDirectory($root)|Out-Null;$buildLog=Join-Path $root 'build.log';$cmake=(& (Join-Path $PSScriptRoot 'Resolve-Toolchain.ps1') -ExportPath).CMakePath
Write-Host 'M6-014 FINAL HOUR [1/4]: clean-building and pinning the current Release artifact plus latest recovered save...' -ForegroundColor Cyan
&$cmake --preset win-amd64-release *>&1|Tee-Object -FilePath $buildLog|Out-Null;if($LASTEXITCODE-ne0){throw "Release configure failed. Private run: '$root'."};&$cmake --build --preset win-amd64-release --target mcla --clean-first --parallel 8 *>&1|Tee-Object -FilePath $buildLog -Append|Out-Null;if($LASTEXITCODE-ne0){throw "Release build failed. Private run: '$root'."}
$build=Safe $build 'Release build' -Exists;$artifactsBefore=@(Artifacts $build);$exe=Safe (Join-Path $build 'mcla.exe') 'Release executable' -Exists;$preflight=HostDisplayAudit ([DateTime]::Now.AddMinutes(-1));AssertHost $preflight;$run=Join-Path $root 'run';$user=Join-Path $run 'user';$cache=Join-Path $run 'cache';$captures=Join-Path $root 'captures';$seedCopy=Join-Path $root 'seed-copy';[IO.Directory]::CreateDirectory($user)|Out-Null;[IO.Directory]::CreateDirectory($cache)|Out-Null;[IO.Directory]::CreateDirectory($captures)|Out-Null;[IO.Directory]::CreateDirectory($seedCopy)|Out-Null;$sourceProfile=Join-Path $seed 'B13EBABEBABEBABE';Copy-Item -LiteralPath $sourceProfile -Destination $user -Recurse;$workingProfile=Join-Path $user 'B13EBABEBABEBABE';Copy-Item -LiteralPath $workingProfile -Destination $seedCopy -Recurse;$seedCopyProfile=Join-Path $seedCopy 'B13EBABEBABEBABE';$sourceProfileTree=Tree $sourceProfile;$workingProfileTree=Tree $workingProfile;$seedCopyTree=Tree $seedCopyProfile;if($workingProfileTree.sha256-cne$sourceProfileTree.sha256-or$seedCopyTree.sha256-cne$sourceProfileTree.sha256-or(Hash (Join-Path $workingProfile $saveRelative.Substring(17)))-cne$latest.save_sha256-or(Hash (Join-Path $workingProfile $headerRelative.Substring(17)))-cne$latest.header_sha256){throw 'Copied gameplay seed failed physical identity verification.'}
$archive=Safe (Join-Path $repo "private/save-archive/M6-014/final-hour-$runId") 'Final-hour save archive';$log=Join-Path $run 'mcla.log';$args=@('--mcla_first_frame_probe=true','--mcla_garage_lifecycle_probe=true','--mcla_garage_lifecycle_cycle=2','--xam_user_signin_state=1','--input_backend=sdl','--mnk_mode=false','--readback_resolve=fast','--async_shader_compilation=false','--d3d12_pipeline_creation_threads=0','--log_level=info','--log_max_file_size_mb=16','--log_max_files=30','--fullscreen=false',('--game_data_root="{0}"'-f$game),('--user_data_root="{0}"'-f$user),('--cache_root="{0}"'-f$cache),('--log_file="{0}"'-f$log))
Write-Host ("LATEST SAVE       | {0} | {1}"-f$latest.captured_utc,$latest.save_sha256) -ForegroundColor DarkCyan;Write-Host 'M6-014 FINAL HOUR [2/4]: launching one continuous 60-minute mixed-gameplay process...' -ForegroundColor Cyan
$process=$null;$watcher=$null;$forced=$false
try{$process=Start-Process $exe -ArgumentList $args -WorkingDirectory $build -PassThru;$watcher=Start-Process $pwshHost -ArgumentList @('-NoLogo','-NoProfile','-ExecutionPolicy','Bypass','-File',(ArgQuote $saveWatcher),'-SourceUserRoot',(ArgQuote $user),'-ArchiveRoot',(ArgQuote $archive),'-MclaProcessId',$process.Id) -WorkingDirectory $repo -WindowStyle Hidden -PassThru;WaitMarker $process $run 'MCLA graphics: nontrivial guest frame captured' 90;WaitMarker $process $run 'MCLA_GARAGE_LIFECYCLE_CONFIG v=1 cycle=2' 20;$request=Join-Path $user '.mcla-garage-control.request';$temporary=$request+'.tmp';[IO.File]::WriteAllText($temporary,'1 START',$utf8);Move-Item -LiteralPath $temporary -Destination $request -Force;WaitMarker $process $run 'MCLA_GARAGE_CONTROL v=1 sequence=1 action=START capture=0 width=0 height=0' 30;Start-Sleep -Seconds 30
  ReadProcessAwareExact $process 'Saved gameplay is loaded. For one hour play normally. Races/story/deliveries are allowed. During the hour also enter and leave the garage once, pause/resume once, and Alt-Tab away and back once. No wheel testing is required.' 'MIXED GAMEPLAY READY'
  $started=[DateTime]::UtcNow;$timer=[Diagnostics.Stopwatch]::StartNew();$samples=@(Sample $process 0 0);$initialAttempt=Capture $process (Join-Path $captures 'checkpoint-00.bmp') 0 0 -Required;$captureAttempts=@($initialAttempt);$captureRecords=@([ordered]@{name=$initialAttempt.name;elapsed_seconds=$initialAttempt.elapsed_seconds;sha256=$initialAttempt.sha256;bytes=$initialAttempt.bytes;color_bins=$initialAttempt.color_bins});$nextStatus=60;WriteJson (Join-Path $root 'resource-samples.json') @($samples);WriteJson (Join-Path $root 'captures.json') @($captureRecords);WriteJson (Join-Path $root 'capture-attempts.json') @($captureAttempts)
  for($checkpoint=1;$checkpoint-le12;$checkpoint++){$target=$checkpoint*300;while($timer.Elapsed.TotalSeconds-lt$target){if($process.HasExited){throw "Process exited during mixed gameplay at $([int]$timer.Elapsed.TotalSeconds)s (exit $($process.ExitCode))."};$elapsed=[int]$timer.Elapsed.TotalSeconds;if($elapsed-ge$nextStatus){Write-Host ("MIXED GAMEPLAY     | {0}/3600s | process alive"-f$elapsed) -ForegroundColor DarkCyan;$nextStatus+=60};Start-Sleep -Milliseconds 200};$elapsed=[int]$timer.Elapsed.TotalSeconds;$samples+=Sample $process $checkpoint $elapsed;WriteJson (Join-Path $root 'resource-samples.json') @($samples);if($checkpoint-eq12){$completed=[DateTime]::UtcNow};if($checkpoint%3-eq0){$captureIndex=[int]($checkpoint/3);$attempt=Capture $process (Join-Path $captures ("checkpoint-{0:D2}.bmp"-f$captureIndex)) $captureIndex $elapsed;$captureAttempts+=$attempt;if($attempt.status-ceq'captured'){$captureRecords+=[ordered]@{name=$attempt.name;elapsed_seconds=$attempt.elapsed_seconds;sha256=$attempt.sha256;bytes=$attempt.bytes;color_bins=$attempt.color_bins};Write-Host ("CAPTURE {0}/4       | CAPTURED - session continues"-f$captureIndex) -ForegroundColor DarkGreen}else{Write-Host ("CAPTURE {0}/4       | SKIPPED ({1}) - session continues"-f$captureIndex,$attempt.reason) -ForegroundColor DarkYellow};WriteJson (Join-Path $root 'capture-attempts.json') @($captureAttempts);WriteJson (Join-Path $root 'captures.json') @($captureRecords)};$audit=HostDisplayAudit $started;AssertHost $audit;WriteJson (Join-Path $root 'host-display-audit.json') $audit}
  $duration=[int]$samples[-1].elapsed_seconds;ReadProcessAwareExact $process 'The measured hour completed. Confirm only if gameplay remained stable and you performed normal moving gameplay plus one garage enter/exit, pause/resume, and Alt-Tab return.' 'MIXED GAMEPLAY STABLE';$attested=[DateTime]::UtcNow;CloseExact $process;if(-not$process.WaitForExit(10000)-or$process.ExitCode-ne0){throw 'Controlled external WM_CLOSE failed.'}
}catch{$failure=$_;if($process-and-not$process.HasExited){try{CloseExact $process;$null=$process.WaitForExit(10000)}catch{};if(-not$process.HasExited){$forced=$true;Stop-Process -Id $process.Id -Force -ErrorAction SilentlyContinue;$null=$process.WaitForExit(5000)}};if($watcher-and-not$watcher.HasExited){$null=$watcher.WaitForExit(15000)};$recovery=RecoveryMessage $watcher $archive $user;if($forced){throw "Final-hour regression required force cleanup. $($failure.Exception.Message) Private run: '$root'. $recovery"};throw "$($failure.Exception.Message) Private run: '$root'. $recovery"}
if($watcher-and-not$watcher.HasExited-and-not$watcher.WaitForExit(15000)){throw 'Save watcher did not finish.'};if($watcher-and$watcher.ExitCode-ne0){throw "Save watcher failed with exit $($watcher.ExitCode)."};$artifactsAfter=@(Artifacts $build);$gameAfter=Game $game;$artifactsChanged=(ConvertTo-Json $artifactsBefore -Compress)-cne(ConvertTo-Json $artifactsAfter -Compress);$gameChanged=(ConvertTo-Json $gameBefore -Compress)-cne(ConvertTo-Json $gameAfter -Compress);if($artifactsChanged-or$gameChanged){throw 'Artifact or game identity changed during the final hour.'}
$fatalPattern='(?i)\[FATAL\]|Assertion failed|REX_GUEST_CRASH|GUEST_CRASH_REPORT|guest crash|PPC_UNIMPLEMENTED|invalid or unregistered function|access violation|device lost|device hung|device reset|DRED|DXGI_ERROR_DEVICE_(?:REMOVED|HUNG|RESET)';$logs=ReadLogs $run;$fatal=[regex]::Matches($logs,$fatalPattern).Count;if($fatal){throw 'Runtime fatal markers were found.'};$logFiles=@(Get-ChildItem -LiteralPath $run -File -Filter 'mcla*.log'|Sort-Object Name);if($logFiles.Count-lt1){throw 'Runtime log set is empty.'};$logManifest=@($logFiles|ForEach-Object{[ordered]@{name=$_.Name;sha256=(Hash $_.FullName);bytes=[long]$_.Length}});$bounds=Bounds $samples;if($bounds.private_peak_growth_bytes-gt1GB-or$bounds.working_peak_growth_bytes-gt512MB-or$bounds.handle_growth-gt128-or$bounds.thread_growth-gt32){throw 'One-hour resource growth exceeded the bounded acceptance limits.'}
$finalSave=Hash (Join-Path $user $saveRelative);$finalHeader=Hash (Join-Path $user $headerRelative);$archiveLatestPath=Safe (Join-Path $archive 'latest.json') 'Final-hour latest snapshot' -Exists;$archiveLatest=Get-Content -LiteralPath $archiveLatestPath -Raw|ConvertFrom-Json;$archiveSnapshot=Safe (Join-Path $archive $archiveLatest.snapshot_directory) 'Final-hour snapshot directory' -Exists;if((Split-Path $archiveSnapshot -Parent)-cne$archive){throw 'Final-hour snapshot directory escapes its archive.'};$snapshotManifestPath=Safe (Join-Path $archiveSnapshot 'snapshot.json') 'Final-hour snapshot manifest' -Exists;$snapshotManifest=Get-Content -LiteralPath $snapshotManifestPath -Raw|ConvertFrom-Json;if($archiveLatest.schema-cne'mcla-soak-save-snapshot-v1'-or$snapshotManifest.schema-cne'mcla-soak-save-snapshot-v1'-or$archiveLatest.snapshot_directory-cne$snapshotManifest.snapshot_directory-or$archiveLatest.identity-cne$snapshotManifest.identity-or-not$archiveLatest.complete_profile_tree-or-not$snapshotManifest.complete_profile_tree-or(Hash (Join-Path $archiveSnapshot $saveRelative))-cne$finalSave-or(Hash (Join-Path $archiveSnapshot $headerRelative))-cne$finalHeader-or$archiveLatest.save_sha256-cne$finalSave-or$archiveLatest.header_sha256-cne$finalHeader){throw 'Final save archive does not match the complete physical profile snapshot.'};$hostPath=Join-Path $root 'host-display-audit.json'
$seedArchiveRelative=$seedCandidate.Archive.Substring($repo.Length+1).Replace('\','/');$latestRelative=$latestPath.Substring($repo.Length+1).Replace('\','/')
$result=[ordered]@{schema='mcla-one-hour-mixed-gameplay-long-session-v3';task='M6-014';decision='one-hour-mixed-gameplay-long-session-pass';run_id=$runId;target_duration_seconds=3600;actual_duration_seconds=$duration;started_utc=$started.ToString('O');completed_utc=$completed.ToString('O');attested_utc=$attested.ToString('O');sdk_baseline=[ordered]@{path='private/evidence/M6-014/20260901-153415-d747cf2d/suite.json';sha256=(Hash $suitePath);sdk_version=$suite.sdk_version;sdk_commit=$suite.sdk_commit};project_build=[ordered]@{version=$projectVersion;configuration='Release';build_log_name='build.log';build_log_sha256=(Hash $buildLog)};historical_frontend=[ordered]@{suite_path='private/evidence/M6-014/20260831-133236-2cecb67b/suite.json';suite_sha256=(Hash $historicalSuitePath);stage_path='private/evidence/M6-014/20260831-133236-2cecb67b/scenarios/frontend/stage.json';stage_sha256=(Hash $historicalFrontendStage);tree_sha256=(Tree $historicalFrontendRoot).sha256;duration_seconds=7202;executable_sha256='9202CDC09DA1402460312E0204AB0CF5B6D05D9C07B205CA136414CD1C655FD4'};delivery_prerequisite=[ordered]@{result_path='private/evidence/M6-014/delivery-regressions/20260901-203448-d31ab681/result.json';result_sha256=(Hash $deliveryPath)};gameplay_seed=[ordered]@{archive_path=$seedArchiveRelative;latest_path=$latestRelative;latest_sha256=(Hash $latestPath);captured_utc=$latest.captured_utc;snapshot_directory=$latest.snapshot_directory;snapshot_tree_sha256=(Tree $seed).sha256;save_before_sha256=$latest.save_sha256;header_before_sha256=$latest.header_sha256;save_after_sha256=$finalSave;header_after_sha256=$finalHeader};game=$gameAfter;release_artifacts=$artifactsAfter;resource_samples=@($samples);resource_bounds=$bounds;capture_attempts=@($captureAttempts);captures=@($captureRecords);runtime_logs=$logManifest;runtime_fatal_markers=$fatal;host_display_audit=[ordered]@{sha256=(Hash $hostPath);audit_available=$audit.audit_available;nvidia_driver_errors=$audit.nvidia_driver_errors;sunshine_application_errors=$audit.sunshine_application_errors};controlled_external_close=$true;exit_code=0;force_cleanup=$false;save_archive=(Tree $archive);scope=[ordered]@{historical_frontend_two_hours=$true;current_artifact_interactive_mixed_gameplay_one_hour=$true;normal_moving_gameplay_owner_attested=$true;garage_enter_exit_owner_attested=$true;pause_resume_owner_attested=$true;alt_tab_return_owner_attested=$true;same_release_artifacts=$false;single_continuous_three_hour_run_claimed=$false;current_five_stage_soak_complete=$false;five_two_hour_suite_claimed=$false;two_hour_current_artifact_mixed_gameplay_claimed=$false;full_campaign_claimed=$false;rendering_parity_claimed=$false;music_continuity_claimed=$false;wheel_centering_stability_claimed=$false}}
$result.host_display_audit=[ordered]@{schema=$audit.schema;sha256=(Hash $hostPath);since_utc=$audit.since_utc;checked_utc=$audit.checked_utc;audit_available=$audit.audit_available;nvidia_driver_errors=$audit.nvidia_driver_errors;sunshine_application_errors=$audit.sunshine_application_errors}
$result.gameplay_seed['working_copy_tree_sha256']=$seedCopyTree.sha256
WriteJson (Join-Path $root 'result.json') $result;Write-Host 'M6-014 FINAL HOUR [3/4]: physical hour, resources, captures, logs, host health, and save archive persisted.' -ForegroundColor Cyan;$final=&$verify -ResultPath (Join-Path $root 'result.json');Write-Host 'M6-014 FINAL HOUR [4/4]: PASS - mixed-gameplay long-session gate revalidated.' -ForegroundColor Green;$final
