[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$repo=(Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '..')).Path;$verify=Join-Path $PSScriptRoot 'verify-profile-settings-smoke.ps1';$source=&$verify -SourceOnly
if(-not$source.SourceContractVerified-or$source.SourceChecks-ne30-or$source.ProfileCases-ne7-or$source.ProfileAssertions-ne40-or$source.CvarCases-ne26-or$source.CvarAssertions-ne128-or$source.TitleWriteImported){throw 'Source contract failed.'}
function Good{
  $paths=@('third_party/rexglue-sdk/include/rex/system/xam/content_manager.h','third_party/rexglue-sdk/include/rex/system/xam/user_profile.h','third_party/rexglue-sdk/src/kernel/xam/xam_user.cpp','third_party/rexglue-sdk/src/system/kernel_state.cpp','third_party/rexglue-sdk/src/system/xam/content_manager.cpp','third_party/rexglue-sdk/src/system/xam/user_profile.cpp','third_party/rexglue-sdk/tests/unit/kernel/xam_user_profile_test.cpp','third_party/rexglue-sdk/src/core/cvar.cpp','third_party/rexglue-sdk/src/input/input_system.cpp','third_party/rexglue-sdk/src/input/mnk/mnk_input_driver.cpp')
  $prior=@([ordered]@{task='M4-004';run_id='20260812-123316-db0f1cf4';sha256='388F2FC350C43149CA6E5AD4E24A1B743F18CFE3A450C6D80962099F73C89AE0';decision='single-local-offline-profile'},[ordered]@{task='M4-010';run_id='20260813-213301-505ca1ca';sha256='458B742FC1112DDAF39BDC8B81935CC8F2F9C616477B258B1E6FBA10058E096A';decision='locale-selection-unicode-path-title-matrix-pass'},[ordered]@{task='M5-006';run_id='20260814-130533-0b95f6b6';sha256='A89C0CC3E02C8D264B0DA29157021D050276BF46F028BBAAAD9B1FFC220CCEAB';decision='saved-gameplay-input-pass'},[ordered]@{task='M6-005';run_id='20260818-201702-5d089d9c';sha256='5F46FA6657F39EE5AF990BD505B67D5EDBE6A781E8283D1D51BE07F3543F169E';decision='native-autosave-load-overwrite-plus-isolated-creation-destructive-save-matrix-pass'})
  [ordered]@{schema='mcla-profile-settings-v1';task='M6-006';decision='isolated-profile-controller-language-restart-matrix-pass';sdk_version='0.9.0.25';sdk_commit='f28ddabbae3bca56ddf5ffea067982c49c9549b7';build_configuration='Release+RelWithDebInfo';prior_evidence=$prior;focused_tests=[ordered]@{profile_cases=7;profile_assertions=40;cvar_cases=26;cvar_assertions=128;scalar_restart=$true;unicode_restart=$true;metadata_rejected=$true;backup_recovered=$true;title_settings_isolated=$true;config_save_load=$true;sdk_build_log_sha256=('A'*64);profile_test_log_sha256=('B'*64);cvar_test_log_sha256=('C'*64);unit_executable_sha256=('D'*64)};preferences=[ordered]@{language_flag='user_language';controller_backend_flag='input_backend';controller_mode_flag='mnk_mode';named_flags_source_bound=$true;restart_serialization_verified=$true};source_integrity=[ordered]@{seed_save_before_sha256='126F7482878C7AACB09AA6795331C906DFB9C4218BE94EDB1D8E51B27CA78AB2';seed_save_after_sha256='126F7482878C7AACB09AA6795331C906DFB9C4218BE94EDB1D8E51B27CA78AB2';seed_header_before_sha256='5827A913515AC0E5D55BB56AEC56DE99CACC0ABB7C8061F59336DF4CEA4A8731';seed_header_after_sha256='5827A913515AC0E5D55BB56AEC56DE99CACC0ABB7C8061F59336DF4CEA4A8731';source_save_mutated=$false;release_build_log_sha256=('E'*64)};release_artifacts=@('mcla.exe','rexruntime.dll','TracyClient.dll','rexgpu-xenos.dll')|ForEach-Object{[ordered]@{name=$_;sha256=('F'*64)}};source_files=@($paths|ForEach-Object{[ordered]@{path=$_;sha256=('1'*64)}});scope=[ordered]@{title_write_imported=$false;native_profile_write_route_claimed=$false;isolated_platform_persistence=$true;prior_profile_identity_physical=$true;prior_language_selection_physical=$true;prior_controller_route_physical=$true;profile_read_runtime_claimed=$false;account_picker_claimed=$false;multiple_profiles_claimed=$false;first_run_oobe_claimed=$false;native_gameplay_replayed=$false;general_host_config_claimed=$false}}
}
function MustFail([scriptblock]$Mutation,[string]$Name){$x=Good;&$Mutation $x;[IO.File]::WriteAllText($path,($x|ConvertTo-Json -Depth 9));try{&$verify -ResultPath $path -FixtureMode|Out-Null;throw "Negative '$Name' passed."}catch{if($_.Exception.Message-ceq"Negative '$Name' passed."){throw}}}
$root=Join-Path $repo ('private/evidence/M6-006/test-'+[guid]::NewGuid().ToString('N'));[IO.Directory]::CreateDirectory($root)|Out-Null;$path=Join-Path $root 'result.json'
try{[IO.File]::WriteAllText($path,((Good)|ConvertTo-Json -Depth 9));$positive=&$verify -ResultPath $path -FixtureMode;if(-not$positive.DataIntegrityVerified){throw 'Positive fixture failed.'}
  $cases=@(
    @{n='schema';m={param($x)$x.schema='bad'}},@{n='task';m={param($x)$x.task='M6-007'}},@{n='decision';m={param($x)$x.decision='pass'}},@{n='sdk version';m={param($x)$x.sdk_version='0'}},@{n='sdk commit';m={param($x)$x.sdk_commit='0'}},@{n='prior count';m={param($x)$x.prior_evidence=@()}},@{n='prior task';m={param($x)$x.prior_evidence[0].task='bad'}},@{n='prior hash';m={param($x)$x.prior_evidence[1].sha256='0'}},
    @{n='profile cases';m={param($x)$x.focused_tests.profile_cases=6}},@{n='profile assertions';m={param($x)$x.focused_tests.profile_assertions=39}},@{n='cvar cases';m={param($x)$x.focused_tests.cvar_cases=25}},@{n='cvar assertions';m={param($x)$x.focused_tests.cvar_assertions=127}},@{n='scalar';m={param($x)$x.focused_tests.scalar_restart=$false}},@{n='unicode';m={param($x)$x.focused_tests.unicode_restart=$false}},@{n='metadata';m={param($x)$x.focused_tests.metadata_rejected=$false}},@{n='backup';m={param($x)$x.focused_tests.backup_recovered=$false}},@{n='title isolation';m={param($x)$x.focused_tests.title_settings_isolated=$false}},@{n='config';m={param($x)$x.focused_tests.config_save_load=$false}},
    @{n='language flag';m={param($x)$x.preferences.language_flag='language'}},@{n='backend flag';m={param($x)$x.preferences.controller_backend_flag='backend'}},@{n='mode flag';m={param($x)$x.preferences.controller_mode_flag='mode'}},@{n='source binding';m={param($x)$x.preferences.named_flags_source_bound=$false}},@{n='restart serialization';m={param($x)$x.preferences.restart_serialization_verified=$false}},@{n='seed changed';m={param($x)$x.source_integrity.seed_save_after_sha256=('0'*64)}},@{n='mutation';m={param($x)$x.source_integrity.source_save_mutated=$true}},@{n='artifact count';m={param($x)$x.release_artifacts=@()}},@{n='source count';m={param($x)$x.source_files=@()}},
    @{n='title import';m={param($x)$x.scope.title_write_imported=$true}},@{n='native write claim';m={param($x)$x.scope.native_profile_write_route_claimed=$true}},@{n='isolated false';m={param($x)$x.scope.isolated_platform_persistence=$false}},@{n='profile prior';m={param($x)$x.scope.prior_profile_identity_physical=$false}},@{n='language prior';m={param($x)$x.scope.prior_language_selection_physical=$false}},@{n='controller prior';m={param($x)$x.scope.prior_controller_route_physical=$false}},@{n='read claim';m={param($x)$x.scope.profile_read_runtime_claimed=$true}},@{n='account picker';m={param($x)$x.scope.account_picker_claimed=$true}},@{n='multi profile';m={param($x)$x.scope.multiple_profiles_claimed=$true}},@{n='oobe';m={param($x)$x.scope.first_run_oobe_claimed=$true}},@{n='game replay';m={param($x)$x.scope.native_gameplay_replayed=$true}},@{n='host config';m={param($x)$x.scope.general_host_config_claimed=$true}},@{n='extra';m={param($x)$x.extra='x'}},@{n='wrong bool';m={param($x)$x.scope.first_run_oobe_claimed=0}}
  );foreach($case in $cases){MustFail $case.m $case.n};[pscustomobject][ordered]@{Passed=$true;Positives=1;FailClosedNegatives=$cases.Count;SourceChecks=$source.SourceChecks;ProfileCases=$source.ProfileCases;ProfileAssertions=$source.ProfileAssertions;CvarCases=$source.CvarCases;CvarAssertions=$source.CvarAssertions}
}finally{Remove-Item -LiteralPath $root -Recurse -Force -ErrorAction SilentlyContinue}
