[CmdletBinding()]
param()
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop'
$repo=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path;$verify=Join-Path $PSScriptRoot 'verify-offline-service-smoke.ps1';$root=Join-Path $repo ('private\evidence\M4-009\test-'+[guid]::NewGuid().ToString('N'));$utf8=[Text.UTF8Encoding]::new($false);New-Item -ItemType Directory -Force (Join-Path $root 'user')|Out-Null
function WriteBmp([string]$Path){$bytes=[byte[]]::new(3686454);$bytes[0]=0x42;$bytes[1]=0x4D;[BitConverter]::GetBytes([int]1280).CopyTo($bytes,18);[BitConverter]::GetBytes([int]720).CopyTo($bytes,22);[BitConverter]::GetBytes([uint16]32).CopyTo($bytes,28);[IO.File]::WriteAllBytes($Path,$bytes)}
$config='OFFLINE_SERVICE_AUDIT_CONFIG v=1 enabled=1 policy=explicit-offline network_block=1 record_limit=64'
$summary='OFFLINE_SERVICE_AUDIT_SUMMARY v=1 phase=title status=PASS message_calls=0 known_calls=0 local_calls=0 unavailable_calls=0 unexpected_calls=0 unexpected_results=0 socket_attempts=0 blocked_socket_attempts=0 host_socket_attempts=0 records=0 overflow=0 dropped_records=0'
$capture='MCLA graphics: nontrivial guest frame captured 1280x720, rgb555 bins 10, luma p05 1, luma p95 2, modal permille 10, nonmodal grid cells 4'
$project='MCLA offline services: title route summarized'
$lifecycle="Window closing, shutting down...`nExecution complete`nTitle terminated; hard-exiting process."
$log=Join-Path $root 'mcla.log';$bmp=Join-Path $root 'user\mcla-first-frame.bmp';WriteBmp $bmp
function Accept([string]$Text){[IO.File]::WriteAllText($log,$Text,$utf8);$null=&$verify -ProbeOnly -OfflineOnly -RuntimeLogPath $log -BmpPath $bmp}
function Reject([string]$Name,[string]$Text){[IO.File]::WriteAllText($log,$Text,$utf8);$failed=$false;try{$null=&$verify -ProbeOnly -OfflineOnly -RuntimeLogPath $log -BmpPath $bmp}catch{$failed=$true};if(-not$failed){throw "Negative '$Name' was accepted."}}
try{Accept "$config`n$capture`n$summary`n$project`n$lifecycle";$cases=[ordered]@{missing_config="$summary`n$project";duplicate_config="$config`n$config`n$summary`n$project";missing_summary="$config`n$project";duplicate_summary="$config`n$summary`n$summary`n$project";fail_summary="$config`n$($summary.Replace('status=PASS','status=FAIL'))`n$project";unexpected_call="$config`n$($summary.Replace('unexpected_calls=0','unexpected_calls=1'))`n$project";unexpected_result="$config`n$($summary.Replace('unexpected_results=0','unexpected_results=1'))`n$project";host_socket="$config`n$($summary.Replace('host_socket_attempts=0','host_socket_attempts=1'))`n$project";overflow="$config`n$($summary.Replace('overflow=0','overflow=1'))`n$project";unimplemented="$config`nUnimplemented XLIVEBASE message`n$summary`n$project";fatal="$config`n[fatal] crash`n$summary`n$project";bad_order="$config`n$project`n$summary"};foreach($c in $cases.GetEnumerator()){Reject $c.Key (($c.Value)+"`n$capture`n$lifecycle")};[pscustomobject]@{Passed=$true;PositiveFixtures=1;FailClosedNegatives=$cases.Count}}finally{if(Test-Path $root){Remove-Item -LiteralPath $root -Recurse -Force}}
