[CmdletBinding()]
param()
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$repo=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path;$verify=Join-Path $PSScriptRoot 'verify-race-resource-smoke.ps1';$run=Join-Path $PSScriptRoot 'run-race-resource-smoke.ps1';$app=Join-Path $repo 'src/mcla_app.cpp';$root=Join-Path $repo ('private/evidence/M5-013/test-'+[guid]::NewGuid().ToString('N'));$utf8=[Text.UTF8Encoding]::new($false)
function Write-Bmp([string]$Path,[byte]$Value){$b=[byte[]]::new(3686454);$b[0]=0x42;$b[1]=0x4D;[BitConverter]::GetBytes([int]1280).CopyTo($b,18);[BitConverter]::GetBytes([int]720).CopyTo($b,22);[BitConverter]::GetBytes([uint16]32).CopyTo($b,28);for($i=54;$i-lt$b.Length;$i+=4096){$b[$i]=$Value};[IO.File]::WriteAllBytes($Path,$b)}
function New-Fixture([string]$Path){$cycle=Join-Path $Path 'runs/01';$user=Join-Path $cycle 'user';$cache=Join-Path $cycle 'cache';[IO.Directory]::CreateDirectory($user)|Out-Null;[IO.Directory]::CreateDirectory($cache)|Out-Null;Copy-Item -LiteralPath (Join-Path $repo 'private/evidence/M5-012/20260816-132209-a316f851/runs/01/user/B13EBABEBABEBABE') -Destination $user -Recurse
  [IO.File]::WriteAllLines((Join-Path $Path 'release-clean-build.log'),@('CMAKE_BUILD_TYPE="Release"','REXSDK_VERSION="0.9.0.21"','[1/1] Cleaning all built files...','[71/71] Linking CXX executable mcla.exe'),$utf8)
  $lines=@('MCLA_RACE_RESOURCE_CONFIG v=1 checkpoints=5 operator_confirmed=1 external_close_required=1');for($i=1;$i-le5;$i++){$lines+="MCLA_RACE_RESOURCE_FRAME v=1 checkpoint=$i width=1280 height=720 present_seq=$($i*100) status=PASS";Write-Bmp (Join-Path $user "mcla-race-resource-$i.bmp") ([byte]$i)};$lines+=@('MCLA_RACE_RESOURCE_SUMMARY v=1 status=PASS checkpoints=5 external_close_required=1','Window closing, shutting down...','Execution complete','Title terminated; hard-exiting process.');[IO.File]::WriteAllLines((Join-Path $cycle 'mcla.log'),$lines,$utf8)
  $samples=@();for($i=0;$i-le5;$i++){$samples+=[ordered]@{checkpoint=$i;private_bytes=[int64](100000000+$i*1000000);working_set_bytes=[int64](80000000+$i*1000000);handle_count=[int64](300+$i);thread_count=[int64]40;gpu_dedicated_bytes=[int64](200000000+$i*2000000);gpu_shared_bytes=[int64](50000000+$i*1000000)}};[IO.File]::WriteAllText((Join-Path $Path 'resource-samples.json'),(ConvertTo-Json @($samples)-Depth 4),$utf8)
}
function Fail([scriptblock]$Action,[string]$Name){try{&$Action|Out-Null;throw "Negative '$Name' accepted."}catch{if($_.Exception.Message-ceq"Negative '$Name' accepted."){throw}}}
$finalizeRoot=Join-Path (Split-Path $root -Parent) ('20990101-000000-'+[guid]::NewGuid().ToString('N').Substring(0,8))
try{New-Fixture $finalizeRoot;$recovered=&$run -FinalizeRun $finalizeRoot;if($recovered.Decision-cne'five-race-bounded-resource-growth-pass'-or-not$recovered.FiveRaceCheckpointsVerified-or-not(Test-Path -LiteralPath (Join-Path $finalizeRoot 'result.json'))){throw 'Finalize-run positive failed.'}}finally{if(Test-Path -LiteralPath $finalizeRoot){Remove-Item -LiteralPath $finalizeRoot -Recurse -Force}}
try{$counterSelfTest=&$run -CounterSelfTest;if(-not$counterSelfTest.ValidAggregationVerified-or-not$counterSelfTest.InvalidStatusIgnored-or-not$counterSelfTest.WrongPidRejected-or-not$counterSelfTest.RetryRequiredForIncompletePair){throw 'GPU counter selector self-test failed.'};New-Fixture $root;$p=&$verify -RunPath $root -Fixture;if($p.decision-cne'five-race-bounded-resource-growth-pass'-or-not$p.controlled_exit-or@($p.samples).Count-ne6){throw 'Positive fixture failed.'};$workingSave=Join-Path $root 'runs/01/user/B13EBABEBABEBABE/545407F8/00000001/mc4.sav/mc4.sav';$originalSave=[IO.File]::ReadAllBytes($workingSave);$updatedSave=[byte[]]$originalSave.Clone();$updatedSave[100]=$updatedSave[100]-bxor0x01;[IO.File]::WriteAllBytes($workingSave,$updatedSave);$updated=&$verify -RunPath $root -Fixture;if(-not$updated.working_save_updated-or$updated.final_save_sha256-ceq$updated.seed_save_sha256){throw 'Shape-preserving working-save update fixture failed.'};[IO.File]::WriteAllBytes($workingSave,$originalSave);$artifacts=@('mcla.exe','rexruntime.dll','TracyClient.dll','rexgpu-xenos.dll')|%{$path=Join-Path $repo "out/build/win-amd64-release/$_";[ordered]@{name=$_;sha256=(Get-FileHash $path -Algorithm SHA256).Hash}};$result=[ordered]@{schema='mcla-race-resource-v1';task='M5-013';decision='five-race-bounded-resource-growth-pass';sdk_version='0.9.0.21';sdk_commit='3ef5b4f143d56b57e3c0e539cb0009ffe3a67e05';build_configuration='Release';seed_save_sha256='711B94303445034A3B127F83E8143FF6DBA3FC96C2B6176F8720E49829AD5021';seed_header_sha256='6DDB2A36CB2AF9FC76F80DBC7BCE9B17F71DDC153FABB47084086CB3FB0B1494';probe=$p;release_artifacts=@($artifacts);scope='five operator-confirmed race completions in one Release process; bounded host private/working memory, handles, threads, and Windows GPU process-memory counters; the isolated working save may update; no claim of all-race or all-driver coverage'};[IO.File]::WriteAllText((Join-Path $root 'result.json'),(ConvertTo-Json $result -Depth 9),$utf8);$persisted=&$verify -ResultPath (Join-Path $root 'result.json');if(-not$persisted.DataIntegrityVerified){throw 'Persisted positive fixture failed.'};$negative=0;$log=Join-Path $root 'runs/01/mcla.log';$logText=[IO.File]::ReadAllText($log);$samplePath=Join-Path $root 'resource-samples.json';$sampleText=[IO.File]::ReadAllText($samplePath)
  foreach($case in @(
    @{n='fatal';kind='log';f={param($x)$x+"`n[FATAL] fixture"}},
    @{n='missing checkpoint';kind='log';f={param($x)$x.Replace('MCLA_RACE_RESOURCE_FRAME v=1 checkpoint=3 width=1280 height=720 present_seq=300 status=PASS','')}},
    @{n='duplicate checkpoint';kind='log';f={param($x)$x+"`nMCLA_RACE_RESOURCE_FRAME v=1 checkpoint=5 width=1280 height=720 present_seq=600 status=PASS"}},
    @{n='nonmonotonic sequence';kind='log';f={param($x)$x.Replace('present_seq=400','present_seq=200')}},
    @{n='missing close';kind='log';f={param($x)$x.Replace('Window closing, shutting down...','')}},
    @{n='private growth';kind='sample';f={param($x)$x.Replace('105000000','900000000')}},
    @{n='handle growth';kind='sample';f={param($x)$x.Replace('305','900')}},
    @{n='thread growth';kind='sample';f={param($x)$o=@($x|ConvertFrom-Json);$o[5].thread_count=100;ConvertTo-Json @($o)-Depth 4}},
    @{n='gpu dedicated growth';kind='sample';f={param($x)$x.Replace('210000000','900000000')}},
    @{n='gpu shared growth';kind='sample';f={param($x)$x.Replace('55000000','500000000')}},
    @{n='transient private spike';kind='sample';f={param($x)$o=@($x|ConvertFrom-Json);$o[3].private_bytes=900000000;ConvertTo-Json @($o)-Depth 4}}
  )){if($case.kind-ceq'log'){[IO.File]::WriteAllText($log,(&$case.f $logText),$utf8);Fail {&$verify -RunPath $root -Fixture} $case.n;[IO.File]::WriteAllText($log,$logText,$utf8)}else{[IO.File]::WriteAllText($samplePath,(&$case.f $sampleText),$utf8);Fail {&$verify -RunPath $root -Fixture} $case.n;[IO.File]::WriteAllText($samplePath,$sampleText,$utf8)};$negative++}
  $bmp=Join-Path $root 'runs/01/user/mcla-race-resource-5.bmp';$bytes=[IO.File]::ReadAllBytes($bmp);$bytes[0]=0;[IO.File]::WriteAllBytes($bmp,$bytes);Fail {&$verify -RunPath $root -Fixture} 'bad bmp';$negative++;Write-Bmp $bmp 5
  [IO.File]::WriteAllBytes($workingSave,[byte[]](1,2,3));Fail {&$verify -RunPath $root -Fixture} 'truncated working save';$negative++;[IO.File]::WriteAllBytes($workingSave,$originalSave)
  $buildLog=Join-Path $root 'release-clean-build.log';$buildText=[IO.File]::ReadAllText($buildLog);[IO.File]::WriteAllText($buildLog,$buildText.Replace('CMAKE_BUILD_TYPE="Release"','CMAKE_BUILD_TYPE="Debug"'),$utf8);Fail {&$verify -RunPath $root -Fixture} 'wrong build configuration';$negative++;[IO.File]::WriteAllText($buildLog,$buildText,$utf8)
  $texts=[IO.File]::ReadAllText($run)+[IO.File]::ReadAllText($verify)+[IO.File]::ReadAllText($app);$needles=@('mcla_race_resource_probe','MCLA_RACE_RESOURCE_CONFIG v=1 checkpoints=5','MCLA_RACE_RESOURCE_FRAME v=1 checkpoint={} width={} height={}','MCLA_RACE_RESOURCE_SUMMARY v=1 status=PASS checkpoints={}','$Process.PrivateMemorySize64','$Process.WorkingSet64','$Process.HandleCount','$Process.Threads.Count','GPU Process Memory(*)','[uint32]$sample.Status-ne0','Get-GpuProcessMemorySample','AddSeconds(10)','CounterSelfTest','InvalidStatusIgnored','RetryRequiredForIncompletePair','Write-ResourceSamples $samplePath $samples','RACE $Index COMPLETE','five-race-bounded-resource-growth-pass','gpu_dedicated_bytes','gpu_shared_bytes','512*$MiB','256*$MiB','Window closing, shutting down','v0.9.0.21','711B94303445034A3B127F83E8143FF6DBA3FC96C2B6176F8720E49829AD5021','6DDB2A36CB2AF9FC76F80DBC7BCE9B17F71DDC153FABB47084086CB3FB0B1494','final_save_sha256','working_save_updated','the isolated working save may update','CMAKE_BUILD_TYPE="Release"','build_log_sha256','"0x8220B810" = { end = 0x8220B834','{ 0x8220B810, sub_8220B810 }','registrar->SetFunction(0x8220B810, sub_8220B810);','DEFINE_REX_FUNC(sub_8220B810)','REX_FUNC_PROLOGUE(0x8220B810);');foreach($needle in $needles){if(-not$texts.Contains($needle)){throw "Source contract missing '$needle'."}}
  $extraNeedles=@('FinalizeRun','Complete-Run','revalidating the completed physical run without relaunch');foreach($needle in $extraNeedles){if(-not$texts.Contains($needle)){throw "Finalize source contract missing '$needle'."}}
  [pscustomobject][ordered]@{PositiveFixtures=5;FailClosedNegatives=$negative;SourceChecks=$needles.Count+$extraNeedles.Count}
}finally{if(Test-Path -LiteralPath $root){Remove-Item -LiteralPath $root -Recurse -Force}}
