[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$repo=(Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '..')).Path;$verify=Join-Path $PSScriptRoot 'verify-retired-service-unlock-policy.ps1';$policy=[IO.File]::ReadAllText((Join-Path $repo 'config/retired-service-unlock-policy.json'))|ConvertFrom-Json
function Clone($Value){(($Value|ConvertTo-Json -Depth 12)|ConvertFrom-Json)}
function TextHash([string]$Path){$text=[IO.File]::ReadAllText($Path).Replace("`r`n","`n");$sha=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($text)))).Replace('-','')}finally{$sha.Dispose()}}
function Record{[ordered]@{schema='mcla-retired-service-unlock-decision-v1';task='M6-009';decision='retail-preserving-compatibility-with-explicit-cheat-separation';policy_sha256=TextHash (Join-Path $repo 'config/retired-service-unlock-policy.json');prior_evidence=[ordered]@{task='M6-008';run_id='20260819-164950-4b322fe1';sha256='7DC8946ABD4B1BB78D52E527655D713EB4FD7037421997F4BA209689BC21903B';decision='explicit-offline-progression-and-retired-service-matrix-pass'};policy=Clone $policy;source_audit=[ordered]@{runtime_unlock_implementation_present=$false;save_or_source_game_mutation_performed=$false;current_service_entitlement_claimed=$false};scope=[ordered]@{retail_progression_preserved=$true;existing_authentic_entitlements_preserved=$true;compatibility_and_cheats_separated=$true;future_cheat_requires_explicit_opt_in=$true;future_cheat_excluded_from_canonical_evidence=$true;audi_r8_unlocked=$false;retired_service_emulated=$false;fake_live_state_used=$false;save_mutated=$false;source_game_mutated=$false;cheat_implemented=$false}}}
$source=&$verify -SourceOnly;$tmp=Join-Path $repo ('private/evidence/M6-009/test-'+[guid]::NewGuid().ToString('N'));[IO.Directory]::CreateDirectory($tmp)|Out-Null;$path=Join-Path $tmp 'result.json';$positive=0;$negative=0
try{
  $base=Record;[IO.File]::WriteAllText($path,($base|ConvertTo-Json -Depth 12),[Text.UTF8Encoding]::new($false));&$verify -ResultPath $path -FixtureMode|Out-Null;$positive++
  $cases=@(
    @{n='schema';m={param($x)$x.schema='bad'}},@{n='task';m={param($x)$x.task='M6-008'}},@{n='decision';m={param($x)$x.decision='unlock'}},@{n='policy hash';m={param($x)$x.policy_sha256='0'}},@{n='prior task';m={param($x)$x.prior_evidence.task='M5'}},@{n='prior run';m={param($x)$x.prior_evidence.run_id='0'}},@{n='prior hash';m={param($x)$x.prior_evidence.sha256='0'}},@{n='prior decision';m={param($x)$x.prior_evidence.decision='pass'}},
    @{n='policy schema';m={param($x)$x.policy.schema='bad'}},@{n='basis missing';m={param($x)$x.policy.historical_basis=@()}},@{n='publisher claim';m={param($x)$x.policy.historical_basis[0].claim='unknown'}},@{n='guide url';m={param($x)$x.policy.historical_basis[1].url='https://example.com'}},@{n='canonical class';m={param($x)$x.policy.canonical_compatibility.classification='cheat'}},@{n='canonical behavior';m={param($x)$x.policy.canonical_compatibility.retired_service_behavior='unlock'}},@{n='offline contract';m={param($x)$x.policy.canonical_compatibility.offline_or_on_disc_contract_required=$false}},@{n='fabrication';m={param($x)$x.policy.canonical_compatibility.new_entitlement_fabricated=$true}},@{n='fake service';m={param($x)$x.policy.canonical_compatibility.fake_service_completion=$true}},@{n='save mutation';m={param($x)$x.policy.canonical_compatibility.save_mutation=$true}},@{n='game mutation';m={param($x)$x.policy.canonical_compatibility.source_game_mutation=$true}},
    @{n='cheat status';m={param($x)$x.policy.optional_cheat.implementation_status='implemented'}},@{n='cheat optin';m={param($x)$x.policy.optional_cheat.explicit_user_opt_in_required=$false}},@{n='cheat default';m={param($x)$x.policy.optional_cheat.default_enabled=$true}},@{n='cheat init';m={param($x)$x.policy.optional_cheat.init_only_required=$false}},@{n='cheat save';m={param($x)$x.policy.optional_cheat.save_mutation_allowed=$true}},@{n='canonical cheat evidence';m={param($x)$x.policy.optional_cheat.canonical_progression_evidence_allowed=$true}},@{n='asset count';m={param($x)$x.policy.asset_decisions=@()}},@{n='asset id';m={param($x)$x.policy.asset_decisions[0].asset='car'}},@{n='historical gate';m={param($x)$x.policy.asset_decisions[0].historical_gate='career'}},@{n='canonical action';m={param($x)$x.policy.asset_decisions[0].canonical_action='unlock'}},@{n='entitlement claim';m={param($x)$x.policy.asset_decisions[0].exact_entitlement_state_in_supported_save_claimed=$true}},
    @{n='runtime unlock';m={param($x)$x.source_audit.runtime_unlock_implementation_present=$true}},@{n='mutation performed';m={param($x)$x.source_audit.save_or_source_game_mutation_performed=$true}},@{n='entitlement claimed';m={param($x)$x.source_audit.current_service_entitlement_claimed=$true}},@{n='retail scope';m={param($x)$x.scope.retail_progression_preserved=$false}},@{n='existing entitlement';m={param($x)$x.scope.existing_authentic_entitlements_preserved=$false}},@{n='separation';m={param($x)$x.scope.compatibility_and_cheats_separated=$false}},@{n='audi unlocked';m={param($x)$x.scope.audi_r8_unlocked=$true}},@{n='service emulated';m={param($x)$x.scope.retired_service_emulated=$true}},@{n='fake live';m={param($x)$x.scope.fake_live_state_used=$true}},@{n='cheat implemented';m={param($x)$x.scope.cheat_implemented=$true}}
  )
  foreach($case in $cases){$r=Clone $base;&$case.m $r;[IO.File]::WriteAllText($path,($r|ConvertTo-Json -Depth 12),[Text.UTF8Encoding]::new($false));$failed=$false;try{&$verify -ResultPath $path -FixtureMode|Out-Null}catch{$failed=$true};if(-not$failed){throw "Negative fixture '$($case.n)' passed."};$negative++}
}finally{if(Test-Path -LiteralPath $tmp){Remove-Item -LiteralPath $tmp -Recurse -Force}}
[pscustomobject][ordered]@{Passed=$true;PositiveFixtures=$positive;FailClosedNegatives=$negative;SourceContractChecks=$source.SourceChecks}
