[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$repo=(Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '..')).Path;$verify=Join-Path $PSScriptRoot 'verify-save-matrix-smoke.ps1';$source=&$verify -SourceOnly;if(-not$source.SourceContractVerified-or$source.SourceChecks-ne28-or$source.FocusedCases-ne10-or$source.FocusedAssertions-ne117){throw 'Source contract failed.'}
function Good{
  $paths=@('third_party/rexglue-sdk/include/rex/system/xtypes.h','third_party/rexglue-sdk/include/rex/system/xam/content_device.h','third_party/rexglue-sdk/include/rex/system/xam/content_manager.h','third_party/rexglue-sdk/src/kernel/xam/xam_content.cpp','third_party/rexglue-sdk/src/kernel/xam/xam_content_device.cpp','third_party/rexglue-sdk/src/kernel/xam/xam_ui.cpp','third_party/rexglue-sdk/src/system/xam/content_manager.cpp','third_party/rexglue-sdk/tests/unit/system/xam_content_persistence_test.cpp','third_party/rexglue-sdk/tests/unit/CMakeLists.txt')
  [ordered]@{schema='mcla-save-matrix-v1';task='M6-005';decision='native-autosave-load-overwrite-plus-isolated-creation-destructive-save-matrix-pass';sdk_version='0.9.0.23';sdk_commit='2473e42d76f6aa0081c93e6745e91f4b35b393fa';build_configuration='Release+RelWithDebInfo';prior_native=[ordered]@{task='M6-002';run_id='20260817-155005-1dd57bd3';result_sha256='21FCBE38695B45D22AE516E33E51AD0A292286985549673811E0FE3E33900644';creation=$false;autosave=$true;load=$true;overwrite=$true;fresh_process=$true;controlled_exit=$true};focused_test=[ordered]@{cases=10;assertions=117;isolated_creation_roundtrip=$true;restart_metadata=$true;truncated_header_rejected=$true;mismatched_header_rejected=$true;interrupted_overwrite_restored=$true;interrupted_new_removed=$true;restart_recovery_idempotent=$true;commit_point_preserved=$true;live_enumeration_safe=$true;committed_overwrite_preserved=$true;storage_full_rejected=$true;sdk_build_log_sha256=('A'*64);test_log_sha256=('B'*64);unit_executable_sha256=('C'*64)};source_integrity=[ordered]@{seed_save_before_sha256='126F7482878C7AACB09AA6795331C906DFB9C4218BE94EDB1D8E51B27CA78AB2';seed_save_after_sha256='126F7482878C7AACB09AA6795331C906DFB9C4218BE94EDB1D8E51B27CA78AB2';seed_header_before_sha256='5827A913515AC0E5D55BB56AEC56DE99CACC0ABB7C8061F59336DF4CEA4A8731';seed_header_after_sha256='5827A913515AC0E5D55BB56AEC56DE99CACC0ABB7C8061F59336DF4CEA4A8731';source_save_mutated=$false;release_build_log_sha256=('D'*64)};release_artifacts=@('mcla.exe','rexruntime.dll','TracyClient.dll','rexgpu-xenos.dll')|ForEach-Object{[ordered]@{name=$_;sha256=('E'*64)}};source_files=@($paths|ForEach-Object{[ordered]@{path=$_;sha256=('F'*64)}});scope=[ordered]@{manual_save_applicable=$false;manual_save_claimed=$false;first_run_oobe_claimed=$false;stock_creation_baseline=$true;general_profile_persistence_claimed=$false;native_gameplay_replayed=$false;destructive_tests_isolated=$true}}
}
function MustFail([scriptblock]$Mutate,[string]$Name){$x=Good;&$Mutate $x;[IO.File]::WriteAllText($path,($x|ConvertTo-Json -Depth 9));try{&$verify -ResultPath $path -FixtureMode|Out-Null;throw "Negative '$Name' passed."}catch{if($_.Exception.Message-ceq"Negative '$Name' passed."){throw}}}
$root=Join-Path $repo ('private/evidence/M6-005/test-'+[guid]::NewGuid().ToString('N'));[IO.Directory]::CreateDirectory($root)|Out-Null;$path=Join-Path $root 'result.json'
try{
  [IO.File]::WriteAllText($path,((Good)|ConvertTo-Json -Depth 9));$positive=&$verify -ResultPath $path -FixtureMode;if(-not$positive.DataIntegrityVerified){throw 'Positive fixture failed.'}
  $cases=@(
    @{n='schema';m={param($x)$x.schema='bad'}},@{n='task';m={param($x)$x.task='M6-006'}},@{n='decision';m={param($x)$x.decision='pass'}},@{n='sdk';m={param($x)$x.sdk_version='0'}},@{n='commit';m={param($x)$x.sdk_commit='0'}},
    @{n='prior hash';m={param($x)$x.prior_native.result_sha256='0'}},@{n='false native creation';m={param($x)$x.prior_native.creation=$true}},@{n='autosave';m={param($x)$x.prior_native.autosave=$false}},@{n='load';m={param($x)$x.prior_native.load=$false}},@{n='overwrite';m={param($x)$x.prior_native.overwrite=$false}},@{n='fresh process';m={param($x)$x.prior_native.fresh_process=$false}},@{n='exit';m={param($x)$x.prior_native.controlled_exit=$false}},
    @{n='cases';m={param($x)$x.focused_test.cases=9}},@{n='assertions';m={param($x)$x.focused_test.assertions=116}},@{n='isolated creation';m={param($x)$x.focused_test.isolated_creation_roundtrip=$false}},@{n='truncated';m={param($x)$x.focused_test.truncated_header_rejected=$false}},@{n='mismatch';m={param($x)$x.focused_test.mismatched_header_rejected=$false}},@{n='interruption';m={param($x)$x.focused_test.interrupted_overwrite_restored=$false}},@{n='new interruption';m={param($x)$x.focused_test.interrupted_new_removed=$false}},@{n='idempotence';m={param($x)$x.focused_test.restart_recovery_idempotent=$false}},@{n='commit point';m={param($x)$x.focused_test.commit_point_preserved=$false}},@{n='live enumeration';m={param($x)$x.focused_test.live_enumeration_safe=$false}},@{n='committed overwrite';m={param($x)$x.focused_test.committed_overwrite_preserved=$false}},@{n='full storage';m={param($x)$x.focused_test.storage_full_rejected=$false}},
    @{n='seed changed';m={param($x)$x.source_integrity.seed_save_after_sha256=('0'*64)}},@{n='mutation flag';m={param($x)$x.source_integrity.source_save_mutated=$true}},@{n='artifact count';m={param($x)$x.release_artifacts=@()}},@{n='source count';m={param($x)$x.source_files=@()}},
    @{n='manual applicable';m={param($x)$x.scope.manual_save_applicable=$true}},@{n='manual claim';m={param($x)$x.scope.manual_save_claimed=$true}},@{n='oobe claim';m={param($x)$x.scope.first_run_oobe_claimed=$true}},@{n='profile claim';m={param($x)$x.scope.general_profile_persistence_claimed=$true}},@{n='game replay';m={param($x)$x.scope.native_gameplay_replayed=$true}},@{n='not isolated';m={param($x)$x.scope.destructive_tests_isolated=$false}},@{n='extra property';m={param($x)$x.extra='x'}},@{n='wrong bool type';m={param($x)$x.scope.manual_save_claimed=0}}
  );foreach($case in $cases){MustFail $case.m $case.n}
  [pscustomobject][ordered]@{Passed=$true;Positives=1;FailClosedNegatives=$cases.Count;SourceChecks=$source.SourceChecks;FocusedCases=$source.FocusedCases;FocusedAssertions=$source.FocusedAssertions}
}finally{Remove-Item -LiteralPath $root -Recurse -Force -ErrorAction SilentlyContinue}
