[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$repo=(Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '..')).Path;$verify=Join-Path $PSScriptRoot 'verify-offline-progression-report.ps1';$source=&$verify -SourceOnly
if(-not$source.SourceContractVerified-or$source.SourceChecks-ne28-or$source.OfflineXamCases-ne6-or$source.OfflineXamAssertions-ne25-or$source.OfflineServiceCases-ne3-or$source.OfflineServiceAssertions-ne32-or$source.AchievementCases-ne6-or$source.AchievementAssertions-ne50-or$source.ImportedReturnHooks-ne5){throw 'Source contract failed.'}
function Good{
  $prior=@([ordered]@{task='M4-004';run_id='20260812-123316-db0f1cf4';sha256='388F2FC350C43149CA6E5AD4E24A1B743F18CFE3A450C6D80962099F73C89AE0';decision='single-local-offline-profile'},[ordered]@{task='M4-009';run_id='20260813-193514-2bb7e7ca';sha256='52AC3A713038DC4EF9A6236CFB76462006B5AAF8D3856D2422A5410AA9847539';decision='offline-service-title-route-pass'},[ordered]@{task='M5-012';run_id='20260817-001225-ade395f8';sha256='D993E2612D1AC769D88264C83FD9C9186BC761E2067317F5A7EB66038C250E58';decision='first-series-results-return-and-release-restart-pass'},[ordered]@{task='M6-003';run_id='20260818-180605-e3b74fb5';sha256='AD3573B56412D7DBC10650BE0D250AFD4AACA22EB8EEEB6F9816E94EC3007E3A';decision='representative-race-system-matrix-pass'},[ordered]@{task='M6-005';run_id='20260818-201702-5d089d9c';sha256='5F46FA6657F39EE5AF990BD505B67D5EDBE6A781E8283D1D51BE07F3543F169E';decision='native-autosave-load-overwrite-plus-isolated-creation-destructive-save-matrix-pass'})
  $matrix=@([ordered]@{feature='achievements';behavior='local';progression_source='achievement-manager';retired_service_result='000004DD';fabricated_rows_or_unlocks=$false},[ordered]@{feature='presence';behavior='unavailable';progression_source='none';retired_service_result='explicit-offline';fabricated_rows_or_unlocks=$false},[ordered]@{feature='leaderboards';behavior='empty-enumeration';progression_source='none';retired_service_result='00000000';fabricated_rows_or_unlocks=$false},[ordered]@{feature='rate-my-ride';behavior='unavailable';progression_source='none';retired_service_result='explicit-offline';fabricated_rows_or_unlocks=$false},[ordered]@{feature='driving-test';behavior='local-save';progression_source='title-save';retired_service_result='not-applicable';fabricated_rows_or_unlocks=$false},[ordered]@{feature='voice';behavior='unavailable';progression_source='none';retired_service_result='800700AA';fabricated_rows_or_unlocks=$false})
  $paths=@('third_party/rexglue-sdk/include/rex/kernel/xam/offline_progression.h','third_party/rexglue-sdk/src/kernel/xam/xam_ui.cpp','third_party/rexglue-sdk/src/kernel/xam/xam_user.cpp','third_party/rexglue-sdk/src/kernel/xam/xam_voice.cpp','third_party/rexglue-sdk/tests/unit/kernel/offline_service_test.cpp','third_party/rexglue-sdk/tests/unit/kernel/offline_service_route_test.cpp','third_party/rexglue-sdk/tests/unit/system/achievement_manager_test.cpp','generated/default/mcla_init.cpp','generated/default/mcla_recomp.0.cpp','generated/default/mcla_recomp.29.cpp','generated/default/mcla_recomp.58.cpp')
  [ordered]@{schema='mcla-offline-progression-v1';task='M6-008';decision='explicit-offline-progression-and-retired-service-matrix-pass';sdk_version='0.9.0.26';sdk_commit='51f18fab1a5c11d50a380a30fbe592b93fd98248';build_configuration='Release+RelWithDebInfo';prior_evidence=$prior;service_matrix=$matrix;focused_tests=[ordered]@{offline_xam_cases=6;offline_xam_assertions=25;offline_service_cases=3;offline_service_assertions=32;achievement_cases=6;achievement_assertions=50;sdk_build_log_sha256=('A'*64);offline_xam_test_log_sha256=('B'*64);offline_service_test_log_sha256=('C'*64);achievement_test_log_sha256=('D'*64);unit_executable_sha256=('E'*64)};release=[ordered]@{build_log_sha256=('F'*64);artifacts=@('mcla.exe','rexruntime.dll','TracyClient.dll','rexgpu-xenos.dll')|ForEach-Object{[ordered]@{name=$_;sha256=('1'*64)}}};source_files=@($paths|ForEach-Object{[ordered]@{path=$_;sha256=('2'*64)}});scope=[ordered]@{prior_offline_frontend_route_bound=$true;prior_local_profile_route_bound=$true;prior_race_progression_bound=$true;prior_save_restart_bound=$true;m6_009_unlock_policy_unchanged=$true;native_current_service_calls_claimed=$false;achievement_guide_ui_claimed=$false;xbox_live_presence_claimed=$false;leaderboard_rows_claimed=$false;rate_my_ride_backend_claimed=$false;voice_transport_claimed=$false;driving_test_exact_unlock_physically_claimed=$false;service_vehicle_unlock_claimed=$false;fake_online_identity_used=$false;fabricated_progression_used=$false}}
}
function MustFail([scriptblock]$Mutation,[string]$Name){$x=Good;&$Mutation $x;[IO.File]::WriteAllText($path,($x|ConvertTo-Json -Depth 10));try{&$verify -ResultPath $path -FixtureMode|Out-Null;throw "Negative '$Name' passed."}catch{if($_.Exception.Message-ceq"Negative '$Name' passed."){throw}}}
$root=Join-Path $repo ('private/evidence/M6-008/test-'+[guid]::NewGuid().ToString('N'));[IO.Directory]::CreateDirectory($root)|Out-Null;$path=Join-Path $root 'result.json'
try{[IO.File]::WriteAllText($path,((Good)|ConvertTo-Json -Depth 10));$positive=&$verify -ResultPath $path -FixtureMode;if(-not$positive.DataIntegrityVerified){throw 'Positive fixture failed.'}
  $cases=@(
    @{n='schema';m={param($x)$x.schema='bad'}},@{n='task';m={param($x)$x.task='M6-009'}},@{n='decision';m={param($x)$x.decision='pass'}},@{n='sdk version';m={param($x)$x.sdk_version='0'}},@{n='sdk commit';m={param($x)$x.sdk_commit='0'}},@{n='prior count';m={param($x)$x.prior_evidence=@()}},@{n='prior hash';m={param($x)$x.prior_evidence[1].sha256='0'}},@{n='matrix count';m={param($x)$x.service_matrix=@()}},@{n='feature';m={param($x)$x.service_matrix[0].feature='online'}},@{n='behavior';m={param($x)$x.service_matrix[2].behavior='fake'}},@{n='progression';m={param($x)$x.service_matrix[4].progression_source='online'}},@{n='result';m={param($x)$x.service_matrix[5].retired_service_result='0'}},@{n='fabricated row';m={param($x)$x.service_matrix[2].fabricated_rows_or_unlocks=$true}},@{n='fabricated unlock';m={param($x)$x.service_matrix[4].fabricated_rows_or_unlocks=$true}},
    @{n='xam cases';m={param($x)$x.focused_tests.offline_xam_cases=5}},@{n='xam assertions';m={param($x)$x.focused_tests.offline_xam_assertions=24}},@{n='service cases';m={param($x)$x.focused_tests.offline_service_cases=2}},@{n='service assertions';m={param($x)$x.focused_tests.offline_service_assertions=31}},@{n='achievement cases';m={param($x)$x.focused_tests.achievement_cases=5}},@{n='achievement assertions';m={param($x)$x.focused_tests.achievement_assertions=49}},@{n='bad digest';m={param($x)$x.focused_tests.unit_executable_sha256='0'}},@{n='artifact count';m={param($x)$x.release.artifacts=@()}},@{n='source count';m={param($x)$x.source_files=@()}},
    @{n='offline prior';m={param($x)$x.scope.prior_offline_frontend_route_bound=$false}},@{n='profile prior';m={param($x)$x.scope.prior_local_profile_route_bound=$false}},@{n='race prior';m={param($x)$x.scope.prior_race_progression_bound=$false}},@{n='save prior';m={param($x)$x.scope.prior_save_restart_bound=$false}},@{n='current service overclaim';m={param($x)$x.scope.native_current_service_calls_claimed=$true}},@{n='guide overclaim';m={param($x)$x.scope.achievement_guide_ui_claimed=$true}},@{n='presence overclaim';m={param($x)$x.scope.xbox_live_presence_claimed=$true}},@{n='rows overclaim';m={param($x)$x.scope.leaderboard_rows_claimed=$true}},@{n='rate backend overclaim';m={param($x)$x.scope.rate_my_ride_backend_claimed=$true}},@{n='voice overclaim';m={param($x)$x.scope.voice_transport_claimed=$true}},@{n='driving exact overclaim';m={param($x)$x.scope.driving_test_exact_unlock_physically_claimed=$true}},@{n='vehicle unlock overclaim';m={param($x)$x.scope.service_vehicle_unlock_claimed=$true}},@{n='m6009 policy';m={param($x)$x.scope.m6_009_unlock_policy_unchanged=$false}},@{n='fake identity';m={param($x)$x.scope.fake_online_identity_used=$true}},@{n='fake progression';m={param($x)$x.scope.fabricated_progression_used=$true}},@{n='wrong bool';m={param($x)$x.scope.voice_transport_claimed=0}},@{n='extra';m={param($x)$x.extra='x'}}
  );foreach($case in $cases){MustFail $case.m $case.n};[pscustomobject][ordered]@{Passed=$true;Positives=1;FailClosedNegatives=$cases.Count;SourceChecks=$source.SourceChecks;OfflineXamCases=$source.OfflineXamCases;OfflineXamAssertions=$source.OfflineXamAssertions;OfflineServiceCases=$source.OfflineServiceCases;OfflineServiceAssertions=$source.OfflineServiceAssertions;AchievementCases=$source.AchievementCases;AchievementAssertions=$source.AchievementAssertions}
}finally{Remove-Item -LiteralPath $root -Recurse -Force -ErrorAction SilentlyContinue}
