[CmdletBinding()]
param()
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$repo=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$verify=Join-Path $PSScriptRoot 'verify-garage-lifecycle-smoke.ps1'
$runScript=Join-Path $PSScriptRoot 'run-garage-lifecycle-smoke.ps1'
$utf8=[Text.UTF8Encoding]::new($false)
$ids=@(@('garage-main-before','showroom-purchase-confirmed','visual-purchase-confirmed','performance-purchase-confirmed','paint-purchase-confirmed','vehicle-switch-confirmed','free-roam-after-garage'),@('restart-garage-main','restart-purchased-vehicle','restart-customization-paint','restart-vehicle-switch','restart-free-roam'))
$actions=@(
  @('START','START','DPAD_DOWN','A','DPAD_DOWN','DPAD_DOWN','A','DPAD_LEFT','A','A','DPAD_UP','A','A','DPAD_RIGHT','A','A','DPAD_DOWN','A','A','DPAD_DOWN','A','A','B','A','DPAD_UP','A','B','DPAD_DOWN','DPAD_DOWN','DPAD_DOWN','A','A','DPAD_DOWN','DPAD_DOWN','DPAD_DOWN','A','DPAD_RIGHT','DPAD_RIGHT','DPAD_RIGHT','DPAD_RIGHT','A','B','B','DPAD_UP','A','DPAD_UP','A','DPAD_DOWN','DPAD_DOWN','DPAD_DOWN','A','A','A'),
  @('START','START','DPAD_DOWN','A','A','DPAD_DOWN','A','A','DPAD_UP','A','DPAD_DOWN','DPAD_DOWN','DPAD_DOWN','A','A','A')
)
$buttons=[ordered]@{START='0010';BACK='0020';A='1000';B='2000';X='4000';Y='8000';DPAD_UP='0001';DPAD_DOWN='0002';DPAD_LEFT='0004';DPAD_RIGHT='0008';LB='0100';RB='0200'}
$seedSave='126F7482878C7AACB09AA6795331C906DFB9C4218BE94EDB1D8E51B27CA78AB2';$seedHeader='5827A913515AC0E5D55BB56AEC56DE99CACC0ABB7C8061F59336DF4CEA4A8731';$prior='D993E2612D1AC769D88264C83FD9C9186BC761E2067317F5A7EB66038C250E58';$scope='one affordable unlocked second vehicle, one representative visual item, one performance item, one changed paint color, vehicle switching, free-roam return, and fresh-process persistence under explicit guest sign-in compatibility state 2; no real network service and no exhaustive vehicle, item, price, economy, garage, or campaign coverage'
function Fail([scriptblock]$Action,[string]$Name){$failed=$false;try{&$Action|Out-Null}catch{$failed=$true};if(-not$failed){throw "Fail-closed fixture '$Name' was accepted."}}
function Write-Json([string]$Path,$Value){[IO.File]::WriteAllText($Path,(ConvertTo-Json $Value -Depth 14),$utf8)}
function Write-Bmp([string]$Path,[byte]$Tag){$bytes=New-Object byte[] 64;$bytes[0]=0x42;$bytes[1]=0x4D;[BitConverter]::GetBytes([int]3686454).CopyTo($bytes,2);[BitConverter]::GetBytes([int]54).CopyTo($bytes,10);[BitConverter]::GetBytes([int]40).CopyTo($bytes,14);[BitConverter]::GetBytes([int]1280).CopyTo($bytes,18);[BitConverter]::GetBytes([int]720).CopyTo($bytes,22);[BitConverter]::GetBytes([uint16]1).CopyTo($bytes,26);[BitConverter]::GetBytes([uint16]32).CopyTo($bytes,28);$bytes[54]=$Tag;$stream=[IO.File]::Open($Path,'Create','Write','None');try{$stream.Write($bytes,0,$bytes.Length);$stream.SetLength(3686454)}finally{$stream.Dispose()}}
function Write-Sparse([string]$Path,[int64]$Length,[byte]$Tag){$stream=[IO.File]::Open($Path,'Create','Write','None');try{$stream.SetLength($Length);$stream.Position=0;$stream.WriteByte($Tag)}finally{$stream.Dispose()}}
function New-Log([int]$Cycle){$phaseIds=$ids[$Cycle-1];$cycleActions=$actions[$Cycle-1];$purchase=if($Cycle-eq1){1}else{0};$persist=if($Cycle-eq2){1}else{0};$lines=@('[I] XAM_USER_SIGNIN_CONFIG v=1 state=2 mode=online-compatible','[I] KernelState: Preparing module launch...','[I] MCLA graphics: nontrivial guest frame captured 1280x720, rgb555 bins 100, luma p05 1, luma p95 250, modal permille 10, nonmodal grid cells 100',"[I] MCLA_GARAGE_LIFECYCLE_CONFIG v=1 cycle=$Cycle phases=$($phaseIds.Count) vehicle_purchase_required=$purchase visual_purchase_required=$purchase performance_purchase_required=$purchase paint_purchase_required=$purchase vehicle_switch_required=1 persistence_required=$persist external_close_required=1");for($i=0;$i-lt$cycleActions.Count;$i++){$sequence=$i+1;$action=$cycleActions[$i];$mask=$buttons[$action];$lines+=@("[I] MCLA_FRONTEND_SMOKE_INPUT v=1 side=source sequence=$sequence buttons=$mask","[I] MCLA_FRONTEND_SMOKE_INPUT v=1 side=guest sequence=$sequence buttons=$mask","[I] MCLA_FRONTEND_SMOKE_INPUT v=1 side=source sequence=$sequence buttons=0000","[I] MCLA_FRONTEND_SMOKE_INPUT v=1 side=guest sequence=$sequence buttons=0000","[I] MCLA_GARAGE_CONTROL v=1 sequence=$sequence action=$action capture=0 width=0 height=0 present_seq=$($Cycle*1000+$sequence) status=PASS")};for($i=0;$i-lt$phaseIds.Count;$i++){$lines+="[I] MCLA_GARAGE_LIFECYCLE_FRAME v=1 cycle=$Cycle phase=$($i+1) id=$($phaseIds[$i]) width=1280 height=720 present_seq=$($Cycle*2000+$i+1) status=PASS"};$lines+=@("[I] MCLA_GARAGE_LIFECYCLE_SUMMARY v=1 status=PASS cycle=$Cycle phases=$($phaseIds.Count) persistence_required=$persist external_close_required=1",'[I] Window closing, shutting down...','[I] Execution complete','[I] Title terminated; hard-exiting process.');$lines-join"`n"}
function Get-Paths([string]$User){[ordered]@{save=Join-Path $User 'B13EBABEBABEBABE/545407F8/00000001/mc4.sav/mc4.sav';header=Join-Path $User 'B13EBABEBABEBABE/545407F8/Headers/00000001/mc4.sav.header'}}
function New-Chain($P1,$P2){[ordered]@{schema='mcla-garage-save-chain-v1';seed_save_sha256=$seedSave;seed_header_sha256=$seedHeader;cycle1_post_save_sha256=(Get-FileHash $P1.save -Algorithm SHA256).Hash;cycle1_post_header_sha256=(Get-FileHash $P1.header -Algorithm SHA256).Hash;cycle2_pre_save_sha256=(Get-FileHash $P1.save -Algorithm SHA256).Hash;cycle2_pre_header_sha256=(Get-FileHash $P1.header -Algorithm SHA256).Hash;cycle2_post_save_sha256=(Get-FileHash $P2.save -Algorithm SHA256).Hash;cycle2_post_header_sha256=(Get-FileHash $P2.header -Algorithm SHA256).Hash;save_bytes=537428;header_bytes=328;cycle1_save_changed=$true;handoff_exact=$true}}
function New-Record($Probe){[ordered]@{schema='mcla-garage-lifecycle-v1';task='M6-002';decision='representative-garage-purchase-customization-persistence-pass';sdk_version='0.9.0.22';sdk_commit='576b34fd233acf4579dd2375691dbe86fb4bf8e1';build_configuration='Release';route_id='representative-two-process-garage-v1';prior_race_restart_result_sha256=$prior;seed_source_run_id='20260817-013319-c2e7223f';seed_source_context='external-owner-identified-hangout-save-after-race-1';seed_source_log_sha256='F6D9B7C09C730242B7D96C7F9FE3C6754A4FE726D22093A2BDAF089D2EABE04A';seed_source_capture_sha256='AAB64D0118D75F9EAECA50805DF3FB9EAC56B75726F4D2B97484C681509530A3';seed_save_sha256=$seedSave;seed_header_sha256=$seedHeader;signin_compatibility_state=2;network_services_claimed=$false;probe=$Probe;release_artifacts=@();scope=$scope}}
$root=Join-Path $repo ('private/evidence/M6-002/test-'+[guid]::NewGuid().ToString('N'));$negative=0
try{
  [IO.Directory]::CreateDirectory($root)|Out-Null;[IO.File]::WriteAllText((Join-Path $root 'release-clean-build.log'),'fixture',$utf8)
  $paths=@();for($cycle=1;$cycle-le2;$cycle++){$cycleRoot=Join-Path $root ("runs/{0:D2}"-f$cycle);$user=Join-Path $cycleRoot 'user';$cache=Join-Path $cycleRoot 'cache';[IO.Directory]::CreateDirectory($user)|Out-Null;[IO.Directory]::CreateDirectory($cache)|Out-Null;[IO.File]::WriteAllText((Join-Path $cycleRoot 'mcla.log'),(New-Log $cycle),$utf8);for($i=0;$i-lt$ids[$cycle-1].Count;$i++){Write-Bmp (Join-Path $user "mcla-garage-lifecycle-$($ids[$cycle-1][$i]).bmp") ([byte]($cycle*32+$i))};$p=Get-Paths $user;[IO.Directory]::CreateDirectory((Split-Path $p.save -Parent))|Out-Null;[IO.Directory]::CreateDirectory((Split-Path $p.header -Parent))|Out-Null;Write-Sparse $p.save 537428 ([byte]$cycle);Write-Sparse $p.header 328 ([byte](10+$cycle));$paths+=$p}
  $chain=New-Chain $paths[0] $paths[1];Write-Json (Join-Path $root 'save-chain.json') $chain;$probe=&$verify -RunPath $root -Fixture;if($probe.cycle_count-ne2-or$probe.purchase_categories-ne4-or$probe.automated_control_steps-ne69-or$probe.operator_interaction_required-or-not$probe.deterministic_slot0_automation-or-not$probe.fresh_process_persistence){throw 'Positive run fixture failed.'};$positive=1
  $result=Join-Path $root 'result.json';Write-Json $result (New-Record $probe);$verified=&$verify -ResultPath $result -Fixture;if($verified.PurchaseCategoriesVerified-ne4-or-not$verified.FreshProcessPersistenceVerified){throw 'Positive result fixture failed.'};$positive++
  for($cycle=1;$cycle-le2;$cycle++){$log=Join-Path $root ("runs/{0:D2}/mcla.log"-f$cycle);$original=[IO.File]::ReadAllText($log);foreach($case in @(@{name="cycle $cycle missing config";from='[I] MCLA_GARAGE_LIFECYCLE_CONFIG';to='[I] REMOVED_CONFIG'},@{name="cycle $cycle fatal";from='[I] Execution complete';to="[FATAL] boom`n[I] Execution complete"},@{name="cycle $cycle missing summary";from='[I] MCLA_GARAGE_LIFECYCLE_SUMMARY';to='[I] REMOVED_SUMMARY'},@{name="cycle $cycle missing close";from='[I] Window closing';to='[I] REMOVED_CLOSE'})){[IO.File]::WriteAllText($log,$original.Replace($case.from,$case.to),$utf8);Fail {&$verify -RunPath $root -Fixture} $case.name;$negative++};[IO.File]::WriteAllText($log,$original,$utf8)}
  $log1=Join-Path $root 'runs/01/mcla.log';$original=[IO.File]::ReadAllText($log1);[IO.File]::WriteAllText($log1,$original.Replace('id=paint-purchase-confirmed','id=wrong-phase'),$utf8);Fail {&$verify -RunPath $root -Fixture} 'wrong phase id';$negative++;[IO.File]::WriteAllText($log1,$original.Replace('present_seq=102','present_seq=101'),$utf8);Fail {&$verify -RunPath $root -Fixture} 'duplicate present sequence';$negative++;[IO.File]::WriteAllText($log1,$original,$utf8)
  [IO.File]::WriteAllText($log1,$original.Replace('state=2 mode=online-compatible','state=1 mode=local'),$utf8);Fail {&$verify -RunPath $root -Fixture} 'local sign-in state';$negative++;[IO.File]::WriteAllText($log1,$original.Replace('[I] KernelState: Preparing module launch...',"[I] XAM_USER_SIGNIN_CONFIG v=1 state=2 mode=online-compatible`n[I] KernelState: Preparing module launch..."),$utf8);Fail {&$verify -RunPath $root -Fixture} 'duplicate sign-in config';$negative++;[IO.File]::WriteAllText($log1,$original,$utf8)
  [IO.File]::WriteAllText($log1,$original.Replace('[I] MCLA_GARAGE_CONTROL v=1 sequence=1 action=START','[I] REMOVED_GARAGE_CONTROL v=1 sequence=1 action=START'),$utf8);Fail {&$verify -RunPath $root -Fixture} 'missing deterministic control';$negative++;[IO.File]::WriteAllText($log1,$original.Replace('sequence=1 action=START capture=0','sequence=1 action=A capture=0'),$utf8);Fail {&$verify -RunPath $root -Fixture} 'wrong deterministic action';$negative++;[IO.File]::WriteAllText($log1,$original.Replace('sequence=2 action=START capture=0','sequence=1 action=START capture=0'),$utf8);Fail {&$verify -RunPath $root -Fixture} 'duplicate deterministic sequence';$negative++;[IO.File]::WriteAllText($log1,$original.Replace('side=guest sequence=1 buttons=0010','side=guest sequence=1 buttons=1000'),$utf8);Fail {&$verify -RunPath $root -Fixture} 'guest input mismatch';$negative++;[IO.File]::WriteAllText($log1,$original.Replace('sequence=1 action=START capture=0 width=0 height=0','sequence=1 action=START capture=1 width=1280 height=720'),$utf8);Fail {&$verify -RunPath $root -Fixture} 'hidden control capture';$negative++;[IO.File]::WriteAllText($log1,$original,$utf8)
  $user1=Join-Path $root 'runs/01/user';$a=Join-Path $user1 'mcla-garage-lifecycle-garage-main-before.bmp';$b=Join-Path $user1 'mcla-garage-lifecycle-showroom-purchase-confirmed.bmp';$backup=[IO.File]::ReadAllBytes($b);Copy-Item $a $b -Force;Fail {&$verify -RunPath $root -Fixture} 'duplicate cycle capture';$negative++;[IO.File]::WriteAllBytes($b,$backup)
  $chainPath=Join-Path $root 'save-chain.json';$chain=New-Chain $paths[0] $paths[1];$chain.cycle2_pre_save_sha256='0'*64;Write-Json $chainPath $chain;Fail {&$verify -RunPath $root -Fixture} 'handoff mismatch';$negative++;$chain=New-Chain $paths[0] $paths[1];$chain.cycle1_save_changed=$false;Write-Json $chainPath $chain;Fail {&$verify -RunPath $root -Fixture} 'unchanged flag';$negative++;Write-Json $chainPath (New-Chain $paths[0] $paths[1])
  $stream=[IO.File]::Open($paths[1].save,'Open','Write','None');try{$stream.Position=1;$stream.WriteByte(99)}finally{$stream.Dispose()};Fail {&$verify -RunPath $root -Fixture} 'cycle2 save drift';$negative++;Write-Sparse $paths[1].save 537428 2;Write-Json $chainPath (New-Chain $paths[0] $paths[1])
  $request=Join-Path $user1 '.mcla-garage-lifecycle-test.request';[IO.File]::WriteAllText($request,'1',$utf8);Fail {&$verify -RunPath $root -Fixture} 'unconsumed request';$negative++;Remove-Item $request
  $extra=Join-Path $root 'unexpected.txt';[IO.File]::WriteAllText($extra,'x',$utf8);Fail {&$verify -RunPath $root -Fixture} 'extra root child';$negative++;Remove-Item $extra
  $record=New-Record $probe;$record.scope='forged';Write-Json $result $record;Fail {&$verify -ResultPath $result -Fixture} 'scope drift';$negative++;$record=New-Record $probe;$record.probe.vehicle_switches=1;Write-Json $result $record;Fail {&$verify -ResultPath $result -Fixture} 'probe drift';$negative++;$record=New-Record $probe;$record.network_services_claimed=$true;Write-Json $result $record;Fail {&$verify -ResultPath $result -Fixture} 'network-service overclaim';$negative++
  $source=[IO.File]::ReadAllText($runScript)+[IO.File]::ReadAllText($verify)+[IO.File]::ReadAllText((Join-Path $repo 'src/mcla_app.cpp'))+[IO.File]::ReadAllText((Join-Path $repo 'config/garage-lifecycle-route.json'));$needles=@('mcla_garage_lifecycle_probe=true','mcla_garage_lifecycle_cycle=$Cycle','--xam_user_signin_state=2','XAM_USER_SIGNIN_CONFIG v=1 state=2 mode=online-compatible','signin_compatibility_state=2','network_services_claimed=$false','.mcla-garage-control.request','deterministic slot-0 automation','MCLA_GARAGE_CONTROL v=1 sequence={} action={} capture={} width={} ','MCLA_FRONTEND_SMOKE_INPUT v=1 side=guest','kGuestInputObservationTimeout{20}','automated_control_steps=69','operator_interaction_required=$false','Cycle-2 handoff does not exactly match cycle-1 output','cycle1Save-ceq$seedSaveSha','Copy-Item -LiteralPath (Join-Path $user1','Start-Sleep -Seconds 8','MCLA_GARAGE_LIFECYCLE_CONFIG v=1 cycle={} phases={} ','MCLA_GARAGE_LIFECYCLE_FRAME v=1 cycle={} phase={} id={} ','MCLA_GARAGE_LIFECYCLE_SUMMARY v=1 status=PASS cycle={} phases={} ','representative-two-process-garage-v1','showroom-purchase-confirmed','visual-purchase-confirmed','performance-purchase-confirmed','paint-purchase-confirmed','restart-purchased-vehicle','restart-customization-paint','fresh_process_persistence','purchase_categories=4','vehicle_switches=2','--clean-first','--parallel 8','WM_CLOSE','20260817-013319-c2e7223f','external-owner-identified-hangout-save-after-race-1','0x8220B810','HANGOUT seed source evidence drifted','no real network service','no exhaustive vehicle, item, price, economy, garage, or campaign coverage');foreach($needle in $needles){if(-not$source.Contains($needle)){throw "Source contract missing '$needle'."}};if([IO.File]::ReadAllText($runScript).Contains('Read-Host')){throw 'Garage runner unexpectedly requires operator input.'}
  [pscustomobject][ordered]@{PositiveFixtures=$positive;FailClosedNegatives=$negative;SourceContractChecks=$needles.Count;PhysicalRunRequired=$true}
}finally{if(Test-Path -LiteralPath $root){Remove-Item -LiteralPath $root -Recurse -Force}}
