[CmdletBinding()]
param()
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$repo=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path;$verify=Join-Path $PSScriptRoot 'verify-city-streaming-smoke.ps1';$runScript=Join-Path $PSScriptRoot 'run-city-streaming-smoke.ps1';$utf8=[Text.UTF8Encoding]::new($false);$ids=@('hollywood-sunset-start','beverly-westwood','santa-monica-venice','hollywood-hills-valley','downtown-industrial','usc-exposition','crenshaw','south-105','hollywood-sunset-return')
function Fail([scriptblock]$Action,[string]$Name){$failed=$false;try{&$Action|Out-Null}catch{$failed=$true};if(-not$failed){throw "Fail-closed fixture '$Name' was accepted."}}
function Write-Bmp([string]$Path,[byte]$Tag){$bytes=New-Object byte[] 64;$bytes[0]=0x42;$bytes[1]=0x4D;[BitConverter]::GetBytes([int]3686454).CopyTo($bytes,2);[BitConverter]::GetBytes([int]54).CopyTo($bytes,10);[BitConverter]::GetBytes([int]40).CopyTo($bytes,14);[BitConverter]::GetBytes([int]1280).CopyTo($bytes,18);[BitConverter]::GetBytes([int]720).CopyTo($bytes,22);[BitConverter]::GetBytes([uint16]1).CopyTo($bytes,26);[BitConverter]::GetBytes([uint16]32).CopyTo($bytes,28);$bytes[54]=$Tag;$stream=[IO.File]::Open($Path,'Create','Write','None');try{$stream.Write($bytes,0,$bytes.Length);$stream.SetLength(3686454)}finally{$stream.Dispose()}}
function New-Log(){$lines=@('[I] KernelState: Preparing module launch...','[I] MCLA graphics: nontrivial guest frame captured 1280x720, rgb555 bins 100, luma p05 1, luma p95 250, modal permille 10, nonmodal grid cells 100','[I] MCLA_CITY_STREAMING_CONFIG v=1 checkpoints=9 unique_regions=8 gps_capture=1 operator_confirmed=1 return_to_start=1 external_close_required=1');for($i=0;$i-lt9;$i++){$lines+="[I] MCLA_CITY_STREAMING_FRAME v=1 checkpoint=$($i+1) id=$($ids[$i]) width=1280 height=720 present_seq=$($i+101) status=PASS"};$lines+=@('[I] MCLA_CITY_STREAMING_SUMMARY v=1 status=PASS checkpoints=9 unique_regions=8 return_to_start=1 external_close_required=1','[I] Window closing, shutting down...','[I] Execution complete','[I] Title terminated; hard-exiting process.');$lines-join"`n"}
function New-Samples(){@([ordered]@{checkpoint=0;id='baseline';private_bytes=[int64]100000000;working_set_bytes=[int64]90000000;handle_count=[int64]20;thread_count=[int64]10;io_read_bytes=[int64]0})+@(for($i=0;$i-lt9;$i++){[ordered]@{checkpoint=$i+1;id=$ids[$i];private_bytes=[int64](100000000+$i*1000000);working_set_bytes=[int64](90000000+$i*500000);handle_count=[int64]20;thread_count=[int64]10;io_read_bytes=[int64](($i+1)*2097152)}})}
function Write-Samples([string]$Path,$Samples){[IO.File]::WriteAllText($Path,(ConvertTo-Json @($Samples)-Depth 5),$utf8)}
function New-Record($Probe){[ordered]@{schema='mcla-city-streaming-v1';task='M6-001';decision='all-major-city-regions-streaming-pass';sdk_version='0.9.0.21';sdk_commit='3ef5b4f143d56b57e3c0e539cb0009ffe3a67e05';build_configuration='Release';route_id='major-city-regions-v1';prior_world_streaming_result_sha256='A582A41BB254D9187BC6F8147E89E2FF2E92D0EA4B79945760BA6FBCF334BC28';seed_save_sha256='711B94303445034A3B127F83E8143FF6DBA3FC96C2B6176F8720E49829AD5021';seed_header_sha256='6DDB2A36CB2AF9FC76F80DBC7BCE9B17F71DDC153FABB47084086CB3FB0B1494';probe=$Probe;release_artifacts=@();scope='eight project-defined geographic coverage zones plus return-to-start in one operator-driven Release process; GPS checkpoint captures and bounded host/process-I/O telemetry; archive-backed RPF behavior inherited from immutable M5-002 evidence; no claim of event, road, collectible, or campaign-content completeness'}}
$root=Join-Path $repo ('private/evidence/M6-001/test-'+[guid]::NewGuid().ToString('N'));$cycle=Join-Path $root 'runs/01';$user=Join-Path $cycle 'user';$saveDir=Join-Path $user 'B13EBABEBABEBABE/545407F8/00000001/mc4.sav';$headerDir=Join-Path $user 'B13EBABEBABEBABE/545407F8/Headers/00000001';$negative=0
try{
  [IO.Directory]::CreateDirectory($saveDir)|Out-Null;[IO.Directory]::CreateDirectory($headerDir)|Out-Null;[IO.File]::WriteAllText((Join-Path $root 'release-clean-build.log'),'fixture',$utf8);[IO.File]::WriteAllText((Join-Path $cycle 'mcla.log'),(New-Log),$utf8);$stream=[IO.File]::Open((Join-Path $saveDir 'mc4.sav'),'Create','Write','None');$stream.SetLength(537428);$stream.Dispose();$stream=[IO.File]::Open((Join-Path $headerDir 'mc4.sav.header'),'Create','Write','None');$stream.SetLength(328);$stream.Dispose();for($i=0;$i-lt9;$i++){Write-Bmp (Join-Path $user "mcla-city-streaming-$($ids[$i]).bmp") ([byte]($i+1))};Write-Samples (Join-Path $root 'resource-samples.json') (New-Samples)
  $probe=&$verify -RunPath $root -Fixture;if($probe.checkpoint_count-ne9-or$probe.unique_region_count-ne8-or-not$probe.return_to_start){throw 'Positive run fixture failed.'};$positive=1
  $result=Join-Path $root 'result.json';$record=New-Record $probe;[IO.File]::WriteAllText($result,(ConvertTo-Json $record -Depth 14),$utf8);$verified=&$verify -ResultPath $result -Fixture;if($verified.MajorRegionsVerified-ne8){throw 'Positive result fixture failed.'};$positive++
  $log=Join-Path $cycle 'mcla.log';$original=[IO.File]::ReadAllText($log)
  foreach($case in @(@{name='missing config';from='[I] MCLA_CITY_STREAMING_CONFIG';to='[I] REMOVED_CONFIG'},@{name='fatal tail';from='[I] Execution complete';to="[FATAL] boom`n[I] Execution complete"},@{name='wrong route id';from='id=crenshaw';to='id=wrong'},@{name='duplicate sequence';from='present_seq=102';to='present_seq=101'},@{name='missing summary';from='[I] MCLA_CITY_STREAMING_SUMMARY';to='[I] REMOVED_SUMMARY'},@{name='missing close';from='[I] Window closing';to='[I] REMOVED_CLOSE'})){[IO.File]::WriteAllText($log,$original.Replace($case.from,$case.to),$utf8);Fail {&$verify -RunPath $root -Fixture} $case.name;$negative++};[IO.File]::WriteAllText($log,$original,$utf8)
  $captureA=Join-Path $user 'mcla-city-streaming-hollywood-sunset-start.bmp';$captureB=Join-Path $user 'mcla-city-streaming-beverly-westwood.bmp';$captureBackup=[IO.File]::ReadAllBytes($captureB);Copy-Item $captureA $captureB -Force;Fail {&$verify -RunPath $root -Fixture} 'duplicate capture';$negative++;[IO.File]::WriteAllBytes($captureB,$captureBackup)
  $samples=New-Samples;Write-Samples (Join-Path $root 'resource-samples.json') @($samples[0..8]);Fail {&$verify -RunPath $root -Fixture} 'missing sample';$negative++;$samples=New-Samples;$samples[4].io_read_bytes=[int64]1;Write-Samples (Join-Path $root 'resource-samples.json') $samples;Fail {&$verify -RunPath $root -Fixture} 'read counter regression';$negative++;$samples=New-Samples;foreach($sample in $samples){$sample.io_read_bytes=[int64]0};Write-Samples (Join-Path $root 'resource-samples.json') $samples;Fail {&$verify -RunPath $root -Fixture} 'no route reads';$negative++;$samples=New-Samples;$samples[5].private_bytes=[int64](2GB);Write-Samples (Join-Path $root 'resource-samples.json') $samples;Fail {&$verify -RunPath $root -Fixture} 'unbounded private memory';$negative++;Write-Samples (Join-Path $root 'resource-samples.json') (New-Samples)
  $record=New-Record $probe;$record.scope='forged';[IO.File]::WriteAllText($result,(ConvertTo-Json $record -Depth 14),$utf8);Fail {&$verify -ResultPath $result -Fixture} 'scope drift';$negative++;$record=New-Record $probe;$record.route_id='wrong';[IO.File]::WriteAllText($result,(ConvertTo-Json $record -Depth 14),$utf8);Fail {&$verify -ResultPath $result -Fixture} 'result route drift';$negative++;$record=New-Record $probe;$record.probe.checkpoint_count=8;[IO.File]::WriteAllText($result,(ConvertTo-Json $record -Depth 14),$utf8);Fail {&$verify -ResultPath $result -Fixture} 'probe drift';$negative++
  $source=([IO.File]::ReadAllText($runScript)+[IO.File]::ReadAllText($verify)+[IO.File]::ReadAllText((Join-Path $repo 'src/mcla_app.cpp')));$needles=@('mcla_city_streaming_probe=true','REGION $($checkpoint.index)/9','$short="$($checkpoint.id.ToUpperInvariant()) READY"','The game is still running','GetProcessIoCounters','CounterSelfTestPassed','$parsedSamples=Get-Content -LiteralPath $samplesPath -Raw|ConvertFrom-Json','$samples=@($parsedSamples)','MCLA_CITY_STREAMING_CONFIG v=1 checkpoints=9','MCLA_CITY_STREAMING_FRAME v=1 checkpoint=','MCLA_CITY_STREAMING_SUMMARY v=1 status=PASS checkpoints=9','major-city-regions-v1','gps_capture=1','return_to_start=1','external_close_required=1','prior_world_streaming_result_sha256','A582A41BB254D9187BC6F8147E89E2FF2E92D0EA4B79945760BA6FBCF334BC28','all-major-city-regions-streaming-pass','open the full GPS map','--clean-first','--parallel 8','WM_CLOSE','no claim of event, road, collectible, or campaign-content completeness');foreach($needle in $needles){if(-not$source.Contains($needle)){throw "Source contract missing '$needle'."}}
  [pscustomobject][ordered]@{PositiveFixtures=$positive;FailClosedNegatives=$negative;SourceContractChecks=$needles.Count;PhysicalRunRequired=$true}
}finally{if(Test-Path -LiteralPath $root){Remove-Item -LiteralPath $root -Recurse -Force}}
