[CmdletBinding()]param()
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$repo=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path;$verify=Join-Path $PSScriptRoot 'verify-delivery-transition-regression.ps1';$runner=Join-Path $PSScriptRoot 'run-delivery-transition-regression.ps1';$tmp=Join-Path $repo ('private/evidence/M6-014/test-delivery-'+[guid]::NewGuid().ToString('N').Substring(0,8));[IO.Directory]::CreateDirectory($tmp)|Out-Null;$path=Join-Path $tmp 'result.json';$positive=0;$negative=0
function Clone($Value){$Value|ConvertTo-Json -Depth 12|ConvertFrom-Json}
function Record{[ordered]@{schema='mcla-delivery-transition-regression-v1';task='M6-014';known_issue='KI-024';decision='delivery-transition-current-artifact-pass';suite_id='20260901-153415-d747cf2d';sdk_version='0.10.0.1';sdk_commit='7dd5cb33002a443b097c0f65d5566c0a0f2db838';build_configuration='Release';run_id='20260901-203448-d31ab681';active_confirmation_utc='2026-09-01T17:45:53Z';stable_confirmation_utc='2026-09-01T17:50:53Z';stability_seconds=300;seed_save_sha256=('A'*64);seed_header_sha256=('B'*64);save_after_sha256=('C'*64);header_after_sha256=('D'*64);release_artifacts=@([ordered]@{name='mcla.exe';sha256=('1'*64)},[ordered]@{name='rexruntime.dll';sha256=('2'*64)},[ordered]@{name='TracyClient.dll';sha256=('3'*64)},[ordered]@{name='rexgpu-xenos.dll';sha256=('4'*64)});runtime_logs=@([ordered]@{name='mcla.log';sha256=('5'*64);bytes=1L});runtime_fatal_markers=0;controlled_external_close=$true;exit_code=0;force_cleanup=$false;save_archive=[ordered]@{sha256=('6'*64);files=1;bytes=1L};scope=[ordered]@{delivery_transition_physically_confirmed=$true;active_delivery_gameplay_physically_confirmed=$true;five_minute_stability_physically_confirmed=$true;full_delivery_completion_claimed=$false;two_hour_soak_claimed=$false}}}
try{$base=Record;[IO.File]::WriteAllText($path,($base|ConvertTo-Json -Depth 12));&$verify -ResultPath $path -Fixture|Out-Null;$positive++;$cases=@(@{n='schema';m={param($x)$x.schema='bad'}},@{n='issue';m={param($x)$x.known_issue='KI-023'}},@{n='decision';m={param($x)$x.decision='pass'}},@{n='sdk';m={param($x)$x.sdk_version='0.10.0.0'}},@{n='suite';m={param($x)$x.suite_id='other'}},@{n='short';m={param($x)$x.stability_seconds=299}},@{n='timing';m={param($x)$x.stable_confirmation_utc='2026-09-01T17:46:53Z'}},@{n='artifacts';m={param($x)$x.release_artifacts=@()}},@{n='logs';m={param($x)$x.runtime_logs=@()}},@{n='fatal';m={param($x)$x.runtime_fatal_markers=1}},@{n='exit';m={param($x)$x.exit_code=1}},@{n='forced';m={param($x)$x.force_cleanup=$true}},@{n='archive';m={param($x)$x.save_archive.files=0}},@{n='physical';m={param($x)$x.scope.active_delivery_gameplay_physically_confirmed=$false}},@{n='broad soak';m={param($x)$x.scope.two_hour_soak_claimed=$true}});foreach($case in $cases){$record=Clone $base;&$case.m $record;[IO.File]::WriteAllText($path,($record|ConvertTo-Json -Depth 12));$failed=$false;try{&$verify -ResultPath $path -Fixture|Out-Null}catch{$failed=$true};if(-not$failed){throw "Negative '$($case.n)' passed."};$negative++}
  $source=[IO.File]::ReadAllText($runner);$verifySource=[IO.File]::ReadAllText($verify);foreach($needle in @('ValidateRange(300,600)','DELIVERY ACTIVE','DELIVERY STABLE','ReadProcessAwareExact','[Console]::KeyAvailable','Process exited while waiting','stability window','watch-soak-save.ps1','ArgQuote $saveWatcher','ArgQuote $user','ArgQuote $archive','Delivery runtime log set is empty.','controlled_external_close=$true','two_hour_soak_claimed=$false','verify-delivery-transition-regression.ps1','gameBefore=Game','gameAfter=Game','Source-game payload changed during delivery regression.')){if(-not$source.Contains($needle)){throw "Runner source contract missing: $needle"}};foreach($needle in @('latest.json','complete_profile_tree','save_after_sha256','header_after_sha256','Progressed delivery seed','snapshot.json','BE2D1D6C79DC834A0E5C50A601667A51E10EA86AF5E16062380ACFC2DEAEE79B','currentGame=Game','Current source-game payload drifted from the bound suite.')){if(-not$verifySource.Contains($needle)){throw "Verifier source contract missing: $needle"}};if($source.Contains('Read-Host')-or$source.Contains('Get-FileHash')){throw 'Delivery runner contains a blocking prompt or unavailable hash cmdlet.'}
}finally{if(Test-Path -LiteralPath $tmp){Remove-Item -LiteralPath $tmp -Recurse -Force}}
[pscustomobject]@{Passed=$true;PositiveFixtures=$positive;FailClosedNegatives=$negative;SourceChecks=29}
