[CmdletBinding()]
param(
    [string]$GeneratedRoot,
    [string]$ExpectedManifestPath,
    [ValidateRange(1, 10000)][int]$ExpectedCppCount = 62,
    [string]$BuildRoot
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoRoot = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '..')).Path
if (-not $GeneratedRoot) {
    $GeneratedRoot = Join-Path $repoRoot 'generated/default'
}
if (-not $ExpectedManifestPath) {
    $ExpectedManifestPath = Join-Path $repoRoot 'private/evidence/M3-005/generated-manifest.json'
}

foreach ($path in @($GeneratedRoot, $ExpectedManifestPath)) {
    if (-not (Test-Path -LiteralPath $path)) { throw "Required path was not found: '$path'." }
}
$generatedRootPath = (Resolve-Path -LiteralPath $GeneratedRoot).Path
$manifestPath = (Resolve-Path -LiteralPath $ExpectedManifestPath).Path
$repoPrefix = $repoRoot.TrimEnd('\') + '\'
$generatedPrefix = $generatedRootPath.TrimEnd('\') + '\'
if (-not $generatedRootPath.StartsWith($repoPrefix, [System.StringComparison]::OrdinalIgnoreCase)) {
    throw "Generated root must stay inside the repository: '$generatedRootPath'."
}
if ((Get-Item -LiteralPath $generatedRootPath -Force).Attributes -band [System.IO.FileAttributes]::ReparsePoint) {
    throw "Generated root must not be a reparse point: '$generatedRootPath'."
}

$expected = Get-Content -LiteralPath $manifestPath -Raw | ConvertFrom-Json
if ($expected.schema -ne 1 -or $expected.file_count -ne @($expected.files).Count) {
    throw 'Generated manifest schema or file count is invalid.'
}
$expectedPaths = @($expected.files.path)
if (@($expectedPaths | Sort-Object -Unique).Count -ne $expected.file_count) {
    throw 'Generated manifest contains duplicate paths.'
}

$actualFiles = @(Get-ChildItem -LiteralPath $generatedRootPath -File -Recurse -Force | Sort-Object FullName)
if ($actualFiles.Count -ne $expected.file_count) {
    throw "Generated file count $($actualFiles.Count) does not match manifest count $($expected.file_count)."
}
$actualTotalBytes = [long](($actualFiles | Measure-Object Length -Sum).Sum)
if ($actualTotalBytes -ne $expected.total_bytes) {
    throw "Generated byte count $actualTotalBytes does not match manifest total $($expected.total_bytes)."
}

$actualByPath = @{}
foreach ($item in $actualFiles) {
    if ($item.Attributes -band [System.IO.FileAttributes]::ReparsePoint) {
        throw "Generated file must not be a reparse point: '$($item.FullName)'."
    }
    $relative = $item.FullName.Substring($generatedPrefix.Length).Replace('\', '/')
    $actualByPath[$relative] = $item
}
if (Compare-Object @($actualByPath.Keys) $expectedPaths) {
    throw 'Generated directory paths do not exactly match the accepted manifest.'
}

foreach ($entry in @($expected.files)) {
    $relative = [string]$entry.path
    if (-not $actualByPath.ContainsKey($relative)) {
        throw "Generated manifest entry is missing: '$relative'."
    }
    $item = $actualByPath[$relative]
    $hash = (Get-FileHash -LiteralPath $item.FullName -Algorithm SHA256).Hash
    if ($item.Length -ne $entry.bytes -or $hash -ne $entry.sha256) {
        throw "Generated file differs from the accepted manifest: '$relative'."
    }
}

$sourcesPath = Join-Path $generatedRootPath 'sources.cmake'
$headerPath = Join-Path $generatedRootPath 'mcla_init.h'
foreach ($path in @($sourcesPath, $headerPath)) {
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
        throw "Required generated integration file is missing: '$path'."
    }
}
$sourceText = Get-Content -LiteralPath $sourcesPath -Raw
$sourceEntries = @([regex]::Matches(
    $sourceText,
    '\$\{CMAKE_CURRENT_LIST_DIR\}/(?<path>[A-Za-z0-9._/-]+[.]cpp)'
) | ForEach-Object { $_.Groups['path'].Value })
$uniqueSourceEntries = @($sourceEntries | Sort-Object -Unique)
$manifestCppEntries = @($expected.files.path | Where-Object { $_ -match '[.]cpp$' } | Sort-Object)
if ($sourceEntries.Count -ne $ExpectedCppCount -or
    $uniqueSourceEntries.Count -ne $ExpectedCppCount -or
    (Compare-Object $uniqueSourceEntries $manifestCppEntries)) {
    throw 'sources.cmake does not list the exact unique C++ set from the accepted manifest.'
}

$relativeRoot = $generatedRootPath.Substring($repoPrefix.Length).Replace('\', '/')
$tracked = @(& git -C $repoRoot ls-files -- $relativeRoot)
if ($LASTEXITCODE -ne 0) { throw 'git ls-files failed during the generated-source audit.' }
if ($tracked.Count -ne 0) { throw "Generated files are tracked: $($tracked -join ', ')." }
foreach ($item in $actualFiles) {
    $relative = $item.FullName.Substring($repoPrefix.Length).Replace('\', '/')
    & git -C $repoRoot check-ignore -q -- $relative
    if ($LASTEXITCODE -ne 0) { throw "Generated file is not ignored by Git: '$relative'." }
}

$executableHash = $null
$objectCount = $null
if ($BuildRoot) {
    if (-not (Test-Path -LiteralPath $BuildRoot -PathType Container)) {
        throw "Build root was not found: '$BuildRoot'."
    }
    $buildRootPath = (Resolve-Path -LiteralPath $BuildRoot).Path
    $executablePath = Join-Path $buildRootPath 'mcla.exe'
    if (-not (Test-Path -LiteralPath $executablePath -PathType Leaf)) {
        throw "Native build output was not found: '$executablePath'."
    }
    $stream = [System.IO.File]::OpenRead($executablePath)
    try {
        if ($stream.ReadByte() -ne 0x4D -or $stream.ReadByte() -ne 0x5A) {
            throw "Native build output is not a PE executable: '$executablePath'."
        }
    } finally {
        $stream.Dispose()
    }
    $objectCount = @(Get-ChildItem -LiteralPath $buildRootPath -File -Recurse -Filter '*.cpp.obj' |
        Where-Object { $_.FullName.Replace('\', '/') -match '/generated/default/' }).Count
    if ($objectCount -ne $ExpectedCppCount) {
        throw "Build consumed $objectCount generated C++ objects; expected $ExpectedCppCount."
    }
    $executableHash = (Get-FileHash -LiteralPath $executablePath -Algorithm SHA256).Hash
}

[pscustomobject]@{
    Validated = $true
    GeneratedFiles = $actualFiles.Count
    GeneratedCppSources = $uniqueSourceEntries.Count
    GeneratedBytes = $actualTotalBytes
    ManifestSha256 = (Get-FileHash -LiteralPath $manifestPath -Algorithm SHA256).Hash
    TrackedGeneratedFiles = $tracked.Count
    BuildObjectCount = $objectCount
    ExecutableSha256 = $executableHash
}
