[CmdletBinding(DefaultParameterSetName='Run')]
param(
  [Parameter(Mandatory,ParameterSetName='Run')][string]$RunPath,
  [Parameter(Mandatory,ParameterSetName='Result')][string]$ResultPath,
  [switch]$Fixture
)

Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$repo=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$utf8=[Text.UTF8Encoding]::new($false)
$routeIds=@('hollywood-sunset-start','beverly-westwood','santa-monica-venice','hollywood-hills-valley','downtown-industrial','usc-exposition','crenshaw','south-105','hollywood-sunset-return')
$seedSaveSha='711B94303445034A3B127F83E8143FF6DBA3FC96C2B6176F8720E49829AD5021'
$seedHeaderSha='6DDB2A36CB2AF9FC76F80DBC7BCE9B17F71DDC153FABB47084086CB3FB0B1494'
$priorResultSha='A582A41BB254D9187BC6F8147E89E2FF2E92D0EA4B79945760BA6FBCF334BC28'
$sdkCommit='3ef5b4f143d56b57e3c0e539cb0009ffe3a67e05'

function Resolve-Safe([string]$Path,[string]$Description,[switch]$Exists){
  $full=if([IO.Path]::IsPathRooted($Path)){[IO.Path]::GetFullPath($Path)}else{[IO.Path]::GetFullPath((Join-Path $repo $Path))}
  $prefix=$repo.TrimEnd('\')+'\';if(-not$full.StartsWith($prefix,[StringComparison]::OrdinalIgnoreCase)){throw "$Description escapes repository."}
  $current=$repo;foreach($part in @($full.Substring($prefix.Length).Split('\')|Where-Object{$_.Length})){$current=Join-Path $current $part;if((Test-Path -LiteralPath $current)-and((Get-Item -LiteralPath $current -Force).Attributes-band[IO.FileAttributes]::ReparsePoint)){throw "$Description traverses a reparse point."}}
  if($Exists-and-not(Test-Path -LiteralPath $full)){throw "$Description is missing."};$full
}
function Assert-NoReparse([string]$Root){foreach($item in @(Get-ChildItem -LiteralPath $Root -Recurse -Force)){if($item.Attributes-band[IO.FileAttributes]::ReparsePoint){throw 'Evidence contains a reparse point.'}}}
function Get-Tree([string]$Root){
  $entries=@();$bytes=0L;foreach($item in @(Get-ChildItem -LiteralPath $Root -Recurse -Force|Sort-Object FullName)){$rel=$item.FullName.Substring($Root.Length).TrimStart('\').Replace('\','/');if($rel-ceq'result.json'){continue};if($item.PSIsContainer){$entries+=[ordered]@{kind='directory';path=$rel}}else{$bytes+=$item.Length;$entries+=[ordered]@{kind='file';path=$rel;bytes=$item.Length;sha256=(Get-FileHash -LiteralPath $item.FullName -Algorithm SHA256).Hash}}}
  $json=ConvertTo-Json @($entries)-Compress -Depth 4;$sha=[Security.Cryptography.SHA256]::Create();try{$hash=-join($sha.ComputeHash($utf8.GetBytes($json))|ForEach-Object{$_.ToString('X2')})}finally{$sha.Dispose()};[ordered]@{sha256=$hash;files=@($entries|Where-Object{$_.kind-ceq'file'}).Count;directories=@($entries|Where-Object{$_.kind-ceq'directory'}).Count;bytes=$bytes}
}
function Get-Logs([string]$Root){
  $files=@(Get-ChildItem -LiteralPath $Root -File -Filter 'mcla*.log');if($files.Count-lt1-or$files.Count-gt31){throw 'Runtime-log count is invalid.'};$current=@($files|Where-Object{$_.Name-ceq'mcla.log'});if($current.Count-ne1){throw 'Current runtime log missing.'}
  $rot=@();foreach($file in @($files|Where-Object{$_.Name-cne'mcla.log'})){$match=[regex]::Match($file.Name,'^mcla\.([1-9][0-9]*)\.log$');if(-not$match.Success){throw 'Malformed runtime-log rotation.'};$rot+=[pscustomobject]@{index=[int]$match.Groups[1].Value;file=$file}}
  $indices=@($rot|ForEach-Object{$_.index}|Sort-Object);for($i=0;$i-lt$indices.Count;$i++){if($indices[$i]-ne$i+1){throw 'Runtime-log rotation gap.'}}
  $ordered=@($rot|Sort-Object index -Descending|ForEach-Object{$_.file})+$current[0];$text='';$manifest=@();$bytes=0L;foreach($file in $ordered){$bytes+=$file.Length;if($bytes-gt268435456){throw 'Runtime logs exceed 256 MiB.'};$text+=[IO.File]::ReadAllText($file.FullName)+"`n";$manifest+=[ordered]@{name=$file.Name;bytes=$file.Length;sha256=(Get-FileHash -LiteralPath $file.FullName -Algorithm SHA256).Hash}}
  [pscustomobject]@{text=$text;manifest=@($manifest);bytes=$bytes}
}
function One([string]$Text,[string]$Pattern,[string]$Name){$matches=[regex]::Matches($Text,$Pattern);if($matches.Count-ne1){throw "$Name count is $($matches.Count)."};$matches[0]}
function Read-Bmp([string]$Path,[string]$Name){$file=Resolve-Safe $Path $Name -Exists;$bytes=[IO.File]::ReadAllBytes($file);if($bytes.Length-ne3686454-or$bytes[0]-ne0x42-or$bytes[1]-ne0x4D-or[BitConverter]::ToInt32($bytes,18)-ne1280-or[Math]::Abs([BitConverter]::ToInt32($bytes,22))-ne720-or[BitConverter]::ToUInt16($bytes,28)-ne32){throw "$Name is not the exact 1280x720x32 BMP shape."};[ordered]@{sha256=(Get-FileHash -LiteralPath $file -Algorithm SHA256).Hash;bytes=$bytes.Length}}
function Assert-StaticContract {
  $route=Get-Content -LiteralPath (Join-Path $repo 'config/city-streaming-route.json') -Raw|ConvertFrom-Json;if($route.schema-cne'mcla-city-streaming-route-v1'-or$route.route_id-cne'major-city-regions-v1'-or$route.checkpoints.Count-ne9){throw 'City route config identity is invalid.'}
  for($i=0;$i-lt9;$i++){if($route.checkpoints[$i].index-ne$i+1-or$route.checkpoints[$i].id-cne$routeIds[$i]-or[string]::IsNullOrWhiteSpace($route.checkpoints[$i].label)-or[string]::IsNullOrWhiteSpace($route.checkpoints[$i].instruction)){throw 'City route checkpoint contract is invalid.'}}
  $source=[IO.File]::ReadAllText((Join-Path $repo 'src/mcla_app.cpp'));foreach($needle in @('mcla_city_streaming_probe','MCLA_CITY_STREAMING_CONFIG v=1 checkpoints=9','MCLA_CITY_STREAMING_FRAME v=1 checkpoint={} id={} width={}','MCLA_CITY_STREAMING_SUMMARY v=1 status=PASS checkpoints={}')){if(-not$source.Contains($needle)){throw "City-streaming source contract is missing '$needle'."}}
  foreach($id in $routeIds){if(-not$source.Contains('"'+$id+'"')){throw "City-streaming source contract is missing route id '$id'."}}
}
function Get-Probe([string]$Path){
  Assert-StaticContract;$root=Resolve-Safe $Path 'M6-001 run root' -Exists;Assert-NoReparse $root
  if(-not$Fixture-and-not[regex]::IsMatch((Split-Path $root -Leaf),'^20[0-9]{6}-[0-9]{6}-[a-f0-9]{8}$')){throw 'Physical run-root name is not canonical.'}
  $buildLog=Resolve-Safe (Join-Path $root 'release-clean-build.log') 'Release clean-build log' -Exists;$buildText=[IO.File]::ReadAllText($buildLog);if(-not$Fixture){foreach($needle in @('CMAKE_BUILD_TYPE="Release"','REXSDK_VERSION="0.9.0.21"','Cleaning all built files','Linking CXX executable mcla.exe')){if(-not$buildText.Contains($needle)){throw "Release clean-build log is missing '$needle'."}}}
  $cycle=Resolve-Safe (Join-Path $root 'runs/01') 'Cycle root' -Exists;$logs=Get-Logs $cycle;$text=$logs.text
  foreach($bad in @('[FATAL]','Assertion failed','PPC_UNIMPLEMENTED','Guest crash','DXGI_ERROR_DEVICE_REMOVED','MCLA city streaming: failed','X_STATUS_IO_DEVICE_ERROR')){if($text.Contains($bad)){throw "Banned marker '$bad'."}}
  $launch=One $text 'KernelState: Preparing module launch\.\.\.' 'Launch';$first=One $text 'MCLA graphics: nontrivial guest frame captured 1280x720' 'First frame';$config=One $text 'MCLA_CITY_STREAMING_CONFIG v=1 checkpoints=9 unique_regions=8 gps_capture=1 operator_confirmed=1 return_to_start=1 external_close_required=1' 'Config'
  $frames=[regex]::Matches($text,'MCLA_CITY_STREAMING_FRAME v=1 checkpoint=([1-9]) id=([a-z0-9-]+) width=1280 height=720 present_seq=([1-9][0-9]*) status=PASS');if($frames.Count-ne9){throw 'City checkpoint frame count is invalid.'};$priorSeq=0L
  for($i=0;$i-lt9;$i++){if([int]$frames[$i].Groups[1].Value-ne$i+1-or$frames[$i].Groups[2].Value-cne$routeIds[$i]-or[int64]$frames[$i].Groups[3].Value-le$priorSeq){throw 'City checkpoint identity/order/present sequence is invalid.'};$priorSeq=[int64]$frames[$i].Groups[3].Value}
  $summary=One $text 'MCLA_CITY_STREAMING_SUMMARY v=1 status=PASS checkpoints=9 unique_regions=8 return_to_start=1 external_close_required=1' 'Summary';$close=One $text 'Window closing, shutting down\.\.\.' 'Close';$complete=One $text 'Execution complete' 'Complete';$hard=One $text 'Title terminated; hard-exiting process\.' 'Hard exit'
  if(-not($launch.Index-lt$first.Index-and$first.Index-lt$config.Index-and$config.Index-lt$frames[0].Index-and$frames[8].Index-lt$summary.Index-and$summary.Index-lt$close.Index-and$close.Index-lt$complete.Index-and$complete.Index-lt$hard.Index)){throw 'City route chronology is invalid.'}
  $captures=@();foreach($id in $routeIds){$captures+=[ordered]@{id=$id;frame=Read-Bmp (Join-Path $cycle "user/mcla-city-streaming-$id.bmp") "Capture $id"}}
  if(@($captures.frame.sha256|Select-Object -Unique).Count-ne9){throw 'City GPS captures are not all distinct.'}
  $samplesPath=Resolve-Safe (Join-Path $root 'resource-samples.json') 'Resource samples' -Exists;$parsedSamples=Get-Content -LiteralPath $samplesPath -Raw|ConvertFrom-Json;$samples=@($parsedSamples);if($samples.Count-ne10){throw 'Expected baseline plus nine region samples.'};$properties=@('checkpoint','id','private_bytes','working_set_bytes','handle_count','thread_count','io_read_bytes')
  for($i=0;$i-lt10;$i++){if(($samples[$i].PSObject.Properties.Name-join',')-cne($properties-join',')-or$samples[$i].checkpoint-ne$i){throw 'Resource sample schema/order is invalid.'};$expectedId=if($i-eq0){'baseline'}else{$routeIds[$i-1]};if($samples[$i].id-cne$expectedId){throw 'Resource sample route identity is invalid.'};foreach($property in $properties[2..6]){if($samples[$i].$property-isnot[long]-and$samples[$i].$property-isnot[int]){throw "Resource sample $property type is invalid."};if([int64]$samples[$i].$property-lt0){throw "Resource sample $property is negative."}};if($i-gt0-and[int64]$samples[$i].io_read_bytes-lt[int64]$samples[$i-1].io_read_bytes){throw 'Process read-byte counter regressed.'}}
  $MiB=1048576L;$routeSamples=@($samples[1..9]);$firstRoute=$samples[1];$peakPrivate=[int64](($routeSamples|Measure-Object private_bytes -Maximum).Maximum)-[int64]$firstRoute.private_bytes;$peakWorking=[int64](($routeSamples|Measure-Object working_set_bytes -Maximum).Maximum)-[int64]$firstRoute.working_set_bytes;$peakHandles=[int64](($routeSamples|Measure-Object handle_count -Maximum).Maximum)-[int64]$firstRoute.handle_count;$peakThreads=[int64](($routeSamples|Measure-Object thread_count -Maximum).Maximum)-[int64]$firstRoute.thread_count;$ioGrowth=[int64]$samples[9].io_read_bytes-[int64]$samples[0].io_read_bytes
  if($peakPrivate-gt768*$MiB-or$peakWorking-gt768*$MiB-or$peakHandles-gt256-or$peakThreads-gt32-or$ioGrowth-lt1*$MiB){throw 'City-route resource or process-I/O bounds failed.'}
  $save=Resolve-Safe (Join-Path $cycle 'user/B13EBABEBABEBABE/545407F8/00000001/mc4.sav/mc4.sav') 'Working save' -Exists;$header=Resolve-Safe (Join-Path $cycle 'user/B13EBABEBABEBABE/545407F8/Headers/00000001/mc4.sav.header') 'Working save header' -Exists;if((Get-Item $save).Length-ne537428-or(Get-Item $header).Length-ne328){throw 'Working save shape changed unexpectedly.'}
  if(-not$Fixture){$prior=Resolve-Safe 'private/evidence/M5-002/20260814-093131-ddca5b9d/result.json' 'M5-002 result' -Exists;if((Get-FileHash $prior -Algorithm SHA256).Hash-cne$priorResultSha){throw 'M5-002 archive-streaming prerequisite drifted.'}}
  [ordered]@{decision='all-major-city-regions-streaming-pass';route_id='major-city-regions-v1';checkpoint_count=9;unique_region_count=8;return_to_start=$true;captures=@($captures);samples=@($samples);peak_growth=[ordered]@{private_bytes=[Math]::Max(0L,$peakPrivate);working_set_bytes=[Math]::Max(0L,$peakWorking);handle_count=[Math]::Max(0L,$peakHandles);thread_count=[Math]::Max(0L,$peakThreads)};io_read_growth_bytes=$ioGrowth;runtime_logs=@($logs.manifest);runtime_log_bytes=$logs.bytes;final_save_sha256=(Get-FileHash $save -Algorithm SHA256).Hash;final_header_sha256=(Get-FileHash $header -Algorithm SHA256).Hash;controlled_exit=$true;tree=Get-Tree $root}
}

if($PSCmdlet.ParameterSetName-ceq'Run'){Get-Probe $RunPath;return}
$result=Resolve-Safe $ResultPath 'M6-001 result' -Exists;$record=Get-Content -LiteralPath $result -Raw|ConvertFrom-Json;$props=@('schema','task','decision','sdk_version','sdk_commit','build_configuration','route_id','prior_world_streaming_result_sha256','seed_save_sha256','seed_header_sha256','probe','release_artifacts','scope');if(($record.PSObject.Properties.Name-join',')-cne($props-join',')-or$record.schema-cne'mcla-city-streaming-v1'-or$record.task-cne'M6-001'-or$record.decision-cne'all-major-city-regions-streaming-pass'-or$record.sdk_version-cne'0.9.0.21'-or$record.sdk_commit-cne$sdkCommit-or$record.build_configuration-cne'Release'-or$record.route_id-cne'major-city-regions-v1'-or$record.prior_world_streaming_result_sha256-cne$priorResultSha-or$record.seed_save_sha256-cne$seedSaveSha-or$record.seed_header_sha256-cne$seedHeaderSha){throw 'M6-001 result identity is invalid.'}
$root=Split-Path $result -Parent;$probe=Get-Probe $root;if((ConvertTo-Json $record.probe -Compress -Depth 12)-cne(ConvertTo-Json $probe -Compress -Depth 12)){throw 'M6-001 result probe drifted.'};if($record.scope-cne'eight project-defined geographic coverage zones plus return-to-start in one operator-driven Release process; GPS checkpoint captures and bounded host/process-I/O telemetry; archive-backed RPF behavior inherited from immutable M5-002 evidence; no claim of event, road, collectible, or campaign-content completeness'){throw 'M6-001 result scope is invalid.'}
if(-not$Fixture){$build=Resolve-Safe 'out/build/win-amd64-release' 'Release build' -Exists;$artifacts=@('mcla.exe','rexruntime.dll','TracyClient.dll','rexgpu-xenos.dll')|ForEach-Object{$path=Join-Path $build $_;[ordered]@{name=$_;sha256=(Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash}};if((ConvertTo-Json $record.release_artifacts -Compress)-cne(ConvertTo-Json @($artifacts)-Compress)){throw 'Release artifacts drifted.'};$sdk=Join-Path $repo 'third_party/rexglue-sdk';if((&git -C $sdk rev-parse HEAD).Trim()-cne$sdkCommit-or(&git -C $sdk describe --tags --exact-match HEAD 2>$null).Trim()-cne'v0.9.0.21'-or(git -C $sdk status --porcelain)){throw 'SDK identity drifted.'};if(@((Get-Process mcla -ErrorAction SilentlyContinue)|Where-Object{try{$_.Path-ceq(Join-Path $build 'mcla.exe')}catch{$false}}).Count){throw 'Release process remains.'}}
[pscustomobject][ordered]@{Decision=$record.decision;MajorRegionsVerified=8;ReturnToStartVerified=$true;ArchivePrerequisiteBound=$true;ControlledExitVerified=$true;DataIntegrityVerified=$true}
