[CmdletBinding()]
param(
  [string]$ResultPath,
  [string]$FixturePath,
  [switch]$Fixture
)

Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$repo=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$gameVerifier=Join-Path $PSScriptRoot 'verify-game-manifest.ps1'
$deliveryVerifier=Join-Path $PSScriptRoot 'verify-delivery-transition-regression.ps1'
$artifactNames=@('mcla.exe','mcla_crash_handler.exe','rexruntime.dll','TracyClient.dll','rexgpu-xenos.dll')
$saveRelative='B13EBABEBABEBABE/545407F8/00000001/mc4.sav/mc4.sav'
$headerRelative='B13EBABEBABEBABE/545407F8/Headers/00000001/mc4.sav.header'

function Safe([string]$Path,[string]$Description,[switch]$Exists){if([string]::IsNullOrWhiteSpace($Path)){throw "$Description path is empty."};$full=if([IO.Path]::IsPathRooted($Path)){[IO.Path]::GetFullPath($Path)}else{[IO.Path]::GetFullPath((Join-Path $repo $Path))};$prefix=$repo.TrimEnd('\')+'\';if(-not$full.StartsWith($prefix,[StringComparison]::OrdinalIgnoreCase)){throw "$Description escapes repository."};$cursor=$repo;foreach($part in @($full.Substring($prefix.Length).Split('\')|Where-Object Length)){$cursor=Join-Path $cursor $part;if((Test-Path -LiteralPath $cursor)-and((Get-Item -LiteralPath $cursor -Force).Attributes-band[IO.FileAttributes]::ReparsePoint)){throw "$Description traverses a reparse point."}};if($Exists-and-not(Test-Path -LiteralPath $full)){throw "$Description is missing."};$full}
function Hash([string]$Path){$stream=[IO.File]::OpenRead((Safe $Path 'Hash source' -Exists));$sha=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($sha.ComputeHash($stream))).Replace('-','')}finally{$sha.Dispose();$stream.Dispose()}}
function Tree([string]$Root){$sha=[Security.Cryptography.SHA256]::Create();try{$files=@(Get-ChildItem -LiteralPath $Root -File -Recurse -Force|Sort-Object FullName);$bytes=0L;foreach($file in $files){$rel=$file.FullName.Substring($Root.TrimEnd('\').Length+1).Replace('\','/');$line=[Text.Encoding]::UTF8.GetBytes("$rel`t$($file.Length)`t$(Hash $file.FullName)`n");$null=$sha.TransformBlock($line,0,$line.Length,$line,0);$bytes+=$file.Length};$null=$sha.TransformFinalBlock([byte[]]::new(0),0,0);[ordered]@{sha256=([BitConverter]::ToString($sha.Hash)).Replace('-','');files=$files.Count;bytes=$bytes}}finally{$sha.Dispose()}}
function Game([string]$Root){$verified=&$gameVerifier -GamePath $Root;$manifest=Get-Content -LiteralPath $verified.ManifestPath -Raw|ConvertFrom-Json;$hashes=0;foreach($entry in @($manifest.Files)){$candidate=Join-Path $Root ([string]$entry.Path).Replace('/','\');if((Hash $candidate)-cne([string]$entry.Sha256).ToUpperInvariant()){throw "Source-game hash drifted for '$($entry.Path)'."};$hashes++};if($hashes-ne[int]$verified.FileCount){throw 'Source-game hash coverage is incomplete.'};[ordered]@{file_count=[int]$verified.FileCount;payload_bytes=[long]$verified.PayloadBytes;source_iso_sha256=[string]$verified.SourceIsoSha256}}
function Artifacts([string]$Root){@($artifactNames|ForEach-Object{[ordered]@{name=$_;sha256=(Hash (Join-Path $Root $_))}})}
function Exact($Value,[string[]]$Names,[string]$Description){if(($Value.PSObject.Properties.Name-join',')-cne($Names-join',')){throw "$Description properties changed."}}
function Sha([string]$Value,[string]$Description){if($Value-cnotmatch'^[0-9A-F]{64}$'){throw "$Description is not an uppercase SHA-256."}}
function IntExact($Value,[long]$Minimum,[long]$Maximum,[string]$Description){$integer=$Value-is[byte]-or$Value-is[sbyte]-or$Value-is[int16]-or$Value-is[uint16]-or$Value-is[int32]-or$Value-is[uint32]-or$Value-is[int64]-or$Value-is[uint64];if(-not$integer){throw "$Description is not an integer."};$number=[long]$Value;if($number-lt$Minimum-or$number-gt$Maximum){throw "$Description is outside its accepted range."};$number}
function BoolExact($Value,[bool]$Expected,[string]$Description){if($Value-isnot[bool]-or$Value-ne$Expected){throw "$Description is not the exact expected boolean."}}
function TimeExact($Value,[string]$Description){if($Value-is[DateTime]){return $Value.ToUniversalTime()};if($Value-isnot[string]){throw "$Description is not a timestamp string."};$parsed=[DateTime]::MinValue;if(-not[DateTime]::TryParseExact($Value,'O',[Globalization.CultureInfo]::InvariantCulture,[Globalization.DateTimeStyles]::RoundtripKind,[ref]$parsed)){throw "$Description is not an ISO round-trip timestamp."};$parsed.ToUniversalTime()}
function NoReparse([string]$Root,[string]$Description){if(@(Get-ChildItem -LiteralPath $Root -Recurse -Force|Where-Object{$_.Attributes-band[IO.FileAttributes]::ReparsePoint}).Count){throw "$Description contains a reparse point."}}
function Bounds($Samples){$first=$Samples[0];$last=$Samples[-1];[ordered]@{private_growth_bytes=[long]$last.private_bytes-[long]$first.private_bytes;working_growth_bytes=[long]$last.working_set_bytes-[long]$first.working_set_bytes;handle_growth=[long]$last.handle_count-[long]$first.handle_count;thread_growth=[long]$last.thread_count-[long]$first.thread_count;io_read_growth_bytes=[long]$last.io_read_bytes-[long]$first.io_read_bytes;private_peak_growth_bytes=[long](($Samples|ForEach-Object private_bytes|Measure-Object -Maximum).Maximum)-[long]$first.private_bytes;working_peak_growth_bytes=[long](($Samples|ForEach-Object working_set_bytes|Measure-Object -Maximum).Maximum)-[long]$first.working_set_bytes}}

$path=if($Fixture){Safe $FixturePath 'Fixture result' -Exists}else{Safe $ResultPath 'Mixed-gameplay result' -Exists};$r=Get-Content -LiteralPath $path -Raw|ConvertFrom-Json
$top=@('schema','task','decision','run_id','target_duration_seconds','actual_duration_seconds','started_utc','completed_utc','attested_utc','sdk_baseline','project_build','historical_frontend','delivery_prerequisite','gameplay_seed','game','release_artifacts','resource_samples','resource_bounds','capture_attempts','captures','runtime_logs','runtime_fatal_markers','host_display_audit','controlled_external_close','exit_code','force_cleanup','save_archive','scope');Exact $r $top 'Result'
if($r.schema-cne'mcla-one-hour-mixed-gameplay-long-session-v3'-or$r.task-cne'M6-014'-or$r.decision-cne'one-hour-mixed-gameplay-long-session-pass'-or$r.run_id-cnotmatch'^\d{8}-\d{6}-[0-9a-f]{8}$'){throw 'Result identity is invalid.'};$targetDuration=IntExact $r.target_duration_seconds 3600 3600 'Target duration';$actualDuration=IntExact $r.actual_duration_seconds 3600 3630 'Actual duration'
$started=TimeExact $r.started_utc 'Started';$completed=TimeExact $r.completed_utc 'Completed';$attested=TimeExact $r.attested_utc 'Attested';$utcDuration=[long][Math]::Floor(($completed-$started).TotalSeconds);if($utcDuration-lt$actualDuration-or$utcDuration-gt($actualDuration+30)-or$attested-lt$completed){throw 'One-hour chronology is invalid.'}
Exact $r.sdk_baseline @('path','sha256','sdk_version','sdk_commit') 'SDK baseline';if($r.sdk_baseline.path-cne'private/evidence/M6-014/20260901-153415-d747cf2d/suite.json'-or$r.sdk_baseline.sha256-cne'EB553F0B34F00837A7A0C2FA3FDDD4FBEA9444FE4268EAC266D889A80DCA37C6'-or$r.sdk_baseline.sdk_version-cne'0.10.0.1'-or$r.sdk_baseline.sdk_commit-cne'7dd5cb33002a443b097c0f65d5566c0a0f2db838'){throw 'SDK baseline contract failed.'}
Exact $r.project_build @('version','configuration','build_log_name','build_log_sha256') 'Project build';if($r.project_build.version-cne'0.8.2.0'-or$r.project_build.configuration-cne'Release'-or$r.project_build.build_log_name-cne'build.log'){throw 'Project build contract failed.'};Sha ([string]$r.project_build.build_log_sha256) 'Project build log'
Exact $r.historical_frontend @('suite_path','suite_sha256','stage_path','stage_sha256','tree_sha256','duration_seconds','executable_sha256') 'Historical frontend';$historicalDuration=IntExact $r.historical_frontend.duration_seconds 7202 7202 'Historical frontend duration';if($r.historical_frontend.suite_sha256-cne'009DB466CA39195C02B137C45F4A11EBA87080D1C60B15D54887C5CBD85E0F3C'-or$r.historical_frontend.stage_sha256-cne'4E97A021296A0521F959CB9A37AE7BA1B0D3A93B6D311651E10DFCF75E39AC9C'-or$r.historical_frontend.tree_sha256-cne'C44F1C9D0E47834BA745CE267500E826E490706B1BDFE4A081AE65FE88D6665D'-or$r.historical_frontend.executable_sha256-cne'9202CDC09DA1402460312E0204AB0CF5B6D05D9C07B205CA136414CD1C655FD4'){throw 'Historical frontend contract failed.'}
Exact $r.delivery_prerequisite @('result_path','result_sha256') 'Delivery prerequisite';if($r.delivery_prerequisite.result_path-cne'private/evidence/M6-014/delivery-regressions/20260901-203448-d31ab681/result.json'-or$r.delivery_prerequisite.result_sha256-cne'E7200300CA38718DD6978C26E8F4CE5CF4EF1279441B5F032CE2075F387FF0F1'){throw 'Delivery prerequisite contract failed.'}
Exact $r.gameplay_seed @('archive_path','latest_path','latest_sha256','captured_utc','snapshot_directory','snapshot_tree_sha256','save_before_sha256','header_before_sha256','save_after_sha256','header_after_sha256','working_copy_tree_sha256') 'Gameplay seed';if($r.gameplay_seed.archive_path-cnotmatch'^private/save-archive/M6-014/[^/]+$'-or$r.gameplay_seed.latest_path-cne($r.gameplay_seed.archive_path+'/latest.json')-or$r.gameplay_seed.snapshot_directory-cnotmatch'^\d{8}-\d{6}Z-[0-9A-F]{16}-[0-9A-F]{16}$'){throw 'Gameplay seed path contract failed.'};$null=TimeExact $r.gameplay_seed.captured_utc 'Gameplay seed captured';foreach($name in @('latest_sha256','snapshot_tree_sha256','save_before_sha256','header_before_sha256','save_after_sha256','header_after_sha256','working_copy_tree_sha256')){Sha ([string]$r.gameplay_seed.$name) "Gameplay seed $name"}
Exact $r.game @('file_count','payload_bytes','source_iso_sha256') 'Game'
$gameFiles=IntExact $r.game.file_count 15 15 'Game file count';$gameBytes=IntExact $r.game.payload_bytes 6569586392 6569586392 'Game payload bytes';if($r.game.source_iso_sha256-cne'AFCAAE68593246B1F83328681B690E254A13C37DD2E8DC34AB0DEB6C0F471FDB'){throw 'Game identity failed.'}
$artifacts=@($r.release_artifacts)
if($artifacts.Count-ne5-or(@($artifacts.name)-join ',')-cne($artifactNames -join ',')){throw 'Release artifact set failed.'}
foreach($entry in $artifacts){Exact $entry @('name','sha256') "Artifact $($entry.name)";Sha ([string]$entry.sha256) "Artifact $($entry.name)"}
if($artifacts[0].sha256-ceq$r.historical_frontend.executable_sha256){throw 'Historical and current executable identities must remain distinct.'}
$samples=@($r.resource_samples);if($samples.Count-ne13){throw 'Exactly thirteen resource samples are required.'};for($i=0;$i-lt13;$i++){$s=$samples[$i];Exact $s @('checkpoint','elapsed_seconds','private_bytes','working_set_bytes','handle_count','thread_count','io_read_bytes') "Sample $i";$checkpointValue=IntExact $s.checkpoint $i $i "Sample $i checkpoint";$elapsedValue=IntExact $s.elapsed_seconds 0 3630 "Sample $i elapsed";if(($i-eq0-and$elapsedValue-ne0)-or($i-gt0-and($elapsedValue-lt($i*300)-or$elapsedValue-gt(($i*300)+30)))){throw "Sample $i chronology failed."};foreach($field in @('private_bytes','working_set_bytes','handle_count','thread_count','io_read_bytes')){$null=IntExact $s.$field 0 ([long]::MaxValue) "Sample $i $field"}}
if([long]$samples[-1].elapsed_seconds-ne$actualDuration){throw 'Actual duration is not bound to the final sample.'}
Exact $r.resource_bounds @('private_growth_bytes','working_growth_bytes','handle_growth','thread_growth','io_read_growth_bytes','private_peak_growth_bytes','working_peak_growth_bytes') 'Resource bounds';foreach($field in @('private_growth_bytes','working_growth_bytes','handle_growth','thread_growth','io_read_growth_bytes','private_peak_growth_bytes','working_peak_growth_bytes')){$null=IntExact $r.resource_bounds.$field ([long]::MinValue) ([long]::MaxValue) "Resource bound $field"};$bounds=Bounds $samples;if((ConvertTo-Json $bounds -Compress)-cne(ConvertTo-Json $r.resource_bounds -Compress)){throw 'Resource bounds do not recompute.'};if([long]$bounds.private_peak_growth_bytes-gt1GB-or[long]$bounds.working_peak_growth_bytes-gt512MB-or[long]$bounds.handle_growth-gt128-or[long]$bounds.thread_growth-gt32){throw 'Resource bounds exceed the accepted limits.'}
$attempts=@($r.capture_attempts);if($attempts.Count-ne5){throw 'Exactly five capture attempts are required.'};$captureNames=@();for($i=0;$i-lt5;$i++){$a=$attempts[$i];$scheduled=$i*900;$attempted=IntExact $a.attempted_elapsed_seconds $scheduled ($scheduled+30) "Capture attempt $i attempted elapsed";if($a.status-ceq'captured'){Exact $a @('status','checkpoint','scheduled_elapsed_seconds','attempted_elapsed_seconds','name','elapsed_seconds','sha256','bytes','color_bins') "Capture attempt $i";if($a.name-cne('checkpoint-{0:D2}.bmp'-f$i)){throw "Capture attempt $i name failed."};$capturedElapsed=IntExact $a.elapsed_seconds $scheduled ($scheduled+30) "Capture attempt $i elapsed";if($capturedElapsed-ne$attempted){throw "Capture attempt $i timestamps differ."};$null=IntExact $a.bytes 1 ([long]::MaxValue) "Capture attempt $i bytes";$null=IntExact $a.color_bins 80 ([long]::MaxValue) "Capture attempt $i color bins";Sha ([string]$a.sha256) "Capture attempt $i";$captureNames+=$a.name}else{Exact $a @('status','checkpoint','scheduled_elapsed_seconds','attempted_elapsed_seconds','reason') "Capture attempt $i";if($i-eq0-or$a.status-cne'skipped'-or$a.reason-cnotmatch'^(mcla-window-not-foreground|invalid-client-geometry|capture-error|nontrivial-frame-unavailable)$'){throw "Capture attempt $i skip contract failed."}};$null=IntExact $a.checkpoint $i $i "Capture attempt $i checkpoint";$null=IntExact $a.scheduled_elapsed_seconds $scheduled $scheduled "Capture attempt $i schedule"}
$captures=@($r.captures);if($captures.Count-lt1-or$captures.Count-gt5){throw 'Captured frame count is outside the accepted range.'};if(($captures.name-join',')-cne($captureNames-join',')){throw 'Captured frames do not match successful attempts.'};for($i=0;$i-lt$captures.Count;$i++){Exact $captures[$i] @('name','elapsed_seconds','sha256','bytes','color_bins') "Capture $i";$captureElapsed=IntExact $captures[$i].elapsed_seconds 0 3630 "Capture $i elapsed";$captureBytes=IntExact $captures[$i].bytes 1 ([long]::MaxValue) "Capture $i bytes";$captureBins=IntExact $captures[$i].color_bins 80 ([long]::MaxValue) "Capture $i color bins";Sha ([string]$captures[$i].sha256) "Capture $i";$captureName=$captures[$i].name;$attempt=@($attempts|Where-Object{$_.status-ceq'captured'-and$_.name-ceq$captureName});if($attempt.Count-ne1-or$captureElapsed-ne[long]$attempt[0].elapsed_seconds-or$captures[$i].sha256-cne$attempt[0].sha256-or$captureBytes-ne[long]$attempt[0].bytes-or$captureBins-ne[long]$attempt[0].color_bins){throw "Capture $i does not match its attempt."}}
$logs=@($r.runtime_logs);if($logs.Count-lt1){throw 'Runtime log set is empty.'};foreach($entry in $logs){Exact $entry @('name','sha256','bytes') 'Runtime log';if($entry.name-cnotmatch'^mcla(?:\.\d+)?\.log$'){throw 'Runtime log entry failed.'};$null=IntExact $entry.bytes 1 ([long]::MaxValue) 'Runtime log bytes';Sha ([string]$entry.sha256) 'Runtime log'}
Exact $r.host_display_audit @('schema','sha256','since_utc','checked_utc','audit_available','nvidia_driver_errors','sunshine_application_errors') 'Host display audit';Sha ([string]$r.host_display_audit.sha256) 'Host display audit';$hostSince=TimeExact $r.host_display_audit.since_utc 'Host audit since';$hostChecked=TimeExact $r.host_display_audit.checked_utc 'Host audit checked';BoolExact $r.host_display_audit.audit_available $true 'Host audit available';$hostNvidia=IntExact $r.host_display_audit.nvidia_driver_errors 0 0 'Host NVIDIA errors';$hostSunshine=IntExact $r.host_display_audit.sunshine_application_errors 0 0 'Host Sunshine errors';if($r.host_display_audit.schema-cne'mcla-host-display-audit-v1'-or$hostSince-ne$started-or$hostChecked-lt$started.AddSeconds($actualDuration)-or$hostChecked-gt$attested){throw 'Host display audit chronology failed.'}
$fatalCount=IntExact $r.runtime_fatal_markers 0 0 'Runtime fatal markers';BoolExact $r.controlled_external_close $true 'Controlled external close';$exitCode=IntExact $r.exit_code 0 0 'Exit code';BoolExact $r.force_cleanup $false 'Force cleanup';Exact $r.save_archive @('sha256','files','bytes') 'Save archive';Sha ([string]$r.save_archive.sha256) 'Save archive';$archiveFiles=IntExact $r.save_archive.files 1 ([long]::MaxValue) 'Save archive files';$archiveBytes=IntExact $r.save_archive.bytes 1 ([long]::MaxValue) 'Save archive bytes'
$scopeNames=@('historical_frontend_two_hours','current_artifact_interactive_mixed_gameplay_one_hour','normal_moving_gameplay_owner_attested','garage_enter_exit_owner_attested','pause_resume_owner_attested','alt_tab_return_owner_attested','same_release_artifacts','single_continuous_three_hour_run_claimed','current_five_stage_soak_complete','five_two_hour_suite_claimed','two_hour_current_artifact_mixed_gameplay_claimed','full_campaign_claimed','rendering_parity_claimed','music_continuity_claimed','wheel_centering_stability_claimed');Exact $r.scope $scopeNames 'Scope';foreach($name in $scopeNames[0..5]){BoolExact $r.scope.$name $true "Required scope '$name'"};foreach($name in $scopeNames[6..14]){BoolExact $r.scope.$name $false "Excluded scope '$name'"}
if($Fixture){[pscustomobject]@{Passed=$true;Decision=$r.decision;DurationSeconds=[int]$r.actual_duration_seconds;Samples=13;Captures=$captures.Count;ControlledExit=$true};return}

$root=Split-Path $path;$expected=Safe 'private/evidence/M6-014/final-hour' 'Final-hour evidence root' -Exists
if((Split-Path $root -Parent)-cne$expected-or(Split-Path $root -Leaf)-cne$r.run_id){throw 'Result location failed.'}
NoReparse $root 'Final-hour evidence'
$suitePath=Safe $r.sdk_baseline.path 'SDK baseline' -Exists
if((Hash $suitePath)-cne$r.sdk_baseline.sha256){throw 'SDK baseline file drifted.'}
$suite=Get-Content -LiteralPath $suitePath -Raw|ConvertFrom-Json
$build=Safe 'out/build/win-amd64-release' 'Release build' -Exists
$physicalArtifacts=@(Artifacts $build)
$physicalGame=Game (Safe 'private/game' 'Game root' -Exists)
$artifactsDrifted=(ConvertTo-Json $physicalArtifacts -Compress)-cne(ConvertTo-Json $artifacts -Compress)
$gameDrifted=(ConvertTo-Json $physicalGame -Compress)-cne(ConvertTo-Json $r.game -Compress)
$suiteGameDrifted=(ConvertTo-Json $suite.game -Compress)-cne(ConvertTo-Json $r.game -Compress)
if($artifactsDrifted-or$gameDrifted-or$suiteGameDrifted){throw 'Current physical artifact, game, or SDK baseline identity drifted.'}
$version=(Get-Content -LiteralPath (Safe 'VERSION' 'Project version' -Exists) -Raw).Trim();if($version-cne$r.project_build.version){throw 'Current project version drifted.'};$buildLog=Safe (Join-Path $root $r.project_build.build_log_name) 'Project build log' -Exists;if((Hash $buildLog)-cne$r.project_build.build_log_sha256){throw 'Project build log drifted.'}
$historicalSuite=Safe $r.historical_frontend.suite_path 'Historical suite' -Exists;$historicalStage=Safe $r.historical_frontend.stage_path 'Historical frontend stage' -Exists;$historicalRoot=Split-Path $historicalStage;$historicalTree=Tree $historicalRoot
if((Hash $historicalSuite)-cne$r.historical_frontend.suite_sha256-or(Hash $historicalStage)-cne$r.historical_frontend.stage_sha256-or$historicalTree.sha256-cne$r.historical_frontend.tree_sha256){throw 'Historical frontend evidence drifted.'}
$delivery=Safe $r.delivery_prerequisite.result_path 'Delivery result' -Exists;if((Hash $delivery)-cne$r.delivery_prerequisite.result_sha256){throw 'Delivery result drifted.'};$deliveryCheck=&$deliveryVerifier -ResultPath $delivery -Fixture;if($deliveryCheck.Decision-cne'delivery-transition-current-artifact-pass'){throw 'Accepted immutable delivery prerequisite did not revalidate.'};$seedArchive=Safe $r.gameplay_seed.archive_path 'Gameplay seed archive' -Exists;$latestPath=Safe $r.gameplay_seed.latest_path 'Gameplay seed latest snapshot' -Exists;if((Split-Path $latestPath -Parent)-cne$seedArchive){throw 'Gameplay seed latest path escapes its archive.'};$latest=Get-Content -LiteralPath $latestPath -Raw|ConvertFrom-Json;$seed=Safe (Join-Path $seedArchive $r.gameplay_seed.snapshot_directory) 'Gameplay seed snapshot' -Exists;if((Split-Path $seed -Parent)-cne$seedArchive){throw 'Gameplay seed snapshot escapes its archive.'};$seedManifestPath=Safe (Join-Path $seed 'snapshot.json') 'Gameplay seed manifest' -Exists;$seedManifest=Get-Content -LiteralPath $seedManifestPath -Raw|ConvertFrom-Json;$seedTree=Tree $seed
if($latest.schema-cne'mcla-soak-save-snapshot-v1'-or-not$latest.complete_profile_tree-or(ConvertTo-Json $latest -Compress)-cne(ConvertTo-Json $seedManifest -Compress)-or$latest.captured_utc-cne$r.gameplay_seed.captured_utc-or(Hash $latestPath)-cne$r.gameplay_seed.latest_sha256-or$seedTree.sha256-cne$r.gameplay_seed.snapshot_tree_sha256-or(Hash (Join-Path $seed $saveRelative))-cne$r.gameplay_seed.save_before_sha256-or(Hash (Join-Path $seed $headerRelative))-cne$r.gameplay_seed.header_before_sha256){throw 'Physical gameplay seed drifted.'}
$seedProfile=Safe (Join-Path $seed 'B13EBABEBABEBABE') 'Gameplay seed profile' -Exists;$workingSeedCopy=Safe (Join-Path $root 'seed-copy/B13EBABEBABEBABE') 'Preserved working seed copy' -Exists;if((Tree $workingSeedCopy).sha256-cne$r.gameplay_seed.working_copy_tree_sha256-or(Tree $seedProfile).sha256-cne$r.gameplay_seed.working_copy_tree_sha256-or(Hash (Join-Path $workingSeedCopy $saveRelative.Substring(17)))-cne$r.gameplay_seed.save_before_sha256-or(Hash (Join-Path $workingSeedCopy $headerRelative.Substring(17)))-cne$r.gameplay_seed.header_before_sha256){throw 'Physical working seed copy drifted.'}
$user=Safe (Join-Path $root 'run/user') 'Final user root' -Exists;if((Hash (Join-Path $user $saveRelative))-cne$r.gameplay_seed.save_after_sha256-or(Hash (Join-Path $user $headerRelative))-cne$r.gameplay_seed.header_after_sha256){throw 'Final save identity drifted.'};$samplePath=Safe (Join-Path $root 'resource-samples.json') 'Resource journal' -Exists;$captureManifest=Safe (Join-Path $root 'captures.json') 'Capture journal' -Exists;$attemptManifest=Safe (Join-Path $root 'capture-attempts.json') 'Capture-attempt journal' -Exists
$persistedSamples=@(Get-Content $samplePath -Raw|ConvertFrom-Json);$persistedCaptures=@(Get-Content $captureManifest -Raw|ConvertFrom-Json);$persistedAttempts=@(Get-Content $attemptManifest -Raw|ConvertFrom-Json)
$sampleJournalDrifted=(ConvertTo-Json $persistedSamples -Compress)-cne(ConvertTo-Json $samples -Compress)
$captureJournalDrifted=(ConvertTo-Json $persistedCaptures -Compress)-cne(ConvertTo-Json $captures -Compress);$attemptJournalDrifted=(ConvertTo-Json $persistedAttempts -Compress)-cne(ConvertTo-Json $attempts -Compress)
if($sampleJournalDrifted-or$captureJournalDrifted-or$attemptJournalDrifted){throw 'Persisted sample, capture, or capture-attempt journal drifted.'}
$captureRoot=Safe (Join-Path $root 'captures') 'Capture root' -Exists;$files=@(Get-ChildItem -LiteralPath $captureRoot -File -Filter '*.bmp'|Sort-Object Name);if($files.Count-ne$captures.Count){throw 'Physical capture count drifted.'};for($i=0;$i-lt$captures.Count;$i++){if($files[$i].Name-cne$captures[$i].name-or$files[$i].Length-ne[long]$captures[$i].bytes-or(Hash $files[$i].FullName)-cne$captures[$i].sha256){throw "Physical capture $i drifted."}}
$run=Safe (Join-Path $root 'run') 'Runtime root' -Exists;$actualLogs=@(Get-ChildItem -LiteralPath $run -File -Filter 'mcla*.log'|Sort-Object Name);if($actualLogs.Count-ne$logs.Count){throw 'Physical runtime log count drifted.'};$text='';for($i=0;$i-lt$logs.Count;$i++){if($actualLogs[$i].Name-cne$logs[$i].name-or$actualLogs[$i].Length-ne[long]$logs[$i].bytes-or(Hash $actualLogs[$i].FullName)-cne$logs[$i].sha256){throw 'Physical runtime log drifted.'};$text+=Get-Content -LiteralPath $actualLogs[$i].FullName -Raw};foreach($marker in @('MCLA module config: static image 82000000-829E0000, code 82130000-827CD054, 30034 mappings','MCLA graphics: nontrivial guest frame captured','MCLA_GARAGE_CONTROL v=1 sequence=1 action=START','Window closing, shutting down...','Execution complete','Title terminated; hard-exiting process.')){if(-not$text.Contains($marker)){throw "Runtime marker missing: $marker"}};$fatalPattern='(?i)\[FATAL\]|Assertion failed|REX_GUEST_CRASH|GUEST_CRASH_REPORT|guest crash|PPC_UNIMPLEMENTED|invalid or unregistered function|access violation|device lost|device hung|device reset|DRED|DXGI_ERROR_DEVICE_(?:REMOVED|HUNG|RESET)';if([regex]::Matches($text,$fatalPattern).Count){throw 'Physical runtime contains a fatal marker.'}
$hostPath=Safe (Join-Path $root 'host-display-audit.json') 'Host display audit' -Exists;$host=Get-Content -LiteralPath $hostPath -Raw|ConvertFrom-Json;Exact $host @('schema','since_utc','checked_utc','audit_available','nvidia_driver_errors','sunshine_application_errors') 'Physical host display audit';if((Hash $hostPath)-cne$r.host_display_audit.sha256-or(ConvertTo-Json $host -Compress)-cne(ConvertTo-Json ([ordered]@{schema=$r.host_display_audit.schema;since_utc=$r.host_display_audit.since_utc;checked_utc=$r.host_display_audit.checked_utc;audit_available=$r.host_display_audit.audit_available;nvidia_driver_errors=$r.host_display_audit.nvidia_driver_errors;sunshine_application_errors=$r.host_display_audit.sunshine_application_errors}) -Compress)){throw 'Physical host display audit drifted.'}
$archive=Safe "private/save-archive/M6-014/final-hour-$($r.run_id)" 'Final save archive' -Exists;NoReparse $archive 'Final save archive';if((ConvertTo-Json (Tree $archive) -Compress)-cne(ConvertTo-Json $r.save_archive -Compress)){throw 'Final save archive drifted.'}
$archiveLatestPath=Safe (Join-Path $archive 'latest.json') 'Final archive latest' -Exists;$archiveLatest=Get-Content -LiteralPath $archiveLatestPath -Raw|ConvertFrom-Json;Exact $archiveLatest @('schema','identity','captured_utc','reason','source_user_root','snapshot_directory','save_sha256','save_bytes','header_sha256','header_bytes','complete_profile_tree') 'Final archive latest';$snapshot=Safe (Join-Path $archive $archiveLatest.snapshot_directory) 'Final archive snapshot' -Exists;if((Split-Path $snapshot -Parent)-cne$archive){throw 'Final archive snapshot escapes its archive.'};$snapshotManifestPath=Safe (Join-Path $snapshot 'snapshot.json') 'Final archive snapshot manifest' -Exists;$snapshotManifest=Get-Content -LiteralPath $snapshotManifestPath -Raw|ConvertFrom-Json;Exact $snapshotManifest @('schema','identity','captured_utc','reason','source_user_root','snapshot_directory','save_sha256','save_bytes','header_sha256','header_bytes','complete_profile_tree') 'Final archive snapshot manifest';$expectedSource="private/evidence/M6-014/final-hour/$($r.run_id)/run/user";$snapshotSave=Safe (Join-Path $snapshot $saveRelative) 'Final archived save' -Exists;$snapshotHeader=Safe (Join-Path $snapshot $headerRelative) 'Final archived header' -Exists
if($archiveLatest.schema-cne'mcla-soak-save-snapshot-v1'-or$archiveLatest.source_user_root-cne$expectedSource-or$archiveLatest.snapshot_directory-cne$snapshotManifest.snapshot_directory-or$archiveLatest.identity-cne$snapshotManifest.identity-or(ConvertTo-Json $archiveLatest -Compress)-cne(ConvertTo-Json $snapshotManifest -Compress)-or$archiveLatest.save_sha256-cne$r.gameplay_seed.save_after_sha256-or$archiveLatest.header_sha256-cne$r.gameplay_seed.header_after_sha256-or(Hash $snapshotSave)-cne$archiveLatest.save_sha256-or(Hash $snapshotHeader)-cne$archiveLatest.header_sha256){throw 'Final archive physical snapshot drifted.'};BoolExact $archiveLatest.complete_profile_tree $true 'Final archive complete profile';$null=TimeExact $archiveLatest.captured_utc 'Final archive captured';$null=IntExact $archiveLatest.save_bytes 1 ([long]::MaxValue) 'Final archive save bytes';$null=IntExact $archiveLatest.header_bytes 1 ([long]::MaxValue) 'Final archive header bytes'
$exe=Join-Path $build 'mcla.exe';if(@((Get-Process mcla -ErrorAction SilentlyContinue)|Where-Object{try{$_.Path-ceq$exe}catch{$false}}).Count){throw 'Canonical MCLA process remains.'}
[pscustomobject]@{Passed=$true;Decision=$r.decision;DurationSeconds=[int]$r.actual_duration_seconds;Samples=13;Captures=$captures.Count;ControlledExit=$true;HistoricalFrontendHours=2;CurrentMixedGameplayHours=1;SameReleaseArtifacts=$false;SaveArchiveSha256=$r.save_archive.sha256}
