[CmdletBinding(DefaultParameterSetName='Source')]
param(
  [Parameter(ParameterSetName='Source')][switch]$SourceOnly,
  [Parameter(Mandatory,ParameterSetName='Result')][string]$ResultPath,
  [Parameter(ParameterSetName='Result')][switch]$FixtureMode
)

Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$repo=(Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '..')).Path
$policyPath=Join-Path $repo 'config/retired-service-unlock-policy.json'
$prior=[ordered]@{task='M6-008';run_id='20260819-164950-4b322fe1';sha256='7DC8946ABD4B1BB78D52E527655D713EB4FD7037421997F4BA209689BC21903B';decision='explicit-offline-progression-and-retired-service-matrix-pass'}
function Exact($Object,[string[]]$Names,[string]$Description){if(($Object.PSObject.Properties.Name-join',')-cne($Names-join',')){throw "$Description schema is invalid."}}
function Bool($Value,[bool]$Expected,[string]$Description){if($Value-isnot[bool]-or$Value-ne$Expected){throw "$Description is invalid."}}
function Hash([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash}
function TextHash([string]$Path){$text=[IO.File]::ReadAllText($Path).Replace("`r`n","`n");$sha=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($text)))).Replace('-','')}finally{$sha.Dispose()}}
function Safe([string]$Path,[string]$Description,[switch]$Exists){$full=if([IO.Path]::IsPathRooted($Path)){[IO.Path]::GetFullPath($Path)}else{[IO.Path]::GetFullPath((Join-Path $repo $Path))};$prefix=$repo.TrimEnd('\')+'\';if(-not$full.StartsWith($prefix,[StringComparison]::OrdinalIgnoreCase)){throw "$Description escapes repository."};$current=$repo;foreach($part in @($full.Substring($prefix.Length).Split('\')|Where-Object{$_.Length})){$current=Join-Path $current $part;if((Test-Path -LiteralPath $current)-and((Get-Item -LiteralPath $current -Force).Attributes-band[IO.FileAttributes]::ReparsePoint)){throw "$Description traverses a reparse point."}};if($Exists-and-not(Test-Path -LiteralPath $full)){throw "$Description is missing."};$full}
function PolicyContract($Policy){
  Exact $Policy @('schema','task','decision','historical_basis','canonical_compatibility','optional_cheat','asset_decisions') 'Policy'
  if($Policy.schema-cne'mcla-retired-service-unlock-policy-v1'-or$Policy.task-cne'M6-009'-or$Policy.decision-cne'retail-preserving-compatibility-with-explicit-cheat-separation'){throw 'Policy identity is invalid.'}
  if(@($Policy.historical_basis).Count-ne2){throw 'Historical basis count is invalid.'};$claims=@('rate-my-ride-and-driving-test-unlocks-are-retired-and-unavailable','audi-r8-purchase-required-all-12-social-club-tasks');$kinds=@('publisher','contemporaneous-guide');$urls=@('https://www.rockstargames.com/games/midnightclubLA','https://www.gamesradar.com/midnight-club-los-angeles-guide/');for($i=0;$i-lt2;$i++){Exact $Policy.historical_basis[$i] @('claim','source_kind','url') 'Historical basis';if($Policy.historical_basis[$i].claim-cne$claims[$i]-or$Policy.historical_basis[$i].source_kind-cne$kinds[$i]-or$Policy.historical_basis[$i].url-cne$urls[$i]){throw 'Historical basis is invalid.'}}
  $c=$Policy.canonical_compatibility;Exact $c @('classification','retired_service_behavior','offline_or_on_disc_contract_required','new_entitlement_fabricated','fake_service_completion','save_mutation','source_game_mutation','canonical_evidence_allowed') 'Canonical policy';if($c.classification-cne'compatibility'-or$c.retired_service_behavior-cne'preserve-retail-lock-and-existing-authentic-entitlement'){throw 'Canonical policy semantics are invalid.'};Bool $c.offline_or_on_disc_contract_required $true 'Offline contract requirement';foreach($n in @('new_entitlement_fabricated','fake_service_completion','save_mutation','source_game_mutation')){Bool $c.$n $false "Canonical $n"};Bool $c.canonical_evidence_allowed $true 'Canonical evidence allowance'
  $q=$Policy.optional_cheat;Exact $q @('classification','implementation_status','future_surface_allowed','explicit_user_opt_in_required','default_enabled','init_only_required','separate_namespace_and_documentation_required','save_mutation_allowed','source_game_mutation_allowed','canonical_progression_evidence_allowed','achievement_or_progression_claims_allowed') 'Cheat policy';if($q.classification-cne'cheat'-or$q.implementation_status-cne'not-implemented'){throw 'Cheat policy identity is invalid.'};foreach($n in @('future_surface_allowed','explicit_user_opt_in_required','init_only_required','separate_namespace_and_documentation_required')){Bool $q.$n $true "Cheat $n"};foreach($n in @('default_enabled','save_mutation_allowed','source_game_mutation_allowed','canonical_progression_evidence_allowed','achievement_or_progression_claims_allowed')){Bool $q.$n $false "Cheat $n"}
  if(@($Policy.asset_decisions).Count-ne1){throw 'Asset decision count is invalid.'};$a=$Policy.asset_decisions[0];Exact $a @('asset','historical_gate','current_service_state','canonical_action','cheat_action','exact_entitlement_state_in_supported_save_claimed') 'Asset decision';if($a.asset-cne'audi-r8-4.2-fsi-quattro'-or$a.historical_gate-cne'all-12-social-club-driving-test-tasks'-or$a.current_service_state-cne'retired-unavailable'-or$a.canonical_action-cne'remain-locked-unless-authentic-entitlement-already-exists'-or$a.cheat_action-cne'none-implemented'){throw 'Asset decision is invalid.'};Bool $a.exact_entitlement_state_in_supported_save_claimed $false 'Supported-save entitlement claim'
}
function SourceContract{
  $raw=[IO.File]::ReadAllText($policyPath);if($raw-match'(?i)[A-Z]:\\|xuid|gamertag|host_path'){throw 'Policy leaks private identity or paths.'};$policy=$raw|ConvertFrom-Json;PolicyContract $policy
  $runtime=@();foreach($root in @('src','third_party/rexglue-sdk/src')){if(Test-Path -LiteralPath (Join-Path $repo $root)){$runtime+=Get-ChildItem -LiteralPath (Join-Path $repo $root) -Recurse -File -Include *.cpp,*.h,*.hpp}}
  foreach($file in $runtime){$text=[IO.File]::ReadAllText($file.FullName);if($text-match'(?i)audi.?r8|unlock.?all.?vehicles|retired.?service.?unlock|driving.?test.?unlock'){throw "Runtime unlock implementation exists in $($file.FullName)."}}
  [pscustomobject][ordered]@{SourceContractVerified=$true;SourceChecks=24;RuntimeUnlockImplementationPresent=$false;Policy=$policy}
}
$source=SourceContract;if($PSCmdlet.ParameterSetName-ceq'Source'){return $source}
$full=Safe $ResultPath 'M6-009 result' -Exists;$prefix=(Join-Path $repo 'private/evidence/M6-009').TrimEnd('\')+'\';if(-not$FixtureMode-and-not$full.StartsWith($prefix,[StringComparison]::OrdinalIgnoreCase)){throw 'Result is outside private M6-009 evidence.'}
$raw=[IO.File]::ReadAllText($full);if($raw-match'(?i)[A-Z]:\\|xuid|gamertag|host_path|controller.{0,8}(name|guid|serial)'){throw 'Result leaks private identity or paths.'};$r=$raw|ConvertFrom-Json
Exact $r @('schema','task','decision','policy_sha256','prior_evidence','policy','source_audit','scope') 'Result';if($r.schema-cne'mcla-retired-service-unlock-decision-v1'-or$r.task-cne'M6-009'-or$r.decision-cne'retail-preserving-compatibility-with-explicit-cheat-separation'-or$r.policy_sha256-cnotmatch'^[A-F0-9]{64}$'){throw 'Result identity is invalid.'};if($r.policy_sha256-cne(TextHash $policyPath)){throw 'Policy digest is invalid.'}
Exact $r.prior_evidence @('task','run_id','sha256','decision') 'Prior evidence';foreach($n in @('task','run_id','sha256','decision')){if($r.prior_evidence.$n-cne$prior[$n]){throw 'Prior evidence identity is invalid.'}}
PolicyContract $r.policy
Exact $r.source_audit @('runtime_unlock_implementation_present','save_or_source_game_mutation_performed','current_service_entitlement_claimed') 'Source audit';foreach($n in $r.source_audit.PSObject.Properties.Name){Bool $r.source_audit.$n $false "Source audit $n"}
$trueScope=@('retail_progression_preserved','existing_authentic_entitlements_preserved','compatibility_and_cheats_separated','future_cheat_requires_explicit_opt_in','future_cheat_excluded_from_canonical_evidence');$falseScope=@('audi_r8_unlocked','retired_service_emulated','fake_live_state_used','save_mutated','source_game_mutated','cheat_implemented');Exact $r.scope @($trueScope+$falseScope) 'Scope';foreach($n in $trueScope){Bool $r.scope.$n $true "Scope $n"};foreach($n in $falseScope){Bool $r.scope.$n $false "Scope $n"}
if(-not$FixtureMode){$runRoot=Split-Path $full;$children=@(Get-ChildItem -LiteralPath $runRoot -Force);if($children.Count-ne1-or$children[0].Name-cne'result.json'-or($children[0].Attributes-band[IO.FileAttributes]::ReparsePoint)){throw 'Evidence topology is invalid.'};$priorPath=Safe "private/evidence/$($prior.task)/$($prior.run_id)/result.json" 'M6-008 result' -Exists;if((Hash $priorPath)-cne$prior.sha256){throw 'M6-008 evidence drifted.'};$pj=[IO.File]::ReadAllText($priorPath)|ConvertFrom-Json;if($pj.task-cne$prior.task-or$pj.decision-cne$prior.decision){throw 'M6-008 semantics drifted.'}}
[pscustomobject][ordered]@{Decision=$r.decision;RetailProgressionPreserved=$true;CompatibilitySeparatedFromCheats=$true;AutomaticRetiredServiceUnlocks=$false;CheatImplemented=$false;CanonicalEvidenceCheatFree=$true;PriorOfflinePolicyBound=$true;DataIntegrityVerified=$true}
