[CmdletBinding(DefaultParameterSetName='Result')]
param(
  [Parameter(Mandatory,ParameterSetName='Result')][string]$ResultPath,
  [Parameter(Mandatory,ParameterSetName='Fixture')][string]$FixturePath,
  [Parameter(ParameterSetName='Fixture')][switch]$Fixture
)

Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$repo=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$scenarioNames=@('frontend','free-roam','races','garage','lifecycle')
$artifactNames=@('mcla.exe','rexruntime.dll','TracyClient.dll','rexgpu-xenos.dll')
$priorEvidence=@(
  @('M6-001','private/evidence/M6-001/20260817-115619-d269e2a9/result.json','all-major-city-regions-streaming-pass','519B84FF456BDD3220BFC8BE3DD230CCB209A56CF2B203D51CFF5454729E178F'),
  @('M6-002','private/evidence/M6-002/20260817-155005-1dd57bd3/result.json','representative-garage-purchase-customization-persistence-pass','21FCBE38695B45D22AE516E33E51AD0A292286985549673811E0FE3E33900644'),
  @('M6-003','private/evidence/M6-003/20260818-180605-e3b74fb5/result.json','representative-race-system-matrix-pass','AD3573B56412D7DBC10650BE0D250AFD4AACA22EB8EEEB6F9816E94EC3007E3A'),
  @('M6-005','private/evidence/M6-005/20260818-201702-5d089d9c/result.json','native-autosave-load-overwrite-plus-isolated-creation-destructive-save-matrix-pass','5F46FA6657F39EE5AF990BD505B67D5EDBE6A781E8283D1D51BE07F3543F169E'),
  @('M6-007','private/evidence/M6-007/20260819-122150-2ad3b961/result.json','two-hour-audio-and-device-recovery-pass','CE4B4700CEA1108243989165211A8C70AC0C67F72130708A129C1BD834948B5B'),
  @('M6-010','private/evidence/M6-010/20260819-180446-730942f2/result.json','split-window-device-lifecycle-matrix-pass','746D7DAECD475E48EEA9EE8342319A84CC2E059992A635579AB55AF7A719C71B'),
  @('M6-012','private/evidence/M6-012/20260819-192540-2a9e82fe/result.json','timestamped-performance-telemetry-pass','BFEA11FB1A7E8C5D380343C252612BC3BCBE471F0DC1BFB1FCA56B771FB27CB3'),
  @('M6-013','private/evidence/M6-013/20260819-200712-a4cc8715/result.json','reached-unsupported-surface-fixed-or-bounded-nonblocking','279DA2FDEDF20D8C69D3DE6B5993A26AC625FBA9B624BF52BC3F800F8F1BC4ED')
)

function Safe([string]$Path,[string]$Description,[switch]$Exists){
  $full=if([IO.Path]::IsPathRooted($Path)){[IO.Path]::GetFullPath($Path)}else{[IO.Path]::GetFullPath((Join-Path $repo $Path))}
  $prefix=$repo.TrimEnd('\')+'\';if(-not$full.StartsWith($prefix,[StringComparison]::OrdinalIgnoreCase)){throw "$Description escapes repository."}
  $cursor=$repo;foreach($part in @($full.Substring($prefix.Length).Split('\')|Where-Object Length)){$cursor=Join-Path $cursor $part;if((Test-Path -LiteralPath $cursor)-and((Get-Item -LiteralPath $cursor -Force).Attributes-band[IO.FileAttributes]::ReparsePoint)){throw "$Description traverses a reparse point."}}
  if($Exists-and-not(Test-Path -LiteralPath $full)){throw "$Description is missing."};$full
}
function Hash([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash}
function Exact($Object,[string[]]$Names,[string]$Label){if(($Object.PSObject.Properties.Name-join',')-cne($Names-join',')){throw "$Label schema is invalid."}}
function Bool($Value,[bool]$Expected,[string]$Label){if($Value-isnot[bool]-or$Value-ne$Expected){throw "$Label is invalid."}}
function Int($Value,[long]$Minimum,[long]$Maximum,[string]$Label){if(($Value-isnot[int])-and($Value-isnot[long])){throw "$Label type is invalid."};$n=[long]$Value;if($n-lt$Minimum-or$n-gt$Maximum){throw "$Label is out of range."};$n}
function Hex64($Value,[string]$Label){if($Value-isnot[string]-or$Value-cnotmatch'^[0-9A-F]{64}$'){throw "$Label is not uppercase SHA-256."}}
function Hex([byte[]]$Bytes){([BitConverter]::ToString($Bytes)).Replace('-','')}
function Tree([string]$Root){$sha=[Security.Cryptography.SHA256]::Create();try{$files=@(Get-ChildItem -LiteralPath $Root -File -Recurse -Force|Sort-Object FullName);$bytes=0L;foreach($f in $files){$relative=$f.FullName.Substring($Root.TrimEnd('\').Length+1).Replace('\','/');$line=[Text.Encoding]::UTF8.GetBytes("$relative`t$($f.Length)`t$(Hash $f.FullName)`n");$null=$sha.TransformBlock($line,0,$line.Length,$line,0);$bytes+=$f.Length};$null=$sha.TransformFinalBlock([byte[]]::new(0),0,0);[pscustomobject]@{hash=(Hex $sha.Hash);files=$files.Count;bytes=$bytes}}finally{$sha.Dispose()}}
function LogSet([string]$Root){$files=@(Get-ChildItem -LiteralPath $Root -File -Filter 'mcla*.log'|Sort-Object @{Expression={if($_.Name-eq'mcla.log'){999}else{[int]([regex]::Match($_.Name,'\.(\d+)\.log$').Groups[1].Value)}}});$sha=[Security.Cryptography.SHA256]::Create();$text='';$manifest=@();try{foreach($f in $files){$content=[IO.File]::ReadAllText($f.FullName);$text+=$content;$h=Hash $f.FullName;$manifest+=[ordered]@{name=$f.Name;bytes=[long]$f.Length;sha256=$h};$line=[Text.Encoding]::UTF8.GetBytes("$($f.Name)`t$($f.Length)`t$h`n");$null=$sha.TransformBlock($line,0,$line.Length,$line,0)};$null=$sha.TransformFinalBlock([byte[]]::new(0),0,0);[pscustomobject]@{hash=(Hex $sha.Hash);files=@($manifest);text=$text}}finally{$sha.Dispose()}}
function Bounds($Samples){$first=$Samples[0];$last=$Samples[-1];$maxPrivate=[long](($Samples|Measure-Object private_bytes -Maximum).Maximum);$maxWorking=[long](($Samples|Measure-Object working_set_bytes -Maximum).Maximum);[ordered]@{private_growth_bytes=[Math]::Max(0L,[long]$last.private_bytes-[long]$first.private_bytes);working_growth_bytes=[Math]::Max(0L,[long]$last.working_set_bytes-[long]$first.working_set_bytes);handle_growth=[Math]::Max(0L,[long]$last.handle_count-[long]$first.handle_count);thread_growth=[Math]::Max(0L,[long]$last.thread_count-[long]$first.thread_count);io_read_growth_bytes=[Math]::Max(0L,[long]$last.io_read_bytes-[long]$first.io_read_bytes);private_peak_growth_bytes=[Math]::Max(0L,$maxPrivate-[long]$first.private_bytes);working_peak_growth_bytes=[Math]::Max(0L,$maxWorking-[long]$first.working_set_bytes)}}
function Read-SaveStatU32([string]$Path,[string]$Tag){$bytes=[IO.File]::ReadAllBytes((Safe $Path 'Save-stat source' -Exists));$needle=[Text.Encoding]::ASCII.GetBytes($Tag);$hits=@();for($i=0;$i-le$bytes.Length-16;$i++){$match=$true;for($j=0;$j-lt4;$j++){if($bytes[$i+$j]-ne$needle[$j]){$match=$false;break}};if($match-and$bytes[$i+4]-eq0-and$bytes[$i+5]-eq0-and$bytes[$i+6]-eq0-and$bytes[$i+7]-eq0){$hits+=$i}};if($hits.Count-ne1){throw "Save-stat tag '$Tag' is not unique."};$offset=$hits[0];[uint32](([uint32]$bytes[$offset+12]-shl24)-bor([uint32]$bytes[$offset+13]-shl16)-bor([uint32]$bytes[$offset+14]-shl8)-bor[uint32]$bytes[$offset+15])}

$path=if($Fixture){Safe $FixturePath 'Fixture result' -Exists}else{Safe $ResultPath 'M6-014 result' -Exists}
$r=Get-Content -LiteralPath $path -Raw|ConvertFrom-Json
Exact $r @('schema','task','decision','suite_id','sdk_version','sdk_commit','build_configuration','duration_seconds_per_scenario','sample_interval_seconds','capture_interval_seconds','game','seeds','build','prior_evidence','scenarios','scope') 'Result'
if($r.schema-cne'mcla-two-hour-soak-suite-v2'-or$r.task-cne'M6-014'-or$r.decision-cne'five-two-hour-soak-suite-pass'-or$r.build_configuration-cne'Release'){throw 'Result identity is invalid.'}
if($r.suite_id-cnotmatch'^20\d{6}-\d{6}-[0-9a-f]{8}$'-or$r.sdk_version-cnotmatch'^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$'-or$r.sdk_commit-cnotmatch'^[0-9a-f]{40}$'){throw 'Suite or SDK identity is invalid.'}
$cmakePinText=Get-Content -LiteralPath (Join-Path $repo 'CMakeLists.txt') -Raw;$bootstrapPinText=Get-Content -LiteralPath (Join-Path $PSScriptRoot 'bootstrap.ps1') -Raw
$versionPin=[regex]::Match($cmakePinText,'set\(MCLA_REXGLUE_VERSION\s+"(?<v>[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)"\)');$commitPin=[regex]::Match($bootstrapPinText,"ReXGlueCommit\s*=\s*'(?<c>[0-9a-f]{40})'");$tagPin=[regex]::Match($bootstrapPinText,"ReXGlueTag\s*=\s*'(?<t>v[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)'")
if(-not$versionPin.Success-or-not$commitPin.Success-or-not$tagPin.Success-or$tagPin.Groups['t'].Value-cne('v'+$versionPin.Groups['v'].Value)-or$r.sdk_version-cne$versionPin.Groups['v'].Value-or$r.sdk_commit-cne$commitPin.Groups['c'].Value){throw 'Result SDK does not match the exact project pin.'}
if((Int $r.duration_seconds_per_scenario 7200 7200 'Duration')-ne7200-or(Int $r.sample_interval_seconds 300 300 'Sample interval')-ne300-or(Int $r.capture_interval_seconds 900 900 'Capture interval')-ne900){throw 'Canonical timing is invalid.'}
Exact $r.game @('file_count','payload_bytes','source_iso_sha256') 'Game';Int $r.game.file_count 1 ([long]::MaxValue) 'Game files'|Out-Null;Int $r.game.payload_bytes 1 ([long]::MaxValue) 'Game bytes'|Out-Null;Hex64 $r.game.source_iso_sha256 'Game ISO'
if(@($r.seeds).Count-ne2){throw 'Explicit seed lineage count is invalid.'}
$seedExpectations=@(
  @('frontend','private/evidence/M5-013/20260817-013319-c2e7223f/runs/01/user','immutable-five-race-resource-seed','private/evidence/M5-013/20260817-013319-c2e7223f/result.json','D890A903775A3B53262B9957E7B7DC1D4B76B49B8735360BECD8233842446298'),
  @('gameplay','private/save-archive/M6-014/20260831-133236-2cecb67b/free-roam/20260901-114045Z-A575F88F4FDFA19B-2FAEFBC7FF8CDEAD','owner-progressed-save-37-races-31-wins','private/save-archive/M6-014/20260831-133236-2cecb67b/free-roam/20260901-114045Z-A575F88F4FDFA19B-2FAEFBC7FF8CDEAD/snapshot.json','BE2D1D6C79DC834A0E5C50A601667A51E10EA86AF5E16062380ACFC2DEAEE79B')
)
for($i=0;$i-lt2;$i++){Exact $r.seeds[$i] @('role','source','source_context','upstream_result_path','upstream_result_sha256','tree_sha256','save_sha256','header_sha256') "Seed $i";$expected=$seedExpectations[$i];if($r.seeds[$i].role-cne$expected[0]-or$r.seeds[$i].source-cne$expected[1]-or$r.seeds[$i].source_context-cne$expected[2]-or$r.seeds[$i].upstream_result_path-cne$expected[3]-or$r.seeds[$i].upstream_result_sha256-cne$expected[4]){throw "Seed $i provenance is invalid."};foreach($field in @('upstream_result_sha256','tree_sha256','save_sha256','header_sha256')){Hex64 $r.seeds[$i].$field "Seed $i $field"}}
Exact $r.build @('clean_build_log_sha256','artifacts') 'Build';Hex64 $r.build.clean_build_log_sha256 'Build log';if(@($r.build.artifacts).Count-ne4){throw 'Artifact count is invalid.'};for($i=0;$i-lt4;$i++){Exact $r.build.artifacts[$i] @('name','sha256') "Artifact $i";if($r.build.artifacts[$i].name-cne$artifactNames[$i]){throw 'Artifact order is invalid.'};Hex64 $r.build.artifacts[$i].sha256 "Artifact $i hash"}
if(@($r.prior_evidence).Count-ne$priorEvidence.Count){throw 'Prior evidence count is invalid.'};for($i=0;$i-lt$priorEvidence.Count;$i++){Exact $r.prior_evidence[$i] @('task','path','decision','sha256') "Prior evidence $i";$expected=$priorEvidence[$i];if($r.prior_evidence[$i].task-cne$expected[0]-or$r.prior_evidence[$i].path-cne$expected[1]-or$r.prior_evidence[$i].decision-cne$expected[2]-or$r.prior_evidence[$i].sha256-cne$expected[3]){throw "Prior evidence $i identity is invalid."}}
if(@($r.scenarios).Count-ne5){throw 'Scenario count is invalid.'}
$minimumActivity=@{'frontend'=@(0,0);'free-roam'=@(8,0);'races'=@(10,2);'garage'=@(20,10);'lifecycle'=@(30,1)}
for($i=0;$i-lt5;$i++){
  $s=$r.scenarios[$i];Exact $s @('name','seed_class','decision','duration_seconds','sample_count','capture_count','activity_primary','activity_secondary','distinct_labels','resource_bounds','runtime_log_set_sha256','scenario_tree_sha256','save_before_sha256','save_after_sha256','header_before_sha256','header_after_sha256','controlled_exit','exit_code','force_cleanup','fatal_markers','stage_path') "Scenario $i"
  $name=$scenarioNames[$i];$seedClass=if($name-ceq'frontend'){'frontend'}else{'gameplay'};if($s.name-cne$name-or$s.seed_class-cne$seedClass-or$s.decision-cne"two-hour-$name-soak-pass"){throw "Scenario $i identity is invalid."}
  if((Int $s.duration_seconds 7200 7500 "$name duration")-lt7200){throw "$name duration is short."};if((Int $s.sample_count 25 30 "$name samples")-lt25){throw "$name sample count is short."};if((Int $s.capture_count 9 12 "$name captures")-lt9){throw "$name capture count is short."}
  $primary=Int $s.activity_primary 0 100000 "$name primary";$secondary=Int $s.activity_secondary 0 100000 "$name secondary"
  if (($primary -lt $minimumActivity[$name][0]) -or ($secondary -lt $minimumActivity[$name][1])) { throw "$name semantic activity is insufficient ($primary/$secondary; expected $($minimumActivity[$name][0])/$($minimumActivity[$name][1]))." }
  if($s.distinct_labels-isnot[Object[]]-and$s.distinct_labels-isnot[string]){throw "$name labels type is invalid."};if($name-eq'free-roam'-and@($s.distinct_labels).Count-lt5){throw 'Free-roam region diversity is insufficient.'}
  foreach($label in @($s.distinct_labels)){if($label-isnot[string]-or$label-cnotmatch'^[A-Z0-9-]{2,40}$'-and$label-cne'title-frontend'-and$label-cne'race-events'-and$label-cne'garage-cycles'-and$label-cne'lifecycle-cycles'){throw "$name activity label is invalid or privacy-unsafe."}}
  Exact $s.resource_bounds @('private_growth_bytes','working_growth_bytes','handle_growth','thread_growth','io_read_growth_bytes','private_peak_growth_bytes','working_peak_growth_bytes') "$name bounds"
  $privateGrowth=Int $s.resource_bounds.private_growth_bytes 0 1073741824 "$name private growth";$workingGrowth=Int $s.resource_bounds.working_growth_bytes 0 536870912 "$name working growth";$handleGrowth=Int $s.resource_bounds.handle_growth 0 128 "$name handles";$threadGrowth=Int $s.resource_bounds.thread_growth 0 32 "$name threads"
  if (($privateGrowth -gt 1073741824) -or ($workingGrowth -gt 536870912) -or ($handleGrowth -gt 128) -or ($threadGrowth -gt 32)) { throw "$name resource growth exceeds bounds." }
  foreach($field in @('io_read_growth_bytes','private_peak_growth_bytes','working_peak_growth_bytes')){Int $s.resource_bounds.$field 0 ([long]::MaxValue) "$name $field"|Out-Null}
  Hex64 $s.runtime_log_set_sha256 "$name log set";Hex64 $s.scenario_tree_sha256 "$name tree";Hex64 $s.save_before_sha256 "$name save before";Hex64 $s.save_after_sha256 "$name save after";Hex64 $s.header_before_sha256 "$name header before";Hex64 $s.header_after_sha256 "$name header after";if($name-eq'frontend'-and($s.save_before_sha256-cne$s.save_after_sha256-or$s.header_before_sha256-cne$s.header_after_sha256)){throw 'Frontend soak mutated the isolated save.'}
  Bool $s.controlled_exit $true "$name controlled exit";if((Int $s.exit_code 0 0 "$name exit")-ne0){throw "$name exit code is invalid."};Bool $s.force_cleanup $false "$name cleanup";if((Int $s.fatal_markers 0 0 "$name fatals")-ne0){throw "$name fatal markers are present."};$expectedStage=if($name-ceq'races' -and $r.scope.mixed_free_roam_races_session){'scenarios/free-roam/race-coverage.json'}else{"scenarios/$name/stage.json"};if($s.stage_path-cne$expectedStage){throw "$name stage path is invalid."}
}
Exact $r.scope @('five_independent_processes','four_physical_processes','mixed_free_roam_races_session','same_release_artifacts','two_explicit_seed_lineages','same_gameplay_seed_identity','same_seed_identity','frontend_two_hours','free_roam_two_hours','races_two_hours','garage_two_hours','lifecycle_two_hours','monolithic_ten_hour_run_claimed','full_campaign_claimed','music_continuity_claimed') 'Scope'
foreach($n in @('same_release_artifacts','two_explicit_seed_lineages','same_gameplay_seed_identity','frontend_two_hours','free_roam_two_hours','races_two_hours','garage_two_hours','lifecycle_two_hours')){Bool $r.scope.$n $true "Scope $n"};foreach($n in @('same_seed_identity','monolithic_ten_hour_run_claimed','full_campaign_claimed','music_continuity_claimed')){Bool $r.scope.$n $false "Scope $n"};if($r.scope.mixed_free_roam_races_session-isnot[bool]){throw 'Mixed-session scope type is invalid.'};if($r.scope.mixed_free_roam_races_session){Bool $r.scope.five_independent_processes $false 'Mixed five-process claim';Bool $r.scope.four_physical_processes $true 'Mixed four-process claim'}else{Bool $r.scope.five_independent_processes $true 'Independent five-process claim';Bool $r.scope.four_physical_processes $false 'Independent four-process claim'}

if(-not$Fixture){
  $root=Split-Path $path; if((Split-Path $root -Parent)-cne(Safe 'private/evidence/M6-014' 'M6-014 evidence root' -Exists)-or(Split-Path $root -Leaf)-cne$r.suite_id){throw 'Result location is invalid.'}
  if(@(Get-ChildItem -LiteralPath $root -Recurse -Force|Where-Object{$_.Attributes-band[IO.FileAttributes]::ReparsePoint}).Count){throw 'Evidence contains a reparse point.'}
  if((Hash (Join-Path $root 'release-clean-build.log'))-cne$r.build.clean_build_log_sha256){throw 'Build log drifted.'}
  $build=Safe 'out/build/win-amd64-release' 'Release build' -Exists;for($i=0;$i-lt4;$i++){if((Hash (Join-Path $build $artifactNames[$i]))-cne$r.build.artifacts[$i].sha256){throw 'Runtime artifact drifted.'}}
  $seedRoots=@{};for($i=0;$i-lt2;$i++){$seed=Safe $r.seeds[$i].source "Seed $i root" -Exists;if((Tree $seed).hash-cne$r.seeds[$i].tree_sha256-or(Hash (Join-Path $seed 'B13EBABEBABEBABE/545407F8/00000001/mc4.sav/mc4.sav'))-cne$r.seeds[$i].save_sha256-or(Hash (Join-Path $seed 'B13EBABEBABEBABE/545407F8/Headers/00000001/mc4.sav.header'))-cne$r.seeds[$i].header_sha256){throw "Seed $i identity drifted."};$upstream=Safe $r.seeds[$i].upstream_result_path "Seed $i upstream result" -Exists;if((Hash $upstream)-cne$r.seeds[$i].upstream_result_sha256){throw "Seed $i upstream result drifted."};$seedRoots[$r.seeds[$i].role]=$seed}
  $game=&(Join-Path $PSScriptRoot 'verify-game-manifest.ps1') -GamePath (Safe 'private/game' 'Canonical game' -Exists) -VerifyHashes;if($game.FileCount-ne$r.game.file_count-or$game.PayloadBytes-ne$r.game.payload_bytes-or$game.SourceIsoSha256-cne$r.game.source_iso_sha256){throw 'Source-game identity drifted.'}
  for($i=0;$i-lt$priorEvidence.Count;$i++){$prior=Safe $r.prior_evidence[$i].path "Prior evidence $i" -Exists;if((Hash $prior)-cne$r.prior_evidence[$i].sha256){throw "Prior evidence $i drifted."};$priorResult=Get-Content -LiteralPath $prior -Raw|ConvertFrom-Json;if($priorResult.task-cne$r.prior_evidence[$i].task-or$priorResult.decision-cne$r.prior_evidence[$i].decision){throw "Prior evidence $i payload is invalid."}}
  for($i=0;$i-lt5;$i++){
    $s=$r.scenarios[$i];$mixedRace=$s.name-ceq'races' -and $r.scope.mixed_free_roam_races_session;$physicalName=if($mixedRace){'free-roam'}else{$s.name};$scenarioRoot=Safe (Join-Path $root "scenarios/$physicalName") "$($s.name) root" -Exists;$stagePath=Join-Path $scenarioRoot 'stage.json';if(-not(Test-Path $stagePath)){throw "$($s.name) stage is missing."};$stage=Get-Content $stagePath -Raw|ConvertFrom-Json
    Exact $stage @('schema','name','seed_class','decision','duration_seconds','sample_count','capture_count','activity_primary','activity_secondary','distinct_labels','resource_bounds','runtime_log_set_sha256','save_before_sha256','save_after_sha256','header_before_sha256','header_after_sha256','controlled_exit','exit_code','force_cleanup','fatal_markers') "$($s.name) stage"
    Bool $stage.controlled_exit $true "$($s.name) stage controlled exit";Bool $stage.force_cleanup $false "$($s.name) stage cleanup";Int $stage.exit_code 0 0 "$($s.name) stage exit"|Out-Null;Int $stage.fatal_markers 0 0 "$($s.name) stage fatals"|Out-Null
    if($mixedRace){
      $coveragePath=Safe (Join-Path $scenarioRoot 'race-coverage.json') 'Mixed race coverage' -Exists;$coverage=Get-Content $coveragePath -Raw|ConvertFrom-Json
      Exact $coverage @('schema','physical_scenario','decision','duration_seconds','race_completions_before','race_completions_after','race_completions_delta','wins_before','wins_after','wins_delta','operator_series_completed','operator_freeway_drivers_completed','operator_pink_slip_series_completed','operator_attestation','reviewed_active_race_capture','reviewed_active_race_capture_sha256','source_stage_sha256','shared_physical_session') 'Mixed race coverage'
      foreach($n in @('operator_attestation','shared_physical_session')){Bool $coverage.$n $true "Mixed race $n"};foreach($h in @('reviewed_active_race_capture_sha256','source_stage_sha256')){Hex64 $coverage.$h "Mixed race $h"}
      foreach($n in @('duration_seconds','race_completions_before','race_completions_after','race_completions_delta','wins_before','wins_after','wins_delta','operator_series_completed','operator_freeway_drivers_completed','operator_pink_slip_series_completed')){Int $coverage.$n 0 ([uint32]::MaxValue) "Mixed race $n"|Out-Null}
      $seedSave=Join-Path $seedRoots['gameplay'] 'B13EBABEBABEBABE/545407F8/00000001/mc4.sav/mc4.sav';$finalSave=Join-Path $scenarioRoot 'run/user/B13EBABEBABEBABE/545407F8/00000001/mc4.sav/mc4.sav'
      $raceBefore=Read-SaveStatU32 $seedSave 'gRCP';$raceAfter=Read-SaveStatU32 $finalSave 'gRCP';$winBefore=Read-SaveStatU32 $seedSave 'gWIN';$winAfter=Read-SaveStatU32 $finalSave 'gWIN'
      if($coverage.schema-cne'mcla-soak-mixed-race-coverage-v1'-or$coverage.physical_scenario-cne'free-roam'-or$coverage.decision-cne$s.decision-or$coverage.duration_seconds-ne$s.duration_seconds-or$coverage.race_completions_before-ne$raceBefore-or$coverage.race_completions_after-ne$raceAfter-or$coverage.race_completions_delta-ne([long]$raceAfter-[long]$raceBefore)-or$coverage.wins_before-ne$winBefore-or$coverage.wins_after-ne$winAfter-or$coverage.wins_delta-ne([long]$winAfter-[long]$winBefore)-or$coverage.race_completions_delta-ne$s.activity_primary-or$coverage.operator_series_completed-ne$s.activity_secondary-or$coverage.race_completions_delta-lt10-or$coverage.operator_series_completed-lt2-or$coverage.wins_delta-lt1-or$coverage.reviewed_active_race_capture-cne'checkpoint-00.bmp'-or(Hash (Join-Path $scenarioRoot "captures/$($coverage.reviewed_active_race_capture)"))-cne$coverage.reviewed_active_race_capture_sha256-or(Hash $stagePath)-cne$coverage.source_stage_sha256){throw 'Mixed race coverage is invalid.'}
    }elseif($stage.name-cne$s.name-or$stage.decision-cne$s.decision-or$stage.activity_primary-ne$s.activity_primary-or$stage.activity_secondary-ne$s.activity_secondary-or(ConvertTo-Json @($stage.distinct_labels)-Compress)-cne(ConvertTo-Json @($s.distinct_labels)-Compress)){throw "$($s.name) semantic stage/result mismatch."}
    if($stage.schema-cne'mcla-two-hour-soak-stage-v2'-or$stage.seed_class-cne$s.seed_class-or$stage.duration_seconds-ne$s.duration_seconds-or$stage.sample_count-ne$s.sample_count-or$stage.capture_count-ne$s.capture_count-or(ConvertTo-Json $stage.resource_bounds -Compress)-cne(ConvertTo-Json $s.resource_bounds -Compress)-or$stage.runtime_log_set_sha256-cne$s.runtime_log_set_sha256-or$stage.save_before_sha256-cne$s.save_before_sha256-or$stage.save_after_sha256-cne$s.save_after_sha256-or$stage.header_before_sha256-cne$s.header_before_sha256-or$stage.header_after_sha256-cne$s.header_after_sha256-or-not$stage.controlled_exit-or$stage.exit_code-ne0-or$stage.force_cleanup-or$stage.fatal_markers-ne0){throw "$($s.name) physical stage/result mismatch."}
    $set=LogSet (Join-Path $scenarioRoot 'run');if($set.hash-cne$s.runtime_log_set_sha256){throw "$($s.name) runtime logs drifted."};$tree=Tree $scenarioRoot;if($tree.hash-cne$s.scenario_tree_sha256){throw "$($s.name) tree drifted."}
    $seed=$seedRoots[$s.seed_class];if((Hash (Join-Path $seed 'B13EBABEBABEBABE/545407F8/00000001/mc4.sav/mc4.sav'))-cne$s.save_before_sha256-or(Hash (Join-Path $scenarioRoot 'run/user/B13EBABEBABEBABE/545407F8/00000001/mc4.sav/mc4.sav'))-cne$s.save_after_sha256-or(Hash (Join-Path $seed 'B13EBABEBABEBABE/545407F8/Headers/00000001/mc4.sav.header'))-cne$s.header_before_sha256-or(Hash (Join-Path $scenarioRoot 'run/user/B13EBABEBABEBABE/545407F8/Headers/00000001/mc4.sav.header'))-cne$s.header_after_sha256){throw "$($s.name) save identity drifted."}
    if($set.text-notmatch'MCLA graphics: nontrivial guest frame captured'-or$set.text-notmatch'Window closing, shutting down\.\.\.'-or$set.text-notmatch'Title terminated; hard-exiting process\.'-or$set.text-match'(?i)guest crash|PPC_UNIMPLEMENTED|invalid or unregistered function|device lost|DXGI_ERROR_DEVICE_REMOVED|\[FATAL\]'){throw "$($s.name) runtime health contract failed."}
    $samples=@(Get-Content (Join-Path $scenarioRoot 'resource-samples.json') -Raw|ConvertFrom-Json);if($samples.Count-ne$s.sample_count){throw "$($s.name) physical sample count drifted."};$sampleProps=@('checkpoint','elapsed_seconds','private_bytes','working_set_bytes','handle_count','thread_count','io_read_bytes');$maxGap=if($s.name-ceq'frontend'){480}else{900};for($j=0;$j-lt$samples.Count;$j++){Exact $samples[$j] $sampleProps "$($s.name) sample $j";$minimumElapsed=if($j-eq0){0}elseif($s.name-ceq'frontend'){[long]$samples[$j-1].elapsed_seconds+1}else{[long]$samples[$j-1].elapsed_seconds};if($samples[$j].checkpoint-ne$j-or[long]$samples[$j].elapsed_seconds-lt$minimumElapsed){throw "$($s.name) sample chronology is invalid."};foreach($field in $sampleProps[2..6]){Int $samples[$j].$field 0 ([long]::MaxValue) "$($s.name) sample $field"|Out-Null};if($j-gt0-and([long]$samples[$j].elapsed_seconds-[long]$samples[$j-1].elapsed_seconds)-gt$maxGap){throw "$($s.name) sampling gap exceeds $maxGap seconds."}};if($samples[0].elapsed_seconds-ne0-or[long]$samples[-1].elapsed_seconds-lt7200){throw "$($s.name) resource timeline is incomplete."};if((ConvertTo-Json (Bounds $samples) -Compress)-cne(ConvertTo-Json $s.resource_bounds -Compress)){throw "$($s.name) resource bounds do not recompute."}
    $activity=@(Get-Content (Join-Path $scenarioRoot 'activity.json') -Raw|ConvertFrom-Json);$primary=if($activity.Count){[int](($activity|Measure-Object primary -Sum).Sum)}else{0};$secondary=if($activity.Count){[int](($activity|Measure-Object secondary -Sum).Sum)}else{0};$labels=if($s.name-eq'frontend'){@('title-frontend')}else{@($activity|ForEach-Object label|Sort-Object -Unique)};if(-not$mixedRace-and($primary-ne$s.activity_primary-or$secondary-ne$s.activity_secondary-or(ConvertTo-Json @($labels)-Compress)-cne(ConvertTo-Json @($s.distinct_labels)-Compress))){throw "$($s.name) activity journal drifted."}
    $captureRecords=@(Get-Content (Join-Path $scenarioRoot 'captures.json') -Raw|ConvertFrom-Json);$captures=@(Get-ChildItem (Join-Path $scenarioRoot 'captures') -File -Filter '*.bmp'|Sort-Object Name);if($captures.Count-ne$s.capture_count-or$captureRecords.Count-ne$s.capture_count){throw "$($s.name) physical capture count drifted."};for($j=0;$j-lt$captures.Count;$j++){Exact $captureRecords[$j] @('name','sha256','bytes','color_bins') "$($s.name) capture $j";$expected="checkpoint-{0:D2}.bmp"-f$j;if($captures[$j].Name-cne$expected-or$captureRecords[$j].name-cne$expected-or(Hash $captures[$j].FullName)-cne$captureRecords[$j].sha256-or$captures[$j].Length-ne$captureRecords[$j].bytes-or$captureRecords[$j].color_bins-lt80){throw "$($s.name) capture manifest drifted."}};if(@($captureRecords.sha256|Sort-Object -Unique).Count-lt3){throw "$($s.name) capture sequence lacks temporal variation."}
  }
  $sdk=Safe 'third_party/rexglue-sdk' 'SDK' -Exists;$sdkCommitOutput=@(&git -C $sdk rev-parse HEAD);if($LASTEXITCODE-ne0-or$sdkCommitOutput.Count-ne1){throw 'SDK identity drifted.'};$sdkTagOutput=@(&git -C $sdk describe --tags --exact-match HEAD 2>$null);if($LASTEXITCODE-ne0-or$sdkTagOutput.Count-ne1){throw 'SDK identity drifted.'};$sdkDirty=@(&git -C $sdk status --porcelain);if($LASTEXITCODE-ne0-or$sdkDirty.Count-or$sdkCommitOutput[0].Trim()-cne$r.sdk_commit-or$sdkTagOutput[0].Trim()-cne$tagPin.Groups['t'].Value){throw 'SDK identity drifted.'}
  $exe=Join-Path $build 'mcla.exe';if(@((Get-Process mcla -ErrorAction SilentlyContinue)|Where-Object{try{$_.Path-ceq$exe}catch{$false}}).Count){throw 'Canonical MCLA process remains.'}
}

$physicalHours=if($r.scope.mixed_free_roam_races_session){8}else{10}
[pscustomobject][ordered]@{Decision=$r.decision;ScenariosVerified=5;CategoryCoverageHours=10;PhysicalSoakHours=$physicalHours;ControlledExitsVerified=$true;ResourceBoundsVerified=$true;DataIntegrityVerified=$true}
