[CmdletBinding(DefaultParameterSetName='Run')]
param(
  [Parameter(Mandatory,ParameterSetName='Run')][string]$RunPath,
  [Parameter(Mandatory,ParameterSetName='Result')][string]$ResultPath,
  [switch]$Fixture
)

Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$repo=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$utf8=[Text.UTF8Encoding]::new($false)
$sdkCommit='c4aa30c35386bb4d2ef051a59ea8e71bab667172'

function Resolve-SafePath([string]$Path,[string]$Description,[switch]$Exists){
  $full=if([IO.Path]::IsPathRooted($Path)){[IO.Path]::GetFullPath($Path)}else{[IO.Path]::GetFullPath((Join-Path $repo $Path))}
  $prefix=$repo.TrimEnd('\')+'\';if(-not$full.StartsWith($prefix,[StringComparison]::OrdinalIgnoreCase)){throw "$Description escapes repository."}
  $current=$repo;foreach($part in @($full.Substring($prefix.Length).Split('\')|Where-Object{$_.Length})){$current=Join-Path $current $part;if((Test-Path -LiteralPath $current)-and((Get-Item -LiteralPath $current -Force).Attributes-band[IO.FileAttributes]::ReparsePoint)){throw "$Description traverses a reparse point."}}
  if($Exists-and-not(Test-Path -LiteralPath $full)){throw "$Description is missing."};$full
}
function Assert-NoReparseTree([string]$Root){$pending=[Collections.Generic.Stack[string]]::new();$pending.Push($Root);while($pending.Count){foreach($item in @(Get-ChildItem -LiteralPath $pending.Pop() -Force)){if($item.Attributes-band[IO.FileAttributes]::ReparsePoint){throw 'Tree contains a reparse point.'};if($item.PSIsContainer){$pending.Push($item.FullName)}}}}
function Get-TreeSnapshot([string]$Root){$root=Resolve-SafePath $Root 'Tree' -Exists;Assert-NoReparseTree $root;$items=@(Get-ChildItem -LiteralPath $root -Recurse -Force);$files=@($items|Where-Object{-not$_.PSIsContainer-and-not($_.FullName-ceq(Join-Path $root 'result.json'))}|Sort-Object FullName);$entries=@();$bytes=0L;foreach($d in @($items|Where-Object{$_.PSIsContainer}|Sort-Object FullName)){$entries+=[ordered]@{kind='directory';path=$d.FullName.Substring($root.Length).TrimStart('\').Replace('\','/')}};foreach($f in $files){$bytes+=$f.Length;$entries+=[ordered]@{kind='file';path=$f.FullName.Substring($root.Length).TrimStart('\').Replace('\','/');bytes=$f.Length;sha256=(Get-FileHash -LiteralPath $f.FullName -Algorithm SHA256).Hash}};$json=ConvertTo-Json -InputObject @($entries) -Compress -Depth 4;$sha=[Security.Cryptography.SHA256]::Create();try{$hash=-join($sha.ComputeHash($utf8.GetBytes($json))|ForEach-Object{$_.ToString('X2')})}finally{$sha.Dispose()};[pscustomobject]@{Hash=$hash;FileCount=$files.Count;DirectoryCount=@($items|Where-Object{$_.PSIsContainer}).Count;Bytes=$bytes}}
function Get-GameIdentity([string]$Root){$tree=Get-TreeSnapshot $Root;$verified=& (Join-Path $PSScriptRoot 'verify-game-manifest.ps1') -GamePath $Root -VerifyHashes;[pscustomobject][ordered]@{file_count=[int]$verified.FileCount;payload_bytes=[int64]$verified.PayloadBytes;manifest_sha256=(Get-FileHash -LiteralPath $verified.ManifestPath -Algorithm SHA256).Hash;tree_sha256=$tree.Hash;tree_file_count=$tree.FileCount;tree_directory_count=$tree.DirectoryCount;tree_bytes=$tree.Bytes}}
function Get-Artifacts([string]$Root){@('mcla.exe','rexruntimerd.dll','TracyClientrd.dll','rexgpu-xenosrd.dll')|ForEach-Object{$path=Resolve-SafePath (Join-Path $Root $_) "Artifact $_" -Exists;[pscustomobject][ordered]@{name=$_;sha256=(Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash}}}
function Get-ExactProcesses([string]$Executable){@((Get-Process mcla -ErrorAction SilentlyContinue)|Where-Object{try{[string]::Equals($_.Path,$Executable,[StringComparison]::OrdinalIgnoreCase)}catch{$false}})}
function Get-LogSet([string]$Root){$files=@(Get-ChildItem -LiteralPath $Root -File -Filter 'mcla*.log');if($files.Count-lt1-or$files.Count-gt16){throw 'Runtime-log topology is invalid.'};$current=@($files|Where-Object{$_.Name-ceq'mcla.log'});if($current.Count-ne1){throw 'Current runtime-log count is invalid.'};$rotated=@();foreach($file in @($files|Where-Object{$_.Name-cne'mcla.log'})){$m=[regex]::Match($file.Name,'^mcla\.([1-9][0-9]*)\.log$');if(-not$m.Success){throw 'Malformed runtime-log rotation.'};$rotated+=[pscustomobject]@{Index=[int]$m.Groups[1].Value;File=$file}};$indices=@($rotated|ForEach-Object{$_.Index}|Sort-Object);for($i=0;$i-lt$indices.Count;$i++){if($indices[$i]-ne$i+1){throw 'Runtime-log rotations are not contiguous.'}};$ordered=@($rotated|Sort-Object Index -Descending|ForEach-Object{$_.File})+$current[0];$text=@();$manifest=@();$bytes=0L;foreach($file in $ordered){$bytes+=$file.Length;if($bytes-gt134217728){throw 'Runtime logs exceed 128 MiB.'};$text+=[IO.File]::ReadAllText($file.FullName);$manifest+=[ordered]@{name=$file.Name;bytes=$file.Length;sha256=(Get-FileHash -LiteralPath $file.FullName -Algorithm SHA256).Hash}};$json=ConvertTo-Json -InputObject @($manifest) -Compress -Depth 3;$sha=[Security.Cryptography.SHA256]::Create();try{$hash=-join($sha.ComputeHash($utf8.GetBytes($json))|ForEach-Object{$_.ToString('X2')})}finally{$sha.Dispose()};[pscustomobject]@{Text=$text-join"`n";Manifest=@($manifest);Hash=$hash;Count=$manifest.Count;Bytes=$bytes}}
function One([string]$Text,[string]$Pattern,[string]$Name){$m=[regex]::Matches($Text,$Pattern);if($m.Count-ne1){throw "$Name count is $($m.Count), expected 1."};$m[0]}
function Bmp([string]$Path){$path=Resolve-SafePath $Path 'Title BMP' -Exists;$bytes=[IO.File]::ReadAllBytes($path);if($bytes.Length-ne3686454-or$bytes[0]-ne0x42-or$bytes[1]-ne0x4D-or[BitConverter]::ToInt32($bytes,18)-ne1280-or[Math]::Abs([BitConverter]::ToInt32($bytes,22))-ne720-or[BitConverter]::ToUInt16($bytes,28)-ne32){throw 'Title capture is not canonical 1280x720 BGRA.'};[pscustomobject]@{sha256=(Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash;bytes=$bytes.Length}}

function Get-Probe([string]$Path){
  $root=Resolve-SafePath $Path 'M5-009 run' -Exists;Assert-NoReparseTree $root;$logs=Get-LogSet $root;$text=$logs.Text
  foreach($bad in @('SDL_AUDIO_EVENT_AUDIT_FAILURE','status=FAIL','Assertion failed','PPC_UNIMPLEMENTED','Guest crash','DXGI_ERROR_DEVICE_REMOVED','device removed','FATAL:')){if($text.Contains($bad)){throw "Audio event run contains banned marker '$bad'."}}
  $knownEvent='(?:SDL_AUDIO_EVENT_AUDIT_CONFIG v=1 enabled=1 backend=sdl sample_rate=48000 phases=music,ambient,voice,engine,collision,ui|SDL_AUDIO_EVENT_AUDIT_PHASE v=1 event=(?:BEGIN phase=(?:music|ambient|voice|engine|collision|ui) index=[0-5]|END phase=(?:music|ambient|voice|engine|collision|ui) index=[0-5] status=PASS device_frames=\d+ nonzero=\d+ invalid=\d+ submit_failures=\d+ peak_ppm=\d+)|SDL_AUDIO_EVENT_AUDIT_SUMMARY v=1 status=PASS phases=6 failures=0 dropped_records=0 external_listening_required=1|MCLA_AUDIO_EVENT_CONFIG v=1 slot=0 gameplay_wait_seconds=45 dismiss_pulses=6 music_seconds=8 ambient_seconds=8 voice_seconds=30 engine_seconds=8 collision_seconds=15 ui_seconds=4 external_listening_required=1|MCLA_AUDIO_EVENT_WINDOW v=1 phase=(?:music|ambient|voice|engine|collision|ui) event=LISTEN|MCLA_AUDIO_EVENT_SUMMARY v=1 status=COMPLETE phases=6 external_listening_required=1 external_close_required=1)'
  foreach($match in [regex]::Matches($text,'(?m)^.*(?:SDL_AUDIO_EVENT_AUDIT_|MCLA_AUDIO_EVENT_).*$')){if($match.Value.TrimEnd()-notmatch($knownEvent+'$')){throw 'Unknown or malformed audio-event marker.'}}
  $config=One $text 'SDL_AUDIO_EVENT_AUDIT_CONFIG v=1 enabled=1 backend=sdl sample_rate=48000 phases=music,ambient,voice,engine,collision,ui' 'Event config'
  $appConfig=One $text 'MCLA_AUDIO_EVENT_CONFIG v=1 slot=0 gameplay_wait_seconds=45 dismiss_pulses=6 music_seconds=8 ambient_seconds=8 voice_seconds=30 engine_seconds=8 collision_seconds=15 ui_seconds=4 external_listening_required=1' 'App config'
  if($appConfig.Index-ge$config.Index){throw 'Audio event configuration chronology is invalid.'}
  $phaseNames=@('music','ambient','voice','engine','collision','ui');$minimumFrames=@(900,900,3500,900,1800,500);$minimumPeaks=@(1000,1000,1000,5000,5000,2000);$phases=@();$last=$appConfig.Index
  for($i=0;$i-lt6;$i++){$name=$phaseNames[$i];$begin=One $text "SDL_AUDIO_EVENT_AUDIT_PHASE v=1 event=BEGIN phase=$name index=$i" "$name begin";$listen=One $text "MCLA_AUDIO_EVENT_WINDOW v=1 phase=$name event=LISTEN" "$name listen window";$end=One $text "SDL_AUDIO_EVENT_AUDIT_PHASE v=1 event=END phase=$name index=$i status=PASS device_frames=(\d+) nonzero=(\d+) invalid=(\d+) submit_failures=(\d+) peak_ppm=(\d+)" "$name end";if($begin.Index-le$last-or($i-eq0-and$begin.Index-le$config.Index)-or$listen.Index-le$begin.Index-or$end.Index-le$listen.Index){throw 'Audio event chronology is invalid.'};$frames=[int64]$end.Groups[1].Value;$nonzero=[int64]$end.Groups[2].Value;$invalid=[int64]$end.Groups[3].Value;$failures=[int64]$end.Groups[4].Value;$peak=[int]$end.Groups[5].Value;if($frames-lt$minimumFrames[$i]-or$nonzero*1000000L/$frames-lt900000-or$invalid-ne0-or$failures-ne0-or$peak-lt$minimumPeaks[$i]){throw "Audio event phase '$name' violates calibrated output bounds."};$phases+=[pscustomobject][ordered]@{phase=$name;device_frames=$frames;nonzero_frames=$nonzero;nonzero_ratio_ppm=[int]($nonzero*1000000L/$frames);peak_ppm=$peak};$last=$end.Index}
  $eventSummary=One $text 'SDL_AUDIO_EVENT_AUDIT_SUMMARY v=1 status=PASS phases=6 failures=0 dropped_records=0 external_listening_required=1' 'Event summary'
  $route=One $text 'SDL_AUDIO_AUDIT_SUMMARY v=1 phase=title status=PASS client_calls=(\d+) client_success=(\d+) submit_frames=(\d+) submit_nonzero=(\d+) submit_invalid=(\d+) submit_peak_ppm=(\d+) device_frames=(\d+) device_nonzero=(\d+) device_invalid=(\d+) device_submit_fail=(\d+) device_peak_ppm=(\d+) xma_frames=(\d+) xma_nonzero=(\d+) xma_invalid=(\d+) xma_peak_ppm=(\d+) max_queue_depth=(\d+) starvation_fills=(\d+) max_consecutive_starvation_fills=(\d+) dropped_records=0' 'Route summary'
  $appSummary=One $text 'MCLA_AUDIO_EVENT_SUMMARY v=1 status=COMPLETE phases=6 external_listening_required=1 external_close_required=1' 'App summary';$closing=One $text 'Window closing, shutting down\.\.\.' 'Window close';$complete=One $text 'Execution complete' 'Execution complete';$hard=One $text 'Title terminated; hard-exiting process\.' 'Hard exit';if(-not($eventSummary.Index-gt$last-and$route.Index-gt$eventSummary.Index-and$appSummary.Index-gt$route.Index-and$closing.Index-gt$appSummary.Index-and$complete.Index-gt$closing.Index-and$hard.Index-gt$complete.Index)){throw 'Audio summary/lifecycle chronology is invalid.'}
  $submit=[int64]$route.Groups[3].Value;$submitNonzero=[int64]$route.Groups[4].Value;$device=[int64]$route.Groups[7].Value;$deviceNonzero=[int64]$route.Groups[8].Value;$xma=[int64]$route.Groups[12].Value;$xmaNonzero=[int64]$route.Groups[13].Value;$maxQueue=[int]$route.Groups[16].Value;$starve=[int]$route.Groups[17].Value;$maxStarve=[int]$route.Groups[18].Value;if($route.Groups[1].Value-ne'1'-or$route.Groups[2].Value-ne'1'-or$submit-lt10000-or$submitNonzero*1000000L/$submit-lt900000-or$device-lt10000-or$deviceNonzero*1000000L/$device-lt900000-or$xma-lt50000-or$xmaNonzero*1000000L/$xma-lt900000-or$route.Groups[5].Value-ne'0'-or$route.Groups[9].Value-ne'0'-or$route.Groups[10].Value-ne'0'-or$route.Groups[14].Value-ne'0'-or$maxQueue-gt64-or$starve-gt2-or$maxStarve-gt2){throw 'Current XMA/XAudio/SDL route health is invalid.'}
  $capture=Bmp (Join-Path $root 'user/mcla-first-frame.bmp');[pscustomobject][ordered]@{phases=@($phases);runtime_logs=@($logs.Manifest);runtime_log_set_sha256=$logs.Hash;runtime_log_file_count=$logs.Count;runtime_log_bytes=$logs.Bytes;capture_sha256=$capture.sha256;capture_bytes=$capture.bytes;submit_frames=$submit;submit_nonzero=$submitNonzero;device_frames=$device;device_nonzero=$deviceNonzero;xma_frames=$xma;xma_nonzero=$xmaNonzero;max_queue_depth=$maxQueue;max_consecutive_starvation=$maxStarve;controlled_exit=$true}
}

if($PSCmdlet.ParameterSetName-eq'Run'){$probe=Get-Probe $RunPath;if(-not$Fixture){$children=@(Get-ChildItem -LiteralPath (Resolve-SafePath $RunPath 'Run root' -Exists) -Force);$directories=@($children|Where-Object{$_.PSIsContainer}|ForEach-Object{$_.Name}|Sort-Object);$files=@($children|Where-Object{-not$_.PSIsContainer}|ForEach-Object{$_.Name});if(($directories-join',')-cne'cache,user'-or@($files|Where-Object{$_-notmatch'^mcla(?:\.[1-9][0-9]*)?\.log$'}).Count-ne0-or-not($files-ccontains'mcla.log')){throw 'Probe topology is invalid.'}};$probe;return}

$result=Resolve-SafePath $ResultPath 'M5-009 result' -Exists;if((Get-Item -LiteralPath $result -Force).Attributes-band[IO.FileAttributes]::ReparsePoint){throw 'Result is a reparse point.'};$record=Get-Content -LiteralPath $result -Raw|ConvertFrom-Json
$properties=@('schema','task','decision','sdk_version','sdk_commit','build_configuration','listening_presence_only','other_sounds_allowed','operator_confirmation','operator_categories','seed_save_sha256','seed_header_sha256','game_before','game_after','artifacts_before','artifacts_after','build_logs','cycle','evidence_tree_sha256','evidence_tree_file_count','evidence_tree_directory_count','evidence_tree_bytes','scope')
if(($record.PSObject.Properties.Name-join',')-cne($properties-join',')-or$record.schema-cne'mcla-audio-event-v1'-or$record.task-cne'M5-009'-or$record.decision-cne'six-class-audio-stream-presence-pass'-or$record.sdk_version-cne'0.9.0.20'-or$record.sdk_commit-cne$sdkCommit-or$record.build_configuration-cne'RelWithDebInfo'-or-not($record.listening_presence_only-is[bool])-or-not$record.listening_presence_only-or-not($record.other_sounds_allowed-is[bool])-or-not$record.other_sounds_allowed-or-not($record.operator_confirmation-is[bool])-or-not$record.operator_confirmation-or@($record.operator_categories).Count-ne6-or($record.operator_categories-join',')-cne'music,ambient,voice,engine,collision,ui'-or$record.seed_save_sha256-cne'E8B559E1F2D03341B1147CAB4F5A3F3C778E6E9633B0B04B9908360FA2C67D68'-or$record.seed_header_sha256-cne'1DAEF55FA78BDD3F1AA75A36772B801C6C714B6D1A115A97904F3D1C957BC4C9'-or$record.scope-cne'presence of six allowlisted audio event classes over the current XMA/XAudio/SDL route; isolation, mix balance, content fidelity, and exhaustive coverage are not claimed'){throw 'Result schema, types, or listening decision are invalid.'}
$root=Split-Path $result -Parent;Assert-NoReparseTree $root;$children=@(Get-ChildItem -LiteralPath $root -Force|ForEach-Object{$_.Name}|Sort-Object);if(($children-join',')-cne'app-clean-build.log,result.json,runs,sdk-audio-test.log,sdk-install.log'){throw 'Result-root topology is invalid.'};$probe=Get-Probe (Join-Path $root 'runs/01');if((ConvertTo-Json $record.cycle -Compress -Depth 8)-cne(ConvertTo-Json $probe -Compress -Depth 8)){throw 'Result cycle does not match physical evidence.'}
$game=Get-GameIdentity (Join-Path $repo 'private/game');if((ConvertTo-Json $record.game_before -Compress -Depth 5)-cne(ConvertTo-Json $game -Compress -Depth 5)-or(ConvertTo-Json $record.game_after -Compress -Depth 5)-cne(ConvertTo-Json $game -Compress -Depth 5)){throw 'Canonical game identity mismatch.'};$artifacts=@(Get-Artifacts (Join-Path $repo 'out/build/win-amd64-relwithdebinfo'));if((ConvertTo-Json $record.artifacts_before -Compress -Depth 4)-cne(ConvertTo-Json $artifacts -Compress -Depth 4)-or(ConvertTo-Json $record.artifacts_after -Compress -Depth 4)-cne(ConvertTo-Json $artifacts -Compress -Depth 4)){throw 'Runtime artifact identity mismatch.'}
if(($record.build_logs.PSObject.Properties.Name-join',')-cne'sdk-install_log,sdk-audio-test_log,app-clean-build_log'){throw 'Build-log schema is invalid.'};foreach($name in @('sdk-install.log','sdk-audio-test.log','app-clean-build.log')){$key=$name.Replace('.','_');if($record.build_logs.$key-cnotmatch'^[A-F0-9]{64}$'-or$record.build_logs.$key-cne(Get-FileHash -LiteralPath (Join-Path $root $name) -Algorithm SHA256).Hash){throw "Build log '$name' identity mismatch."}};$testText=[IO.File]::ReadAllText((Join-Path $root 'sdk-audio-test.log'));if($testText-notmatch'All tests passed \(30 assertions in 8 test cases\)'){throw 'Focused audio-test totals are missing.'};$cycleUser=Join-Path $root 'runs/01/user';if((Get-FileHash -LiteralPath (Join-Path $cycleUser 'B13EBABEBABEBABE/545407F8/00000001/mc4.sav/mc4.sav') -Algorithm SHA256).Hash-cne$record.seed_save_sha256-or(Get-FileHash -LiteralPath (Join-Path $cycleUser 'B13EBABEBABEBABE/545407F8/Headers/00000001/mc4.sav.header') -Algorithm SHA256).Hash-cne$record.seed_header_sha256){throw 'Cycle save identity mismatch.'};$head=(&git -C (Join-Path $repo 'third_party/rexglue-sdk') rev-parse HEAD).Trim();if($LASTEXITCODE-ne0-or$head-cne$sdkCommit){throw 'Current SDK identity mismatch.'};$tree=Get-TreeSnapshot $root;if($record.evidence_tree_sha256-cne$tree.Hash-or$record.evidence_tree_file_count-ne$tree.FileCount-or$record.evidence_tree_directory_count-ne$tree.DirectoryCount-or$record.evidence_tree_bytes-ne$tree.Bytes){throw 'Evidence-tree identity mismatch.'};$exe=Resolve-SafePath 'out/build/win-amd64-relwithdebinfo/mcla.exe' 'Canonical executable' -Exists;if(@(Get-ExactProcesses $exe).Count){throw 'Canonical MCLA process is still running.'}
[pscustomobject][ordered]@{Decision=$record.decision;AudioClassesVerified=6;CurrentXmaXAudioSdlRouteVerified=$true;OperatorListeningConfirmed=$true;PresenceOnly=$true;OtherSoundsAllowed=$true;ControlledExitVerified=$true;DataIntegrityVerified=$true}
