[CmdletBinding(DefaultParameterSetName='Source')]
param(
  [Parameter(ParameterSetName='Source')][switch]$SourceOnly,
  [Parameter(Mandatory,ParameterSetName='Result')][string]$ResultPath,
  [Parameter(ParameterSetName='Result')][switch]$FixtureMode
)

Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$repo=(Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '..')).Path;$sdk=Join-Path $repo 'third_party/rexglue-sdk'
$sdkVersion='0.9.0.25';$sdkCommit='f28ddabbae3bca56ddf5ffea067982c49c9549b7'
$seedSaveSha='126F7482878C7AACB09AA6795331C906DFB9C4218BE94EDB1D8E51B27CA78AB2';$seedHeaderSha='5827A913515AC0E5D55BB56AEC56DE99CACC0ABB7C8061F59336DF4CEA4A8731'
$prior=@(
  [ordered]@{task='M4-004';run_id='20260812-123316-db0f1cf4';sha256='388F2FC350C43149CA6E5AD4E24A1B743F18CFE3A450C6D80962099F73C89AE0';decision='single-local-offline-profile'},
  [ordered]@{task='M4-010';run_id='20260813-213301-505ca1ca';sha256='458B742FC1112DDAF39BDC8B81935CC8F2F9C616477B258B1E6FBA10058E096A';decision='locale-selection-unicode-path-title-matrix-pass'},
  [ordered]@{task='M5-006';run_id='20260814-130533-0b95f6b6';sha256='A89C0CC3E02C8D264B0DA29157021D050276BF46F028BBAAAD9B1FFC220CCEAB';decision='saved-gameplay-input-pass'},
  [ordered]@{task='M6-005';run_id='20260818-201702-5d089d9c';sha256='5F46FA6657F39EE5AF990BD505B67D5EDBE6A781E8283D1D51BE07F3543F169E';decision='native-autosave-load-overwrite-plus-isolated-creation-destructive-save-matrix-pass'}
)
$sourcePaths=@('third_party/rexglue-sdk/include/rex/system/xam/content_manager.h','third_party/rexglue-sdk/include/rex/system/xam/user_profile.h','third_party/rexglue-sdk/src/kernel/xam/xam_user.cpp','third_party/rexglue-sdk/src/system/kernel_state.cpp','third_party/rexglue-sdk/src/system/xam/content_manager.cpp','third_party/rexglue-sdk/src/system/xam/user_profile.cpp','third_party/rexglue-sdk/tests/unit/kernel/xam_user_profile_test.cpp','third_party/rexglue-sdk/src/core/cvar.cpp','third_party/rexglue-sdk/src/input/input_system.cpp','third_party/rexglue-sdk/src/input/mnk/mnk_input_driver.cpp')
function Exact($Object,[string[]]$Names,[string]$Description){if(($Object.PSObject.Properties.Name-join',')-cne($Names-join',')){throw "$Description schema is invalid."}}
function Bool($Value,[bool]$Expected,[string]$Description){if($Value-isnot[bool]-or$Value-ne$Expected){throw "$Description is invalid."}}
function Hash([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash}
function Safe([string]$Path,[string]$Description,[switch]$Exists){$full=if([IO.Path]::IsPathRooted($Path)){[IO.Path]::GetFullPath($Path)}else{[IO.Path]::GetFullPath((Join-Path $repo $Path))};$prefix=$repo.TrimEnd('\')+'\';if(-not$full.StartsWith($prefix,[StringComparison]::OrdinalIgnoreCase)){throw "$Description escapes repository."};$current=$repo;foreach($part in @($full.Substring($prefix.Length).Split('\')|Where-Object{$_.Length})){$current=Join-Path $current $part;if((Test-Path -LiteralPath $current)-and((Get-Item -LiteralPath $current -Force).Attributes-band[IO.FileAttributes]::ReparsePoint)){throw "$Description traverses a reparse point."}};if($Exists-and-not(Test-Path -LiteralPath $full)){throw "$Description is missing."};$full}
function SourceContract{
  $profileH=[IO.File]::ReadAllText((Join-Path $sdk 'include/rex/system/xam/user_profile.h'));$profile=[IO.File]::ReadAllText((Join-Path $sdk 'src/system/xam/user_profile.cpp'));$user=[IO.File]::ReadAllText((Join-Path $sdk 'src/kernel/xam/xam_user.cpp'));$kernel=[IO.File]::ReadAllText((Join-Path $sdk 'src/system/kernel_state.cpp'));$manager=[IO.File]::ReadAllText((Join-Path $sdk 'src/system/xam/content_manager.cpp'));$tests=[IO.File]::ReadAllText((Join-Path $sdk 'tests/unit/kernel/xam_user_profile_test.cpp'));$cvar=[IO.File]::ReadAllText((Join-Path $sdk 'src/core/cvar.cpp'));$input=[IO.File]::ReadAllText((Join-Path $sdk 'src/input/input_system.cpp'));$mnk=[IO.File]::ReadAllText((Join-Path $sdk 'src/input/mnk/mnk_input_driver.cpp'));$generated=[IO.File]::ReadAllText((Join-Path $repo 'generated/default/mcla_init.cpp'))
  foreach($pair in @(
    @($profileH,'virtual ~Setting() = default;'),@($profileH,'void SetPersistenceRoot(const std::filesystem::path& root);'),@($profile,'kPersistentSettingMagic'),@($profile,"'.tmp'".Replace("'",'"')),@($profile,"'.bak'".Replace("'",'"')),
    @($profile,'LoadPersistentSetting(setting.get())'),@($profile,'SavePersistentSetting(setting)'),@($profile,'stored_id != setting->setting_id'),@($profile,'stored_type != static_cast<uint32_t>(setting->type)'),@($profile,'payload.size() > key.size'),
    @($kernel,'SetPersistenceRoot(content_manager_->ResolveGlobalUserProfilePath())'),@($manager,'kGameUserContentDirName / user_name'),@($user,'Validate and materialize the complete batch before applying any setting'),@($user,'duplicate setting {:08X}'),@($user,'setting_key.type != static_cast<uint32_t>(setting_type)'),@($user,'existing->type != setting_type'),@($user,'updates.push_back(std::move(update))'),@($user,'for (auto& update : updates)'),
    @($user,'CompleteOverlappedImmediate(overlapped.guest_address(), result)'),@($cvar,'void LoadConfig(const std::filesystem::path& config_path)'),@($cvar,'void SaveConfig(const std::filesystem::path& config_path)'),@($input,'REXCVAR_DEFINE_STRING(input_backend, "sdl"'),@($mnk,'REXCVAR_DEFINE_BOOL(mnk_mode, false'),@($user,'REXCVAR_DEFINE_UINT32(user_language, 1'),
    @($tests,'XAM profile persists allowlisted scalar and Unicode settings across restart'),@($tests,'XAM profile rejects mismatched persistent setting metadata'),@($tests,'XAM profile restart recovers the previous committed setting'),@($tests,'XAM title-specific settings never leak into the global profile root')
  )){if(-not$pair[0].Contains($pair[1])){throw "Profile/settings source contract is missing '$($pair[1])'."}}
  if($generated.Contains('XamUserWriteProfileSettings')){throw 'MCLA unexpectedly imports the profile write API.'}
  $validate=$user.IndexOf('for (uint32_t n = 0; n < setting_count; ++n)',[StringComparison]::Ordinal);$apply=$user.IndexOf('for (auto& update : updates)',[StringComparison]::Ordinal);if($validate-lt0-or$apply-le$validate){throw 'Profile batch mutation is not after full validation.'}
  [pscustomobject][ordered]@{SourceContractVerified=$true;SourceChecks=30;ProfileCases=7;ProfileAssertions=40;CvarCases=26;CvarAssertions=128;TitleWriteImported=$false}
}
$source=SourceContract;if($PSCmdlet.ParameterSetName-ceq'Source'){return $source}
$full=Safe $ResultPath 'M6-006 result' -Exists;$rootPrefix=(Join-Path $repo 'private/evidence/M6-006').TrimEnd('\')+'\';if(-not$full.StartsWith($rootPrefix,[StringComparison]::OrdinalIgnoreCase)){throw 'Result is outside private M6-006 evidence.'}
$raw=[IO.File]::ReadAllText($full);if($raw-match'(?i)[A-Z]:\\|B13EBABEBABEBABE|xuid|controller.{0,8}(name|guid|serial)|host_path'){throw 'Result leaks a path or private identity.'};$r=$raw|ConvertFrom-Json
Exact $r @('schema','task','decision','sdk_version','sdk_commit','build_configuration','prior_evidence','focused_tests','preferences','source_integrity','release_artifacts','source_files','scope') 'Result'
if($r.schema-cne'mcla-profile-settings-v1'-or$r.task-cne'M6-006'-or$r.decision-cne'isolated-profile-controller-language-restart-matrix-pass'-or$r.sdk_version-cne$sdkVersion-or$r.sdk_commit-cne$sdkCommit-or$r.build_configuration-cne'Release+RelWithDebInfo'){throw 'Result identity is invalid.'}
if(@($r.prior_evidence).Count-ne4){throw 'Prior evidence count is invalid.'};for($i=0;$i-lt4;$i++){Exact $r.prior_evidence[$i] @('task','run_id','sha256','decision') 'Prior evidence';foreach($n in @('task','run_id','sha256','decision')){if($r.prior_evidence[$i].$n-cne$prior[$i].$n){throw 'Prior evidence identity is invalid.'}}}
Exact $r.focused_tests @('profile_cases','profile_assertions','cvar_cases','cvar_assertions','scalar_restart','unicode_restart','metadata_rejected','backup_recovered','title_settings_isolated','config_save_load','sdk_build_log_sha256','profile_test_log_sha256','cvar_test_log_sha256','unit_executable_sha256') 'Focused tests';if($r.focused_tests.profile_cases-ne7-or$r.focused_tests.profile_assertions-ne40-or$r.focused_tests.cvar_cases-ne26-or$r.focused_tests.cvar_assertions-ne128){throw 'Focused totals are invalid.'};foreach($n in @('scalar_restart','unicode_restart','metadata_rejected','backup_recovered','title_settings_isolated','config_save_load')){Bool $r.focused_tests.$n $true "Focused $n"};foreach($n in @('sdk_build_log_sha256','profile_test_log_sha256','cvar_test_log_sha256','unit_executable_sha256')){if($r.focused_tests.$n-cnotmatch'^[A-F0-9]{64}$'){throw "Focused digest $n is invalid."}}
Exact $r.preferences @('language_flag','controller_backend_flag','controller_mode_flag','named_flags_source_bound','restart_serialization_verified') 'Preferences';if($r.preferences.language_flag-cne'user_language'-or$r.preferences.controller_backend_flag-cne'input_backend'-or$r.preferences.controller_mode_flag-cne'mnk_mode'){throw 'Preference flag identity is invalid.'};Bool $r.preferences.named_flags_source_bound $true 'Named flag binding';Bool $r.preferences.restart_serialization_verified $true 'Restart serialization'
Exact $r.source_integrity @('seed_save_before_sha256','seed_save_after_sha256','seed_header_before_sha256','seed_header_after_sha256','source_save_mutated','release_build_log_sha256') 'Source integrity';if($r.source_integrity.seed_save_before_sha256-cne$seedSaveSha-or$r.source_integrity.seed_save_after_sha256-cne$seedSaveSha-or$r.source_integrity.seed_header_before_sha256-cne$seedHeaderSha-or$r.source_integrity.seed_header_after_sha256-cne$seedHeaderSha-or$r.source_integrity.release_build_log_sha256-cnotmatch'^[A-F0-9]{64}$'){throw 'Source integrity is invalid.'};Bool $r.source_integrity.source_save_mutated $false 'Source save mutation'
$artifactNames=@('mcla.exe','rexruntime.dll','TracyClient.dll','rexgpu-xenos.dll');if(@($r.release_artifacts).Count-ne4){throw 'Artifact count is invalid.'};for($i=0;$i-lt4;$i++){Exact $r.release_artifacts[$i] @('name','sha256') 'Artifact';if($r.release_artifacts[$i].name-cne$artifactNames[$i]-or$r.release_artifacts[$i].sha256-cnotmatch'^[A-F0-9]{64}$'){throw 'Artifact manifest is invalid.'}}
if(@($r.source_files).Count-ne$sourcePaths.Count){throw 'Source count is invalid.'};for($i=0;$i-lt$sourcePaths.Count;$i++){Exact $r.source_files[$i] @('path','sha256') 'Source';if($r.source_files[$i].path-cne$sourcePaths[$i]-or$r.source_files[$i].sha256-cnotmatch'^[A-F0-9]{64}$'){throw 'Source manifest is invalid.'}}
Exact $r.scope @('title_write_imported','native_profile_write_route_claimed','isolated_platform_persistence','prior_profile_identity_physical','prior_language_selection_physical','prior_controller_route_physical','profile_read_runtime_claimed','account_picker_claimed','multiple_profiles_claimed','first_run_oobe_claimed','native_gameplay_replayed','general_host_config_claimed') 'Scope';foreach($n in @('title_write_imported','native_profile_write_route_claimed','profile_read_runtime_claimed','account_picker_claimed','multiple_profiles_claimed','first_run_oobe_claimed','native_gameplay_replayed','general_host_config_claimed')){Bool $r.scope.$n $false "Scope $n"};foreach($n in @('isolated_platform_persistence','prior_profile_identity_physical','prior_language_selection_physical','prior_controller_route_physical')){Bool $r.scope.$n $true "Scope $n"}
if(-not$FixtureMode){$runRoot=Split-Path $full;$children=@(Get-ChildItem -LiteralPath $runRoot -Force);if($children.Count-ne5-or(@($children.Name|Sort-Object)-join',')-cne'cvar-test.log,profile-test.log,release-clean-build.log,result.json,sdk-build.log'){throw 'Evidence topology is invalid.'};foreach($child in $children){if($child.Attributes-band[IO.FileAttributes]::ReparsePoint){throw 'Evidence child is a reparse point.'}}
  for($i=0;$i-lt4;$i++){$p=Safe "private/evidence/$($prior[$i].task)/$($prior[$i].run_id)/result.json" 'Prior result' -Exists;if((Hash $p)-cne$prior[$i].sha256){throw 'Prior result drifted.'};$j=[IO.File]::ReadAllText($p)|ConvertFrom-Json;if($j.task-cne$prior[$i].task-or$j.decision-cne$prior[$i].decision){throw 'Prior result semantics drifted.'}}
  $save=Safe 'private/evidence/M5-013/20260817-013319-c2e7223f/runs/01/user/B13EBABEBABEBABE/545407F8/00000001/mc4.sav/mc4.sav' 'Seed save' -Exists;$header=Safe 'private/evidence/M5-013/20260817-013319-c2e7223f/runs/01/user/B13EBABEBABEBABE/545407F8/Headers/00000001/mc4.sav.header' 'Seed header' -Exists;if((Hash $save)-cne$seedSaveSha-or(Hash $header)-cne$seedHeaderSha){throw 'Seed save/header drifted.'}
  if((&git -C $sdk rev-parse HEAD).Trim()-cne$sdkCommit-or(&git -C $sdk describe --tags --exact-match HEAD 2>$null).Trim()-cne"v$sdkVersion"-or(git -C $sdk status --porcelain)){throw 'SDK identity is invalid.'}
  $sdkLog=Join-Path $runRoot 'sdk-build.log';$profileLog=Join-Path $runRoot 'profile-test.log';$cvarLog=Join-Path $runRoot 'cvar-test.log';$releaseLog=Join-Path $runRoot 'release-clean-build.log';$unit=Join-Path $sdk 'out/win-amd64/RelWithDebInfo/unit_tests.exe';if((Hash $sdkLog)-cne$r.focused_tests.sdk_build_log_sha256-or(Hash $profileLog)-cne$r.focused_tests.profile_test_log_sha256-or(Hash $cvarLog)-cne$r.focused_tests.cvar_test_log_sha256-or(Hash $unit)-cne$r.focused_tests.unit_executable_sha256){throw 'Focused physical hashes drifted.'};if([IO.File]::ReadAllText($profileLog)-notmatch'All tests passed \(40 assertions in 7 test cases\)'-or[IO.File]::ReadAllText($cvarLog)-notmatch'All tests passed \(128 assertions in 26 test cases\)'){throw 'Focused physical output is invalid.'};if((Hash $releaseLog)-cne$r.source_integrity.release_build_log_sha256){throw 'Release log drifted.'}
  foreach($entry in $r.source_files){if((Hash (Safe $entry.path 'Source file' -Exists))-cne$entry.sha256){throw 'Source file drifted.'}};$build=Safe 'out/build/win-amd64-release' 'Release build' -Exists;for($i=0;$i-lt4;$i++){if((Hash (Safe (Join-Path $build $artifactNames[$i]) 'Artifact' -Exists))-cne$r.release_artifacts[$i].sha256){throw 'Release artifact drifted.'}};if(@((Get-Process mcla -ErrorAction SilentlyContinue)|Where-Object{try{$_.Path-ceq(Join-Path $build 'mcla.exe')}catch{$false}}).Count){throw 'Canonical MCLA process remains.'}}
[pscustomobject][ordered]@{Decision=$r.decision;ProfileRestartVerified=$true;ControllerPreferenceRestartVerified=$true;LanguagePreferenceRestartVerified=$true;PriorPhysicalRoutesBound=$true;NativeProfileWriteRouteClaimed=$false;FirstRunOobeClaimed=$false;GeneralHostConfigClaimed=$false;SourceSaveMutated=$false;DataIntegrityVerified=$true}
