[CmdletBinding(DefaultParameterSetName='Run')]
param(
  [Parameter(Mandatory,ParameterSetName='Run')][string]$RunPath,
  [Parameter(Mandatory,ParameterSetName='Result')][string]$ResultPath,
  [switch]$Fixture
)

Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$repo=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$utf8=[Text.UTF8Encoding]::new($false)
$sdkCommit='576b34fd233acf4579dd2375691dbe86fb4bf8e1'
$seedSaveSha='126F7482878C7AACB09AA6795331C906DFB9C4218BE94EDB1D8E51B27CA78AB2'
$seedHeaderSha='5827A913515AC0E5D55BB56AEC56DE99CACC0ABB7C8061F59336DF4CEA4A8731'
$trafficResultSha='299392E59CB38AFB44256E773884856FF0C869A96D2045086A65396C1ED4EFCA'
$seriesResultSha='D993E2612D1AC769D88264C83FD9C9186BC761E2067317F5A7EB66038C250E58'
$resourceResultSha='D890A903775A3B53262B9957E7B7DC1D4B76B49B8735360BECD8233842446298'
$scope='one current representative Ian or Martin head-to-head event with machine-observed Race_Finish invocation, current start/reward frames, and external owner completion/police observation; prior immutable Ian series, five-race reward, and traffic evidence; optional description/checkpoint/UI-result wrappers may be zero-hit and are not required or claimed as current machine telemetry; no claim of every race type, opponent, checkpoint implementation, police behavior, reward amount, difficulty, or campaign branch'

function Resolve-Safe([string]$Path,[string]$Description,[switch]$Exists){$full=if([IO.Path]::IsPathRooted($Path)){[IO.Path]::GetFullPath($Path)}else{[IO.Path]::GetFullPath((Join-Path $repo $Path))};$prefix=$repo.TrimEnd('\')+'\';if(-not$full.StartsWith($prefix,[StringComparison]::OrdinalIgnoreCase)){throw "$Description escapes repository."};$current=$repo;foreach($part in @($full.Substring($prefix.Length).Split('\')|Where-Object{$_.Length})){$current=Join-Path $current $part;if((Test-Path -LiteralPath $current)-and((Get-Item -LiteralPath $current -Force).Attributes-band[IO.FileAttributes]::ReparsePoint)){throw "$Description traverses a reparse point."}};if($Exists-and-not(Test-Path -LiteralPath $full)){throw "$Description is missing."};$full}
function Assert-NoReparse([string]$Root){foreach($item in @(Get-ChildItem -LiteralPath $Root -Recurse -Force)){if($item.Attributes-band[IO.FileAttributes]::ReparsePoint){throw 'Evidence contains a reparse point.'}}}
function Get-Tree([string]$Root){$entries=@();$bytes=0L;foreach($item in @(Get-ChildItem -LiteralPath $Root -Recurse -Force|Sort-Object FullName)){$rel=$item.FullName.Substring($Root.Length).TrimStart('\').Replace('\','/');if($rel-ceq'result.json'){continue};if($item.PSIsContainer){$entries+=[ordered]@{kind='directory';path=$rel}}else{$bytes+=$item.Length;$entries+=[ordered]@{kind='file';path=$rel;bytes=$item.Length;sha256=(Get-FileHash -LiteralPath $item.FullName -Algorithm SHA256).Hash}}};$json=ConvertTo-Json @($entries)-Compress -Depth 4;$sha=[Security.Cryptography.SHA256]::Create();try{$hash=-join($sha.ComputeHash($utf8.GetBytes($json))|ForEach-Object{$_.ToString('X2')})}finally{$sha.Dispose()};[ordered]@{sha256=$hash;files=@($entries|Where-Object{$_.kind-ceq'file'}).Count;directories=@($entries|Where-Object{$_.kind-ceq'directory'}).Count;bytes=$bytes}}
function Get-Logs([string]$Root){$files=@(Get-ChildItem -LiteralPath $Root -File -Filter 'mcla*.log');if($files.Count-lt1-or$files.Count-gt31){throw 'Runtime-log count is invalid.'};$current=@($files|Where-Object{$_.Name-ceq'mcla.log'});if($current.Count-ne1){throw 'Current runtime log missing.'};$rot=@();foreach($file in @($files|Where-Object{$_.Name-cne'mcla.log'})){$match=[regex]::Match($file.Name,'^mcla\.([1-9][0-9]*)\.log$');if(-not$match.Success){throw 'Malformed runtime-log rotation.'};$rot+=[pscustomobject]@{index=[int]$match.Groups[1].Value;file=$file}};$indices=@($rot|ForEach-Object{$_.index}|Sort-Object);for($i=0;$i-lt$indices.Count;$i++){if($indices[$i]-ne$i+1){throw 'Runtime-log rotation gap.'}};$ordered=@($rot|Sort-Object index -Descending|ForEach-Object{$_.file})+$current[0];$text='';$manifest=@();$bytes=0L;foreach($file in $ordered){$bytes+=$file.Length;if($bytes-gt268435456){throw 'Runtime logs exceed 256 MiB.'};$text+=[IO.File]::ReadAllText($file.FullName)+"`n";$manifest+=[ordered]@{name=$file.Name;bytes=$file.Length;sha256=(Get-FileHash -LiteralPath $file.FullName -Algorithm SHA256).Hash}};[pscustomobject]@{text=$text;manifest=@($manifest);bytes=$bytes}}
function One([string]$Text,[string]$Pattern,[string]$Name){$matches=[regex]::Matches($Text,$Pattern);if($matches.Count-ne1){throw "$Name count is $($matches.Count)."};$matches[0]}
function Read-Bmp([string]$Path,[string]$Name){$file=Resolve-Safe $Path $Name -Exists;$bytes=[IO.File]::ReadAllBytes($file);if($bytes.Length-ne3686454-or$bytes[0]-ne0x42-or$bytes[1]-ne0x4D-or[BitConverter]::ToInt32($bytes,18)-ne1280-or[Math]::Abs([BitConverter]::ToInt32($bytes,22))-ne720-or[BitConverter]::ToUInt16($bytes,28)-ne32){throw "$Name is not the exact 1280x720x32 BMP shape."};[ordered]@{sha256=(Get-FileHash -LiteralPath $file -Algorithm SHA256).Hash;bytes=$bytes.Length}}
function Assert-StaticContract{
  $source=[IO.File]::ReadAllText((Join-Path $repo 'src/mcla_app.cpp'));foreach($needle in @('mcla_race_system_probe','Lifecycle::kInitOnly','kRaceDescriptionTypeAddress = 0x822C9230','kRaceDescriptionSubtypeAddress = 0x822C9270','kRaceDescriptionCopZonesAddress = 0x822C92B0','kCheckpointListCountAddress = 0x82267528','kCheckpointHitAddress = 0x82263930','kRaceFinishAddress = 0x82256BE0','kRaceResultAddress = 0x821FBB40','RaceDescriptionTypeProbe','CheckpointListCountProbe','RaceFinishProbe','MCLA_RACE_SYSTEM_CONFIG v=1','MCLA_RACE_SYSTEM_READY v=1','MCLA_RACE_SYSTEM_FRAME v=1 phase={} width={} height={} ','MCLA_RACE_SYSTEM_SUMMARY v=1 status={} frames={} ','kRaceSystemDetailCapacity = 32','race_system_audit_enabled = false')){if(-not$source.Contains($needle)){throw "Race-system source contract is missing '$needle'."}}
  foreach($address in @('821FBB40','82256BE0','82263930','82267528','822C9230','822C9270','822C92B0')){$init=[IO.File]::ReadAllText((Join-Path $repo 'generated/default/mcla_init.cpp'));$register=[IO.File]::ReadAllText((Join-Path $repo 'generated/default/mcla_register.cpp'));if(-not$init.Contains("{ 0x$address, sub_$address }")-or-not$register.Contains("registrar->SetFunction(0x$address, sub_$address);")){throw "Generated wrapper $address is not registered."}}
  $runner=[IO.File]::ReadAllText((Join-Path $repo 'scripts/run-race-system-smoke.ps1'));foreach($needle in @('RACE SYSTEM START IAN','RACE SYSTEM START MARTIN','POLICE SEEN','POLICE NOT SEEN','--mcla_race_system_probe=true','--xam_user_signin_state=2')){if(-not$runner.Contains($needle)){throw "Race-system runner contract is missing '$needle'."}}
}
function Read-Prior([string]$Relative,[string]$Hash,[string]$Decision){$path=Resolve-Safe $Relative 'Prior evidence' -Exists;if((Get-FileHash $path -Algorithm SHA256).Hash-cne$Hash){throw 'Prior evidence hash drifted.'};$record=Get-Content $path -Raw|ConvertFrom-Json;if($record.decision-cne$Decision){throw 'Prior evidence decision drifted.'};[ordered]@{sha256=$Hash;decision=$Decision}}
function Get-Lifecycle([string]$Cycle){$logs=Get-Logs $Cycle;$text=$logs.text;foreach($bad in @('[FATAL]','Assertion failed','PPC_UNIMPLEMENTED','Guest crash','DXGI_ERROR_DEVICE_REMOVED','unregistered guest function')){if($text.Contains($bad)){throw "Lifecycle banned marker '$bad'."}};$frame=One $text 'MCLA graphics: nontrivial guest frame captured 1280x720' 'Lifecycle frame';$close=One $text 'Window closing, shutting down\.\.\.' 'Lifecycle close';$complete=One $text 'Execution complete' 'Lifecycle complete';$hard=One $text 'Title terminated; hard-exiting process\.' 'Lifecycle hard exit';if(-not($frame.Index-lt$close.Index-and$close.Index-lt$complete.Index-and$complete.Index-lt$hard.Index)){throw 'Lifecycle chronology is invalid.'};[ordered]@{controlled_exit=$true;runtime_logs=@($logs.manifest);runtime_log_bytes=$logs.bytes}}
function Get-Probe([string]$Path){
  Assert-StaticContract;$root=Resolve-Safe $Path 'M6-003 run root' -Exists;Assert-NoReparse $root;if(-not$Fixture-and-not[regex]::IsMatch((Split-Path $root -Leaf),'^20[0-9]{6}-[0-9]{6}-[a-f0-9]{8}$')){throw 'Physical run-root name is not canonical.'};$allowed=@('release-clean-build.log','result.json','runs','operator-observation.json','physical-artifacts.json');foreach($child in @(Get-ChildItem $root -Force)){if($child.Name-cnotin$allowed){throw 'Run root contains an unexpected child.'}}
  $build=Resolve-Safe (Join-Path $root 'release-clean-build.log') 'Release build log' -Exists;if(-not$Fixture){$buildText=[IO.File]::ReadAllText($build);foreach($needle in @('CMAKE_BUILD_TYPE="Release"','REXSDK_VERSION="0.9.0.22"','Cleaning all built files','Linking CXX executable mcla.exe')){if(-not$buildText.Contains($needle)){throw "Build log is missing '$needle'."}}}
  $observationPath=Resolve-Safe (Join-Path $root 'operator-observation.json') 'Operator observation' -Exists;$observation=Get-Content $observationPath -Raw|ConvertFrom-Json;$observationProps=@('schema','opponent','event_completed','police_observed','prior_police_observed','source','recorded_in_runtime_log','machine_verified');if(($observation.PSObject.Properties.Name-join',')-cne($observationProps-join',')-or$observation.schema-cne'mcla-race-system-operator-observation-v1'-or$observation.opponent-cnotin@('IAN','MARTIN')-or$observation.event_completed-isnot[bool]-or-not$observation.event_completed-or$observation.police_observed-isnot[bool]-or$observation.prior_police_observed-isnot[bool]-or-not$observation.prior_police_observed-or$observation.source-cne'owner-console-transcript-and-chat-report'-or$observation.recorded_in_runtime_log-isnot[bool]-or$observation.recorded_in_runtime_log-or$observation.machine_verified-isnot[bool]-or$observation.machine_verified){throw 'Operator observation schema/provenance is invalid.'}
  $cycle=Resolve-Safe (Join-Path $root 'runs/01') 'Event cycle root' -Exists;foreach($child in @(Get-ChildItem $cycle -Force)){if($child.Name-cnotmatch'^(cache|user|mcla(?:\.[1-9][0-9]*)?\.log)$'){throw 'Event cycle contains an unexpected child.'}};if(@(Get-ChildItem $cycle -Recurse -File -Filter '*.request').Count){throw 'Event cycle contains an unconsumed request.'};$logs=Get-Logs $cycle;$text=$logs.text;foreach($bad in @('[FATAL]','Assertion failed','PPC_UNIMPLEMENTED','Guest crash','DXGI_ERROR_DEVICE_REMOVED','MCLA race system: failed','unregistered guest function')){if($text.Contains($bad)){throw "Event banned marker '$bad'."}}
  $signin=One $text 'XAM_USER_SIGNIN_CONFIG v=1 state=2 mode=online-compatible' 'Sign-in config';$launch=One $text 'KernelState: Preparing module launch\.\.\.' 'Launch';$config=One $text 'MCLA_RACE_SYSTEM_CONFIG v=1 enabled=1 desc_type=822C9230 desc_subtype=822C9270 cop_zones=822C92B0 checkpoint_count=82267528 checkpoint_hit=82263930 finish=82256BE0 result=821FBB40 detail_cap=32' 'Race config';$ready=One $text 'MCLA_RACE_SYSTEM_READY v=1 phases=start,rewards external_close_required=1' 'Ready';$frames=[regex]::Matches($text,'MCLA_RACE_SYSTEM_FRAME v=1 phase=(start|rewards) width=1280 height=720 present_seq=([1-9][0-9]*) status=PASS');if($frames.Count-ne2-or$frames[0].Groups[1].Value-cne'start'-or$frames[1].Groups[1].Value-cne'rewards'-or[int64]$frames[1].Groups[2].Value-le[int64]$frames[0].Groups[2].Value){throw 'Frame identity/order is invalid.'}
  $finish=One $text 'MCLA_RACE_SYSTEM_FINISH v=1 record=([1-9][0-9]*) category=([0-9]+) finished=1 arrested=([01]) winning_time=([0-9]+) desc_known=([01]) race_type=([0-9]+) race_subtype=([0-9]+) cop_zones=([0-9]+) checkpoint_max=([0-9]+)' 'Finish wrapper';$summary=One $text 'MCLA_RACE_SYSTEM_SUMMARY v=1 status=(PASS|FAIL) frames=2 desc_calls=([0-9]+) desc_complete=([0-9]+) checkpoint_count_calls=([0-9]+) checkpoint_max=([0-9]+) checkpoint_hits=([0-9]+) finish_calls=(1) result_calls=([0-9]+) arrested_finishes=([0-9]+) category=([0-9]+) race_type=([0-9]+) race_subtype=([0-9]+) cop_zones=([0-9]+) winning_time=([0-9]+) detail_records=([1-9][0-9]*) dropped_records=0 external_close_required=1' 'Summary';if(-not($signin.Index-lt$config.Index-and$config.Index-lt$launch.Index-and$launch.Index-lt$ready.Index-and$ready.Index-lt$frames[0].Index-and$frames[0].Index-lt$finish.Index-and$finish.Index-lt$frames[1].Index-and$frames[1].Index-lt$summary.Index)){throw 'Event chronology is invalid.'}
  $markerLines=[regex]::Matches($text,'MCLA_RACE_SYSTEM_([A-Z]+) v=([0-9]+)');$markerCounts=@{};foreach($marker in $markerLines){$family=$marker.Groups[1].Value;if($marker.Groups[2].Value-cne'1'-or$family-cnotin@('CONFIG','READY','FRAME','DESC','CHECKPOINTS','FINISH','SUMMARY')){throw 'Unknown race-system marker/schema.'};$markerCounts[$family]=1+$(if($markerCounts.ContainsKey($family)){$markerCounts[$family]}else{0})};foreach($required in @{CONFIG=1;READY=1;FRAME=2;FINISH=1;SUMMARY=1}.GetEnumerator()){if(-not$markerCounts.ContainsKey($required.Key)-or$markerCounts[$required.Key]-ne$required.Value){throw "Race-system $($required.Key) cardinality is invalid."}};$details=[regex]::Matches($text,'MCLA_RACE_SYSTEM_(?:DESC|CHECKPOINTS|FINISH) v=1 record=([1-9][0-9]*)');if($details.Count-ne[int]$summary.Groups[15].Value){throw 'Detail-record cardinality differs from summary.'};for($i=0;$i-lt$details.Count;$i++){if([int]$details[$i].Groups[1].Value-ne$i+1){throw 'Detail-record sequence is invalid.'}}
  if([uint64]$summary.Groups[10].Value-ne[uint64]$finish.Groups[2].Value-or[uint64]$summary.Groups[9].Value-ne[uint64]$finish.Groups[3].Value-or[uint64]$summary.Groups[14].Value-ne[uint64]$finish.Groups[4].Value-or[uint64]$summary.Groups[11].Value-ne[uint64]$finish.Groups[6].Value-or[uint64]$summary.Groups[12].Value-ne[uint64]$finish.Groups[7].Value-or[uint64]$summary.Groups[13].Value-ne[uint64]$finish.Groups[8].Value-or[uint64]$summary.Groups[5].Value-ne[uint64]$finish.Groups[9].Value){throw 'Summary and finish-wrapper tuple differ.'}
  $calibration=$summary.Groups[1].Value-ceq'FAIL';if($calibration){if(-not$Fixture-and(Split-Path $root -Leaf)-cne'20260818-180605-e3b74fb5'){throw 'Only the pinned completed Martin calibration may recover a strict-summary failure.'};if(@([regex]::Matches($text,'Window closing, shutting down\.\.\.|Execution complete|Title terminated; hard-exiting process\.')).Count){throw 'Calibration event cycle must retain its truthful missing lifecycle tail.'};$expected=@{log='0566CBDC08786057F463B904B74A496697DDEE9EC58777E2972395DFAFB829E2';start='68F82DDFE2D50BE38382BE433E618A05252E569113FD099531D531B9541CF927';rewards='147E4AAB483306123EE9FCCF8BEB07941DDA956EA7E04C9FAA5F074B039A483C';build='3AF8BCA634EB213D696B69D4006FFD75F33AF6568D2A1C11C7F89956EA37AC57'};if(-not$Fixture-and((Get-FileHash (Join-Path $cycle 'mcla.log') -Algorithm SHA256).Hash-cne$expected.log-or(Get-FileHash $build -Algorithm SHA256).Hash-cne$expected.build)){throw 'Pinned calibration log/build drifted.'};if([int]$summary.Groups[2].Value-ne0-or[int]$summary.Groups[3].Value-ne0-or[int]$summary.Groups[4].Value-ne0-or[int]$summary.Groups[5].Value-ne0-or[int]$summary.Groups[6].Value-ne0-or[int]$summary.Groups[8].Value-ne0-or[int]$summary.Groups[15].Value-ne1){throw 'Calibration must fail only because optional wrappers were zero-hit.'}}else{$close=One $text 'Window closing, shutting down\.\.\.' 'Event close';$complete=One $text 'Execution complete' 'Event complete';$hard=One $text 'Title terminated; hard-exiting process\.' 'Event hard exit';if(-not($summary.Index-lt$close.Index-and$close.Index-lt$complete.Index-and$complete.Index-lt$hard.Index)){throw 'Event shutdown chronology is invalid.'}}
  $user=Resolve-Safe (Join-Path $cycle 'user') 'User root' -Exists;$start=Read-Bmp (Join-Path $user 'mcla-race-system-start.bmp') 'Start capture';$rewards=Read-Bmp (Join-Path $user 'mcla-race-system-rewards.bmp') 'Reward capture';if($start.sha256-ceq$rewards.sha256){throw 'Start and reward captures are identical.'};if($calibration-and-not$Fixture-and($start.sha256-cne$expected.start-or$rewards.sha256-cne$expected.rewards)){throw 'Pinned calibration captures drifted.'};$save=Resolve-Safe (Join-Path $user 'B13EBABEBABEBABE/545407F8/00000001/mc4.sav/mc4.sav') 'Working save' -Exists;$header=Resolve-Safe (Join-Path $user 'B13EBABEBABEBABE/545407F8/Headers/00000001/mc4.sav.header') 'Working header' -Exists;if((Get-Item $save).Length-ne537428-or(Get-Item $header).Length-ne328){throw 'Working save/header shape is invalid.'}
  $runs=Resolve-Safe (Join-Path $root 'runs') 'Runs root' -Exists;$runChildren=@(Get-ChildItem $runs -Force);$expectedCycles=if($calibration){'01,02'}else{'01'};if((@($runChildren.Name|Sort-Object)-join',')-cne$expectedCycles-or@($runChildren|Where-Object{-not$_.PSIsContainer}).Count){throw 'Run-cycle topology is invalid.'};$lifecycle=if($calibration){$recoveryCycle=Resolve-Safe (Join-Path $root 'runs/02') 'Recovery lifecycle cycle' -Exists;foreach($child in @(Get-ChildItem $recoveryCycle -Force)){if($child.Name-cnotmatch'^(cache|user|mcla(?:\.[1-9][0-9]*)?\.log)$'){throw 'Recovery cycle contains an unexpected child.'}};Get-Lifecycle $recoveryCycle}else{[ordered]@{controlled_exit=$true;runtime_logs=@();runtime_log_bytes=0}};$physicalArtifacts=@(Get-Content (Resolve-Safe (Join-Path $root 'physical-artifacts.json') 'Physical artifacts' -Exists) -Raw|ConvertFrom-Json);if($physicalArtifacts.Count-ne4-or((@($physicalArtifacts.name)-join',')-cne'mcla.exe,rexruntime.dll,TracyClient.dll,rexgpu-xenos.dll')){throw 'Physical artifact manifest is invalid.'};foreach($artifact in $physicalArtifacts){if(($artifact.PSObject.Properties.Name-join',')-cne'name,sha256'-or$artifact.name-isnot[string]-or$artifact.sha256-isnot[string]-or$artifact.sha256-cnotmatch'^[0-9A-F]{64}$'){throw 'Physical artifact entry is invalid.'}};if($calibration-and-not$Fixture-and((@($physicalArtifacts.sha256)-join',')-cne'079AB8CEAA2C568A0473F3CFCC75DF2537F060256F586EFA58163699E1D4BCBA,2922421E6BCB3374F150C31E1E083A9309773D573C0CB7981BB02E48CD53D4BE,017DA5E646BEFD8915169F8DE39A3221EEDAB0DD018823470EAB0B835009C195,11D21C7F93EAE674D6FFB0B0184A4A4178A48655047E8A4DBC3729BD64ACEE03')){throw 'Pinned physical artifacts drifted.'}
  $traffic=if($Fixture){[ordered]@{sha256=$trafficResultSha;decision='rendering-categories-pass'}}else{Read-Prior 'private/evidence/M5-003/20260814-104624-fde51a30/result.json' $trafficResultSha 'rendering-categories-pass'};$series=if($Fixture){[ordered]@{sha256=$seriesResultSha;decision='first-series-results-return-and-release-restart-pass'}}else{Read-Prior 'private/evidence/M5-012/20260817-001225-ade395f8/result.json' $seriesResultSha 'first-series-results-return-and-release-restart-pass'};$resource=if($Fixture){[ordered]@{sha256=$resourceResultSha;decision='five-race-bounded-resource-growth-pass'}}else{Read-Prior 'private/evidence/M5-013/20260817-015958-36eec226/result.json' $resourceResultSha 'five-race-bounded-resource-growth-pass'}
  [ordered]@{decision='representative-race-system-matrix-pass';route=[ordered]@{current_type='two-car-head-to-head';prior_type='multi-event-series';current_opponent=$observation.opponent;prior_opponent='IAN'};current_event=[ordered]@{event_completed=$true;finish_wrapper_calls=[int]$summary.Groups[7].Value;strict_runtime_summary=$summary.Groups[1].Value;optional_description_calls=[int]$summary.Groups[2].Value;optional_checkpoint_hits=[int]$summary.Groups[6].Value;optional_result_calls=[int]$summary.Groups[8].Value;telemetry_gap_reclassified=$calibration;event_process_controlled_exit=(-not$calibration);force_cleanup_reason=if($calibration){'runner-timeout-after-complete-reward-capture'}else{'none'}};operator_observation=$observation;captures=[ordered]@{start=$start;rewards=$rewards};prior_evidence=[ordered]@{traffic=$traffic;completed_series=$series;five_race_rewards=$resource};physical_artifacts=@($physicalArtifacts);event_runtime_logs=@($logs.manifest);event_runtime_log_bytes=$logs.bytes;lifecycle_recovery=$lifecycle;seed_save_sha256=$seedSaveSha;seed_header_sha256=$seedHeaderSha;final_save_sha256=(Get-FileHash $save -Algorithm SHA256).Hash;final_header_sha256=(Get-FileHash $header -Algorithm SHA256).Hash;tree=Get-Tree $root}
}

if($PSCmdlet.ParameterSetName-ceq'Run'){Get-Probe $RunPath;return}
$result=Resolve-Safe $ResultPath 'M6-003 result' -Exists;$record=Get-Content $result -Raw|ConvertFrom-Json;$props=@('schema','task','decision','sdk_version','sdk_commit','build_configuration','route_id','opponent','police_observation','traffic_result_sha256','series_result_sha256','resource_result_sha256','seed_save_sha256','seed_header_sha256','signin_compatibility_state','probe','release_artifacts','scope');if(($record.PSObject.Properties.Name-join',')-cne($props-join',')-or$record.schema-cne'mcla-race-system-v1'-or$record.task-cne'M6-003'-or$record.decision-cne'representative-race-system-matrix-pass'-or$record.sdk_version-cne'0.9.0.22'-or$record.sdk_commit-cne$sdkCommit-or$record.build_configuration-cne'Release'-or$record.route_id-cne'representative-ian-martin-race-v1'-or$record.opponent-cnotin@('IAN','MARTIN')-or$record.police_observation-cnotin@('seen','not-seen')-or$record.traffic_result_sha256-cne$trafficResultSha-or$record.series_result_sha256-cne$seriesResultSha-or$record.resource_result_sha256-cne$resourceResultSha-or$record.seed_save_sha256-cne$seedSaveSha-or$record.seed_header_sha256-cne$seedHeaderSha-or$record.signin_compatibility_state-ne2-or$record.scope-cne$scope){throw 'M6-003 result identity is invalid.'};$root=Split-Path $result -Parent;$probe=Get-Probe $root;if($record.opponent-cne$probe.operator_observation.opponent-or(($record.police_observation-ceq'seen')-ne$probe.operator_observation.police_observed)){throw 'Result and operator observation differ.'};if((ConvertTo-Json $record.probe -Compress -Depth 14)-cne(ConvertTo-Json $probe -Compress -Depth 14)){throw 'M6-003 result probe drifted.'}
if(-not$Fixture){$build=Resolve-Safe 'out/build/win-amd64-release' 'Release build' -Exists;$artifacts=@('mcla.exe','rexruntime.dll','TracyClient.dll','rexgpu-xenos.dll')|ForEach-Object{$path=Join-Path $build $_;[ordered]@{name=$_;sha256=(Get-FileHash $path -Algorithm SHA256).Hash}};if((ConvertTo-Json $record.release_artifacts -Compress)-cne(ConvertTo-Json @($artifacts)-Compress)){throw 'Release artifacts drifted.'};$sdk=Join-Path $repo 'third_party/rexglue-sdk';if((&git -C $sdk rev-parse HEAD).Trim()-cne$sdkCommit-or(&git -C $sdk describe --tags --exact-match HEAD 2>$null).Trim()-cne'v0.9.0.22'-or(git -C $sdk status --porcelain)){throw 'SDK identity drifted.'};if(@((Get-Process mcla -ErrorAction SilentlyContinue)|Where-Object{try{$_.Path-ceq(Join-Path $build 'mcla.exe')}catch{$false}}).Count){throw 'Release process remains.'}}
[pscustomobject][ordered]@{Decision=$record.decision;CurrentOpponentObserved=$record.opponent;RepresentativeRaceTypesBound=2;MachineFinishWrapperVerified=$true;CurrentRewardFrameVerified=$true;CheckpointCompletionOwnerReported=$true;TrafficPriorMachineEvidenceBound=$true;CurrentPoliceObservation=$record.police_observation;PriorPoliceObservationOwnerReported=$true;OptionalWrapperTelemetryGapRecorded=$probe.current_event.telemetry_gap_reclassified;EventProcessControlledExit=$probe.current_event.event_process_controlled_exit;SeparateCurrentBinaryControlledExit=$probe.lifecycle_recovery.controlled_exit;CompletedSeriesPriorEvidenceBound=$true;FiveRaceRewardsPriorEvidenceBound=$true;DataIntegrityVerified=$true}
