[CmdletBinding(DefaultParameterSetName='Run')]
param(
  [Parameter(Mandatory,ParameterSetName='Run')][string]$RunPath,
  [Parameter(Mandatory,ParameterSetName='Result')][string]$ResultPath,
  [switch]$Fixture
)

Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$repo=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$utf8=[Text.UTF8Encoding]::new($false)
$cycleIds=@(
  @('garage-main-before','showroom-purchase-confirmed','visual-purchase-confirmed','performance-purchase-confirmed','paint-purchase-confirmed','vehicle-switch-confirmed','free-roam-after-garage'),
  @('restart-garage-main','restart-purchased-vehicle','restart-customization-paint','restart-vehicle-switch','restart-free-roam')
)
$cycleActions=@(
  @('START','START','DPAD_DOWN','A','DPAD_DOWN','DPAD_DOWN','A','DPAD_LEFT','A','A','DPAD_UP','A','A','DPAD_RIGHT','A','A','DPAD_DOWN','A','A','DPAD_DOWN','A','A','B','A','DPAD_UP','A','B','DPAD_DOWN','DPAD_DOWN','DPAD_DOWN','A','A','DPAD_DOWN','DPAD_DOWN','DPAD_DOWN','A','DPAD_RIGHT','DPAD_RIGHT','DPAD_RIGHT','DPAD_RIGHT','A','B','B','DPAD_UP','A','DPAD_UP','A','DPAD_DOWN','DPAD_DOWN','DPAD_DOWN','A','A','A'),
  @('START','START','DPAD_DOWN','A','A','DPAD_DOWN','A','A','DPAD_UP','A','DPAD_DOWN','DPAD_DOWN','DPAD_DOWN','A','A','A')
)
$actionButtons=[ordered]@{START='0010';BACK='0020';A='1000';B='2000';X='4000';Y='8000';DPAD_UP='0001';DPAD_DOWN='0002';DPAD_LEFT='0004';DPAD_RIGHT='0008';LB='0100';RB='0200'}
$seedSaveSha='126F7482878C7AACB09AA6795331C906DFB9C4218BE94EDB1D8E51B27CA78AB2'
$seedHeaderSha='5827A913515AC0E5D55BB56AEC56DE99CACC0ABB7C8061F59336DF4CEA4A8731'
$seedSourceRunId='20260817-013319-c2e7223f'
$seedSourceLogSha='F6D9B7C09C730242B7D96C7F9FE3C6754A4FE726D22093A2BDAF089D2EABE04A'
$seedSourceCaptureSha='AAB64D0118D75F9EAECA50805DF3FB9EAC56B75726F4D2B97484C681509530A3'
$priorResultSha='D993E2612D1AC769D88264C83FD9C9186BC761E2067317F5A7EB66038C250E58'
$sdkCommit='576b34fd233acf4579dd2375691dbe86fb4bf8e1'
$scope='one affordable unlocked second vehicle, one representative visual item, one performance item, one changed paint color, vehicle switching, free-roam return, and fresh-process persistence under explicit guest sign-in compatibility state 2; no real network service and no exhaustive vehicle, item, price, economy, garage, or campaign coverage'

function Resolve-Safe([string]$Path,[string]$Description,[switch]$Exists){$full=if([IO.Path]::IsPathRooted($Path)){[IO.Path]::GetFullPath($Path)}else{[IO.Path]::GetFullPath((Join-Path $repo $Path))};$prefix=$repo.TrimEnd('\')+'\';if(-not$full.StartsWith($prefix,[StringComparison]::OrdinalIgnoreCase)){throw "$Description escapes repository."};$current=$repo;foreach($part in @($full.Substring($prefix.Length).Split('\')|Where-Object{$_.Length})){$current=Join-Path $current $part;if((Test-Path -LiteralPath $current)-and((Get-Item -LiteralPath $current -Force).Attributes-band[IO.FileAttributes]::ReparsePoint)){throw "$Description traverses a reparse point."}};if($Exists-and-not(Test-Path -LiteralPath $full)){throw "$Description is missing."};$full}
function Assert-NoReparse([string]$Root){foreach($item in @(Get-ChildItem -LiteralPath $Root -Recurse -Force)){if($item.Attributes-band[IO.FileAttributes]::ReparsePoint){throw 'Evidence contains a reparse point.'}}}
function Get-Tree([string]$Root){$entries=@();$bytes=0L;foreach($item in @(Get-ChildItem -LiteralPath $Root -Recurse -Force|Sort-Object FullName)){$rel=$item.FullName.Substring($Root.Length).TrimStart('\').Replace('\','/');if($rel-ceq'result.json'){continue};if($item.PSIsContainer){$entries+=[ordered]@{kind='directory';path=$rel}}else{$bytes+=$item.Length;$entries+=[ordered]@{kind='file';path=$rel;bytes=$item.Length;sha256=(Get-FileHash -LiteralPath $item.FullName -Algorithm SHA256).Hash}}};$json=ConvertTo-Json @($entries)-Compress -Depth 4;$sha=[Security.Cryptography.SHA256]::Create();try{$hash=-join($sha.ComputeHash($utf8.GetBytes($json))|ForEach-Object{$_.ToString('X2')})}finally{$sha.Dispose()};[ordered]@{sha256=$hash;files=@($entries|Where-Object{$_.kind-ceq'file'}).Count;directories=@($entries|Where-Object{$_.kind-ceq'directory'}).Count;bytes=$bytes}}
function Get-Logs([string]$Root){$files=@(Get-ChildItem -LiteralPath $Root -File -Filter 'mcla*.log');if($files.Count-lt1-or$files.Count-gt31){throw 'Runtime-log count is invalid.'};$current=@($files|Where-Object{$_.Name-ceq'mcla.log'});if($current.Count-ne1){throw 'Current runtime log missing.'};$rot=@();foreach($file in @($files|Where-Object{$_.Name-cne'mcla.log'})){$match=[regex]::Match($file.Name,'^mcla\.([1-9][0-9]*)\.log$');if(-not$match.Success){throw 'Malformed runtime-log rotation.'};$rot+=[pscustomobject]@{index=[int]$match.Groups[1].Value;file=$file}};$indices=@($rot|ForEach-Object{$_.index}|Sort-Object);for($i=0;$i-lt$indices.Count;$i++){if($indices[$i]-ne$i+1){throw 'Runtime-log rotation gap.'}};$ordered=@($rot|Sort-Object index -Descending|ForEach-Object{$_.file})+$current[0];$text='';$manifest=@();$bytes=0L;foreach($file in $ordered){$bytes+=$file.Length;if($bytes-gt268435456){throw 'Runtime logs exceed 256 MiB.'};$text+=[IO.File]::ReadAllText($file.FullName)+"`n";$manifest+=[ordered]@{name=$file.Name;bytes=$file.Length;sha256=(Get-FileHash -LiteralPath $file.FullName -Algorithm SHA256).Hash}};[pscustomobject]@{text=$text;manifest=@($manifest);bytes=$bytes}}
function One([string]$Text,[string]$Pattern,[string]$Name){$matches=[regex]::Matches($Text,$Pattern);if($matches.Count-ne1){throw "$Name count is $($matches.Count)."};$matches[0]}
function Read-Bmp([string]$Path,[string]$Name){$file=Resolve-Safe $Path $Name -Exists;$bytes=[IO.File]::ReadAllBytes($file);if($bytes.Length-ne3686454-or$bytes[0]-ne0x42-or$bytes[1]-ne0x4D-or[BitConverter]::ToInt32($bytes,18)-ne1280-or[Math]::Abs([BitConverter]::ToInt32($bytes,22))-ne720-or[BitConverter]::ToUInt16($bytes,28)-ne32){throw "$Name is not the exact 1280x720x32 BMP shape."};[ordered]@{sha256=(Get-FileHash -LiteralPath $file -Algorithm SHA256).Hash;bytes=$bytes.Length}}
function Assert-StaticContract{
  $route=Get-Content -LiteralPath (Join-Path $repo 'config/garage-lifecycle-route.json') -Raw|ConvertFrom-Json;if($route.schema-cne'mcla-garage-lifecycle-route-v1'-or$route.route_id-cne'representative-two-process-garage-v1'-or$route.cycles.Count-ne2-or$route.cycles[0].phases.Count-ne7-or$route.cycles[1].phases.Count-ne5){throw 'Garage route config identity is invalid.'}
  for($cycle=0;$cycle-lt2;$cycle++){if($route.cycles[$cycle].cycle-ne$cycle+1){throw 'Garage route cycle identity is invalid.'};for($i=0;$i-lt$cycleIds[$cycle].Count;$i++){if($route.cycles[$cycle].phases[$i].index-ne$i+1-or$route.cycles[$cycle].phases[$i].id-cne$cycleIds[$cycle][$i]-or[string]::IsNullOrWhiteSpace($route.cycles[$cycle].phases[$i].instruction)){throw 'Garage phase contract is invalid.'}}}
  $source=[IO.File]::ReadAllText((Join-Path $repo 'src/mcla_app.cpp'));foreach($needle in @('mcla_garage_lifecycle_probe','mcla_garage_lifecycle_cycle','.mcla-garage-control.request','kGuestInputObservationTimeout{20}','MCLA_GARAGE_CONTROL v=1 sequence={} action={} capture={} width={} ','MCLA_GARAGE_LIFECYCLE_CONFIG v=1 cycle={} phases={} ','MCLA_GARAGE_LIFECYCLE_FRAME v=1 cycle={} phase={} id={} ','MCLA_GARAGE_LIFECYCLE_SUMMARY v=1 status=PASS cycle={} phases={} ')){if(-not$source.Contains($needle)){throw "Garage source contract is missing '$needle'."}};if($source.Contains('action == "CAPTURE"')-or$source.Contains('mcla-garage-control-"')){throw 'Garage control protocol must not capture arbitrary frames.'};foreach($cycle in $cycleIds){foreach($id in $cycle){if(-not$source.Contains('"'+$id+'"')){throw "Garage source contract is missing phase '$id'."}}}
  $runner=[IO.File]::ReadAllText((Join-Path $repo 'scripts/run-garage-lifecycle-smoke.ps1'));foreach($needle in @('deterministic slot-0 automation','MCLA_GARAGE_CONTROL v=1 sequence=$sequence action=$Action capture=0 width=0 height=0','&$send ''START''','&$capture 7','&$capture 5')){if(-not$runner.Contains($needle)){throw "Garage runner automation contract is missing '$needle'."}};if($runner.Contains('Read-Host')){throw 'Garage runner must not require operator input.'}
  $sdk=Join-Path $repo 'third_party/rexglue-sdk';$flags=[IO.File]::ReadAllText((Join-Path $sdk 'include/rex/system/flags.h'));$profileHeader=[IO.File]::ReadAllText((Join-Path $sdk 'include/rex/system/xam/user_profile.h'));$xamUser=[IO.File]::ReadAllText((Join-Path $sdk 'src/kernel/xam/xam_user.cpp'));$kernelState=[IO.File]::ReadAllText((Join-Path $sdk 'src/system/kernel_state.cpp'));$profileSource=[IO.File]::ReadAllText((Join-Path $sdk 'src/system/xam/user_profile.cpp'));$profileTest=[IO.File]::ReadAllText((Join-Path $sdk 'tests/unit/kernel/xam_user_profile_test.cpp'))
  foreach($contract in @(@{text=$flags;needle='REXCVAR_DECLARE(uint32_t, xam_user_signin_state);'},@{text=$xamUser;needle='REXCVAR_DEFINE_UINT32(xam_user_signin_state, 1, "XAM"'},@{text=$xamUser;needle='.lifecycle(rex::cvar::Lifecycle::kInitOnly);'},@{text=$profileHeader;needle='explicit UserProfile(uint32_t signin_state = 1);'},@{text=$profileHeader;needle='uint32_t signin_state() const { return signin_state_; }'},@{text=$kernelState;needle='std::make_unique<xam::UserProfile>(REXCVAR_GET(xam_user_signin_state))'},@{text=$profileSource;needle='signin_state_(signin_state == 2 ? 2 : 1)'},@{text=$profileSource;needle='XAM_USER_SIGNIN_CONFIG v=1 state={} mode={}'},@{text=$profileTest;needle='XAM profile sign-in compatibility state is explicit and fail-closed'})){if(-not$contract.text.Contains($contract.needle)){throw "XAM sign-in source contract is missing '$($contract.needle)'."}}
}
function Get-Cycle([string]$Root,[int]$Cycle){
  $phaseIds=$cycleIds[$Cycle-1];$cycleRoot=Resolve-Safe (Join-Path $Root ("runs/{0:D2}"-f$Cycle)) "Cycle $Cycle root" -Exists;$top=@(Get-ChildItem -LiteralPath $cycleRoot -Force);foreach($item in $top){if($item.Name-cnotmatch'^(cache|user|mcla(?:\.[1-9][0-9]*)?\.log)$'){throw "Cycle $Cycle contains an unexpected top-level child."}};$requests=@(Get-ChildItem -LiteralPath $cycleRoot -Recurse -File -Filter '*.request');if($requests.Count){throw "Cycle $Cycle contains an unconsumed request."}
  $logs=Get-Logs $cycleRoot;$text=$logs.text;foreach($bad in @('[FATAL]','Assertion failed','PPC_UNIMPLEMENTED','Guest crash','DXGI_ERROR_DEVICE_REMOVED','MCLA garage lifecycle: failed','X_STATUS_IO_DEVICE_ERROR','unregistered guest function')){if($text.Contains($bad)){throw "Cycle $Cycle banned marker '$bad'."}}
  $signin=One $text 'XAM_USER_SIGNIN_CONFIG v=1 state=2 mode=online-compatible' "Cycle $Cycle sign-in config";if([regex]::Matches($text,'XAM_USER_SIGNIN_CONFIG v=1').Count-ne1){throw "Cycle $Cycle sign-in config cardinality is invalid."};$launch=One $text 'KernelState: Preparing module launch\.\.\.' "Cycle $Cycle launch";$first=One $text 'MCLA graphics: nontrivial guest frame captured 1280x720' "Cycle $Cycle first frame";$purchase=if($Cycle-eq1){1}else{0};$persist=if($Cycle-eq2){1}else{0};$configPattern="MCLA_GARAGE_LIFECYCLE_CONFIG v=1 cycle=$Cycle phases=$($phaseIds.Count) vehicle_purchase_required=$purchase visual_purchase_required=$purchase performance_purchase_required=$purchase paint_purchase_required=$purchase vehicle_switch_required=1 persistence_required=$persist external_close_required=1";$config=One $text ([regex]::Escape($configPattern)) "Cycle $Cycle config"
  $expectedActions=$cycleActions[$Cycle-1];$controls=[regex]::Matches($text,'MCLA_GARAGE_CONTROL v=1 sequence=([1-9][0-9]*) action=(START|BACK|A|B|X|Y|DPAD_UP|DPAD_DOWN|DPAD_LEFT|DPAD_RIGHT|LB|RB) capture=0 width=0 height=0 present_seq=([1-9][0-9]*) status=PASS');if($controls.Count-ne$expectedActions.Count-or[regex]::Matches($text,'MCLA_GARAGE_CONTROL v=1').Count-ne$expectedActions.Count){throw "Cycle $Cycle deterministic-control count is invalid."};$priorControlPresent=0L;for($i=0;$i-lt$expectedActions.Count;$i++){$sequence=$i+1;$action=$expectedActions[$i];$control=$controls[$i];if([int]$control.Groups[1].Value-ne$sequence-or$control.Groups[2].Value-cne$action-or[int64]$control.Groups[3].Value-lt$priorControlPresent){throw "Cycle $Cycle deterministic-control identity/order is invalid."};$priorControlPresent=[int64]$control.Groups[3].Value;$buttons=$actionButtons[$action];$sourceDown=One $text ([regex]::Escape("MCLA_FRONTEND_SMOKE_INPUT v=1 side=source sequence=$sequence buttons=$buttons")) "Cycle $Cycle control $sequence source down";$guestDown=One $text ([regex]::Escape("MCLA_FRONTEND_SMOKE_INPUT v=1 side=guest sequence=$sequence buttons=$buttons")) "Cycle $Cycle control $sequence guest down";$sourceUp=One $text ([regex]::Escape("MCLA_FRONTEND_SMOKE_INPUT v=1 side=source sequence=$sequence buttons=0000")) "Cycle $Cycle control $sequence source up";$guestUp=One $text ([regex]::Escape("MCLA_FRONTEND_SMOKE_INPUT v=1 side=guest sequence=$sequence buttons=0000")) "Cycle $Cycle control $sequence guest up";if(-not($sourceDown.Index-lt$guestDown.Index-and$guestDown.Index-lt$sourceUp.Index-and$sourceUp.Index-lt$guestUp.Index-and$guestUp.Index-lt$control.Index)){throw "Cycle $Cycle control $sequence source-to-guest chronology is invalid."}}
  if([regex]::Matches($text,'MCLA_FRONTEND_SMOKE_INPUT v=1').Count-ne$expectedActions.Count*4){throw "Cycle $Cycle frontend-input marker cardinality is invalid."}
  $frames=[regex]::Matches($text,"MCLA_GARAGE_LIFECYCLE_FRAME v=1 cycle=$Cycle phase=([1-9][0-9]*) id=([a-z0-9-]+) width=1280 height=720 present_seq=([1-9][0-9]*) status=PASS");if($frames.Count-ne$phaseIds.Count){throw "Cycle $Cycle frame count is invalid."};$priorSeq=0L;for($i=0;$i-lt$phaseIds.Count;$i++){if([int]$frames[$i].Groups[1].Value-ne$i+1-or$frames[$i].Groups[2].Value-cne$phaseIds[$i]-or[int64]$frames[$i].Groups[3].Value-le$priorSeq){throw "Cycle $Cycle phase identity/order/present sequence is invalid."};$priorSeq=[int64]$frames[$i].Groups[3].Value}
  $summaryPattern="MCLA_GARAGE_LIFECYCLE_SUMMARY v=1 status=PASS cycle=$Cycle phases=$($phaseIds.Count) persistence_required=$persist external_close_required=1";$summary=One $text ([regex]::Escape($summaryPattern)) "Cycle $Cycle summary";$close=One $text 'Window closing, shutting down\.\.\.' "Cycle $Cycle close";$complete=One $text 'Execution complete' "Cycle $Cycle complete";$hard=One $text 'Title terminated; hard-exiting process\.' "Cycle $Cycle hard exit";if(-not($signin.Index-lt$launch.Index-and$launch.Index-lt$first.Index-and$first.Index-lt$config.Index-and$config.Index-lt$controls[0].Index-and$controls[0].Index-lt$frames[0].Index-and$controls[$controls.Count-1].Index-lt$frames[$frames.Count-1].Index-and$frames[$frames.Count-1].Index-lt$summary.Index-and$summary.Index-lt$close.Index-and$close.Index-lt$complete.Index-and$complete.Index-lt$hard.Index)){throw "Cycle $Cycle chronology is invalid."}
  $user=Resolve-Safe (Join-Path $cycleRoot 'user') "Cycle $Cycle user root" -Exists;$captures=@();foreach($id in $phaseIds){$captures+=[ordered]@{id=$id;frame=Read-Bmp (Join-Path $user "mcla-garage-lifecycle-$id.bmp") "Cycle $Cycle capture $id"}};if(@($captures.frame.sha256|Select-Object -Unique).Count-ne$phaseIds.Count){throw "Cycle $Cycle captures are not all distinct."}
  $save=Resolve-Safe (Join-Path $user 'B13EBABEBABEBABE/545407F8/00000001/mc4.sav/mc4.sav') "Cycle $Cycle save" -Exists;$header=Resolve-Safe (Join-Path $user 'B13EBABEBABEBABE/545407F8/Headers/00000001/mc4.sav.header') "Cycle $Cycle header" -Exists;if((Get-Item $save).Length-ne537428-or(Get-Item $header).Length-ne328){throw "Cycle $Cycle save/header shape is invalid."}
  [ordered]@{cycle=$Cycle;phase_count=$phaseIds.Count;control_steps=$controls.Count;deterministic_slot0_automation=$true;captures=@($captures);runtime_logs=@($logs.manifest);runtime_log_bytes=$logs.bytes;save_sha256=(Get-FileHash $save -Algorithm SHA256).Hash;header_sha256=(Get-FileHash $header -Algorithm SHA256).Hash;controlled_exit=$true}
}
function Get-Probe([string]$Path){
  Assert-StaticContract;$root=Resolve-Safe $Path 'M6-002 run root' -Exists;Assert-NoReparse $root;if(-not$Fixture-and-not[regex]::IsMatch((Split-Path $root -Leaf),'^20[0-9]{6}-[0-9]{6}-[a-f0-9]{8}$')){throw 'Physical run-root name is not canonical.'};$allowed=@('release-clean-build.log','result.json','runs','save-chain.json');foreach($child in @(Get-ChildItem -LiteralPath $root -Force)){if($child.Name-cnotin$allowed){throw 'Run root contains an unexpected child.'}}
  $buildLog=Resolve-Safe (Join-Path $root 'release-clean-build.log') 'Release clean-build log' -Exists;$buildText=[IO.File]::ReadAllText($buildLog);if(-not$Fixture){foreach($needle in @('CMAKE_BUILD_TYPE="Release"','REXSDK_VERSION="0.9.0.22"','Cleaning all built files','Linking CXX executable mcla.exe')){if(-not$buildText.Contains($needle)){throw "Release clean-build log is missing '$needle'."}}}
  $cycle1=Get-Cycle $root 1;$cycle2=Get-Cycle $root 2;$chainPath=Resolve-Safe (Join-Path $root 'save-chain.json') 'Save chain' -Exists;$chain=Get-Content -LiteralPath $chainPath -Raw|ConvertFrom-Json;$chainProps=@('schema','seed_save_sha256','seed_header_sha256','cycle1_post_save_sha256','cycle1_post_header_sha256','cycle2_pre_save_sha256','cycle2_pre_header_sha256','cycle2_post_save_sha256','cycle2_post_header_sha256','save_bytes','header_bytes','cycle1_save_changed','handoff_exact');if(($chain.PSObject.Properties.Name-join',')-cne($chainProps-join',')-or$chain.schema-cne'mcla-garage-save-chain-v1'-or$chain.seed_save_sha256-cne$seedSaveSha-or$chain.seed_header_sha256-cne$seedHeaderSha-or$chain.save_bytes-ne537428-or$chain.header_bytes-ne328-or$chain.cycle1_save_changed-isnot[bool]-or-not$chain.cycle1_save_changed-or$chain.handoff_exact-isnot[bool]-or-not$chain.handoff_exact){throw 'Save-chain schema or seed contract is invalid.'}
  foreach($name in $chainProps[1..8]){if($chain.$name-cnotmatch'^[0-9A-F]{64}$'){throw "Save-chain digest '$name' is invalid."}};if($chain.cycle1_post_save_sha256-ceq$seedSaveSha-or$chain.cycle2_pre_save_sha256-cne$chain.cycle1_post_save_sha256-or$chain.cycle2_pre_header_sha256-cne$chain.cycle1_post_header_sha256-or$cycle1.save_sha256-cne$chain.cycle1_post_save_sha256-or$cycle1.header_sha256-cne$chain.cycle1_post_header_sha256-or$cycle2.save_sha256-cne$chain.cycle2_post_save_sha256-or$cycle2.header_sha256-cne$chain.cycle2_post_header_sha256){throw 'Save change/handoff/final binding is invalid.'}
  if(-not$Fixture){$prior=Resolve-Safe 'private/evidence/M5-012/20260817-001225-ade395f8/result.json' 'M5-012 restart result' -Exists;if((Get-FileHash $prior -Algorithm SHA256).Hash-cne$priorResultSha){throw 'M5-012 restart prerequisite drifted.'};$seedRoot=Resolve-Safe "private/evidence/M5-013/$seedSourceRunId/runs/01" 'HANGOUT seed source' -Exists;$seedSave=Resolve-Safe (Join-Path $seedRoot 'user/B13EBABEBABEBABE/545407F8/00000001/mc4.sav/mc4.sav') 'HANGOUT seed save' -Exists;$seedHeader=Resolve-Safe (Join-Path $seedRoot 'user/B13EBABEBABEBABE/545407F8/Headers/00000001/mc4.sav.header') 'HANGOUT seed header' -Exists;$seedLog=Resolve-Safe (Join-Path $seedRoot 'mcla.log') 'HANGOUT seed log' -Exists;$seedCapture=Resolve-Safe (Join-Path $seedRoot 'user/mcla-race-resource-1.bmp') 'HANGOUT seed capture' -Exists;if((Get-FileHash $seedSave -Algorithm SHA256).Hash-cne$seedSaveSha-or(Get-FileHash $seedHeader -Algorithm SHA256).Hash-cne$seedHeaderSha-or(Get-FileHash $seedLog -Algorithm SHA256).Hash-cne$seedSourceLogSha-or(Get-FileHash $seedCapture -Algorithm SHA256).Hash-cne$seedSourceCaptureSha){throw 'HANGOUT seed source drifted.'};$seedText=[IO.File]::ReadAllText($seedLog);if(([regex]::Matches($seedText,'MCLA_RACE_RESOURCE_FRAME v=1 checkpoint=1 .* status=PASS').Count-ne1)-or([regex]::Matches($seedText,'\[FATAL\] Call to invalid or unregistered function at guest address 0x8220B810').Count-ne1)){throw 'HANGOUT seed source classification drifted.'}}
  [ordered]@{decision='representative-garage-purchase-customization-persistence-pass';route_id='representative-two-process-garage-v1';cycle_count=2;purchase_categories=4;vehicle_switches=2;automated_control_steps=69;operator_interaction_required=$false;deterministic_slot0_automation=$true;fresh_process_persistence=$true;cycles=@($cycle1,$cycle2);save_chain=$chain;controlled_exit=$true;tree=Get-Tree $root}
}

if($PSCmdlet.ParameterSetName-ceq'Run'){Get-Probe $RunPath;return}
$result=Resolve-Safe $ResultPath 'M6-002 result' -Exists;$record=Get-Content -LiteralPath $result -Raw|ConvertFrom-Json;$props=@('schema','task','decision','sdk_version','sdk_commit','build_configuration','route_id','prior_race_restart_result_sha256','seed_source_run_id','seed_source_context','seed_source_log_sha256','seed_source_capture_sha256','seed_save_sha256','seed_header_sha256','signin_compatibility_state','network_services_claimed','probe','release_artifacts','scope');if(($record.PSObject.Properties.Name-join',')-cne($props-join',')-or$record.schema-cne'mcla-garage-lifecycle-v1'-or$record.task-cne'M6-002'-or$record.decision-cne'representative-garage-purchase-customization-persistence-pass'-or$record.sdk_version-cne'0.9.0.22'-or$record.sdk_commit-cne$sdkCommit-or$record.build_configuration-cne'Release'-or$record.route_id-cne'representative-two-process-garage-v1'-or$record.prior_race_restart_result_sha256-cne$priorResultSha-or$record.seed_source_run_id-cne$seedSourceRunId-or$record.seed_source_context-cne'external-owner-identified-hangout-save-after-race-1'-or$record.seed_source_log_sha256-cne$seedSourceLogSha-or$record.seed_source_capture_sha256-cne$seedSourceCaptureSha-or$record.seed_save_sha256-cne$seedSaveSha-or$record.seed_header_sha256-cne$seedHeaderSha-or$record.signin_compatibility_state-ne2-or$record.network_services_claimed-isnot[bool]-or$record.network_services_claimed-or$record.scope-cne$scope){throw 'M6-002 result identity is invalid.'}
$root=Split-Path $result -Parent;$probe=Get-Probe $root;if((ConvertTo-Json $record.probe -Compress -Depth 14)-cne(ConvertTo-Json $probe -Compress -Depth 14)){throw 'M6-002 result probe drifted.'}
if(-not$Fixture){$build=Resolve-Safe 'out/build/win-amd64-release' 'Release build' -Exists;$artifacts=@('mcla.exe','rexruntime.dll','TracyClient.dll','rexgpu-xenos.dll')|ForEach-Object{$path=Join-Path $build $_;[ordered]@{name=$_;sha256=(Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash}};if((ConvertTo-Json $record.release_artifacts -Compress)-cne(ConvertTo-Json @($artifacts)-Compress)){throw 'Release artifacts drifted.'};$sdk=Join-Path $repo 'third_party/rexglue-sdk';if((&git -C $sdk rev-parse HEAD).Trim()-cne$sdkCommit-or(&git -C $sdk describe --tags --exact-match HEAD 2>$null).Trim()-cne'v0.9.0.22'-or(git -C $sdk status --porcelain)){throw 'SDK identity drifted.'};if(@((Get-Process mcla -ErrorAction SilentlyContinue)|Where-Object{try{$_.Path-ceq(Join-Path $build 'mcla.exe')}catch{$false}}).Count){throw 'Release process remains.'}}
[pscustomobject][ordered]@{Decision=$record.decision;PurchaseCategoriesVerified=4;VehicleSwitchesVerified=2;AutomatedControlSteps=69;OperatorInteractionRequired=$false;DeterministicSlot0AutomationVerified=$true;FreshProcessPersistenceVerified=$true;ControlledExitVerified=$true;DataIntegrityVerified=$true}
