[CmdletBinding(DefaultParameterSetName='Source')]
param(
  [Parameter(ParameterSetName='Source')][switch]$SourceOnly,
  [Parameter(Mandatory,ParameterSetName='Result')][string]$ResultPath,
  [Parameter(ParameterSetName='Result')][switch]$FixtureMode
)

Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$repo=(Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '..')).Path;$sdk=Join-Path $repo 'third_party/rexglue-sdk'
$sdkVersion='0.9.0.26';$sdkCommit='51f18fab1a5c11d50a380a30fbe592b93fd98248'
$prior=@(
  [ordered]@{task='M4-004';run_id='20260812-123316-db0f1cf4';sha256='388F2FC350C43149CA6E5AD4E24A1B743F18CFE3A450C6D80962099F73C89AE0';decision='single-local-offline-profile'},
  [ordered]@{task='M4-009';run_id='20260813-193514-2bb7e7ca';sha256='52AC3A713038DC4EF9A6236CFB76462006B5AAF8D3856D2422A5410AA9847539';decision='offline-service-title-route-pass'},
  [ordered]@{task='M5-012';run_id='20260817-001225-ade395f8';sha256='D993E2612D1AC769D88264C83FD9C9186BC761E2067317F5A7EB66038C250E58';decision='first-series-results-return-and-release-restart-pass'},
  [ordered]@{task='M6-003';run_id='20260818-180605-e3b74fb5';sha256='AD3573B56412D7DBC10650BE0D250AFD4AACA22EB8EEEB6F9816E94EC3007E3A';decision='representative-race-system-matrix-pass'},
  [ordered]@{task='M6-005';run_id='20260818-201702-5d089d9c';sha256='5F46FA6657F39EE5AF990BD505B67D5EDBE6A781E8283D1D51BE07F3543F169E';decision='native-autosave-load-overwrite-plus-isolated-creation-destructive-save-matrix-pass'}
)
$features=@('achievements','presence','leaderboards','rate-my-ride','driving-test','voice')
$behaviors=@('local','unavailable','empty-enumeration','unavailable','local-save','unavailable')
$progression=@('achievement-manager','none','none','none','title-save','none')
$results=@('000004DD','explicit-offline','00000000','explicit-offline','not-applicable','800700AA')
$sourcePaths=@('third_party/rexglue-sdk/include/rex/kernel/xam/offline_progression.h','third_party/rexglue-sdk/src/kernel/xam/xam_ui.cpp','third_party/rexglue-sdk/src/kernel/xam/xam_user.cpp','third_party/rexglue-sdk/src/kernel/xam/xam_voice.cpp','third_party/rexglue-sdk/tests/unit/kernel/offline_service_test.cpp','third_party/rexglue-sdk/tests/unit/kernel/offline_service_route_test.cpp','third_party/rexglue-sdk/tests/unit/system/achievement_manager_test.cpp','generated/default/mcla_init.cpp','generated/default/mcla_recomp.0.cpp','generated/default/mcla_recomp.29.cpp','generated/default/mcla_recomp.58.cpp')
function Exact($Object,[string[]]$Names,[string]$Description){if(($Object.PSObject.Properties.Name-join',')-cne($Names-join',')){throw "$Description schema is invalid."}}
function Bool($Value,[bool]$Expected,[string]$Description){if($Value-isnot[bool]-or$Value-ne$Expected){throw "$Description is invalid."}}
function Hash([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash}
function Safe([string]$Path,[string]$Description,[switch]$Exists){$full=if([IO.Path]::IsPathRooted($Path)){[IO.Path]::GetFullPath($Path)}else{[IO.Path]::GetFullPath((Join-Path $repo $Path))};$prefix=$repo.TrimEnd('\')+'\';if(-not$full.StartsWith($prefix,[StringComparison]::OrdinalIgnoreCase)){throw "$Description escapes repository."};$current=$repo;foreach($part in @($full.Substring($prefix.Length).Split('\')|Where-Object{$_.Length})){$current=Join-Path $current $part;if((Test-Path -LiteralPath $current)-and((Get-Item -LiteralPath $current -Force).Attributes-band[IO.FileAttributes]::ReparsePoint)){throw "$Description traverses a reparse point."}};if($Exists-and-not(Test-Path -LiteralPath $full)){throw "$Description is missing."};$full}
function SourceContract{
  $header=[IO.File]::ReadAllText((Join-Path $sdk 'include/rex/kernel/xam/offline_progression.h'));$ui=[IO.File]::ReadAllText((Join-Path $sdk 'src/kernel/xam/xam_ui.cpp'));$user=[IO.File]::ReadAllText((Join-Path $sdk 'src/kernel/xam/xam_user.cpp'));$voice=[IO.File]::ReadAllText((Join-Path $sdk 'src/kernel/xam/xam_voice.cpp'));$tests=[IO.File]::ReadAllText((Join-Path $sdk 'tests/unit/kernel/offline_service_test.cpp'));$achievements=[IO.File]::ReadAllText((Join-Path $sdk 'tests/unit/system/achievement_manager_test.cpp'));$generated=@('generated/default/mcla_recomp.0.cpp','generated/default/mcla_recomp.29.cpp','generated/default/mcla_recomp.58.cpp')|ForEach-Object{[IO.File]::ReadAllText((Join-Path $repo $_))}|Out-String
  $needles=@('kOfflineProgressionPolicies','kOfflineAchievementsUiResult = X_ERROR_NOT_LOGGED_ON','kOfflineVoiceSubmitResult = X_HRESULT_FROM_WIN32(X_ERROR_BUSY)','ComputeOfflineStatsBufferSize','kOfflineStatsMaxRows = 100','kOfflineStatsMaxColumnsPerSpec = 64','XamShowAchievementsUIOffline_entry','XamUserCreateStatsEnumerator_entry','XamVoiceSubmitPacket_entry','return kOfflineAchievementsUiResult','return kOfflineVoiceSubmitResult','return X_ERROR_INVALID_PARAMETER','new XStaticUntypedEnumerator(REX_KERNEL_STATE(), 1, buffer_size)','returning an empty leaderboard enumerator','Offline progression policies separate local state from retired services','Offline leaderboard buffer sizing is bounded and title-compatible','achievement unlock state persists across manager instances')
  $all=$header+$ui+$user+$voice+$tests+$achievements;foreach($needle in $needles){if(-not$all.Contains($needle)){throw "Offline progression source contract is missing '$needle'."}}
  foreach($stub in @('REX_EXPORT_STUB(__imp__XamShowAchievementsUI)','REX_EXPORT_STUB(__imp__XamUserCreateStatsEnumerator)','REX_EXPORT_STUB(__imp__XamVoiceSubmitPacket)')){if($all.Contains($stub)){throw "Return-bearing offline hook remains generic: $stub"}}
  foreach($export in @('REX_EXPORT(__imp__XamShowAchievementsUI','REX_EXPORT(__imp__XamUserCreateStatsEnumerator','REX_EXPORT(__imp__XamVoiceSubmitPacket')){if(-not$all.Contains($export)){throw "Explicit offline export is missing: $export"}}
  foreach($import in @(@('XamShowAchievementsUI',1),@('XamUserCreateStatsEnumerator',2),@('XamVoiceSubmitPacket',2))){if(([regex]::Matches($generated,"__imp__$($import[0])\(ctx, base\);").Count)-ne$import[1]){throw "MCLA import call count drifted for $($import[0])."}}
  $initialize=$user.IndexOf('new XStaticUntypedEnumerator(REX_KERNEL_STATE(), 1, buffer_size)',[StringComparison]::Ordinal);$publish=$user.IndexOf('*handle_ptr = enumerator->handle()',[StringComparison]::Ordinal);if($initialize-lt0-or$publish-le$initialize){throw 'Leaderboard handle is published before valid enumerator initialization.'}
  [pscustomobject][ordered]@{SourceContractVerified=$true;SourceChecks=28;OfflineXamCases=6;OfflineXamAssertions=25;OfflineServiceCases=3;OfflineServiceAssertions=32;AchievementCases=6;AchievementAssertions=50;ImportedReturnHooks=5}
}
$source=SourceContract;if($PSCmdlet.ParameterSetName-ceq'Source'){return $source}
$full=Safe $ResultPath 'M6-008 result' -Exists;$rootPrefix=(Join-Path $repo 'private/evidence/M6-008').TrimEnd('\')+'\';if(-not$FixtureMode-and-not$full.StartsWith($rootPrefix,[StringComparison]::OrdinalIgnoreCase)){throw 'Result is outside private M6-008 evidence.'}
$raw=[IO.File]::ReadAllText($full);if($raw-match'(?i)[A-Z]:\|B13EBABEBABEBABE|xuid|gamertag|controller.{0,8}(name|guid|serial)|host_path'){throw 'Result leaks a path or private identity.'};$r=$raw|ConvertFrom-Json
Exact $r @('schema','task','decision','sdk_version','sdk_commit','build_configuration','prior_evidence','service_matrix','focused_tests','release','source_files','scope') 'Result'
if($r.schema-cne'mcla-offline-progression-v1'-or$r.task-cne'M6-008'-or$r.decision-cne'explicit-offline-progression-and-retired-service-matrix-pass'-or$r.sdk_version-cne$sdkVersion-or$r.sdk_commit-cne$sdkCommit-or$r.build_configuration-cne'Release+RelWithDebInfo'){throw 'Result identity is invalid.'}
if(@($r.prior_evidence).Count-ne5){throw 'Prior evidence count is invalid.'};for($i=0;$i-lt5;$i++){Exact $r.prior_evidence[$i] @('task','run_id','sha256','decision') 'Prior evidence';foreach($n in @('task','run_id','sha256','decision')){if($r.prior_evidence[$i].$n-cne$prior[$i].$n){throw 'Prior evidence identity is invalid.'}}}
if(@($r.service_matrix).Count-ne6){throw 'Service matrix count is invalid.'};for($i=0;$i-lt6;$i++){Exact $r.service_matrix[$i] @('feature','behavior','progression_source','retired_service_result','fabricated_rows_or_unlocks') 'Service row';if($r.service_matrix[$i].feature-cne$features[$i]-or$r.service_matrix[$i].behavior-cne$behaviors[$i]-or$r.service_matrix[$i].progression_source-cne$progression[$i]-or$r.service_matrix[$i].retired_service_result-cne$results[$i]){throw 'Service matrix semantics are invalid.'};Bool $r.service_matrix[$i].fabricated_rows_or_unlocks $false 'Fabricated service data'}
Exact $r.focused_tests @('offline_xam_cases','offline_xam_assertions','offline_service_cases','offline_service_assertions','achievement_cases','achievement_assertions','sdk_build_log_sha256','offline_xam_test_log_sha256','offline_service_test_log_sha256','achievement_test_log_sha256','unit_executable_sha256') 'Focused tests';if($r.focused_tests.offline_xam_cases-ne6-or$r.focused_tests.offline_xam_assertions-ne25-or$r.focused_tests.offline_service_cases-ne3-or$r.focused_tests.offline_service_assertions-ne32-or$r.focused_tests.achievement_cases-ne6-or$r.focused_tests.achievement_assertions-ne50){throw 'Focused totals are invalid.'};foreach($n in @('sdk_build_log_sha256','offline_xam_test_log_sha256','offline_service_test_log_sha256','achievement_test_log_sha256','unit_executable_sha256')){if($r.focused_tests.$n-cnotmatch'^[A-F0-9]{64}$'){throw "Focused digest $n is invalid."}}
Exact $r.release @('build_log_sha256','artifacts') 'Release';if($r.release.build_log_sha256-cnotmatch'^[A-F0-9]{64}$'-or@($r.release.artifacts).Count-ne4){throw 'Release evidence is invalid.'};$artifactNames=@('mcla.exe','rexruntime.dll','TracyClient.dll','rexgpu-xenos.dll');for($i=0;$i-lt4;$i++){Exact $r.release.artifacts[$i] @('name','sha256') 'Artifact';if($r.release.artifacts[$i].name-cne$artifactNames[$i]-or$r.release.artifacts[$i].sha256-cnotmatch'^[A-F0-9]{64}$'){throw 'Artifact manifest is invalid.'}}
if(@($r.source_files).Count-ne$sourcePaths.Count){throw 'Source count is invalid.'};for($i=0;$i-lt$sourcePaths.Count;$i++){Exact $r.source_files[$i] @('path','sha256') 'Source';if($r.source_files[$i].path-cne$sourcePaths[$i]-or$r.source_files[$i].sha256-cnotmatch'^[A-F0-9]{64}$'){throw 'Source manifest is invalid.'}}
$trueScope=@('prior_offline_frontend_route_bound','prior_local_profile_route_bound','prior_race_progression_bound','prior_save_restart_bound','m6_009_unlock_policy_unchanged');$falseScope=@('native_current_service_calls_claimed','achievement_guide_ui_claimed','xbox_live_presence_claimed','leaderboard_rows_claimed','rate_my_ride_backend_claimed','voice_transport_claimed','driving_test_exact_unlock_physically_claimed','service_vehicle_unlock_claimed','fake_online_identity_used','fabricated_progression_used');Exact $r.scope @($trueScope+$falseScope) 'Scope';foreach($n in $trueScope){Bool $r.scope.$n $true "Scope $n"};foreach($n in $falseScope){Bool $r.scope.$n $false "Scope $n"}
if(-not$FixtureMode){$runRoot=Split-Path $full;$children=@(Get-ChildItem -LiteralPath $runRoot -Force);if($children.Count-ne6-or(@($children.Name|Sort-Object)-join',')-cne'achievement-test.log,offline-service-test.log,offline-xam-test.log,release-clean-build.log,result.json,sdk-build.log'){throw 'Evidence topology is invalid.'};foreach($child in $children){if($child.Attributes-band[IO.FileAttributes]::ReparsePoint){throw 'Evidence child is a reparse point.'}}
  for($i=0;$i-lt5;$i++){$p=Safe "private/evidence/$($prior[$i].task)/$($prior[$i].run_id)/result.json" 'Prior result' -Exists;if((Hash $p)-cne$prior[$i].sha256){throw 'Prior result drifted.'};$j=[IO.File]::ReadAllText($p)|ConvertFrom-Json;if($j.task-cne$prior[$i].task-or$j.decision-cne$prior[$i].decision){throw 'Prior result semantics drifted.'}}
  if((&git -C $sdk rev-parse HEAD).Trim()-cne$sdkCommit-or(&git -C $sdk describe --tags --exact-match HEAD 2>$null).Trim()-cne"v$sdkVersion"-or(git -C $sdk status --porcelain)){throw 'SDK identity is invalid.'}
  $logs=@('sdk-build.log','offline-xam-test.log','offline-service-test.log','achievement-test.log','release-clean-build.log');$digests=@($r.focused_tests.sdk_build_log_sha256,$r.focused_tests.offline_xam_test_log_sha256,$r.focused_tests.offline_service_test_log_sha256,$r.focused_tests.achievement_test_log_sha256,$r.release.build_log_sha256);for($i=0;$i-lt5;$i++){if((Hash (Join-Path $runRoot $logs[$i]))-cne$digests[$i]){throw 'Build/test log drifted.'}}
  if([IO.File]::ReadAllText((Join-Path $runRoot 'offline-xam-test.log'))-notmatch'All tests passed \(25 assertions in 6 test cases\)'-or[IO.File]::ReadAllText((Join-Path $runRoot 'offline-service-test.log'))-notmatch'All tests passed \(32 assertions in 3 test cases\)'-or[IO.File]::ReadAllText((Join-Path $runRoot 'achievement-test.log'))-notmatch'All tests passed \(50 assertions in 6 test cases\)'){throw 'Focused physical output is invalid.'}
  $unit=Safe 'third_party/rexglue-sdk/out/win-amd64/RelWithDebInfo/unit_tests.exe' 'Unit executable' -Exists;if((Hash $unit)-cne$r.focused_tests.unit_executable_sha256){throw 'Unit executable drifted.'};foreach($entry in $r.source_files){if((Hash (Safe $entry.path 'Source file' -Exists))-cne$entry.sha256){throw 'Source file drifted.'}};$build=Safe 'out/build/win-amd64-release' 'Release build' -Exists;for($i=0;$i-lt4;$i++){if((Hash (Safe (Join-Path $build $artifactNames[$i]) 'Artifact' -Exists))-cne$r.release.artifacts[$i].sha256){throw 'Release artifact drifted.'}};if(@((Get-Process mcla -ErrorAction SilentlyContinue)|Where-Object{try{$_.Path-ceq(Join-Path $build 'mcla.exe')}catch{$false}}).Count){throw 'Canonical MCLA process remains.'}}
[pscustomobject][ordered]@{Decision=$r.decision;ServiceRowsVerified=6;LocalAchievementsVerified=$true;EmptyLeaderboardsVerified=$true;UnavailableServicesFailClosed=$true;PriorProgressionAndSaveBound=$true;NativeCurrentServiceCallsClaimed=$false;FabricatedUnlocksUsed=$false;M6009PolicyUnchanged=$true;DataIntegrityVerified=$true}
