[CmdletBinding(DefaultParameterSetName='Run')]
param([Parameter(Mandatory,ParameterSetName='Run')][string]$RunPath,[Parameter(Mandatory,ParameterSetName='Result')][string]$ResultPath,[switch]$Fixture)
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$repo=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path;$utf8=[Text.UTF8Encoding]::new($false)
$saveSha256='711B94303445034A3B127F83E8143FF6DBA3FC96C2B6176F8720E49829AD5021';$headerSha256='6DDB2A36CB2AF9FC76F80DBC7BCE9B17F71DDC153FABB47084086CB3FB0B1494';$saveRelative='runs/01/user/B13EBABEBABEBABE/545407F8/00000001/mc4.sav/mc4.sav';$headerRelative='runs/01/user/B13EBABEBABEBABE/545407F8/Headers/00000001/mc4.sav.header'
function Resolve-Safe([string]$Path,[string]$Description,[switch]$Exists){$full=if([IO.Path]::IsPathRooted($Path)){[IO.Path]::GetFullPath($Path)}else{[IO.Path]::GetFullPath((Join-Path $repo $Path))};$prefix=$repo.TrimEnd('\')+'\';if(-not$full.StartsWith($prefix,[StringComparison]::OrdinalIgnoreCase)){throw "$Description escapes repository."};$current=$repo;foreach($part in @($full.Substring($prefix.Length).Split('\')|?{$_.Length})){$current=Join-Path $current $part;if((Test-Path -LiteralPath $current)-and((Get-Item -LiteralPath $current -Force).Attributes-band[IO.FileAttributes]::ReparsePoint)){throw "$Description traverses a reparse point."}};if($Exists-and-not(Test-Path -LiteralPath $full)){throw "$Description is missing."};$full}
function Assert-NoReparse([string]$Root){foreach($item in @(Get-ChildItem -LiteralPath $Root -Recurse -Force)){if($item.Attributes-band[IO.FileAttributes]::ReparsePoint){throw 'Evidence contains a reparse point.'}}}
function Get-Tree([string]$Root){$entries=@();$bytes=0L;foreach($item in @(Get-ChildItem -LiteralPath $Root -Recurse -Force|Sort-Object FullName)){$rel=$item.FullName.Substring($Root.Length).TrimStart('\').Replace('\','/');if($rel-ceq'result.json'){continue};if($item.PSIsContainer){$entries+=[ordered]@{kind='directory';path=$rel}}else{$bytes+=$item.Length;$entries+=[ordered]@{kind='file';path=$rel;bytes=$item.Length;sha256=(Get-FileHash -LiteralPath $item.FullName -Algorithm SHA256).Hash}}};$json=ConvertTo-Json @($entries)-Compress -Depth 4;$sha=[Security.Cryptography.SHA256]::Create();try{$hash=-join($sha.ComputeHash($utf8.GetBytes($json))|%{$_.ToString('X2')})}finally{$sha.Dispose()};[ordered]@{sha256=$hash;files=@($entries|?{$_.kind-ceq'file'}).Count;directories=@($entries|?{$_.kind-ceq'directory'}).Count;bytes=$bytes}}
function Get-Logs([string]$Root){$files=@(Get-ChildItem -LiteralPath $Root -File -Filter 'mcla*.log');if($files.Count-lt1-or$files.Count-gt21){throw 'Runtime-log count is invalid.'};$current=@($files|?{$_.Name-ceq'mcla.log'});if($current.Count-ne1){throw 'Current log missing.'};$rot=@();foreach($f in @($files|?{$_.Name-cne'mcla.log'})){$m=[regex]::Match($f.Name,'^mcla\.([1-9][0-9]*)\.log$');if(-not$m.Success){throw 'Malformed rotation.'};$rot+=[pscustomobject]@{i=[int]$m.Groups[1].Value;f=$f}};$indices=@($rot|%{$_.i}|Sort-Object);for($i=0;$i-lt$indices.Count;$i++){if($indices[$i]-ne$i+1){throw 'Rotation gap.'}};$ordered=@($rot|Sort-Object i -Descending|%{$_.f})+$current[0];$text='';$manifest=@();$bytes=0L;foreach($f in $ordered){$bytes+=$f.Length;if($bytes-gt268435456){throw 'Logs exceed 256 MiB.'};$text+=[IO.File]::ReadAllText($f.FullName)+"`n";$manifest+=[ordered]@{name=$f.Name;bytes=$f.Length;sha256=(Get-FileHash -LiteralPath $f.FullName -Algorithm SHA256).Hash}};[pscustomobject]@{text=$text;manifest=@($manifest);bytes=$bytes}}
function One([string]$Text,[string]$Pattern,[string]$Name){$m=[regex]::Matches($Text,$Pattern);if($m.Count-ne1){throw "$Name count is $($m.Count)."};$m[0]}
function Growth([int64]$Start,[int64]$End){[Math]::Max(0L,$End-$Start)}
function Peak-Growth($Samples,[string]$Property,[int64]$Start){$maximum=[int64](($Samples|Measure-Object -Property $Property -Maximum).Maximum);Growth $Start $maximum}
function Assert-StaticContract {
  $config=[IO.File]::ReadAllText((Join-Path $repo 'config/mcla_functions.toml'));$init=[IO.File]::ReadAllText((Join-Path $repo 'generated/default/mcla_init.cpp'));$register=[IO.File]::ReadAllText((Join-Path $repo 'generated/default/mcla_register.cpp'));$body=[IO.File]::ReadAllText((Join-Path $repo 'generated/default/mcla_recomp.7.cpp'))
  if(-not$config.Contains('"0x8220B810" = { end = 0x8220B834, name = "sub_8220B810" }')-or-not$init.Contains('{ 0x8220B810, sub_8220B810 }')-or-not$register.Contains('registrar->SetFunction(0x8220B810, sub_8220B810);')-or-not$body.Contains('DEFINE_REX_FUNC(sub_8220B810) {')-or-not$body.Contains('REX_FUNC_PROLOGUE(0x8220B810);')){throw 'The bounded 0x8220B810 series-transition repair is missing from non-force output.'}
}
Assert-StaticContract
function Get-Probe([string]$Path){
  $root=Resolve-Safe $Path 'M5-013 root' -Exists;Assert-NoReparse $root;$buildLog=Resolve-Safe (Join-Path $root 'release-clean-build.log') 'Release clean-build log' -Exists;$buildText=[IO.File]::ReadAllText($buildLog);foreach($needle in @('CMAKE_BUILD_TYPE="Release"','REXSDK_VERSION="0.9.0.21"','Cleaning all built files','Linking CXX executable mcla.exe')){if(-not$buildText.Contains($needle)){throw "Release clean-build log is missing '$needle'."}};$cycle=Join-Path $root 'runs/01';$logs=Get-Logs $cycle;$text=$logs.text
  foreach($bad in @('[FATAL]','Assertion failed','PPC_UNIMPLEMENTED','Guest crash','DXGI_ERROR_DEVICE_REMOVED','MCLA race resource: failed')){if($text.Contains($bad)){throw "Banned marker '$bad'."}}
  $config=One $text 'MCLA_RACE_RESOURCE_CONFIG v=1 checkpoints=5 operator_confirmed=1 external_close_required=1' 'Config';$frames=[regex]::Matches($text,'MCLA_RACE_RESOURCE_FRAME v=1 checkpoint=(\d) width=1280 height=720 present_seq=(\d+) status=PASS');if($frames.Count-ne5){throw 'Frame count invalid.'};$priorSeq=0L
  for($i=0;$i-lt5;$i++){if([int]$frames[$i].Groups[1].Value-ne$i+1-or[int64]$frames[$i].Groups[2].Value-le$priorSeq){throw 'Frame sequence invalid.'};$priorSeq=[int64]$frames[$i].Groups[2].Value}
  $summary=One $text 'MCLA_RACE_RESOURCE_SUMMARY v=1 status=PASS checkpoints=5 external_close_required=1' 'Summary';$close=One $text 'Window closing, shutting down\.\.\.' 'Close';$complete=One $text 'Execution complete' 'Complete';$hard=One $text 'Title terminated; hard-exiting process\.' 'Hard exit';if(-not($config.Index-lt$frames[0].Index-and$frames[4].Index-lt$summary.Index-and$summary.Index-lt$close.Index-and$close.Index-lt$complete.Index-and$complete.Index-lt$hard.Index)){throw 'Chronology invalid.'}
  $samplesPath=Resolve-Safe (Join-Path $root 'resource-samples.json') 'Resource samples' -Exists;$samples=@(Get-Content -LiteralPath $samplesPath -Raw|ConvertFrom-Json);if($samples.Count-ne6){throw 'Expected baseline plus five samples.'};$properties=@('checkpoint','private_bytes','working_set_bytes','handle_count','thread_count','gpu_dedicated_bytes','gpu_shared_bytes')
  for($i=0;$i-lt6;$i++){if(($samples[$i].PSObject.Properties.Name-join',')-cne($properties-join',')-or$samples[$i].checkpoint-ne$i){throw 'Sample schema/order invalid.'};foreach($p in $properties[1..6]){if($samples[$i].$p-isnot[long]-and$samples[$i].$p-isnot[int]){throw "Sample $p type invalid."};if([int64]$samples[$i].$p-lt0){throw "Sample $p negative."}};if(([int64]$samples[$i].gpu_dedicated_bytes+[int64]$samples[$i].gpu_shared_bytes)-le0){throw 'GPU process-memory sample is empty.'}}
  $first=$samples[1];$last=$samples[5];$raceSamples=@($samples[1..5]);$MiB=1048576L;$growth=[ordered]@{private_bytes=Growth $first.private_bytes $last.private_bytes;working_set_bytes=Growth $first.working_set_bytes $last.working_set_bytes;handle_count=Growth $first.handle_count $last.handle_count;thread_count=Growth $first.thread_count $last.thread_count;gpu_dedicated_bytes=Growth $first.gpu_dedicated_bytes $last.gpu_dedicated_bytes;gpu_shared_bytes=Growth $first.gpu_shared_bytes $last.gpu_shared_bytes};$peakGrowth=[ordered]@{private_bytes=Peak-Growth $raceSamples private_bytes $first.private_bytes;working_set_bytes=Peak-Growth $raceSamples working_set_bytes $first.working_set_bytes;handle_count=Peak-Growth $raceSamples handle_count $first.handle_count;thread_count=Peak-Growth $raceSamples thread_count $first.thread_count;gpu_dedicated_bytes=Peak-Growth $raceSamples gpu_dedicated_bytes $first.gpu_dedicated_bytes;gpu_shared_bytes=Peak-Growth $raceSamples gpu_shared_bytes $first.gpu_shared_bytes}
  if($peakGrowth.private_bytes-gt512*$MiB-or$peakGrowth.working_set_bytes-gt512*$MiB-or$peakGrowth.handle_count-gt128-or$peakGrowth.thread_count-gt16-or$peakGrowth.gpu_dedicated_bytes-gt512*$MiB-or$peakGrowth.gpu_shared_bytes-gt256*$MiB){throw 'Peak resource growth exceeds bounded thresholds.'}
  $captures=@();for($i=1;$i-le5;$i++){$bmp=Resolve-Safe (Join-Path $cycle "user/mcla-race-resource-$i.bmp") "Capture $i" -Exists;$b=[IO.File]::ReadAllBytes($bmp);if($b.Length-ne3686454-or$b[0]-ne0x42-or$b[1]-ne0x4D-or[BitConverter]::ToInt32($b,18)-ne1280-or[Math]::Abs([BitConverter]::ToInt32($b,22))-ne720-or[BitConverter]::ToUInt16($b,28)-ne32){throw "Capture $i invalid."};$captures+=[ordered]@{checkpoint=$i;sha256=(Get-FileHash -LiteralPath $bmp -Algorithm SHA256).Hash}}
  if(@($captures.sha256|Select-Object -Unique).Count-lt2){throw 'All race captures are identical.'};$save=Resolve-Safe (Join-Path $root $saveRelative) 'Final working save' -Exists;$header=Resolve-Safe (Join-Path $root $headerRelative) 'Final working save header' -Exists;if((Get-Item -LiteralPath $save).Length-ne537428-or(Get-Item -LiteralPath $header).Length-ne328){throw 'Final working save shape changed unexpectedly.'};$finalSaveHash=(Get-FileHash -LiteralPath $save -Algorithm SHA256).Hash;$finalHeaderHash=(Get-FileHash -LiteralPath $header -Algorithm SHA256).Hash
  [ordered]@{decision='five-race-bounded-resource-growth-pass';build_log_sha256=(Get-FileHash -LiteralPath $buildLog -Algorithm SHA256).Hash;samples=@($samples);final_growth=$growth;peak_growth=$peakGrowth;thresholds=[ordered]@{private_bytes=512*$MiB;working_set_bytes=512*$MiB;handle_count=128;thread_count=16;gpu_dedicated_bytes=512*$MiB;gpu_shared_bytes=256*$MiB};captures=@($captures);seed_save_sha256=$saveSha256;seed_header_sha256=$headerSha256;final_save_sha256=$finalSaveHash;final_header_sha256=$finalHeaderHash;working_save_updated=($finalSaveHash-cne$saveSha256-or$finalHeaderHash-cne$headerSha256);runtime_logs=@($logs.manifest);runtime_log_bytes=$logs.bytes;controlled_exit=$true;tree=Get-Tree $root}
}
if($PSCmdlet.ParameterSetName-ceq'Run'){$probe=Get-Probe $RunPath;$probe;return}
$result=Resolve-Safe $ResultPath 'M5-013 result' -Exists;$record=Get-Content -LiteralPath $result -Raw|ConvertFrom-Json;$props=@('schema','task','decision','sdk_version','sdk_commit','build_configuration','seed_save_sha256','seed_header_sha256','probe','release_artifacts','scope');if(($record.PSObject.Properties.Name-join',')-cne($props-join',')-or$record.schema-cne'mcla-race-resource-v1'-or$record.task-cne'M5-013'-or$record.decision-cne'five-race-bounded-resource-growth-pass'-or$record.sdk_version-cne'0.9.0.21'-or$record.sdk_commit-cne'3ef5b4f143d56b57e3c0e539cb0009ffe3a67e05'-or$record.build_configuration-cne'Release'-or$record.seed_save_sha256-cne$saveSha256-or$record.seed_header_sha256-cne$headerSha256){throw 'Result identity invalid.'}
$root=Split-Path $result -Parent;$probe=Get-Probe $root;if((ConvertTo-Json $record.probe -Compress -Depth 9)-cne(ConvertTo-Json $probe -Compress -Depth 9)){throw 'Result probe drifted.'};if($record.scope-cne'five operator-confirmed race completions in one Release process; bounded host private/working memory, handles, threads, and Windows GPU process-memory counters; the isolated working save may update; no claim of all-race or all-driver coverage'){throw 'Scope invalid.'}
$build=Resolve-Safe 'out/build/win-amd64-release' 'Release build' -Exists;$artifacts=@('mcla.exe','rexruntime.dll','TracyClient.dll','rexgpu-xenos.dll')|%{$p=Join-Path $build $_;[ordered]@{name=$_;sha256=(Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash}};if((ConvertTo-Json $record.release_artifacts -Compress)-cne(ConvertTo-Json @($artifacts)-Compress)){throw 'Release artifacts drifted.'};$sdk=Join-Path $repo 'third_party/rexglue-sdk';if((&git -C $sdk rev-parse HEAD).Trim()-cne$record.sdk_commit-or(&git -C $sdk describe --tags --exact-match HEAD 2>$null).Trim()-cne'v0.9.0.21'-or(git -C $sdk status --porcelain)){throw 'SDK identity drifted.'};if(@((Get-Process mcla -ErrorAction SilentlyContinue)|?{try{$_.Path-ceq(Join-Path $build 'mcla.exe')}catch{$false}}).Count){throw 'Release process remains.'};[pscustomobject][ordered]@{Decision=$record.decision;FiveRaceCheckpointsVerified=$true;BoundedResourceGrowthVerified=$true;ControlledExitVerified=$true;DataIntegrityVerified=$true}
