[CmdletBinding()]
param(
  [Parameter(Mandatory)][string]$ResultPath,
  [switch]$Fixture
)

Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$repo=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$gameVerifier=Join-Path $PSScriptRoot 'verify-game-manifest.ps1'
$saveRelative='B13EBABEBABEBABE/545407F8/00000001/mc4.sav/mc4.sav'
$headerRelative='B13EBABEBABEBABE/545407F8/Headers/00000001/mc4.sav.header'

function Safe([string]$Path,[string]$Description,[switch]$Exists){$full=if([IO.Path]::IsPathRooted($Path)){[IO.Path]::GetFullPath($Path)}else{[IO.Path]::GetFullPath((Join-Path $repo $Path))};$prefix=$repo.TrimEnd('\')+'\';if(-not$full.StartsWith($prefix,[StringComparison]::OrdinalIgnoreCase)){throw "$Description escapes repository."};$cursor=$repo;foreach($part in @($full.Substring($prefix.Length).Split('\')|Where-Object Length)){$cursor=Join-Path $cursor $part;if((Test-Path -LiteralPath $cursor)-and((Get-Item -LiteralPath $cursor -Force).Attributes-band[IO.FileAttributes]::ReparsePoint)){throw "$Description traverses a reparse point."}};if($Exists-and-not(Test-Path -LiteralPath $full)){throw "$Description is missing."};$full}
function Hash([string]$Path){$stream=[IO.File]::OpenRead((Safe $Path 'Hash source' -Exists));$sha=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($sha.ComputeHash($stream))).Replace('-','')}finally{$sha.Dispose();$stream.Dispose()}}
function Game([string]$Root){$verified=&$gameVerifier -GamePath $Root;$manifest=Get-Content -LiteralPath $verified.ManifestPath -Raw|ConvertFrom-Json;$hashes=0;foreach($entry in @($manifest.Files)){$candidate=Join-Path $Root ([string]$entry.Path).Replace('/','\');if((Hash $candidate)-cne([string]$entry.Sha256).ToUpperInvariant()){throw "Source-game hash drifted for '$($entry.Path)'."};$hashes++};if($hashes-ne[int]$verified.FileCount){throw 'Source-game hash coverage is incomplete.'};[ordered]@{file_count=[int]$verified.FileCount;payload_bytes=[long]$verified.PayloadBytes;source_iso_sha256=[string]$verified.SourceIsoSha256}}
function Tree([string]$Root){$sha=[Security.Cryptography.SHA256]::Create();try{$files=@(Get-ChildItem -LiteralPath $Root -File -Recurse -Force|Sort-Object FullName);$bytes=0L;foreach($file in $files){$rel=$file.FullName.Substring($Root.TrimEnd('\').Length+1).Replace('\','/');$line=[Text.Encoding]::UTF8.GetBytes("$rel`t$($file.Length)`t$(Hash $file.FullName)`n");$null=$sha.TransformBlock($line,0,$line.Length,$line,0);$bytes+=$file.Length};$null=$sha.TransformFinalBlock([byte[]]::new(0),0,0);[ordered]@{sha256=([BitConverter]::ToString($sha.Hash)).Replace('-','');files=$files.Count;bytes=$bytes}}finally{$sha.Dispose()}}
function ExactProperties($Value,[string[]]$Names,[string]$Description){if(($Value.PSObject.Properties.Name-join',')-cne($Names-join',')){throw "$Description properties changed."}}
function Sha([string]$Value,[string]$Description){if($Value-cnotmatch'^[0-9A-F]{64}$'){throw "$Description is not an uppercase SHA-256."}}

$path=Safe $ResultPath 'Delivery regression result' -Exists;$r=Get-Content -LiteralPath $path -Raw|ConvertFrom-Json
ExactProperties $r @('schema','task','known_issue','decision','suite_id','sdk_version','sdk_commit','build_configuration','run_id','active_confirmation_utc','stable_confirmation_utc','stability_seconds','seed_save_sha256','seed_header_sha256','save_after_sha256','header_after_sha256','release_artifacts','runtime_logs','runtime_fatal_markers','controlled_external_close','exit_code','force_cleanup','save_archive','scope') 'Result'
if($r.schema-cne'mcla-delivery-transition-regression-v1'-or$r.task-cne'M6-014'-or$r.known_issue-cne'KI-024'-or$r.decision-cne'delivery-transition-current-artifact-pass'){throw 'Delivery result identity is invalid.'}
if($r.sdk_version-cne'0.10.0.1'-or$r.sdk_commit-cne'7dd5cb33002a443b097c0f65d5566c0a0f2db838'-or$r.build_configuration-cne'Release'){throw 'Delivery SDK/build identity is invalid.'}
if($r.suite_id-cnotmatch'^20260901-153415-d747cf2d$'-or$r.run_id-cnotmatch'^\d{8}-\d{6}-[0-9a-f]{8}$'){throw 'Delivery suite/run identity is invalid.'}
$active=[DateTime]::Parse([string]$r.active_confirmation_utc).ToUniversalTime();$stable=[DateTime]::Parse([string]$r.stable_confirmation_utc).ToUniversalTime();if([int]$r.stability_seconds-lt300-or($stable-$active).TotalSeconds-lt[int]$r.stability_seconds){throw 'Delivery stability timing is insufficient.'}
foreach($name in @('seed_save_sha256','seed_header_sha256','save_after_sha256','header_after_sha256')){Sha ([string]$r.$name) $name}
if(@($r.release_artifacts).Count-ne4-or(@($r.release_artifacts|ForEach-Object name)-join',')-cne'mcla.exe,rexruntime.dll,TracyClient.dll,rexgpu-xenos.dll'){throw 'Delivery artifact set is invalid.'};foreach($entry in @($r.release_artifacts)){ExactProperties $entry @('name','sha256') "Artifact $($entry.name)";Sha ([string]$entry.sha256) "Artifact $($entry.name)"}
if(@($r.runtime_logs).Count-lt1){throw 'Delivery runtime log set is empty.'};foreach($entry in @($r.runtime_logs)){ExactProperties $entry @('name','sha256','bytes') "Runtime log $($entry.name)";if($entry.name-cnotmatch'^mcla(?:\.\d+)?\.log$'-or[long]$entry.bytes-lt1){throw 'Delivery runtime log entry is invalid.'};Sha ([string]$entry.sha256) "Runtime log $($entry.name)"}
if([int]$r.runtime_fatal_markers-ne0-or$r.controlled_external_close-ne$true-or[int]$r.exit_code-ne0-or$r.force_cleanup-ne$false){throw 'Delivery runtime health or exit contract failed.'}
ExactProperties $r.save_archive @('sha256','files','bytes') 'Save archive';Sha ([string]$r.save_archive.sha256) 'Save archive';if([int]$r.save_archive.files-lt1-or[long]$r.save_archive.bytes-lt1){throw 'Delivery save archive is empty.'}
ExactProperties $r.scope @('delivery_transition_physically_confirmed','active_delivery_gameplay_physically_confirmed','five_minute_stability_physically_confirmed','full_delivery_completion_claimed','two_hour_soak_claimed') 'Scope'
if($r.scope.delivery_transition_physically_confirmed-ne$true-or$r.scope.active_delivery_gameplay_physically_confirmed-ne$true-or$r.scope.five_minute_stability_physically_confirmed-ne$true-or$r.scope.full_delivery_completion_claimed-ne$false-or$r.scope.two_hour_soak_claimed-ne$false){throw 'Delivery claim boundary is invalid.'}
if($Fixture){[pscustomobject]@{Passed=$true;Decision=$r.decision;StabilitySeconds=[int]$r.stability_seconds;PhysicalTransitionVerified=$true;ControlledExitVerified=$true};return}

$root=Split-Path $path;$expectedParent=Safe 'private/evidence/M6-014/delivery-regressions' 'Delivery evidence root' -Exists;if((Split-Path $root -Parent)-cne$expectedParent-or(Split-Path $root -Leaf)-cne$r.run_id){throw 'Delivery result location is invalid.'}
$suitePath=Safe "private/evidence/M6-014/$($r.suite_id)/suite.json" 'Bound suite state' -Exists;$suite=Get-Content -LiteralPath $suitePath -Raw|ConvertFrom-Json;if($suite.sdk_version-cne$r.sdk_version-or$suite.sdk_commit-cne$r.sdk_commit-or(ConvertTo-Json @($suite.build.artifacts)-Compress)-cne(ConvertTo-Json @($r.release_artifacts)-Compress)){throw 'Delivery result drifted from its bound suite artifacts.'}
$currentGame=Game (Safe 'private/game' 'Canonical source-game payload' -Exists);if((ConvertTo-Json $currentGame -Compress)-cne(ConvertTo-Json $suite.game -Compress)){throw 'Current source-game payload drifted from the bound suite.'}
$seed=Safe 'private/save-archive/M6-014/20260831-133236-2cecb67b/free-roam/20260901-114045Z-A575F88F4FDFA19B-2FAEFBC7FF8CDEAD' 'Progressed delivery seed' -Exists;if((Hash (Join-Path $seed $saveRelative))-cne$r.seed_save_sha256-or(Hash (Join-Path $seed $headerRelative))-cne$r.seed_header_sha256-or(Hash (Join-Path $seed 'snapshot.json'))-cne'BE2D1D6C79DC834A0E5C50A601667A51E10EA86AF5E16062380ACFC2DEAEE79B'){throw 'Delivery seed identity drifted.'}
$build=Safe 'out/build/win-amd64-release' 'Release build' -Exists;foreach($entry in @($r.release_artifacts)){if((Hash (Join-Path $build $entry.name))-cne$entry.sha256){throw "Current artifact '$($entry.name)' drifted."}}
$user=Safe (Join-Path $root 'run/user') 'Delivery user root' -Exists;if((Hash (Join-Path $user $saveRelative))-cne$r.save_after_sha256-or(Hash (Join-Path $user $headerRelative))-cne$r.header_after_sha256){throw 'Delivery final save identity drifted.'}
$logRoot=Safe (Join-Path $root 'run') 'Delivery runtime root' -Exists;$actualLogs=@(Get-ChildItem -LiteralPath $logRoot -File -Filter 'mcla*.log'|Sort-Object Name);if($actualLogs.Count-ne@($r.runtime_logs).Count){throw 'Delivery runtime log file count drifted.'};$text='';for($i=0;$i-lt$actualLogs.Count;$i++){if($actualLogs[$i].Name-cne$r.runtime_logs[$i].name-or$actualLogs[$i].Length-ne[long]$r.runtime_logs[$i].bytes-or(Hash $actualLogs[$i].FullName)-cne$r.runtime_logs[$i].sha256){throw 'Delivery runtime log identity drifted.'};$text+=Get-Content -LiteralPath $actualLogs[$i].FullName -Raw}
foreach($marker in @('MCLA module config: static image 82000000-829E0000, code 82130000-827CD054, 30034 mappings','MCLA graphics: nontrivial guest frame captured','MCLA_GARAGE_LIFECYCLE_CONFIG v=1 cycle=2','MCLA_GARAGE_CONTROL v=1 sequence=1 action=START','Window closing, shutting down...','Execution complete','Title terminated; hard-exiting process.')){if(-not$text.Contains($marker)){throw "Required delivery runtime marker is missing: $marker"}}
if([regex]::Matches($text,'(?i)\[FATAL\]|guest crash|PPC_UNIMPLEMENTED|invalid or unregistered function|device lost|DXGI_ERROR_DEVICE_REMOVED').Count){throw 'Delivery runtime contains a fatal marker.'}
$archive=Safe "private/save-archive/M6-014/delivery-regression-$($r.run_id)" 'Delivery save archive' -Exists;$tree=Tree $archive;if((ConvertTo-Json $tree -Compress)-cne(ConvertTo-Json $r.save_archive -Compress)){throw 'Delivery save archive identity drifted.'}
$latest=Get-Content -LiteralPath (Safe (Join-Path $archive 'latest.json') 'Latest delivery save snapshot' -Exists) -Raw|ConvertFrom-Json;if($latest.schema-cne'mcla-soak-save-snapshot-v1'-or$latest.complete_profile_tree-ne$true-or$latest.save_sha256-cne$r.save_after_sha256-or$latest.header_sha256-cne$r.header_after_sha256){throw 'Latest delivery save snapshot does not bind the final complete profile.'}
[pscustomobject]@{Passed=$true;Decision=$r.decision;StabilitySeconds=[int]$r.stability_seconds;PhysicalTransitionVerified=$true;ControlledExitVerified=$true;RuntimeFatalMarkers=0;SaveArchiveSha256=$tree.sha256}
